In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [2]:
data17 = pd.read_excel("../h1b/H-1B_Disclosure_Data_FY17.xlsx", dtype={'NAICS_CODE':str, 'NAIC_CODE':str})
data16 = pd.read_excel("../h1b/H-1B_Disclosure_Data_FY16.xlsx", dtype={'NAICS_CODE':str, 'NAIC_CODE':str})
data15 = pd.read_excel("../h1b/H-1B_Disclosure_Data_FY15.xlsx", dtype={'NAICS_CODE':str, 'NAIC_CODE':str})
data18 = pd.read_excel("../h1b/H-1B_Disclosure_Data_FY18.xlsx", dtype={'NAICS_CODE':str, 'NAIC_CODE':str})

#allv = pd.read_csv("../prepped/vdatafull_work.csv")
# H-1B_Disclosure_Data_FY17.xlsx
# H-1B_Disclosure_Data_FY16.xlsx
# H-1B_Disclosure_Data_FY15.xlsx
# H-1B_Disclosure_Data_FY14.xlsx
# H-1B_Disclosure_Data_FY13.xlsx
# H-1B_Disclosure_Data_FY12.xlsx
# H-1B_Disclosure_Data_FY11.xlsx
# H-1B_Disclosure_Data_FY10.xlsx
# H-1B_Disclosure_Data_FY09.xlsx
# H-1B_Disclosure_Data_FY08.xlsx
#https://www.foreignlaborcert.doleta.gov/performancedata.cfm

In [9]:
#allv['naics4'].unique().astype(str)

array(['6211.0', '3363.0', '3331.0', '6212.0', '5415.0', '7225.0',
       '6116.0', '5413.0', '5416.0', '5613.0', '3312.0', '5629.0',
       '6213.0', '3361.0', '3362.0', '6113.0', '3332.0', '6221.0',
       '3399.0', '3273.0', '2123.0', '3211.0', '6216.0', '3334.0',
       '8131.0', '3313.0', '3351.0', '3221.0', '5611.0', '3345.0',
       '4249.0', '5419.0', '6111.0', '3327.0', '3261.0', '7221.0',
       '3151.0', '3365.0', '4471.0', '5221.0', '5112.0', '6241.0',
       '3391.0', '6214.0', '3314.0', '4481.0', '3271.0', '2362.0',
       '3311.0', '3254.0', '5111.0', '5412.0', '3342.0', '3121.0',
       '4238.0', '4885.0', '3364.0', '5172.0', '6222.0', '6242.0',
       '4231.0', '5191.0', '4239.0', '5311.0', '3252.0', '4245.0',
       '5619.0', '3353.0', '4251.0', '5179.0', '3272.0', '7139.0',
       '5242.0', '4451.0', '8134.0', '3329.0', '3323.0', '5417.0',
       '3341.0', '3149.0', '2211.0', '4246.0', '4235.0', '3117.0',
       '5222.0', '2111.0', '6244.0', '2131.0', '3241.0', '5239.0',
       '2379.0', '7211.0', '9211.0', '5174.0', '9221.0', '9251.0',
       '6219.0', '4511.0', '2122.0', '4483.0', '5151.0', '6117.0',
       '1141.0', '7121.0', '9231.0', '8133.0', '4234.0', '1153.0',
       '5615.0', '6231.0', '1112.0', '1121.0', '4461.0', '9271.0',
       '1435.0', '4244.0', '3114.0', '6115.0', '6232.0', '1151.0',
       '4521.0', '3253.0', '6223.0', '4841.0', '4411.0', '5259.0',
       '3118.0', '5171.0', '3119.0', '3339.0', '3256.0', '3112.0',
       '5182.0', '3328.0', '3274.0', '5511.0', '5231.0', '1129.0',
       '4811.0', '4921.0', '7212.0', '5313.0', '5241.0', '2361.0',
       '3231.0', '3259.0', '5418.0', '7223.0', '6112.0', '1114.0',
       '8113.0', '4724.0', '8132.0', '3336.0', '6243.0', '5612.0',
       '5121.0', '2373.0', '2213.0', '4421.0', '5181.0', '4242.0',
       '3115.0', '1113.0', '4243.0', '7114.0', '8141.0', '8111.0',
       '3344.0', '4922.0', '5145.0', '2383.0', '5614.0', '9241.0',
       '3333.0', '2371.0', '4931.0', '4232.0', '4881.0', '4422.0',
       '5411.0', '3321.0', '4541.0', '3343.0', '5414.0', '6114.0',
       '4482.0', '3369.0', '7132.0', '4831.0', '1119.0', '3372.0',
       '4241.0', '4248.0', '4889.0', '4812.0', '4539.0', '2381.0',
       '3251.0', '5223.0', '7113.0', '1122.0', '6215.0', '2382.0',
       '7112.0', '1152.0', '4532.0', '3219.0', '3359.0', '3113.0',
       '4233.0', '5312.0', '3116.0', '8139.0', '1511.0', '3222.0',
       '2212.0', '3366.0', '3340.0', '9261.0', '8129.0', '4450.0',
       '5322.0', '4413.0', '5617.0', '5421.0', '1125.0', '7111.0',
       '5161.0', '8123.0', '3324.0', '2389.0', '5616.0', '4871.0',
       '7131.0', '8112.0', '3326.0', '3262.0', '7222.0', '4453.0',
       '4236.0', '3159.0', '3325.0', '3111.0', '3141.0', '8121.0',
       '3255.0', '3132.0', '3131.0', '4431.0', '3279.0', 'nan', '4529.0',
       '7115.0', '3152.0', '3212.0', '3322.0', '4441.0', '161.0',
       '3335.0', '3346.0', '3352.0', '3110.0', '4237.0', '3371.0',
       '5451.0', '3235.0', '4882.0', '4842.0', '3315.0', '1123.0',
       '6233.0', '1111.0', '5622.0', '4412.0', '4543.0', '3133.0',
       '5175.0', '7213.0', '5211.0', '4884.0', '4862.0', '1131.0',
       '4883.0', '4247.0', '5621.0', '5813.0', '5321.0', '3169.0',
       '4853.0', '3379.0', '5251.0', '1124.0', '31.0', '4452.0', '3162.0',
       '7224.0', '6239.0', '2121.0', '3161.0', '4531.0', '5324.0',
       '5152.0', '6131.0', '2110.0', '8399.0', '4859.0', '621.0', '52.0',
       '4218.0', '3122.0', '3250.0', '5122.0', '5173.0', '1517.0',
       '3120.0', '9281.0', '8211.0', '3100.0', '8017.0', '3233.0',
       '1120.0', '622.0', '4832.0', '2333.0', '5510.0', '4910.0',
       '1234.0', '5471.0', '5323.0', '5170.0', '0.0', '4861.0', '236.0',
       '6110.0', '8122.0'], dtype='<U32')

In [105]:
#vdata = data15 #IP #
#vdata = data16 # #
vdata = data17 # #
#vdata = data18 # #

In [106]:
len(vdata)

624650

In [5]:
zip_county = pd.read_excel("../cross-walk/ZIP_COUNTY_122017.xlsx", dtype={'zip': str, 'county': str})
#ref table for 'zipcode'(z) matching
georefz = zip_county[['zip', 'county']]
georefz.head()

     zip county
0  06010  09003
1  06013  09003
2  06033  09003
3  06037  09003
4  06040  09003

In [78]:
vdata.columns

Index(['CASE_NUMBER', 'CASE_STATUS', 'CASE_SUBMITTED', 'DECISION_DATE',
       'VISA_CLASS', 'EMPLOYMENT_START_DATE', 'EMPLOYMENT_END_DATE',
       'EMPLOYER_NAME', 'EMPLOYER_ADDRESS1', 'EMPLOYER_ADDRESS2',
       'EMPLOYER_CITY', 'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE',
       'EMPLOYER_COUNTRY', 'EMPLOYER_PROVINCE', 'EMPLOYER_PHONE',
       'EMPLOYER_PHONE_EXT', 'AGENT_ATTORNEY_NAME', 'AGENT_ATTORNEY_CITY',
       'AGENT_ATTORNEY_STATE', 'JOB_TITLE', 'SOC_CODE', 'SOC_NAME',
       'NAIC_CODE', 'TOTAL WORKERS', 'FULL_TIME_POSITION', 'PREVAILING_WAGE',
       'PW_UNIT_OF_PAY', 'PW_WAGE_LEVEL', 'PW_WAGE_SOURCE',
       'PW_WAGE_SOURCE_YEAR', 'PW_WAGE_SOURCE_OTHER', 'WAGE_RATE_OF_PAY',
       'WAGE_UNIT_OF_PAY', 'H-1B_DEPENDENT', 'WILLFUL VIOLATOR',
       'WORKSITE_CITY', 'WORKSITE_COUNTY', 'WORKSITE_STATE',
       'WORKSITE_POSTAL_CODE', 'NAICS_CODE', 'NAICS4', 'PAYUNIT', 'WAGE',
       'TOTAL_WORKERS', 'WAGESPLIT', 'WAGERANGE', 'WAGE_FROM', 'WAGE_TO',
       'WAGE_MEMO'],
      dtype='object')

In [50]:
vdata.dtypes

CASE_NUMBER                            object
CASE_STATUS                            object
CASE_SUBMITTED                 datetime64[ns]
DECISION_DATE                  datetime64[ns]
VISA_CLASS                             object
EMPLOYMENT_START_DATE          datetime64[ns]
EMPLOYMENT_END_DATE            datetime64[ns]
EMPLOYER_NAME                          object
EMPLOYER_BUSINESS_DBA                  object
EMPLOYER_ADDRESS                       object
EMPLOYER_CITY                          object
EMPLOYER_STATE                         object
EMPLOYER_POSTAL_CODE                   object
EMPLOYER_COUNTRY                       object
EMPLOYER_PROVINCE                      object
EMPLOYER_PHONE                         object
EMPLOYER_PHONE_EXT                     object
AGENT_REPRESENTING_EMPLOYER            object
AGENT_ATTORNEY_NAME                    object
AGENT_ATTORNEY_CITY                    object
AGENT_ATTORNEY_STATE                   object
JOB_TITLE                              object
SOC_CODE                               object
SOC_NAME                               object
NAICS_CODE                             object
TOTAL_WORKERS                           int64
NEW_EMPLOYMENT                          int64
CONTINUED_EMPLOYMENT                    int64
CHANGE_PREVIOUS_EMPLOYMENT              int64
NEW_CONCURRENT_EMPLOYMENT               int64
CHANGE_EMPLOYER                         int64
AMENDED_PETITION                        int64
FULL_TIME_POSITION                     object
PREVAILING_WAGE                       float64
PW_UNIT_OF_PAY                         object
PW_WAGE_LEVEL                          object
PW_SOURCE                              object
PW_SOURCE_YEAR                        float64
PW_SOURCE_OTHER                        object
WAGE_RATE_OF_PAY_FROM                 float64
WAGE_RATE_OF_PAY_TO                   float64
WAGE_UNIT_OF_PAY                       object
H1B_DEPENDENT                          object
WILLFUL_VIOLATOR                       object
SUPPORT_H1B                            object
LABOR_CON_AGREE                        object
PUBLIC_DISCLOSURE_LOCATION            float64
WORKSITE_CITY                          object
WORKSITE_COUNTY                        object
WORKSITE_STATE                         object
WORKSITE_POSTAL_CODE                   object
ORIGINAL_CERT_DATE             datetime64[ns]
dtype: object

In [108]:
#h1ba = h1bdat
#list(h1bdat)
#case status
vdata['CASE_STATUS'] = vdata['CASE_STATUS'].astype('category')
#visa type
#vdata['VISA_CLASS'] = vdata['VISA_CLASS'].astype('category')
#4-digit naics code for the employement
vdata['NAICS_CODE'] = vdata['NAICS_CODE'].astype('str')
vdata['NAICS4'] = vdata['NAICS_CODE'].apply(lambda x: x[:4])
#payunit
vdata['PAYUNIT'] = vdata['WAGE_UNIT_OF_PAY'].astype('category')
#employer location
##vdata['EMPLOYER_POSTAL_CODE'] = vdata['EMPLOYER_POSTAL_CODE']
#job title
##vdata['JOB_TITLE'] = vdata['JOB_TITLE']
#worksite city/state (when zipcodes not available)
##vdata['WORKSITE_CITY'] = vdata['LCA_CASE_WORKLOC1_CITY']
##vdata['WORKSITE_STATE'] = vdata['LCA_CASE_WORKLOC1_STATE']
#wage 
vdata['WAGE'] = vdata['WAGE_RATE_OF_PAY_FROM'] #YEAR 2016
vdata.loc[(np.isfinite(vdata['WAGE_RATE_OF_PAY_TO'])),'WAGE'] = 0.5*(vdata['WAGE_RATE_OF_PAY_FROM'] + vdata['WAGE_RATE_OF_PAY_TO'])
#vdata['WAGE'] = vdata['WAGE_RATE_OF_PAY'] #YEAR 2015

In [80]:
## only for 2015
vdata['TOTAL_WORKERS'] = vdata['TOTAL WORKERS']

In [81]:
### 2015 YES / 2016-17-18 NO
vdata['WAGESPLIT'] = vdata['WAGE'].str.split(' ')
vdata.head(10)

,CASE_NUMBER,CASE_STATUS,CASE_SUBMITTED,DECISION_DATE,VISA_CLASS,EMPLOYMENT_START_DATE,EMPLOYMENT_END_DATE,EMPLOYER_NAME,EMPLOYER_ADDRESS1,EMPLOYER_ADDRESS2,...,NAICS_CODE,NAICS4,PAYUNIT,WAGE,TOTAL_WORKERS,WAGESPLIT,WAGERANGE,WAGE_FROM,WAGE_TO,WAGE_MEMO
0,I-200-09121-701936,WITHDRAWN,2015-02-05,2015-02-05,H-1B,02/09/2015,02/28/2015,"MEDTRONIC, INC.",710 MEDTRONIC PARKWAY NE,NaN,...,334510,3345,Year,20000 -,1.0,"[20000, -]",NO,20000.00,NaN,NaN
1,I-200-09146-796321,CERTIFIED,2014-12-12,2014-12-18,H-1B,01/05/2015,01/04/2018,UNIVERSITY OF OKLAHOMA,905 ASP AVE,NEL BLDG 207,...,611310,6113,Year,85000.00 -,1.0,"[85000.00, -]",NO,85000.00,NaN,NaN
2,I-200-09180-329758,WITHDRAWN,2013-01-03,2014-12-15,H-1B,01/07/2013,01/06/2016,NOKIA INC.,6021 CONNECTION DRIVE,NaN,...,517212,5172,Year,94000 -,1.0,"[94000, -]",NO,94000.00,NaN,NaN
3,I-200-09183-259985,CERTIFIED,2015-03-10,2015-03-16,H-1B,09/07/2015,09/07/2018,"OMRON OILFIELD AND MARINE, INC.",9510 N. HOUSTON ROSSLYN ROAD,NaN,...,335314,3353,Year,66000 - 70000,2.0,"[66000, -, 70000]",YES,66000.00,70000.0,70000.0
4,I-200-09189-800933,CERTIFIED,2014-12-17,2014-12-23,H-1B,06/06/2015,06/05/2018,FEDERAL HOME LOAN MORTGAGE CO.,8250 JONES BRANCH DRIVE,MSA3E,...,522294,5222,Year,97000 - 143300,1.0,"[97000, -, 143300]",YES,97000.00,143300.0,143300.0
5,I-200-09195-662319,WITHDRAWN,2015-01-22,2015-01-22,H-1B,01/25/2015,01/25/2016,"APLARS, LLC",2885 COUNTRY DRIVE,STE. 175,...,454111,4541,Year,20000 -,1.0,"[20000, -]",NO,20000.00,NaN,NaN
6,I-200-09212-834534,CERTIFIED,2014-10-14,2014-10-20,H-1B,11/03/2014,11/02/2017,"VMWARE, INC.",3401 HILLVIEW AVE,NaN,...,541511,5415,Year,155000.00 -,1.0,"[155000.00, -]",NO,155000.00,NaN,NaN
7,I-200-09232-212049,CERTIFIED,2014-12-17,2014-12-23,H-1B,06/14/2015,06/13/2018,FEDERAL HOME LOAN MORTGAGE CORPORATION,8250 JONES BRANCH DRIVE,MSA3E,...,522294,5222,Year,64100 - 127000,1.0,"[64100, -, 127000]",YES,64100.00,127000.0,127000.0
8,I-200-09233-732656,CERTIFIED,2014-10-29,2014-11-04,H-1B,11/17/2014,11/16/2017,"VMWARE, INC.",3401 HILLVIEW AVE,NaN,...,541511,5415,Year,125000.00 -,1.0,"[125000.00, -]",NO,125000.00,NaN,NaN
9,I-200-09238-535119,DENIED,2015-03-19,2015-03-30,H-1B,09/17/2015,09/17/2018,IMAEX TRADING COMPANY,65 CRESTRIDGE DRIVE,NONE,...,424460,4244,Hour,22.46 -,1.0,"[22.46, -]",NO,22.46,NaN,NaN

In [106]:
vdata.dtypes

CASE_NUMBER                      object
CASE_STATUS                    category
CASE_SUBMITTED           datetime64[ns]
DECISION_DATE            datetime64[ns]
VISA_CLASS                       object
EMPLOYMENT_START_DATE            object
EMPLOYMENT_END_DATE              object
EMPLOYER_NAME                    object
EMPLOYER_ADDRESS1                object
EMPLOYER_ADDRESS2                object
EMPLOYER_CITY                    object
EMPLOYER_STATE                   object
EMPLOYER_POSTAL_CODE             object
EMPLOYER_COUNTRY                 object
EMPLOYER_PROVINCE                object
EMPLOYER_PHONE                  float64
EMPLOYER_PHONE_EXT              float64
AGENT_ATTORNEY_NAME              object
AGENT_ATTORNEY_CITY              object
AGENT_ATTORNEY_STATE             object
JOB_TITLE                        object
SOC_CODE                         object
SOC_NAME                         object
NAIC_CODE                        object
TOTAL WORKERS                   float64
FULL_TIME_POSITION               object
PREVAILING_WAGE                 float64
PW_UNIT_OF_PAY                   object
PW_WAGE_LEVEL                    object
PW_WAGE_SOURCE                   object
PW_WAGE_SOURCE_YEAR             float64
PW_WAGE_SOURCE_OTHER             object
WAGE_RATE_OF_PAY                 object
WAGE_UNIT_OF_PAY                 object
H-1B_DEPENDENT                   object
WILLFUL VIOLATOR                 object
WORKSITE_CITY                    object
WORKSITE_COUNTY                  object
WORKSITE_STATE                   object
WORKSITE_POSTAL_CODE             object
NAICS_CODE                       object
NAICS4                           object
PAYUNIT                        category
WAGE                             object
TOTAL_WORKERS                   float64
WAGESPLIT                        object
dtype: object

In [82]:
#2015 ONLY
vdata.loc[(vdata['WAGESPLIT'].apply(lambda x: len(x) == 3)),'WAGERANGE'] = 'YES'
vdata.loc[(vdata['WAGESPLIT'].apply(lambda x: len(x) == 2)),'WAGERANGE'] = 'NO'
vdata['WAGE_FROM'] = vdata['WAGESPLIT'].apply(lambda x: x[0])
vdata.loc[(vdata['WAGERANGE'] == 'YES'), 'WAGE_TO'] = vdata['WAGESPLIT'].apply(lambda x: x[len(x)-1])

In [86]:
vdata['WAGE_FROM'] = vdata['WAGE_FROM'].astype(float)

In [83]:
### IF above throws an error, use below 

## because there were values found with '-' which cannot be converted into float values
# i'm looking for cells that has '-' 
vdata[vdata['WAGE_FROM'].apply(lambda x: any(pd.Series(x).str.contains('-')))]

,CASE_NUMBER,CASE_STATUS,CASE_SUBMITTED,DECISION_DATE,VISA_CLASS,EMPLOYMENT_START_DATE,EMPLOYMENT_END_DATE,EMPLOYER_NAME,EMPLOYER_ADDRESS1,EMPLOYER_ADDRESS2,...,NAICS_CODE,NAICS4,PAYUNIT,WAGE,TOTAL_WORKERS,WAGESPLIT,WAGERANGE,WAGE_FROM,WAGE_TO,WAGE_MEMO
482,I-200-11314-326929,WITHDRAWN,2014-12-24,2014-12-30,H-1B,NaN,NaN,NaN,NaN,NaN,...,nan,nan,NaN,-,NaN,[-],NaN,-,NaN,NaN
8925,I-200-13102-386383,WITHDRAWN,2014-12-24,2014-12-30,H-1B,NaN,NaN,NaN,NaN,NaN,...,nan,nan,NaN,-,NaN,[-],NaN,-,NaN,NaN
16380,I-200-14064-847406,WITHDRAWN,2014-12-24,2014-12-24,H-1B,NaN,NaN,NaN,NaN,NaN,...,nan,nan,NaN,-,NaN,[-],NaN,-,NaN,NaN
17620,I-200-14073-483514,WITHDRAWN,2014-12-24,2014-12-24,H-1B,NaN,NaN,NaN,NaN,NaN,...,nan,nan,NaN,-,NaN,[-],NaN,-,NaN,NaN
19662,I-200-14099-816730,WITHDRAWN,2014-10-09,2014-10-16,H-1B,NaN,NaN,NaN,NaN,NaN,...,nan,nan,NaN,-,NaN,[-],NaN,-,NaN,NaN
22741,I-200-14195-455989,WITHDRAWN,2014-10-09,2014-10-16,H-1B,NaN,NaN,NaN,NaN,NaN,...,nan,nan,NaN,-,NaN,[-],NaN,-,NaN,NaN
25533,I-200-14258-290155,WITHDRAWN,2015-02-04,2015-02-06,H-1B,NaN,NaN,NaN,NaN,NaN,...,nan,nan,NaN,-,NaN,[-],NaN,-,NaN,NaN
35757,I-200-14279-171686,WITHDRAWN,2014-10-06,2014-10-06,H-1B,10/14/2014,10/13/2017,SOUTHWESTERN CONSOLIDATED DIRECTORY CO INC,719 N OAKHURST DR,NaN,...,511140,5111,Hour,-,1.0,[-],NaN,-,NaN,NaN
51430,I-200-14295-518850,WITHDRAWN,2015-01-12,2015-01-14,H-1B,NaN,NaN,NaN,NaN,NaN,...,nan,nan,NaN,-,NaN,[-],NaN,-,NaN,NaN
59209,I-200-14304-038500,WITHDRAWN,2015-02-04,2015-02-06,H-1B,NaN,NaN,NaN,NaN,NaN,...,336321,3363,NaN,-,NaN,[-],NaN,-,NaN,NaN
60512,I-200-14307-066091,WITHDRAWN,2015-01-12,2015-01-14,H-1B,NaN,NaN,NaN,NaN,NaN,...,nan,nan,NaN,-,NaN,[-],NaN,-,NaN,NaN
89221,I-200-14339-681526,WITHDRAWN,2014-12-05,2014-12-16,H-1B,09/01/2015,08/31/2018,NaN,NaN,NaN,...,nan,nan,NaN,-,1.0,[-],NaN,-,NaN,NaN
154129,I-200-15034-445583,DENIED,2015-02-25,2015-03-05,H-1B,08/03/2015,08/02/2018,SIGMA INVESTMENT HOLDINGS LLC,2300 VILLA HEIGHTS ROAD,NaN,...,3251,3251,Hour,22.69-61.55 - 46.02,1.0,"[22.69-61.55, -, 46.02]",YES,22.69-61.55,46.02,61.55
201510,I-200-15049-382092,WITHDRAWN,2015-02-18,2015-02-24,H-1B,NaN,NaN,NaN,NaN,NaN,...,nan,nan,NaN,-,NaN,[-],NaN,-,NaN,NaN
223060,I-200-15055-664971,WITHDRAWN,2015-03-02,2015-03-05,H-1B,NaN,NaN,NaN,NaN,NaN,...,nan,nan,NaN,-,NaN,[-],NaN,-,NaN,NaN
223603,I-200-15055-785381,WITHDRAWN,2015-02-24,2015-02-24,H-1B,NaN,NaN,NaN,NaN,NaN,...,nan,nan,NaN,-,NaN,[-],NaN,-,NaN,NaN
241056,I-200-15060-423031,WITHDRAWN,2015-03-02,2015-03-05,H-1B,NaN,NaN,NaN,NaN,NaN,...,nan,nan,NaN,-,NaN,[-],NaN,-,NaN,NaN
252633,I-200-15062-736928,DENIED,2015-03-03,2015-03-11,H-1B,09/01/2015,08/31/2018,NEXTGEN SOLUTIONS INC,8611 CONCORD MILLS BLVD,SUITE 117,...,54151,5415,NaN,-,1.0,[-],NaN,-,NaN,NaN
415651,I-200-15100-512434,DENIED,2015-04-10,2015-04-16,H-1B,NaN,NaN,NaN,NaN,NaN,...,nan,nan,NaN,-,5.0,[-],NaN,-,NaN,NaN
606135,I-201-15086-501364,DENIED,2015-04-08,2015-04-13,H-1B1 Chile,09/27/2015,09/30/2017,NISO CORP.,12550 BISCAYNE BLVD,SUITE 304B,...,541219,5412,NaN,-,1.0,[-],NaN,-,NaN,NaN

In [84]:
## selective data cleaning 2015
# 22.69-61.55, and rest just '-'
vdata.loc[(vdata['WAGE_FROM'] == '22.69-61.55'),'WAGE_TO'] = '61.55' #[22.69-61.55, -, 46.02]
vdata.loc[(vdata['WAGE_FROM'] == '22.69-61.55'),'WAGE_FROM'] = '22.69'
vdata.loc[(vdata['WAGE_FROM'] == '-'),'WAGE_FROM'] = 'NaN'

In [85]:
## more cleaning 
vdata.loc[(vdata['WAGE_TO'] == 'N/A'), 'WAGE_TO'] = 'NaN'
vdata.loc[(vdata['WAGE_TO'] == '+'), 'WAGE_TO'] = 'NaN'
vdata.loc[(vdata['WAGE_TO'] == '-'), 'WAGE_TO'] = 'NaN'
vdata.loc[(vdata['WAGE_TO'].notnull()), 'WAGE_MEMO'] = vdata['WAGE_TO'].astype(float)

#########
#### now re-run: vdatafull['WAGE_FROM'] = vdatafull['WAGE_FROM'].astype(float)

In [87]:
vdata['WAGE_FROM'] = vdata['WAGE_FROM'].astype(float)
vdata['WAGE_TO'] = vdata['WAGE_TO'].astype(float)
vdata['WAGE'] = vdata['WAGE_FROM']
vdata.loc[(np.isfinite(vdata['WAGE_TO'])),'WAGE'] = 0.5* (vdata['WAGE_FROM'] + vdata['WAGE_TO'])

In [109]:
vdata.columns

Index(['CASE_NUMBER', 'CASE_STATUS', 'CASE_SUBMITTED', 'DECISION_DATE',
       'VISA_CLASS', 'EMPLOYMENT_START_DATE', 'EMPLOYMENT_END_DATE',
       'EMPLOYER_NAME', 'EMPLOYER_BUSINESS_DBA', 'EMPLOYER_ADDRESS',
       'EMPLOYER_CITY', 'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE',
       'EMPLOYER_COUNTRY', 'EMPLOYER_PROVINCE', 'EMPLOYER_PHONE',
       'EMPLOYER_PHONE_EXT', 'AGENT_REPRESENTING_EMPLOYER',
       'AGENT_ATTORNEY_NAME', 'AGENT_ATTORNEY_CITY', 'AGENT_ATTORNEY_STATE',
       'JOB_TITLE', 'SOC_CODE', 'SOC_NAME', 'NAICS_CODE', 'TOTAL_WORKERS',
       'NEW_EMPLOYMENT', 'CONTINUED_EMPLOYMENT', 'CHANGE_PREVIOUS_EMPLOYMENT',
       'NEW_CONCURRENT_EMPLOYMENT', 'CHANGE_EMPLOYER', 'AMENDED_PETITION',
       'FULL_TIME_POSITION', 'PREVAILING_WAGE', 'PW_UNIT_OF_PAY',
       'PW_WAGE_LEVEL', 'PW_SOURCE', 'PW_SOURCE_YEAR', 'PW_SOURCE_OTHER',
       'WAGE_RATE_OF_PAY_FROM', 'WAGE_RATE_OF_PAY_TO', 'WAGE_UNIT_OF_PAY',
       'H1B_DEPENDENT', 'WILLFUL_VIOLATOR', 'SUPPORT_H1B', 'LABOR_CON_AGREE',
       'PUBLIC_DISCLOSURE_LOCATION', 'WORKSITE_CITY', 'WORKSITE_COUNTY',
       'WORKSITE_STATE', 'WORKSITE_POSTAL_CODE', 'ORIGINAL_CERT_DATE',
       'NAICS4', 'PAYUNIT', 'WAGE'],
      dtype='object')

In [90]:
# 2015 
vdata = vdata[['CASE_NUMBER','CASE_STATUS','CASE_SUBMITTED', 'DECISION_DATE',
               'VISA_CLASS','EMPLOYMENT_START_DATE', 'EMPLOYMENT_END_DATE',
               'EMPLOYER_NAME', 'EMPLOYER_ADDRESS1', 'EMPLOYER_ADDRESS2',
               'EMPLOYER_CITY', 'EMPLOYER_STATE','EMPLOYER_POSTAL_CODE',
               'EMPLOYER_COUNTRY', 'EMPLOYER_PROVINCE',# 'EMPLOYER_PHONE',
#       'EMPLOYER_PHONE_EXT', 'AGENT_ATTORNEY_NAME', 'AGENT_ATTORNEY_CITY',
      # 'AGENT_ATTORNEY_STATE', 
               'JOB_TITLE', 'SOC_CODE', 'SOC_NAME', 'NAICS_CODE',
               'NAICS4','TOTAL_WORKERS', 'FULL_TIME_POSITION', 'PREVAILING_WAGE',
       'PW_UNIT_OF_PAY', 'PW_WAGE_LEVEL', 'PW_WAGE_SOURCE',
       'PW_WAGE_SOURCE_YEAR', 'PW_WAGE_SOURCE_OTHER', 'WAGE_RATE_OF_PAY',
       'WAGE_UNIT_OF_PAY', 'H-1B_DEPENDENT', 'WILLFUL VIOLATOR',
       'WORKSITE_CITY', 'WORKSITE_COUNTY', 'WORKSITE_STATE',
               'WORKSITE_POSTAL_CODE','WAGE_FROM', 'WAGE_TO',
                'WAGE', 'PAYUNIT' ]] 
#'ORIGINAL_CERT_DATE' not in 2015, #'EMPLOYMENT_START_DATE','EMPLOYMENT_END_DATE','EMPLOYER_NAME','WORKSITE_POSTAL_CODE','JOB_TITLE',

In [54]:
#2016
vdata = vdata[['CASE_NUMBER', 'CASE_STATUS', 'CASE_SUBMITTED', 'DECISION_DATE',
       'VISA_CLASS', 'EMPLOYMENT_START_DATE', 'EMPLOYMENT_END_DATE',
       'EMPLOYER_NAME', 'EMPLOYER_ADDRESS', 'EMPLOYER_CITY', 'EMPLOYER_STATE',
       'EMPLOYER_POSTAL_CODE', 'EMPLOYER_COUNTRY', 'EMPLOYER_PROVINCE',
       #'EMPLOYER_PHONE', 'EMPLOYER_PHONE_EXT', 'AGENT_ATTORNEY_NAME',
       #'AGENT_ATTORNEY_CITY', 'AGENT_ATTORNEY_STATE', 
       'JOB_TITLE', 'SOC_CODE',
       'SOC_NAME', 'NAIC_CODE', 'TOTAL_WORKERS', 'FULL_TIME_POSITION',
       'PREVAILING_WAGE', 'PW_UNIT_OF_PAY', 'PW_WAGE_SOURCE', 'PW_SOURCE_YEAR',
       'PW_SOURCE_OTHER', 'WAGE_RATE_OF_PAY_FROM', 'WAGE_RATE_OF_PAY_TO',
       'WAGE_UNIT_OF_PAY', 'H-1B_DEPENDENT', 'WILLFUL_VIOLATOR',
       'WORKSITE_CITY', 'WORKSITE_COUNTY', 'WORKSITE_STATE',
       'WORKSITE_POSTAL_CODE', 'ORIGINAL_CERT_DATE', 'NAICS_CODE', 'NAICS4',
       'PAYUNIT', 'WAGE']]

KeyError: "['NAIC_CODE' 'PW_WAGE_SOURCE' 'H-1B_DEPENDENT'] not in index"

In [110]:
#2017
vdata = vdata[['CASE_NUMBER', 'CASE_STATUS', 'CASE_SUBMITTED', 'DECISION_DATE',
       'VISA_CLASS', 'EMPLOYMENT_START_DATE', 'EMPLOYMENT_END_DATE',
       'EMPLOYER_NAME', 'EMPLOYER_BUSINESS_DBA', 'EMPLOYER_ADDRESS',
       'EMPLOYER_CITY', 'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE',
       'EMPLOYER_COUNTRY', 'EMPLOYER_PROVINCE', #'EMPLOYER_PHONE',
       # 'EMPLOYER_PHONE_EXT', 'AGENT_REPRESENTING_EMPLOYER',
       # 'AGENT_ATTORNEY_NAME', 'AGENT_ATTORNEY_CITY', 'AGENT_ATTORNEY_STATE',
       'JOB_TITLE', 'SOC_CODE', 'SOC_NAME', 'NAICS_CODE', 'TOTAL_WORKERS',
       'NEW_EMPLOYMENT', 'CONTINUED_EMPLOYMENT', 'CHANGE_PREVIOUS_EMPLOYMENT',
       'NEW_CONCURRENT_EMPLOYMENT', 'CHANGE_EMPLOYER', 'AMENDED_PETITION',
       'FULL_TIME_POSITION', 'PREVAILING_WAGE', 'PW_UNIT_OF_PAY',
       'PW_WAGE_LEVEL', 'PW_SOURCE', 'PW_SOURCE_YEAR', 'PW_SOURCE_OTHER',
       'WAGE_RATE_OF_PAY_FROM', 'WAGE_RATE_OF_PAY_TO', 'WAGE_UNIT_OF_PAY',
       'H1B_DEPENDENT', 'WILLFUL_VIOLATOR', 'SUPPORT_H1B', 'LABOR_CON_AGREE',
       'PUBLIC_DISCLOSURE_LOCATION', 'WORKSITE_CITY', 'WORKSITE_COUNTY',
       'WORKSITE_STATE', 'WORKSITE_POSTAL_CODE', 'ORIGINAL_CERT_DATE',
       'NAICS4', 'PAYUNIT', 'WAGE']]

In [67]:
#2018
vdata = vdata[['CASE_NUMBER', 'CASE_STATUS', 'CASE_SUBMITTED', 'DECISION_DATE',
       'VISA_CLASS', 'EMPLOYMENT_START_DATE', 'EMPLOYMENT_END_DATE',
       'EMPLOYER_NAME', 'EMPLOYER_BUSINESS_DBA', 'EMPLOYER_ADDRESS',
       'EMPLOYER_CITY', 'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE',
       'EMPLOYER_COUNTRY', 'EMPLOYER_PROVINCE', #'EMPLOYER_PHONE',
       #'EMPLOYER_PHONE_EXT', 'AGENT_REPRESENTING_EMPLOYER',
       #'AGENT_ATTORNEY_NAME', 'AGENT_ATTORNEY_CITY', 'AGENT_ATTORNEY_STATE',
       'JOB_TITLE', 'SOC_CODE', 'SOC_NAME', 'NAICS_CODE', 'TOTAL_WORKERS',
       'NEW_EMPLOYMENT', 'CONTINUED_EMPLOYMENT', 'CHANGE_PREVIOUS_EMPLOYMENT',
       'NEW_CONCURRENT_EMPLOYMENT', 'CHANGE_EMPLOYER', 'AMENDED_PETITION',
       'FULL_TIME_POSITION', 'PREVAILING_WAGE', 'PW_UNIT_OF_PAY',
       'PW_WAGE_LEVEL', 'PW_SOURCE', 'PW_SOURCE_YEAR', 'PW_SOURCE_OTHER',
       'WAGE_RATE_OF_PAY_FROM', 'WAGE_RATE_OF_PAY_TO', 'WAGE_UNIT_OF_PAY',
       'H-1B_DEPENDENT', 'WILLFUL_VIOLATOR', 'SUPPORT_H1B', 'LABOR_CON_AGREE',
       'PUBLIC_DISCLOSURE_LOCATION', 'WORKSITE_CITY', 'WORKSITE_COUNTY',
       'WORKSITE_STATE', 'WORKSITE_POSTAL_CODE', 'ORIGINAL_CERT_DATE',
       'NAICS4', 'PAYUNIT', 'WAGE']]

In [111]:
len(vdata)

624650

In [91]:
#vdata.head()

In [112]:
vdata['YEAR'] = '17'
vdata = vdata.reset_index()

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [113]:
vdata['ID'] = vdata.index
vdata['ID'] = vdata['ID'].astype(str)
vdata['ROW_ID'] = vdata['YEAR'] + '-' + vdata['ID']

In [114]:
### WHEN EMEPLOYER ZIPCODE AVAILABLE 
#join/merging to get clean state fips of employer for each records
vdataem = pd.merge(vdata, georefz, how = 'left', left_on='EMPLOYER_POSTAL_CODE', right_on='zip', validate="m:m")
vdataem = vdataem.rename(columns = {'zip': 'EMP_ZIP', 'county': 'EMP_CNTY'})

In [115]:
vdataem = vdataem.drop_duplicates(subset=['ROW_ID'], keep = 'first') 
len(vdataem)

624650

In [116]:
## WHEN WORKSITE ZIPCODE AVAILABLE 
vdataewm = pd.merge(vdataem, georefz, how = 'left', left_on=['WORKSITE_POSTAL_CODE'] , right_on='zip', validate="m:m")
vdatafull = vdataewm.rename(columns = {'zip': 'WORK_ZIP', 'county': 'WORK_CNTY'})

In [117]:
vdatafull = vdatafull.drop_duplicates(subset=['ROW_ID'], keep = 'first') 
len(vdatafull)

624650

In [118]:
#vdata18 = vdatafull #ready
vdata17 = vdatafull #ready
#vdata16 = vdatafull #ready
#vdata15 = vdatafull #ready

In [101]:
len(vdata18)

94622

In [119]:
len(vdata17)

624650

In [103]:
len(vdata16)

647852

In [104]:
len(vdata15)

618804

In [120]:
vdata15['ORIGINAL_CERT_DATE'] = 'NaT'
vdata15['ORIGINAL_CERT_DATE'] = pd.to_datetime(vdata15['ORIGINAL_CERT_DATE'])

In [121]:
vdata15.dtypes

index                             int64
CASE_NUMBER                      object
CASE_STATUS                    category
CASE_SUBMITTED           datetime64[ns]
DECISION_DATE            datetime64[ns]
VISA_CLASS                       object
EMPLOYMENT_START_DATE            object
EMPLOYMENT_END_DATE              object
EMPLOYER_NAME                    object
EMPLOYER_ADDRESS1                object
EMPLOYER_ADDRESS2                object
EMPLOYER_CITY                    object
EMPLOYER_STATE                   object
EMPLOYER_POSTAL_CODE             object
EMPLOYER_COUNTRY                 object
EMPLOYER_PROVINCE                object
JOB_TITLE                        object
SOC_CODE                         object
SOC_NAME                         object
NAICS_CODE                       object
NAICS4                           object
TOTAL_WORKERS                   float64
FULL_TIME_POSITION               object
PREVAILING_WAGE                 float64
PW_UNIT_OF_PAY                   object
PW_WAGE_LEVEL                    object
PW_WAGE_SOURCE                   object
PW_WAGE_SOURCE_YEAR             float64
PW_WAGE_SOURCE_OTHER             object
WAGE_RATE_OF_PAY                 object
WAGE_UNIT_OF_PAY                 object
H-1B_DEPENDENT                   object
WILLFUL VIOLATOR                 object
WORKSITE_CITY                    object
WORKSITE_COUNTY                  object
WORKSITE_STATE                   object
WORKSITE_POSTAL_CODE             object
WAGE_FROM                       float64
WAGE_TO                         float64
WAGE                            float64
PAYUNIT                        category
YEAR                             object
ID                               object
ROW_ID                           object
EMP_ZIP                          object
EMP_CNTY                         object
WORK_ZIP                         object
WORK_CNTY                        object
ORIGINAL_CERT_DATE       datetime64[ns]
dtype: object

In [122]:
vdata15.to_csv("../prepped/vdata15.csv")
vdata16.to_csv("../prepped/vdata16.csv")
vdata17.to_csv("../prepped/vdata17.csv")
vdata18.to_csv("../prepped/vdata18.csv")

In [540]:
len(vdata15.columns) #50
vdata15.columns

Index(['index', 'CASE_NUMBER', 'CASE_STATUS', 'CASE_SUBMITTED',
       'DECISION_DATE', 'VISA_CLASS', 'EMPLOYMENT_START_DATE',
       'EMPLOYMENT_END_DATE', 'EMPLOYER_NAME', 'EMPLOYER_ADDRESS1',
       'EMPLOYER_ADDRESS2', 'EMPLOYER_CITY', 'EMPLOYER_STATE',
       'EMPLOYER_POSTAL_CODE', 'EMPLOYER_COUNTRY', 'EMPLOYER_PROVINCE',
       'JOB_TITLE', 'SOC_CODE', 'SOC_NAME', 'NAICS_CODE', 'NAICS4',
       'TOTAL_WORKERS', 'FULL_TIME_POSITION', 'PREVAILING_WAGE',
       'PW_UNIT_OF_PAY', 'PW_WAGE_LEVEL', 'PW_WAGE_SOURCE',
       'PW_WAGE_SOURCE_YEAR', 'PW_WAGE_SOURCE_OTHER', 'WAGE_RATE_OF_PAY',
       'WAGE_UNIT_OF_PAY', 'H-1B_DEPENDENT', 'WILLFUL VIOLATOR',
       'WORKSITE_CITY', 'WORKSITE_COUNTY', 'WORKSITE_STATE',
       'WORKSITE_POSTAL_CODE', 'WAGE_FROM', 'WAGE_TO', 'WAGE', 'PAYUNIT',
       'YEAR', 'ID', 'ROW_ID', 'EMP_ZIP', 'EMP_CNTY', 'WORK_ZIP', 'WORK_CNTY',
       'ORIGINAL_CERT_DATE', 'NAICS5'],
      dtype='object')

In [545]:
vdata18.head()

,index,CASE_NUMBER,CASE_STATUS,CASE_SUBMITTED,DECISION_DATE,VISA_CLASS,EMPLOYMENT_START_DATE,EMPLOYMENT_END_DATE,EMPLOYER_NAME,EMPLOYER_BUSINESS_DBA,EMPLOYER_ADDRESS,EMPLOYER_CITY,EMPLOYER_STATE,EMPLOYER_POSTAL_CODE,EMPLOYER_COUNTRY,EMPLOYER_PROVINCE,JOB_TITLE,SOC_CODE,SOC_NAME,NAICS_CODE,TOTAL_WORKERS,NEW_EMPLOYMENT,CONTINUED_EMPLOYMENT,CHANGE_PREVIOUS_EMPLOYMENT,NEW_CONCURRENT_EMPLOYMENT,CHANGE_EMPLOYER,AMENDED_PETITION,FULL_TIME_POSITION,PREVAILING_WAGE,PW_UNIT_OF_PAY,PW_WAGE_LEVEL,PW_SOURCE,PW_SOURCE_YEAR,PW_SOURCE_OTHER,WAGE_RATE_OF_PAY_FROM,WAGE_RATE_OF_PAY_TO,WAGE_UNIT_OF_PAY,H-1B_DEPENDENT,WILLFUL_VIOLATOR,SUPPORT_H1B,LABOR_CON_AGREE,PUBLIC_DISCLOSURE_LOCATION,WORKSITE_CITY,WORKSITE_COUNTY,WORKSITE_STATE,WORKSITE_POSTAL_CODE,ORIGINAL_CERT_DATE,NAICS4,PAYUNIT,WAGE,YEAR,ID,ROW_ID,EMP_ZIP,EMP_CNTY,WORK_ZIP,WORK_CNTY,NAICS5
0,0,I-200-14276-496918,CERTIFIED-WITHDRAWN,2014-10-08,2017-12-14,H-1B,2015-03-17,2018-03-16,"EXPICIENT, INC",NaN,26 CHESTNUT STREET,ANDOVER,MA,01810,UNITED STATES OF AMERICA,NaN,COMPUTER SYSTEMS ANALYST,15-1121,COMPUTER SYSTEMS ANALYSTS,541511,1,0,1,0,0,0,0,Y,76211.0,Year,Level II,OES,2014.0,OFLC ONLINE DATA CENTER,90000.00,0.0,Year,Y,N,Y,Y,NaN,UNION,UNION COUNTY,MA,07083,2014-10-14,5415,Year,45000.000,18,0,18-0,01810,25009,07083,34013,54151
2,1,I-200-14277-767454,CERTIFIED-WITHDRAWN,2014-10-04,2017-10-17,H-1B,2014-11-17,2017-11-16,BAYLOR COLLEGE OF MEDICINE,NaN,ONE BAYLOR PLAZA,HOUSTON,TX,77030,UNITED STATES OF AMERICA,NaN,POSTDOCTORAL ASSOCIATE/FELLOW,19-1021,BIOCHEMISTS AND BIOPHYSICISTS,611310,1,1,0,0,0,0,0,Y,42578.0,Year,Level I,OES,2014.0,NaN,48000.00,0.0,Year,N,N,NaN,NaN,NaN,HOUSTON,HARRIS,TX,77030,2014-10-08,6113,Year,24000.000,18,1,18-1,77030,48201,77030,48201,61131
3,2,I-200-14280-228909,CERTIFIED-WITHDRAWN,2014-10-07,2017-10-10,H-1B,2014-12-01,2017-11-30,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,NaN,77 MASSACHUSETTS AVENUE,CAMBRIDGE,MA,02139,UNITED STATES OF AMERICA,NaN,RESEARCH SCIENTIST,19-2032,MATERIALS SCIENTISTS,6113,1,1,0,0,0,0,0,Y,67912.0,Year,Level IV,OES,2014.0,NaN,79500.00,0.0,Year,N,N,NaN,NaN,NaN,CAMBRIDGE,MIDDLESEX,MA,02139,2014-10-10,6113,Year,39750.000,18,2,18-2,02139,25017,02139,25017,6113
4,3,I-200-14280-196484,WITHDRAWN,2014-10-09,2017-12-07,H-1B,2015-01-01,2017-12-31,"ETEK IT SERVICES, INC.",NaN,830 E HIGGINS RD,SCHAUMBURG,IL,60173,UNITED STATES OF AMERICA,NaN,PROGRAMMER ANALYST,15-1131,COMPUTER PROGRAMMERS,541511,1,0,1,0,0,0,0,Y,74630.0,Year,Level II,Other,2014.0,FLC DATA CENTER ONLINE WAGE LIBRARY,74630.00,0.0,Year,Y,N,Y,NaN,NaN,LAWRENCEVILLE,GWINNETT,GA,30044,NaT,5415,Year,37315.000,18,3,18-3,60173,17031,30044,13135,54151
5,4,I-200-13354-729924,CERTIFIED-WITHDRAWN,2014-11-25,2017-11-08,H-1B,2014-12-21,2017-12-20,MVP SERVICE CORP.,MVP HEALTH CARE,625 STATE STREET,SCHENECTADY,NY,12305,UNITED STATES OF AMERICA,NaN,NETWORK ENGINEER,15-1133,"SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE",621491,1,0,0,0,0,1,0,Y,91374.0,Year,Level II,OES,2014.0,OFLC ONLINE DATA CENTER,92000.09,0.0,Year,N,N,NaN,NaN,NaN,TARRYTOWN,WESTCHESTER,NY,10591-5455,2014-12-02,6214,Year,46000.045,18,4,18-4,12305,36093,NaN,NaN,62149

In [144]:
vdata15['NAICS5'] = vdata15['NAICS_CODE'].apply(lambda x: x[:5])
vdata16['NAICS5'] = vdata16['NAICS_CODE'].apply(lambda x: x[:5])
vdata17['NAICS5'] = vdata17['NAICS_CODE'].apply(lambda x: x[:5])
vdata18['NAICS5'] = vdata18['NAICS_CODE'].apply(lambda x: x[:5])

In [ ]:
#parked: vdata15, vdata16, vdata17, vdata18

In [608]:
vvdata15 = vdata15.rename(columns = {'index' : 'index', 
'CASE_NUMBER' : 'case_num', 
'CASE_STATUS' : 'case_status', 
'CASE_SUBMITTED' : 'submit_date', 
'DECISION_DATE' : 'decision_date', 
'VISA_CLASS' : 'visa_class', 
'EMPLOYMENT_START_DATE' : 'emp_start', 
'EMPLOYMENT_END_DATE' : 'emp_end', 
'EMPLOYER_NAME' : 'emp_name', 
'EMPLOYER_ADDRESS1' : 'emp_address', 
'EMPLOYER_CITY' : 'emp_city', 
'EMPLOYER_STATE' : 'emp_st', 
'EMPLOYER_POSTAL_CODE' : 'emp_zip', 
'EMPLOYER_COUNTRY' : 'emp_cntry', 
'JOB_TITLE' : 'job', 
'SOC_CODE' : 'soc_code', 
'SOC_NAME' : 'soc_name', 
'NAICS_CODE' : 'naics_full', 
'NAICS4' : 'naics4', 
'TOTAL_WORKERS' : 'tot_workers', 
'FULL_TIME_POSITION' : 'full_time', 
'PREVAILING_WAGE' : 'pw', 
'PW_UNIT_OF_PAY' : 'pw_payunit', 
'PW_WAGE_LEVEL' : 'pw_level', 
'WAGE_RATE_OF_PAY' : 'wage_org', 
'WAGE_UNIT_OF_PAY' : 'wage_payunit', 
'H-1B_DEPENDENT' : 'dependent', 
'WILLFUL VIOLATOR' : 'violator', 
'WORKSITE_CITY' : 'work_city', 
'WORKSITE_COUNTY' : 'work_cnty', 
'WORKSITE_STATE' : 'work_st', 
'WAGE_FROM' : 'wage_from', 
'WAGE_TO' : 'wage_to', 
'WAGE' : 'wage', 
'PAYUNIT' : 'payunit', 
'YEAR' : 'year', 
'ID' : 'id', 
'ROW_ID' : 'row_id', 
'EMP_ZIP' : 'emp_zip', 
'EMP_CNTY' : 'emp_cfips', 
'WORK_ZIP' : 'work_zip', 
'WORK_CNTY' : 'work_cfips', 
'ORIGINAL_CERT_DATE' : 'org_cert_date', 
'NAICS5' : 'naics5'})

In [609]:
vvdata15.columns

Index(['index', 'case_num', 'case_status', 'submit_date', 'decision_date',
       'visa_class', 'emp_start', 'emp_end', 'emp_name', 'emp_address',
       'EMPLOYER_ADDRESS2', 'emp_city', 'emp_st', 'emp_zip', 'emp_cntry',
       'EMPLOYER_PROVINCE', 'job', 'soc_code', 'soc_name', 'naics_full',
       'naics4', 'tot_workers', 'full_time', 'pw', 'pw_payunit', 'pw_level',
       'PW_WAGE_SOURCE', 'PW_WAGE_SOURCE_YEAR', 'PW_WAGE_SOURCE_OTHER',
       'wage_org', 'wage_payunit', 'dependent', 'violator', 'work_city',
       'work_cnty', 'work_st', 'WORKSITE_POSTAL_CODE', 'wage_from', 'wage_to',
       'wage', 'payunit', 'year', 'id', 'row_id', 'emp_zip', 'emp_cfips',
       'work_zip', 'work_cfips', 'org_cert_date', 'naics5'],
      dtype='object')

In [610]:
vvdata15 = vvdata15[['index',
'case_num',
'case_status',
'submit_date',
'decision_date',
'visa_class',
'emp_start',
'emp_end',
'emp_name',
'emp_address',
'emp_city',
'emp_st',
'emp_zip',
'emp_cntry',
'job',
'soc_code',
'soc_name',
'naics_full',
'naics4',
'tot_workers',
'full_time',
'pw',
'pw_payunit',
'pw_level',
#'wage_org',
#'wage_payunit',
'dependent',
'violator',
'work_city',
'work_cnty',
'work_st',
'wage_from',
'wage_to',
'wage',
'payunit',
'year',
'id',
'row_id',
'emp_zip',
'emp_cfips',
'work_zip',
'work_cfips',
'org_cert_date',
'naics5']]

In [489]:
len(vdata16.columns) #47
vdata16.columns

Index(['index', 'CASE_NUMBER', 'CASE_STATUS', 'CASE_SUBMITTED',
       'DECISION_DATE', 'VISA_CLASS', 'EMPLOYMENT_START_DATE',
       'EMPLOYMENT_END_DATE', 'EMPLOYER_NAME', 'EMPLOYER_ADDRESS',
       'EMPLOYER_CITY', 'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE',
       'EMPLOYER_COUNTRY', 'EMPLOYER_PROVINCE', 'JOB_TITLE', 'SOC_CODE',
       'SOC_NAME', 'NAIC_CODE', 'TOTAL_WORKERS', 'FULL_TIME_POSITION',
       'PREVAILING_WAGE', 'PW_UNIT_OF_PAY', 'PW_WAGE_SOURCE', 'PW_SOURCE_YEAR',
       'PW_SOURCE_OTHER', 'WAGE_RATE_OF_PAY_FROM', 'WAGE_RATE_OF_PAY_TO',
       'WAGE_UNIT_OF_PAY', 'H-1B_DEPENDENT', 'WILLFUL_VIOLATOR',
       'WORKSITE_CITY', 'WORKSITE_COUNTY', 'WORKSITE_STATE',
       'WORKSITE_POSTAL_CODE', 'ORIGINAL_CERT_DATE', 'NAICS_CODE', 'NAICS4',
       'PAYUNIT', 'WAGE', 'YEAR', 'ID', 'ROW_ID', 'EMP_ZIP', 'EMP_CNTY',
       'WORK_ZIP', 'WORK_CNTY', 'NAICS5'],
      dtype='object')

In [611]:
vvdata16 = vdata16.rename(columns = {'index' : 'index', 
'CASE_NUMBER' : 'case_num', 
'CASE_STATUS' : 'case_status', 
'CASE_SUBMITTED' : 'submit_date', 
'DECISION_DATE' : 'decision_date', 
'VISA_CLASS' : 'visa_class', 
'EMPLOYMENT_START_DATE' : 'emp_start', 
'EMPLOYMENT_END_DATE' : 'emp_end', 
'EMPLOYER_NAME' : 'emp_name', 
'EMPLOYER_ADDRESS' : 'emp_address', 
'EMPLOYER_CITY' : 'emp_city', 
'EMPLOYER_STATE' : 'emp_st', 
'EMPLOYER_POSTAL_CODE' : 'emp_zip', 
'EMPLOYER_COUNTRY' : 'emp_cntry', 
'JOB_TITLE' : 'job', 
'SOC_CODE' : 'soc_code', 
'SOC_NAME' : 'soc_name', 
'NAICS4' : 'naics4', 
'TOTAL_WORKERS' : 'tot_workers', 
'FULL_TIME_POSITION' : 'full_time', 
'PREVAILING_WAGE' : 'pw', 
'PW_UNIT_OF_PAY' : 'pw_payunit', 
'WAGE_RATE_OF_PAY_FROM' : 'wage_from', 
'WAGE_RATE_OF_PAY_TO' : 'wage_to', 
'H-1B_DEPENDENT' : 'dependent', 
'WILLFUL_VIOLATOR' : 'violator', 
'WORKSITE_CITY' : 'work_city', 
'WORKSITE_COUNTY' : 'work_cnty', 
'WORKSITE_STATE' : 'work_st', 
'WAGE' : 'wage', 
'PAYUNIT' : 'payunit', 
'YEAR' : 'year', 
'ID' : 'id', 
'ROW_ID' : 'row_id', 
'EMP_ZIP' : 'emp_zip', 
'EMP_CNTY' : 'emp_cfips', 
'WORK_ZIP' : 'work_zip', 
'WORK_CNTY' : 'work_cfips', 
'ORIGINAL_CERT_DATE' : 'org_cert_date', 
'NAICS5' : 'naics5', 
'NAICS_CODE' : 'naics_full'})

In [612]:
vvdata16 = vvdata16[['index',
'case_num',
'case_status',
'submit_date',
'decision_date',
'visa_class',
'emp_start',
'emp_end',
'emp_name',
'emp_address',
'emp_city',
'emp_st',
'emp_zip',
'emp_cntry',
'job',
'soc_code',
'soc_name',
'naics4',
'tot_workers',
'full_time',
'pw',
'pw_payunit',
'wage_from',
'wage_to',
'dependent',
'violator',
'work_city',
'work_cnty',
'work_st',
'wage',
'payunit',
'year',
'id',
'row_id',
'emp_zip',
'emp_cfips',
'work_zip',
'work_cfips',
'org_cert_date',
'naics5',
'naics_full']]

In [160]:
len(vdata17.columns) #57
vdata17.columns

Index(['index', 'CASE_NUMBER', 'CASE_STATUS', 'CASE_SUBMITTED',
       'DECISION_DATE', 'VISA_CLASS', 'EMPLOYMENT_START_DATE',
       'EMPLOYMENT_END_DATE', 'EMPLOYER_NAME', 'EMPLOYER_BUSINESS_DBA',
       'EMPLOYER_ADDRESS', 'EMPLOYER_CITY', 'EMPLOYER_STATE',
       'EMPLOYER_POSTAL_CODE', 'EMPLOYER_COUNTRY', 'EMPLOYER_PROVINCE',
       'JOB_TITLE', 'SOC_CODE', 'SOC_NAME', 'NAICS_CODE', 'TOTAL_WORKERS',
       'NEW_EMPLOYMENT', 'CONTINUED_EMPLOYMENT', 'CHANGE_PREVIOUS_EMPLOYMENT',
       'NEW_CONCURRENT_EMPLOYMENT', 'CHANGE_EMPLOYER', 'AMENDED_PETITION',
       'FULL_TIME_POSITION', 'PREVAILING_WAGE', 'PW_UNIT_OF_PAY',
       'PW_WAGE_LEVEL', 'PW_SOURCE', 'PW_SOURCE_YEAR', 'PW_SOURCE_OTHER',
       'WAGE_RATE_OF_PAY_FROM', 'WAGE_RATE_OF_PAY_TO', 'WAGE_UNIT_OF_PAY',
       'H1B_DEPENDENT', 'WILLFUL_VIOLATOR', 'SUPPORT_H1B', 'LABOR_CON_AGREE',
       'PUBLIC_DISCLOSURE_LOCATION', 'WORKSITE_CITY', 'WORKSITE_COUNTY',
       'WORKSITE_STATE', 'WORKSITE_POSTAL_CODE', 'ORIGINAL_CERT_DATE',
       'NAICS4', 'PAYUNIT', 'WAGE', 'YEAR', 'ID', 'ROW_ID', 'EMP_ZIP',
       'EMP_CNTY', 'WORK_ZIP', 'WORK_CNTY', 'NAICS5'],
      dtype='object')

In [613]:
vvdata17 = vdata17.rename(columns = {'index' : 'index', 
'CASE_NUMBER' : 'case_num', 
'CASE_STATUS' : 'case_status', 
'CASE_SUBMITTED' : 'submit_date', 
'DECISION_DATE' : 'decision_date', 
'VISA_CLASS' : 'visa_class', 
'EMPLOYMENT_START_DATE' : 'emp_start', 
'EMPLOYMENT_END_DATE' : 'emp_end', 
'EMPLOYER_NAME' : 'emp_name', 
'EMPLOYER_ADDRESS' : 'emp_address', 
'EMPLOYER_CITY' : 'emp_city', 
'EMPLOYER_STATE' : 'emp_st', 
'EMPLOYER_POSTAL_CODE' : 'emp_zip', 
'EMPLOYER_COUNTRY' : 'emp_cntry', 
'JOB_TITLE' : 'job', 
'SOC_CODE' : 'soc_code', 
'SOC_NAME' : 'soc_name', 
'NAICS4' : 'naics4', 
'TOTAL_WORKERS' : 'tot_workers', 
'FULL_TIME_POSITION' : 'full_time', 
'PREVAILING_WAGE' : 'pw', 
'PW_UNIT_OF_PAY' : 'pw_payunit', 
'WAGE_RATE_OF_PAY_FROM' : 'wage_from', 
'WAGE_RATE_OF_PAY_TO' : 'wage_to', 
'H1B_DEPENDENT' : 'dependent', 
'WILLFUL_VIOLATOR' : 'violator', 
'WORKSITE_CITY' : 'work_city', 
'WORKSITE_COUNTY' : 'work_cnty', 
'WORKSITE_STATE' : 'work_st', 
'WAGE' : 'wage', 
'PAYUNIT' : 'payunit', 
'YEAR' : 'year', 
'ID' : 'id', 
'ROW_ID' : 'row_id', 
'EMP_ZIP' : 'emp_zip', 
'EMP_CNTY' : 'emp_cfips', 
'WORK_ZIP' : 'work_zip', 
'WORK_CNTY' : 'work_cfips', 
'ORIGINAL_CERT_DATE' : 'org_cert_date', 
'NAICS5' : 'naics5', 
'NAICS_CODE' : 'naics_full'})

In [614]:
vvdata17 = vvdata17[['index',
'case_num',
'case_status',
'submit_date',
'decision_date',
'visa_class',
'emp_start',
'emp_end',
'emp_name',
'emp_address',
'emp_city',
'emp_st',
'emp_zip',
'emp_cntry',
'job',
'soc_code',
'soc_name',
'naics4',
'tot_workers',
'full_time',
'pw',
'pw_payunit',
'wage_from',
'wage_to',
'dependent',
'violator',
'work_city',
'work_cnty',
'work_st',
'wage',
'payunit',
'year',
'id',
'row_id',
'emp_zip',
'emp_cfips',
'work_zip',
'work_cfips',
'org_cert_date',
'naics5',
'naics_full']]

In [484]:
len(vdata18.columns) #57
vdata18.columns

Index(['index', 'CASE_NUMBER', 'CASE_STATUS', 'CASE_SUBMITTED',
       'DECISION_DATE', 'VISA_CLASS', 'EMPLOYMENT_START_DATE',
       'EMPLOYMENT_END_DATE', 'EMPLOYER_NAME', 'EMPLOYER_BUSINESS_DBA',
       'EMPLOYER_ADDRESS', 'EMPLOYER_CITY', 'EMPLOYER_STATE',
       'EMPLOYER_POSTAL_CODE', 'EMPLOYER_COUNTRY', 'EMPLOYER_PROVINCE',
       'JOB_TITLE', 'SOC_CODE', 'SOC_NAME', 'NAICS_CODE', 'TOTAL_WORKERS',
       'NEW_EMPLOYMENT', 'CONTINUED_EMPLOYMENT', 'CHANGE_PREVIOUS_EMPLOYMENT',
       'NEW_CONCURRENT_EMPLOYMENT', 'CHANGE_EMPLOYER', 'AMENDED_PETITION',
       'FULL_TIME_POSITION', 'PREVAILING_WAGE', 'PW_UNIT_OF_PAY',
       'PW_WAGE_LEVEL', 'PW_SOURCE', 'PW_SOURCE_YEAR', 'PW_SOURCE_OTHER',
       'WAGE_RATE_OF_PAY_FROM', 'WAGE_RATE_OF_PAY_TO', 'WAGE_UNIT_OF_PAY',
       'H-1B_DEPENDENT', 'WILLFUL_VIOLATOR', 'SUPPORT_H1B', 'LABOR_CON_AGREE',
       'PUBLIC_DISCLOSURE_LOCATION', 'WORKSITE_CITY', 'WORKSITE_COUNTY',
       'WORKSITE_STATE', 'WORKSITE_POSTAL_CODE', 'ORIGINAL_CERT_DATE',
       'NAICS4', 'PAYUNIT', 'WAGE', 'YEAR', 'ID', 'ROW_ID', 'EMP_ZIP',
       'EMP_CNTY', 'WORK_ZIP', 'WORK_CNTY', 'NAICS5'],
      dtype='object')

In [615]:
vvdata18 = vdata18.rename(columns = {'index' : 'index', 
'CASE_NUMBER' : 'case_num', 
'CASE_STATUS' : 'case_status', 
'CASE_SUBMITTED' : 'submit_date', 
'DECISION_DATE' : 'decision_date', 
'VISA_CLASS' : 'visa_class', 
'EMPLOYMENT_START_DATE' : 'emp_start', 
'EMPLOYMENT_END_DATE' : 'emp_end', 
'EMPLOYER_NAME' : 'emp_name', 
'EMPLOYER_ADDRESS' : 'emp_address', 
'EMPLOYER_CITY' : 'emp_city', 
'EMPLOYER_STATE' : 'emp_st', 
'EMPLOYER_POSTAL_CODE' : 'emp_zip', 
'EMPLOYER_COUNTRY' : 'emp_cntry', 
'JOB_TITLE' : 'job', 
'SOC_CODE' : 'soc_code', 
'SOC_NAME' : 'soc_name', 
'NAICS4' : 'naics4', 
'TOTAL_WORKERS' : 'tot_workers', 
'FULL_TIME_POSITION' : 'full_time', 
'PREVAILING_WAGE' : 'pw', 
'PW_UNIT_OF_PAY' : 'pw_payunit', 
'WAGE_RATE_OF_PAY_FROM' : 'wage_from', 
'WAGE_RATE_OF_PAY_TO' : 'wage_to', 
'H-1B_DEPENDENT' : 'dependent', 
'WILLFUL_VIOLATOR' : 'violator', 
'WORKSITE_CITY' : 'work_city', 
'WORKSITE_COUNTY' : 'work_cnty', 
'WORKSITE_STATE' : 'work_st', 
'WAGE' : 'wage', 
'PAYUNIT' : 'payunit', 
'YEAR' : 'year', 
'ID' : 'id', 
'ROW_ID' : 'row_id', 
'EMP_ZIP' : 'emp_zip', 
'EMP_CNTY' : 'emp_cfips', 
'WORK_ZIP' : 'work_zip', 
'WORK_CNTY' : 'work_cfips', 
'ORIGINAL_CERT_DATE' : 'org_cert_date', 
'NAICS5' : 'naics5', 
'NAICS_CODE' : 'naics_full'})

In [616]:
vvdata18 = vvdata18[['index',
'case_num',
'case_status',
'submit_date',
'decision_date',
'visa_class',
'emp_start',
'emp_end',
'emp_name',
'emp_address',
'emp_city',
'emp_st',
'emp_zip',
'emp_cntry',
'job',
'soc_code',
'soc_name',
'naics4',
'tot_workers',
'full_time',
'pw',
'pw_payunit',
'wage_from',
'wage_to',
'dependent',
'violator',
'work_city',
'work_cnty',
'work_st',
'wage',
'payunit',
'year',
'id',
'row_id',
'emp_zip',
'emp_cfips',
'work_zip',
'work_cfips',
'org_cert_date',
'naics5',
'naics_full']]

In [176]:
#len(vvdata15.columns) #618804 records #48 cols
#len(vvdata16) #647852 records #43 cols
#len(vvdata17) #624650 records #43 cols
len(vvdata18) #94622 records #43 cols

94622

In [617]:
vvdata18.head()

,index,case_num,case_status,submit_date,decision_date,visa_class,emp_start,emp_end,emp_name,emp_address,emp_city,emp_st,emp_zip,emp_zip,emp_cntry,job,soc_code,soc_name,naics4,tot_workers,full_time,pw,pw_payunit,wage_from,wage_to,dependent,violator,work_city,work_cnty,work_st,wage,payunit,year,id,row_id,emp_zip,emp_zip,emp_cfips,work_zip,work_cfips,org_cert_date,naics5,naics_full
0,0,I-200-14276-496918,CERTIFIED-WITHDRAWN,2014-10-08,2017-12-14,H-1B,2015-03-17,2018-03-16,"EXPICIENT, INC",26 CHESTNUT STREET,ANDOVER,MA,01810,01810,UNITED STATES OF AMERICA,COMPUTER SYSTEMS ANALYST,15-1121,COMPUTER SYSTEMS ANALYSTS,5415,1,Y,76211.0,Year,90000.00,0.0,Y,N,UNION,UNION COUNTY,MA,45000.000,Year,18,0,18-0,01810,01810,25009,07083,34013,2014-10-14,54151,541511
2,1,I-200-14277-767454,CERTIFIED-WITHDRAWN,2014-10-04,2017-10-17,H-1B,2014-11-17,2017-11-16,BAYLOR COLLEGE OF MEDICINE,ONE BAYLOR PLAZA,HOUSTON,TX,77030,77030,UNITED STATES OF AMERICA,POSTDOCTORAL ASSOCIATE/FELLOW,19-1021,BIOCHEMISTS AND BIOPHYSICISTS,6113,1,Y,42578.0,Year,48000.00,0.0,N,N,HOUSTON,HARRIS,TX,24000.000,Year,18,1,18-1,77030,77030,48201,77030,48201,2014-10-08,61131,611310
3,2,I-200-14280-228909,CERTIFIED-WITHDRAWN,2014-10-07,2017-10-10,H-1B,2014-12-01,2017-11-30,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,77 MASSACHUSETTS AVENUE,CAMBRIDGE,MA,02139,02139,UNITED STATES OF AMERICA,RESEARCH SCIENTIST,19-2032,MATERIALS SCIENTISTS,6113,1,Y,67912.0,Year,79500.00,0.0,N,N,CAMBRIDGE,MIDDLESEX,MA,39750.000,Year,18,2,18-2,02139,02139,25017,02139,25017,2014-10-10,6113,6113
4,3,I-200-14280-196484,WITHDRAWN,2014-10-09,2017-12-07,H-1B,2015-01-01,2017-12-31,"ETEK IT SERVICES, INC.",830 E HIGGINS RD,SCHAUMBURG,IL,60173,60173,UNITED STATES OF AMERICA,PROGRAMMER ANALYST,15-1131,COMPUTER PROGRAMMERS,5415,1,Y,74630.0,Year,74630.00,0.0,Y,N,LAWRENCEVILLE,GWINNETT,GA,37315.000,Year,18,3,18-3,60173,60173,17031,30044,13135,NaT,54151,541511
5,4,I-200-13354-729924,CERTIFIED-WITHDRAWN,2014-11-25,2017-11-08,H-1B,2014-12-21,2017-12-20,MVP SERVICE CORP.,625 STATE STREET,SCHENECTADY,NY,12305,12305,UNITED STATES OF AMERICA,NETWORK ENGINEER,15-1133,"SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE",6214,1,Y,91374.0,Year,92000.09,0.0,N,N,TARRYTOWN,WESTCHESTER,NY,46000.045,Year,18,4,18-4,12305,12305,36093,NaN,NaN,2014-12-02,62149,621491

In [618]:
#parking vv18, vv17, vv16, vv15
vv18 = vvdata18
vv17 = vvdata17
vv16 = vvdata16
vv15 = vvdata15

In [619]:
##### selecting final columns + order them the same before merging
## put the columns in order for all years
vvdata15 = vvdata15[['index', 'year', 'row_id', 'case_num', 'case_status', 
                    'submit_date', 'decision_date', 'visa_class', 
                    'emp_start', 'emp_end', 'emp_name', 'emp_address', 
                    'emp_city', 'emp_st', 'emp_zip', 'emp_cfips', 
                    'emp_cntry', 'work_city', 'work_cnty', 'work_zip','work_cfips', 
                    'work_st', 'job', 'soc_code', 'soc_name', 'naics_full',
                    'naics4', 'naics5', 'tot_workers', 'full_time', 'wage',
                    'wage_from', 'wage_to', 'payunit', 'pw', 'pw_payunit',
                    'dependent', 'violator', 'org_cert_date']]

In [623]:
vvdata17.head()

,index,case_num,case_status,submit_date,decision_date,visa_class,emp_start,emp_end,emp_name,emp_address,emp_city,emp_st,emp_zip,emp_cntry,job,soc_code,soc_name,naics4,tot_workers,full_time,pw,pw_payunit,wage_from,wage_to,dependent,violator,work_city,work_cnty,work_st,wage,payunit,year,id,row_id,emp_cfips,work_zip,work_cfips,org_cert_date,naics5,naics_full
0,0,I-200-16055-173457,CERTIFIED-WITHDRAWN,2016-02-24,2016-10-01,H-1B,2016-08-10,2019-08-10,DISCOVER PRODUCTS INC.,2500 LAKE COOK ROAD,RIVERWOODS,IL,60015,UNITED STATES OF AMERICA,ASSOCIATE DATA INTEGRATION,15-1121,COMPUTER SYSTEMS ANALYSTS,5222,1,Y,59197.0,Year,65811.0,67320.0,N,N,RIVERWOODS,LAKE,IL,66565.5,Year,17,0,17-0,17097,60015,17097,2016-03-01,52221,522210
2,1,I-200-16064-557834,CERTIFIED-WITHDRAWN,2016-03-04,2016-10-01,H-1B,2016-08-16,2019-08-16,DFS SERVICES LLC,2500 LAKE COOK ROAD,RIVERWOODS,IL,60015,UNITED STATES OF AMERICA,SENIOR ASSOCIATE,15-2031,OPERATIONS RESEARCH ANALYSTS,5222,1,Y,49800.0,Year,53000.0,57200.0,N,N,RIVERWOODS,LAKE,IL,55100.0,Year,17,1,17-1,17097,60015,17097,2016-03-08,52221,522210
4,2,I-200-16063-996093,CERTIFIED-WITHDRAWN,2016-03-10,2016-10-01,H-1B,2016-09-09,2019-09-09,EASTBANC TECHNOLOGIES LLC,1211 31ST ST. NW,WASHINGTON,DC,20007,UNITED STATES OF AMERICA,.NET SOFTWARE PROGRAMMER,15-1131,COMPUTER PROGRAMMERS,5415,2,Y,76502.0,Year,77000.0,0.0,Y,N,WASHINGTON,NaN,DC,38500.0,Year,17,2,17-2,11001,20007,11001,2016-03-16,54151,541511
5,3,I-200-16272-196340,WITHDRAWN,2016-09-28,2016-10-01,H-1B,2017-01-26,2020-01-25,INFO SERVICES LLC,17177 NORTH LAUREL PARK DR,LIVONIA,MI,48152,UNITED STATES OF AMERICA,PROJECT MANAGER,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",5415,1,Y,90376.0,Year,102000.0,0.0,Y,N,JERSEY CITY,HUDSON,NJ,51000.0,Year,17,3,17-3,26163,07302,34017,NaT,54151,541511
6,4,I-200-15053-636744,CERTIFIED-WITHDRAWN,2015-02-22,2016-10-02,H-1B,2015-03-01,2018-03-01,BB&T CORPORATION,223 WEST NASH STREET,WILSON,NC,27893,UNITED STATES OF AMERICA,ASSOCIATE - ESOTERIC ASSET BACKED SECURITIES,13-2041,CREDIT ANALYSTS,5221,1,Y,116605.0,Year,132500.0,0.0,N,N,NEW YORK,NEW YORK,NY,66250.0,Year,17,4,17-4,37195,10036,36061,2015-02-26,52211,522110

In [189]:
#this works as removing column duplicates 
vtest = vvdata15.loc[:,~vvdata15.columns.duplicated()]
len(vtest.columns)

In [621]:
vvdata15 = vvdata15.loc[:,~vvdata15.columns.duplicated()]
vvdata16 = vvdata16.loc[:,~vvdata16.columns.duplicated()]
vvdata17 = vvdata17.loc[:,~vvdata17.columns.duplicated()]
vvdata18 = vvdata18.loc[:,~vvdata18.columns.duplicated()]

In [624]:
len(vvdata15.columns) #39
len(vvdata16.columns) #39
len(vvdata17.columns) #39
len(vvdata18.columns) #39
vvdata17.columns

Index(['index', 'case_num', 'case_status', 'submit_date', 'decision_date',
       'visa_class', 'emp_start', 'emp_end', 'emp_name', 'emp_address',
       'emp_city', 'emp_st', 'emp_zip', 'emp_cntry', 'job', 'soc_code',
       'soc_name', 'naics4', 'tot_workers', 'full_time', 'pw', 'pw_payunit',
       'wage_from', 'wage_to', 'dependent', 'violator', 'work_city',
       'work_cnty', 'work_st', 'wage', 'payunit', 'year', 'id', 'row_id',
       'emp_cfips', 'work_zip', 'work_cfips', 'org_cert_date', 'naics5',
       'naics_full'],
      dtype='object')

In [584]:
#vvdata18.columns = ['index','year','row_id','case_num','case_status','submit_date','decision_date','visa_class', 'emp_start','emp_end','emp_name','emp_address','emp_city','emp_st','emp_zip','emp_cfips','emp_cntry','work_city','work_cnty','work_zip','work_cfips','work_st','job','soc_code','soc_name','naics_full','naics4','naics5','tot_workers','full_time','wage','wage_from','wage_to','payunit','pw','pw_payunit','dependent','violator','org_cert_date']

In [625]:
## saving mid-process csvs
vvdata15.to_csv("../prepped/vvdata15.csv") # 618804
vvdata16.to_csv("../prepped/vvdata16.csv") #647852
vvdata17.to_csv("../prepped/vvdata17.csv") #624650
vvdata18.to_csv("../prepped/vvdata18.csv") #94622

In [203]:
618804+647852+624650+94622

1985928

In [627]:
#### COMBINE ALL DATASETS TOGETHER ####
frames = [vvdata15, vvdata16, vvdata17, vvdata18]
vvdatafull = pd.concat(frames)

In [877]:
len(vvdatafull) #1985928

1985928

In [629]:
vvdatafull.to_csv("../prepped/vvdatafull_preclean.csv")

In [630]:
vvdatafull.dtypes

case_num                 object
case_status            category
decision_date    datetime64[ns]
dependent                object
emp_address              object
emp_cfips                object
emp_city                 object
emp_cntry                object
emp_end                  object
emp_name                 object
emp_st                   object
emp_start                object
emp_zip                  object
full_time                object
id                       object
index                     int64
job                      object
naics4                   object
naics5                   object
naics_full               object
org_cert_date    datetime64[ns]
payunit                category
pw                      float64
pw_payunit               object
row_id                   object
soc_code                 object
soc_name                 object
submit_date      datetime64[ns]
tot_workers             float64
violator                 object
visa_class               object
wage                    float64
wage_from               float64
wage_to                 float64
work_cfips               object
work_city                object
work_cnty                object
work_st                  object
work_zip                 object
year                     object
dtype: object

In [631]:
vvdatafull = vvdatafull.reset_index()

In [632]:
## data type cleaning
vvdatafull['year'] = vvdatafull['year'].astype('category')
vvdatafull['visa_class'] = vvdatafull['visa_class'].astype('category')
vvdatafull['payunit'] = vvdatafull['payunit'].astype('category')

In [643]:
#parking vvdatafull 
vvdatafull1 = vvdatafull

In [644]:
vvdatafull.head(100)

,level_0,case_num,case_status,decision_date,dependent,emp_address,emp_cfips,emp_city,emp_cntry,emp_end,emp_name,emp_st,emp_start,emp_zip,full_time,id,index,job,naics4,naics5,naics_full,org_cert_date,payunit,pw,pw_payunit,row_id,soc_code,soc_name,submit_date,tot_workers,violator,visa_class,wage,wage_from,wage_to,work_cfips,work_city,work_cnty,work_st,work_zip,year,DROP,test
0,0,I-200-09121-701936,WITHDRAWN,2015-02-05,N,710 MEDTRONIC PARKWAY NE,27003,MINNEAPOLIS,UNITED STATES OF AMERICA,02/28/2015,"MEDTRONIC, INC.",MN,02/09/2015,55432,Y,NaN,0,MECHANICAL ENGINEER,3345,33451,334510,NaT,Year,19000.00,Year,15-0,17-2141.00,MECHANICAL ENGINEERS,2015-02-05,1.0,N,H-1B,20000.000,20000.00,NaN,27053,EDEN PRAIRIE,STERNS,CA,55412,15,NaN,True
1,1,I-200-09146-796321,CERTIFIED,2014-12-18,N,905 ASP AVE,40027,NORMAN,UNITED STATES OF AMERICA,01/04/2018,UNIVERSITY OF OKLAHOMA,OK,01/05/2015,73019,Y,NaN,1,ASSISTANT PROFESSOR,6113,61131,611310,NaT,Year,42860.00,Year,15-1,25-1032,"ENGINEERING TEACHERS, POSTSECONDARY",2014-12-12,1.0,N,H-1B,85000.000,85000.00,NaN,40027,NORMAN,CLEVELAND,OK,73019,15,NaN,True
2,2,I-200-09180-329758,WITHDRAWN,2014-12-15,N,6021 CONNECTION DRIVE,48113,IRVING,UNITED STATES OF AMERICA,01/06/2016,NOKIA INC.,TX,01/07/2013,75039,Y,NaN,2,RELEASE AND SOFTWARE TEST MANAGER,5172,51721,517212,NaT,Year,73965.00,Year,15-2,15-1799,"COMPUTER OCCUPATIONS, ALL OTHER*",2013-01-03,1.0,N,H-1B,94000.000,94000.00,NaN,06073,SAN DIEGO,SAN DIEGO,CA,92127,15,NaN,True
3,3,I-200-09183-259985,CERTIFIED,2015-03-16,N,9510 N. HOUSTON ROSSLYN ROAD,48201,HOUSTON,UNITED STATES OF AMERICA,09/07/2018,"OMRON OILFIELD AND MARINE, INC.",TX,09/07/2015,77088,Y,NaN,3,CONTROL ENGINEERING SPECIALIST,3353,33531,335314,NaT,Year,65998.00,Year,15-3,17-2072,"ELECTRONICS ENGINEERS, EXCEPT COMPUTER",2015-03-10,2.0,N,H-1B,68000.000,66000.00,70000.00,48201,HOUSTON,HARRIS,TX,77088,15,NaN,True
4,4,I-200-09189-800933,CERTIFIED,2014-12-23,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,06/05/2018,FEDERAL HOME LOAN MORTGAGE CO.,VA,06/06/2015,22102,Y,NaN,4,DEVELOPMENT SENIOR,5222,52229,522294,NaT,Year,96907.00,Year,15-4,15-1131,COMPUTER PROGRAMMERS,2014-12-17,1.0,N,H-1B,120150.000,97000.00,143300.00,51059,MCLEAN,FAIRFAX,VA,22102,15,NaN,True
5,5,I-200-09195-662319,WITHDRAWN,2015-01-22,N,2885 COUNTRY DRIVE,27123,LITTLE CANADA,UNITED STATES OF AMERICA,01/25/2016,"APLARS, LLC",MN,01/25/2015,55117,Y,NaN,5,BUSINESS ANALYST,4541,45411,454111,NaT,Year,20000.00,Year,15-5,19-3021.00,MARKET RESEARCH ANALYSTS,2015-01-22,1.0,N,H-1B,20000.000,20000.00,NaN,NaN,SIT,LUNGE,LA,NaN,15,NaN,True
6,6,I-200-09212-834534,CERTIFIED,2014-10-20,N,3401 HILLVIEW AVE,06085,PALO ALTO,UNITED STATES OF AMERICA,11/02/2017,"VMWARE, INC.",CA,11/03/2014,94304,Y,NaN,6,STAFF ENGINEER,5415,54151,541511,NaT,Year,133976.00,Year,15-6,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-10-14,1.0,N,H-1B,155000.000,155000.00,NaN,06085,PALO ALTO,SANTA CLARA,CA,94304,15,NaN,True
7,7,I-200-09232-212049,CERTIFIED,2014-12-23,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,06/13/2018,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,06/14/2015,22102,Y,NaN,7,CREDIT GUARANTEE ANALYTICS SENIOR,5222,52229,522294,NaT,Year,64085.00,Year,15-7,15-2031,OPERATIONS RESEARCH ANALYSTS,2014-12-17,1.0,N,H-1B,95550.000,64100.00,127000.00,51059,MCLEAN,FAIRFAX,VA,22102,15,NaN,True
8,8,I-200-09233-732656,CERTIFIED,2014-11-04,N,3401 HILLVIEW AVE,06085,PALO ALTO,UNITED STATES OF AMERICA,11/16/2017,"VMWARE, INC.",CA,11/17/2014,94304,Y,NaN,8,PROGRAMMER/ANALYST - SENIOR APPLICATIONS DEVEL...,5415,54151,541511,NaT,Year,101900.00,Year,15-8,15-1121,COMPUTER SYSTEMS ANALYSTS,2014-10-29,1.0,N,H-1B,125000.000,125000.00,NaN,06085,PALO ALTO,SANTA CLARA,CA,94304,15,NaN,True
9,9,I-200-09238-535119,DENIED,2015-03-30,N,65 CRESTRIDGE DRIVE,13135,SUWANEE,UNITED STATES OF AMERICA,09/17/2018,IMAEX TRADING COMPANY,GA,09/17/2015,30024,N,NaN,9,COST ACCOUNTANT,4244,42446,424460,NaT,Hour,22.46,Hour,15-9,13-2011,ACCOUNTANTS AND AUDITORS,2015-03-19,1.0,N,H-1B,22.460,22.46,NaN,13135,SUWANEE,FORSYTH,GA,30024,15,NaN,True
10,12,I-200-09244-289740,CERTIFIED,2014-10-28,N,3401 HILLVIEW AVE,06085,PALO ALTO,UNITED STATES OF AMERICA,04/22/2018,"VMWARE, INC.",CA,04/23/2015,94304,Y,NaN,10,MEMBER OF TECHNICAL STAFF - SOFTWARE ENGINEERING,5415,54151,541511,NaT,Year,98557.00,Year,15-10,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-10-22,1.0,N,H-1B,122430.000,122430.00,NaN,06085,PALO ALTO,SANTA CLARA,CA,94304,15,NaN,True
11,13,I-200-09258-461335,DENIED,2015-01-29,N,21 WEST SUPERIOR STREET,27137,DULUTH,UNITED STATES OF AMERICA,01/22/2016,"LHB, INC.",MN,01/22/2015,55802,Y,NaN,11,F,5413,54133,541330,NaT,Year,345000.00,Year,15-11,13-2011,ACCOUNTANTS AND AUDITORS,2015-01-22,1.0,N,H-1B,20000.000,20000.00,NaN,27053,2 WORK,WORK,ME,55401,15,NaN,True
12,14,I-200-09261-001558,DENIED,2015-03-31,Y,1110 ELDEN STREET,51059,HERNDON,UNITED STATES OF AMERICA,08/20/2018,"INTERNATIONAL SOLUTIONS GROUP, INC.",VA,08/20/2015,20170,Y,NaN,12,PROGRAMMER ANALYST,5415,54151,541511,NaT,Year,66976.00,Year,15-12,15-1021.00,COMPUTER PROGRAMMERS,2015-03-20,1.0,N,H-1B,64688.000,64688.00,NaN,10003,MIDDLETOWN,NEW CASTLE,DE,19709,15,NaN,True
13,15,I-200-09274-925070,CERTIFIED,2014-10-28,N,3401 HILLVIEW AVE,06085,PALO ALTO,UNITED STATES OF AMERICA,11/09/2017,"VMWARE, INC.",CA,11/10/2014,94304,Y,NaN,13,SENIOR MEMBER OF TECHNICAL STAFF - QUALITY ENG...,5415,54151,541511,NaT,Year,111742.00,Year,15-13,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2014-10-22,1.0,N,H-1B,140000.000,140000.00,NaN,06085,PALO ALTO,SANTA CLARA,CA,94304,15,NaN,True
14,16,I-200-09285-514415,CERTIFIED,2014-10-30,Y,388 WASHINGTON ROAD,34023,SAYREVILLE,UNITED STATES OF AMERICA,10/23/2017,IT CATS LLC,NJ,10/24/2014,08872,Y,NaN,14,SENIOR BUSINESS ANALYST,5415,54151,541511,NaT,Hour,52.46,Hour,15-14,15-1121,COMPUTER SYSTEMS ANALYSTS,2014-10-24,1.0,N,H-1B,62.500,60.00,65.00,42091,"NORTH WALES,",MONTGOMERY,PA,19454,15,NaN,True
15,18,I-200-09296-661220,CERTIFIED,2014-11-04,N,3401 HILLVIEW AVE,06085,PALO ALTO,UNITED STATES OF AMERICA,02/02/2018,"VMWARE, INC.",CA,02/03/2015,94304,Y,NaN,15,SENIOR MEMBER OF TECHNICAL STAFF - SOFTWARE EN...,5415,54151,541511,NaT,Year,113775.00,Year,15-15,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-10-29,1.0,N,H-1B,140000.000,140000.00,NaN,06085,PALO ALTO,SANTA CLARA,CA,94304,15,NaN,True
16,19,I-200-09302-785109,CERTIFIED-WITHDRAWN,2014-10-29,N,105 CORPORATE CENTER BLVD,37081,GREENSBORO,UNITED STATES OF AMERICA,04/25/2015,VF CORPORATION,NC,04/25/2012,27408,Y,NaN,16,PROJECT MANAGER (DIGITAL/ECOMMERCE),5415,54151,541512,NaT,Year,110300.00,Year,15-16,11-3021,COMPUTER AND INFORMATION SYSTEMS MANAGERS,2012-02-02,1.0,N,H-1B,125000.000,125000.00,NaN,06059,CYPRESS,ORANGE,CA,90630,15,NaN,True
17,21,I-200-09313-334737,CERTIFIED,2014-12-29,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,06/15/2018,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,06/16/2015,22102,Y,NaN,17,SYSTEMS ANALYSIS SENIOR,5222,52229,522294,NaT,Year,75200.00,Year,15-17,15-1121,COMPUTER SYSTEMS ANALYSTS,2014-12-19,1.0,N,H-1B,103850.000,75200.00,132500.00,51059,RESTON,FAIRFAX,VA,20190,15,NaN,True
18,22,I-200-09316-752823,WITHDRAWN,2014-10-13,N,1510 WEST LOOP SOUTH,48201,HOUSTON,UNITED STATES OF AMERICA,10/12/2017,"LANDRY'S RESTAURANTS, INC.",TX,10/13/2014,77027,Y,NaN,18,GENERAL MANAGER,7221,72211,722110,NaT,Year,89569.00,Year,15-18,11-9051.00,FOOD SERVICE MANAGERS,2014-10-13,1.0,N,H-1B,136700.000,109360.00,164040.00,48201,HOUSTON,HARRIS,TX,77027,15,NaN,True
19,23,I-200-09317-262420,WITHDRAWN,2014-10-13,N,1510 WEST LOOP SOUTH,48201,HOUSTON,UNITED STATES OF AMERICA,10/12/2017,"LANDRY'S RESTAURANTS, INC.",TX,10/13/2014,77027,Y,NaN,19,GENERAL MANAGER,7221,72211,722110,NaT,Year,56722.00,Year,15-19,11-9051.00,FOOD SERVICE MANAGERS,2014-10-13,1.0,N,H-1B,69175.000,69175.00,NaN,35001,ALBUQUERQUE,BERNALILLO,NM,87109,15,NaN,True
20,24,I-200-09321-731590,CERTIFIED,2014-12-24,N,100 WEST WALNUT STREET,06037,PASADENA,UNITED STATES OF AMERICA,01/11/2018,PARSONS SERVICES COMPANY,CA,01/12/2015,91124,Y,NaN,20,SENIOR IT SPECIALIST,5511,55111,551114,NaT,Year,108472.00,Year,15-20,15-1141,DATABASE ADMINISTRATORS,2014-12-18,1.0,N,H-1B,127500.000,110000.00,145000.00,06037,PAASADENA,LOS ANGELES,CA,91124,15,NaN,True
21,25,I-200-09329-943146,CERTIFIED-WITHDRAWN,2015-07-27,N,5725 DELPHI DRIVE,26125,TROY,UNITED STATES OF AMERICA,09/13/2017,DELPHI CORPORATION,MI,05/31/2015,48098,Y,NaN,21,ALGORITHM-STATE ESTIMATION DEVELOPMENT ENGINEER,3363,33639,336399,NaT,Year,91936.00,Year,15-21,17-2071,ELECTRICAL ENGINEERS,2015-01-14,1.0,N,H-1B,91936.000,91936.00,NaN,06037,AGOURA HILLS,LOS ANGELES,CA,91301,15,NaN,True
22,26,I-200-09334-392690,WITHDRAWN,2014-10-13,N,3333 S. BANNOCK STREET,08031,ENGLEWOOD,UNITED STATES OF AMERICA,10/12/2017,DAIRY INFORMATION SYSTEMS HOLDINGS LLC,CO,10/13/2014,80110,Y,NaN,22,APPLICATIONS PROGRAMMING MANAGER,5112,51121,511210,NaT,Year,94411.00,Year,15-22,15-1051.00,COMPUTER SYSTEMS ANALYSTS,2014-10-13,1.0,N,H-1B,107872.000,107872.00,NaN,08031,ENGLEWOOD,ARAPAHOE,CO,80110,15,NaN,True
23,28,I-200-09338-814236,CERTIFIED-WITHDRAWN,2015-01-19,Y,"4 ETHEL RD, SUITE 403B",34023,EDISON,UNITED STATES OF AMERICA,09/21/2015,"INTEGRATED RESOURCES, INC",NJ,02/21/2013,08817,Y,NaN,23,OCCUPATIONAL THERAPISTS,5613,56132,561320,NaT,Hour,32.97,Hour,15-23,29-1122,OCCUPATIONAL THERAPISTS,2013-02-21,1.0,N,H-1B,35.000,35.00,NaN,34011,VINELAND,CUMBERLAND,NJ,08362,15,NaN,True
24,29,I-200-09341-564186,CERTIFIED-WITHDRAWN,2015-01-26,Y,205 HOUSE AVENUE SUITE#103,42041,CAMP HILL,UNITED STATES OF AMERICA,06/19/2016,"XPERT TECHNOLOGIES, INC.",PA,06/19/2013,17011,Y,NaN,24,QUALITY ASSURANCE ANALYST,5415,54151,541511,NaT,Year,58282.00,Year,15-24,15-1799,"COMPUTER OCCUPATIONS, ALL OTHER*",2013-06-17,1.0,N,H-1B,60000.000,60000.00,NaN,42041,CAMP HILL,CUMBERLAND,PA,17011,15,NaN,True
25,31,I-200-09342-274341,CERTIFIED,2015-02-22,Y,"559 D'ONOFRIO DRIVE, SUITE 101 & 102",55025,MADISON,UNITED STATES OF AMERICA,03/03/2018,"ISR INFO WAY, INC.",WI,03/04/2015,53719,Y,NaN,25,SR. SOFTWARE DEVELOPER,5415,54151,541511,NaT,Year,84906.00,Year,15-25,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2015-02-13,1.0,N,H-1B,94953.000,84906.00,105000.00,17031,CHICAGO,COOK,IL,60601,15,NaN,True
26,32,I-200-09362-088372,CERTIFIED,2014-12-26,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,06/17/2018,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,06/18/2015,22102,Y,NaN,26,CREDIT GUARANTEE ANALYTICS SENIOR,5222,52229,522294,NaT,Year,64085.00,Year,15-26,15-2031,OPERATIONS RESEARCH ANALYSTS,2014-12-19,1.0,N,H-1B,95550.000,64100.00,127000.00,51059,MCLEAN,FAIRFAX,VA,22102,15,NaN,True
27,33,I-200-09362-500914,CERTIFIED,2015-01-07,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,06/27/2018,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,06/28/2015,22102,Y,NaN,27,SHARED INFORMATION SUPPORT SENIOR,5222,52229,522294,NaT,Year,90800.00,Year,15-27,15-1141,DATABASE ADMINISTRATORS,2014-12-30,1.0,N,H-1B,105550.000,90800.00,120300.00,51059,MCLEAN,FAIRFAX,VA,22102,15,NaN,True
28,34,I-200-09364-425868,CERTIFIED,2015-03-20,N,7 PULASKI STREET,36067,AUBURN,UNITED STATES OF AMERICA,09/15/2018,MAGIC CIRCLE FILMS INTERNATIONAL LLC,NY,09/15/2015,13021,Y,NaN,28,VIDEO EDITOR,5121,51219,51219,NaT,Year,39333.00,Year,15-28,27-4032,FILM AND VIDEO EDITORS,2015-03-16,1.0,N,H-1B,50003.000,50003.00,NaN,36067,AUBURN,CAYUGA,NY,13021,15,NaN,True
29,36,I-200-10006-413683,WITHDRAWN,2015-03-11,Y,"523 GREEN STREET, 2ND FLOOR",34023,ISELIN,UNITED STATES OF AMERICA,04/15/2018,SAPHIRE SOLUTIONS INC,NJ,04/16/2015,08830,Y,NaN,29,SYSTEMS ADMINISTRATOR,5415,54151,541511,NaT,Year,68638.00,Year,15-29,15-1142,NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS,2015-03-10,1.0,N,H-1B,79560.000,79560.00,NaN,36059,BETHPAGE,NASSAU,NY,11714,15,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,84,I-200-10204-793879,WITHDRAWN,2014-10-13,N,"1360 POST OAK BOULEVARD, SUITE 150",48201,HOUSTON,UNITED STATES OF AMERICA,10/12/2017,"BROKEN HILL PROPRIETARY (USA), INC.",TX,10/13/2014,77056,Y,NaN,70,DISTRIBUTION ADMINISTRATOR,5416,54169,541690,NaT,Year,46987.00,Year,15-70,13-1081.00,LOGISTICIANS,2014-10-13,1.0,N,H-1B,66510.000,66510.00,NaN,42003,PITTSBURGH,ALLEGHENY,PA,15205,15,NaN,True
71,85,I-200-10207-775880,WITHDRAWN,2014-10-13,N,11700 KATY FREEWAY,48201,HOUSTON,UNITED STATES OF AMERICA,10/12/2017,"TECHNIP USA, INC.",TX,10/13/2014,77079,Y,NaN,71,SENIOR DEEPWATER RISER ENGINEER,5413,54133,541330,NaT,Year,80392.00,Year,15-71,17-2141.00,MECHANICAL ENGINEERS,2014-10-13,1.0,N,H-1B,85000.240,85000.24,NaN,48201,HOUSTON,HARRIS,TX,77079,15,NaN,True
72,86,I-200-10214-358714,CERTIFIED-WITHDRAWN,2015-04-01,N,"920 MEMORIAL CITY WAY, SUITE 700",48201,HOUSTON,UNITED STATES OF AMERICA,08/17/2015,"WS ATKINS, INC.",TX,08/17/2012,77024,Y,NaN,72,ASSISTANT CFD CONSULTANT,5419,54199,541990,NaT,Year,64400.00,Year,15-72,17-2051,CIVIL ENGINEERS,2012-02-17,1.0,N,H-1B,68000.000,68000.00,NaN,48201,HOUSTON,HARRIS,TX,77024,15,NaN,True
73,87,I-200-10214-421060,CERTIFIED,2015-01-06,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,01/04/2018,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,01/05/2015,22102,Y,NaN,73,SECURITIES MODELING PROFESSIONAL,5222,52229,522294,NaT,Year,64085.00,Year,15-73,15-2031,OPERATIONS RESEARCH ANALYSTS,2014-12-30,1.0,N,H-1B,90800.000,64100.00,117500.00,51059,MCLEAN,FAIRFAX,VA,22102,15,NaN,True
74,88,I-200-10215-099771,CERTIFIED,2015-01-13,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,07/05/2018,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,07/06/2015,22102,Y,NaN,74,INFORMATION SECURITY SENIOR,5222,52229,522294,NaT,Year,85600.00,Year,15-74,15-1142,NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS,2015-01-07,1.0,N,H-1B,105900.000,85600.00,126200.00,51059,RESTON,FAIRFAX,VA,20190,15,NaN,True
75,89,I-200-10217-966696,CERTIFIED,2015-02-10,Y,860 HEBRON PKWY,48121,LEWISVILLE,UNITED STATES OF AMERICA,09/29/2015,TRANS AMERICAN INFORMATION SYSTEMS INC,TX,02/04/2015,75057,Y,NaN,75,ATG DEVELOPER,5415,54151,541511,NaT,Year,79747.00,Year,15-75,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2015-02-04,1.0,N,H-1B,90000.000,90000.00,NaN,48113,RICHARDSON,DALLAS,TX,75081,15,NaN,True
76,90,I-200-10223-731658,CERTIFIED-WITHDRAWN,2015-07-02,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,08/31/2018,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,09/01/2015,22102,Y,NaN,76,INTERNAL AUDIT PROFESSIONAL,5222,52229,522294,NaT,Year,55286.00,Year,15-76,13-2011,ACCOUNTANTS AND AUDITORS,2015-03-02,1.0,N,H-1B,74450.000,55300.00,93600.00,51059,MCLEAN,FAIRFAX,VA,22102,15,NaN,True
77,91,I-200-10224-292346,CERTIFIED,2015-03-06,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,08/31/2018,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,09/01/2015,22102,Y,NaN,77,RISK MODELING SENIOR,5222,52229,522294,NaT,Year,64085.00,Year,15-77,15-2031,OPERATIONS RESEARCH ANALYSTS,2015-03-02,1.0,N,H-1B,85100.000,64100.00,106100.00,51059,MCLEAN,FAIRFAX,VA,22102,15,NaN,True
78,92,I-200-10228-828212,CERTIFIED-WITHDRAWN,2014-12-01,N,1620 MCELDERRY STREET,24510,BALTIMORE,UNITED STATES OF AMERICA,01/14/2018,THE JOHNS HOPKINS UNIVERSITY,MD,01/15/2015,21205,Y,NaN,78,RESEARCH TECHNOLOGIST,6113,61131,611310,NaT,Year,27768.00,Year,15-78,19-4021,BIOLOGICAL TECHNICIANS,2014-09-02,1.0,N,H-1B,28320.000,28320.00,NaN,24510,BALTIMORE,BALTIMORE CITY,MD,21205,15,NaN,True
79,93,I-200-10237-048581,WITHDRAWN,2014-10-13,N,3333 PIEDMONT ROAD,13121,ATLANTA,UNITED STATES OF AMERICA,10/12/2017,SONY ERICSSON MOBILE COMMUNICATIONS (USA) INC.,GA,10/13/2014,30305,Y,NaN,79,REGIONAL BUSINESS MANAGER,3342,33422,334220,NaT,Year,54912.00,Year,15-79,15-2031.00,OPERATIONS RESEARCH ANALYSTS,2014-10-13,1.0,N,H-1B,91348.000,76550.00,106146.00,13121,ATLANTA,FULTON,GA,30305,15,NaN,True
80,94,I-200-10244-239911,CERTIFIED,2015-03-18,N,"1007 MARKET STREET, D-7031",10003,WILMINGTON,UNITED STATES OF AMERICA,09/08/2018,E.I. DU PONT DE NEMOURS AND COMPANY,DE,09/08/2015,19898,Y,NaN,80,"RESEARCH INVESTIGATOR, APPLICATION TECHNOLOGY",3251,32519,325199,NaT,Year,68370.00,Year,15-80,17-2021,AGRICULTURAL ENGINEERS,2015-03-09,1.0,N,H-1B,106015.000,83690.00,128340.00,10003,NEWARK,NEW CASTLE,DE,19711,15,NaN,True
81,95,I-200-10246-559292,WITHDRAWN,2014-10-13,N,1000 THROCKMORTON STREET,48439,FORT WORTH,UNITED STATES OF AMERICA,10/12/2017,THE CITY OF FORT WORTH,TX,10/13/2014,76102,Y,NaN,81,FORENSIC DIVISION MANAGER,9221,92212,92212,NaT,Year,58864.00,Year,15-81,19-4092.00,FORENSIC SCIENCE TECHNICIANS,2014-10-13,1.0,N,H-1B,97240.000,97240.00,NaN,48439,FORT WORTH,TARRANT,TX,76102,15,NaN,True
82,96,I-200-10250-971984,CERTIFIED-WITHDRAWN,2015-04-06,N,2700 LAKE COOK ROAD,17097,RIVERWOODS,UNITED STATES OF AMERICA,06/03/2017,"UNIVERSAL TAX SYSTEMS, INC.",IL,06/03/2014,60015,Y,NaN,82,FIELD SALES REP,5112,51121,511210,NaT,Year,48589.00,Year,15-82,41-1012,FIRST-LINE SUPERVISORS OF NON-RETAIL SALES WOR...,2014-05-22,1.0,N,H-1B,66794.500,48589.00,85000.00,12011,DAVIE,BROWARD,FL,33314,15,NaN,True
83,97,I-200-10250-986276,CERTIFIED-WITHDRAWN,2015-05-12,N,2700 LAKE COOK ROAD,17097,RIVERWOODS,UNITED STATES OF AMERICA,09/12/2017,CCH INCORPORATED,IL,09/12/2014,60015,Y,NaN,83,IT ARCHITECT,5112,51121,511210,NaT,Year,85738.00,Year,15-83,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-08-19,1.0,N,H-1B,94919.000,85738.00,104100.00,20173,WICHITA,SEDGWICK,KS,67207,15,NaN,True
84,98,I-200-10263-046043,WITHDRAWN,2014-10-24,N,5300 CALIFORNIA AVE.,06059,IRVINE,UNITED STATES OF AMERICA,09/30/2015,BROADCOM CORPORATION,CA,10/01/2012,92617,Y,NaN,84,"ENGINEER, PRINCIPAL - IC DESIGN",3344,33441,334413,NaT,Year,131019.00,Year,15-84,17-2072.00,"ELECTRONICS ENGINEERS, EXCEPT COMPUTER",2012-04-02,1.0,N,H-1B,131040.000,131040.00,NaN,06085,SUNNYVALE,SANTA CLARA,CA,94086,15,NaN,True
85,99,I-200-10284-765613,CERTIFIED-WITHDRAWN,2015-02-13,N,180 MAIDEN LANE,36061,NEW YORK,UNITED STATES OF AMERICA,09/22/2016,"AIG PC GLOBAL SERVICES, INC.",NY,09/23/2013,10038,Y,NaN,85,"DIRECTOR, SCIENCE CONSUMER",5242,52429,524298,NaT,Year,141835.00,Year,15-85,11-3031,FINANCIAL MANAGERS,2013-09-17,1.0,N,H-1B,165000.000,165000.00,NaN,36061,NEW YORK,NEW YORK,NY,10038,15,NaN,True
86,100,I-200-10286-468947,CERTIFIED,2014-11-17,N,3401 HILLVIEW AVE,06085,PALO ALTO,UNITED STATES OF AMERICA,05/11/2018,"VMWARE, INC.",CA,05/12/2015,94304,Y,NaN,86,MEMBER OF TECHNICAL STAFF - QUALITY ENGINEERING,5415,54151,541511,NaT,Year,97503.00,Year,15-86,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2014-11-10,1.0,N,H-1B,107277.000,107277.00,NaN,06085,PALO ALTO,SANTA CLARA,CA,94304,15,NaN,True
87,101,I-200-10292-944449,CERTIFIED,2015-03-18,N,"1007 MARKET STREET, D-7031",10003,WILMINGTON,UNITED STATES OF AMERICA,09/08/2018,E.I. DU PONT DE NEMOURS AND COMPANY,DE,09/08/2015,19898,Y,NaN,87,"RESEARCH INVESTIGATOR, RESIDUE FIELD STUDY",3251,32519,325199,NaT,Year,82347.00,Year,15-87,17-2081,ENVIRONMENTAL ENGINEERS,2015-03-09,1.0,N,H-1B,106015.000,83690.00,128340.00,10003,NEWARK,NEW CASTLE,DE,19711,15,NaN,True
88,102,I-200-10293-841987,CERTIFIED,2015-02-09,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,07/30/2018,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,07/31/2015,22102,Y,NaN,88,RELEASE MANAGEMENT SENIOR,5222,52229,522294,NaT,Year,79100.00,Year,15-88,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2015-02-02,1.0,N,H-1B,95400.000,79100.00,111700.00,51059,RESTON,FAIRFAX,VA,20190,15,NaN,True
89,103,I-200-10301-254322,CERTIFIED,2015-02-25,N,"717 N. HARWOOD ST., SUITE 2200",48113,DALLAS,UNITED STATES OF AMERICA,08/04/2018,"LANYON SOLUTIONS, INC.",TX,08/05/2015,75201,Y,NaN,89,ACCOUNTANT,5112,51121,511210,NaT,Year,44500.00,Year,15-89,13-2011,ACCOUNTANTS AND AUDITORS,2015-02-18,1.0,N,H-1B,44750.000,44500.00,45000.00,48113,DALLAS,DALLAS,TX,75201,15,NaN,True

In [645]:
vvdatafull1['emp_zip'] = vvdatafull1['emp_zip'].astype('str')
vvdatafull1.loc[(vvdatafull1['emp_zip'].apply(lambda x: len(x) < 5)),'DROP'] = 'Y'

In [646]:
vvdatafull1['DROP'].describe()

count     549
unique      2
top         Y
freq      384
Name: DROP, dtype: object

In [647]:
vvdatafull1[vvdatafull1['DROP'] == 'Y']

,level_0,case_num,case_status,decision_date,dependent,emp_address,emp_cfips,emp_city,emp_cntry,emp_end,emp_name,emp_st,emp_start,emp_zip,full_time,id,index,job,naics4,naics5,naics_full,org_cert_date,payunit,pw,pw_payunit,row_id,soc_code,soc_name,submit_date,tot_workers,violator,visa_class,wage,wage_from,wage_to,work_cfips,work_city,work_cnty,work_st,work_zip,year,DROP,test
351,406,I-200-11272-319573,CERTIFIED-WITHDRAWN,2014-10-21,N,ONE CVS DRIVE,NaN,WOONSOCKET,UNITED STATES OF AMERICA,03/22/2015,"CVS RX SERVICES, INC.",RI,03/23/2012,2895,N,NaN,351,PHARMACIST,4461,44611,446110,NaT,Hour,52.31,Hour,15-351,29-1051,PHARMACISTS,2011-10-07,1.0,N,H-1B,61.550,55.60,67.50,06065,LAKE ELSINORE,RIVERSIDE,CA,92530,15,Y,True
482,553,I-200-11314-326929,WITHDRAWN,2014-12-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,482,NaN,nan,nan,nan,NaT,NaN,NaN,NaN,15-482,NaN,NaN,2014-12-24,NaN,NaN,H-1B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,Y,False
636,742,I-200-11357-628825,WITHDRAWN,2014-10-10,N,75 REED ROAD,NaN,HUDSON,UNITED STATES OF AMERICA,01/01/2015,INTEL MASSACHUSETTS,MA,01/02/2012,1749,Y,NaN,636,SOFTWARE ENGINEER,3344,33440,334400,NaT,Year,99147.00,Year,15-636,15-1133,"SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE",2011-12-23,1.0,N,H-1B,114323.500,99147.00,129500.00,25017,HUDSON,FRAMINGHAM,MA,01749,15,Y,True
2919,3420,I-200-12139-391973,WITHDRAWN,2015-01-29,N,529 PLEASANT STREET,NaN,ATTLEBORO,UNITED STATES OF AMERICA,05/28/2015,"SENSATA TECHNOLOGIES, INC.",MA,05/29/2012,2703,Y,NaN,2919,DIRECTOR OF PROCUREMENT FINANCE,3345,33451,334513,NaT,Year,137675.00,Year,15-2919,11-3031,FINANCIAL MANAGERS,2012-05-29,1.0,N,H-1B,145020.000,145020.00,NaN,25005,ATTLEBORO,BRISTOL,MA,02703,15,Y,True
3948,4601,I-200-12216-426512,CERTIFIED-WITHDRAWN,2015-06-29,N,ONE CVS DRIVE,NaN,WOONSOCKET,UNITED STATES OF AMERICA,10/01/2015,"CVS RX SERVICES, INC.",RI,10/01/2012,2895,N,NaN,3948,PHARMACIST,4461,44611,446110,NaT,Hour,59.25,Hour,15-3948,29-1051,PHARMACISTS,2012-08-24,1.0,N,H-1B,63.375,59.25,67.50,06037,LA VERNE,LOS ANGELES,CA,91750,15,Y,True
4403,5111,I-200-12258-619355,CERTIFIED-WITHDRAWN,2015-06-29,N,ONE CVS DRIVE,NaN,WOONSOCKET,UNITED STATES OF AMERICA,10/01/2015,"CVS RX SERVICES, INC.",RI,10/01/2012,2895,N,NaN,4403,PHARMACIST,4461,44611,446110,NaT,Hour,53.34,Hour,15-4403,29-1051,PHARMACISTS,2012-09-17,1.0,N,H-1B,60.980,53.34,68.62,04013,PHOENIX,MARICOPA,AZ,85015,15,Y,True
6233,7180,I-200-13042-898310,WITHDRAWN,2014-10-10,N,529 PLEASANT STREET,NaN,ATTLEBORO,UNITED STATES OF AMERICA,02/19/2016,"SENSATA TECHNOLOGIES, INC.",MA,02/20/2013,2703,Y,NaN,6233,MECHANICAL DESIGN ENGINEER,3345,33451,334513,NaT,Year,84600.00,Year,15-6233,17-2141,MECHANICAL ENGINEERS,2013-02-14,1.0,N,H-1B,86040.000,86040.00,NaN,25005,ATTLEBORO,BRISTOL,MA,02703,15,Y,True
8917,10292,I-200-13102-099355,CERTIFIED,2015-03-06,N,"85 EAST CONCORD ST., 1ST FLOOR",NaN,BOSTON,UNITED STATES OF AMERICA,12/06/2017,BOSTON MEDICAL CENTER CORPORATION,MA,06/18/2015,2118,Y,NaN,8917,"MANAGER, ANALYTICS AND QUALITY IMPROVEMENT",6221,62211,622110,NaT,Year,86445.00,Year,15-8917,15-2031,OPERATIONS RESEARCH ANALYSTS,2015-03-02,1.0,N,H-1B,102000.000,102000.00,NaN,25025,BOSTON,SUFFOLK,MA,02118,15,Y,True
8925,10301,I-200-13102-386383,WITHDRAWN,2014-12-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,8925,NaN,nan,nan,nan,NaT,NaN,NaN,NaN,15-8925,NaN,NaN,2014-12-24,NaN,NaN,H-1B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,Y,False
8947,10327,I-200-13102-931389,CERTIFIED,2015-03-09,N,"85 EAST CONCORD ST., 1ST FLOOR",NaN,BOSTON,UNITED STATES OF AMERICA,05/31/2018,BOSTON MEDICAL CENTER CORPORATION,MA,06/01/2015,2118,Y,NaN,8947,NETWORK ENGINEER,6221,62211,622110,NaT,Year,76461.00,Year,15-8947,15-1054,"COMPUTER NETWORK ARCHITECTS, NON R&D",2015-03-02,1.0,N,H-1B,79730.500,76461.00,83000.00,25025,BOSTON,SUFFOLK,MA,02118,15,Y,True
9071,10477,I-200-13108-210469,CERTIFIED,2015-09-05,N,"85 EAST CONCORD ST., 1ST FLOOR",NaN,BOSTON,UNITED STATES OF AMERICA,09/26/2018,BOSTON MEDICAL CENTER CORPORATION,MA,09/27/2015,2118,Y,NaN,9071,APPLICATIONS ANALYST III,6221,62211,622110,NaT,Year,67350.00,Year,15-9071,15-1052,"COMPUTER SYSTEMS ANALYSTS, NON R&D",2015-08-31,1.0,N,H-1B,102000.000,102000.00,NaN,25025,BOSTON,SUFFOLK,MA,02118,15,Y,True
9661,11146,I-200-13137-018489,CERTIFIED-WITHDRAWN,2015-04-01,N,"281 ROUTE 79, SUITE # 208",NaN,MORGANVILLE,UNITED STATES OF AMERICA,06/30/2016,"GLOBAL NEST, LLC",NJ,07/01/2013,7751,Y,NaN,9661,PROGRAMMER ANALYST,5415,54151,541511,NaT,Year,53394.00,Year,15-9661,15-1131,COMPUTER PROGRAMMERS,2013-05-17,1.0,N,H-1B,60000.000,60000.00,NaN,36061,NEW YORK,NEW YORK,NY,10003,15,Y,True
13353,15312,I-200-13340-514729,CERTIFIED-WITHDRAWN,2014-10-30,N,DEPARTMENT OF HUMAN RESOURCES,NaN,FARMINGTON,UNITED STATES OF AMERICA,12/31/2016,UNIVERSITY OF CONNECTICUT HEALTH CENTER,CT,01/01/2014,6001,Y,NaN,13353,CLINICAL INSTRUCTOR,6113,61131,611310,NaT,Year,56473.00,Year,15-13353,25-1199,"POSTSECONDARY TEACHERS, ALL OTHER",2013-12-06,1.0,N,H-1B,83200.000,83200.00,NaN,09003,FARMINGTON,HARTFORD,CT,06032,15,Y,True
14409,16565,I-200-14028-801312,WITHDRAWN,2015-01-23,N,55 EAST 52ND STREET,NaN,NEW YORK,UNITED STATES OF AMERICA,08/31/2017,"EVERCORE PARTNERS SERVICES EAST, LLC",NY,09/01/2014,1055,Y,NaN,14409,ANALYST,5231,52311,523110,NaT,Year,67205.00,Year,15-14409,13-2051,FINANCIAL ANALYSTS,2014-03-03,1.0,N,H-1B,75000.000,75000.00,NaN,36061,NEW YORK,NEW YORK,NY,10055,15,Y,True
14527,16705,I-200-14033-483436,WITHDRAWN,2015-06-12,N,1055 W VICTORIA STREET,NaN,COMPTON,UNITED STATES OF AMERICA,07/01/2017,YAMATO TRANSPORT USA INC,CA,07/01/2014,9022,Y,NaN,14527,HUMAN RESOURCE SPECIALIST,4885,48851,488510,NaT,Hour,19.70,Hour,15-14527,13-1071,HUMAN RESOURCES SPECIALISTS,2014-02-02,1.0,N,H-1B,19.700,19.70,NaN,06037,COMPTON,LOS ANGELES,CA,90220,15,Y,True
16380,18868,I-200-14064-847406,WITHDRAWN,2014-12-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,16380,NaN,nan,nan,nan,NaT,NaN,NaN,NaN,15-16380,NaN,NaN,2014-12-24,NaN,NaN,H-1B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,Y,False
17620,20353,I-200-14073-483514,WITHDRAWN,2014-12-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,17620,NaN,nan,nan,nan,NaT,NaN,NaN,NaN,15-17620,NaN,NaN,2014-12-24,NaN,NaN,H-1B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,Y,False
19645,22822,I-200-14099-477751,WITHDRAWN,2015-03-05,NaN,NaN,NaN,NaN,UNITED STATES OF AMERICA,NaN,NaN,NJ,NaN,nan,Y,NaN,19645,NaN,5241,52413,524130,NaT,Year,107328.00,Year,15-19645,13-1111,MANAGEMENT ANALYSTS,2015-03-02,1.0,NaN,H-1B,128200.000,107400.00,149000.00,NaN,NaN,NaN,NY,NaN,15,Y,False
19662,22841,I-200-14099-816730,WITHDRAWN,2014-10-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,19662,NaN,nan,nan,nan,NaT,NaN,NaN,NaN,15-19662,NaN,NaN,2014-10-09,NaN,NaN,H-1B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,Y,False
22741,26401,I-200-14195-455989,WITHDRAWN,2014-10-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,22741,NaN,nan,nan,nan,NaT,NaN,NaN,NaN,15-22741,NaN,NaN,2014-10-09,NaN,NaN,H-1B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,Y,False
24139,28021,I-200-14230-733320,CERTIFIED-WITHDRAWN,2014-12-12,Y,600 ALEXANDER ROAD,NaN,PRINCETON,UNITED STATES OF AMERICA,12/31/2017,SOFTCRYLIC LLC,NJ,12/31/2014,8540,Y,NaN,24139,SENIOR PROGRAMMER ANALYST,5415,54151,541511,NaT,Year,90584.00,Year,15-24139,15-1131,COMPUTER PROGRAMMERS,2014-08-18,1.0,N,H-1B,110500.000,91000.00,130000.00,34021,PRINCETON,MERCER,NJ,08540,15,Y,True
24440,28381,I-200-14237-494130,CERTIFIED-WITHDRAWN,2015-04-01,N,"281 ROUTE 79, SUITE # 208",NaN,MORGANVILLE,UNITED STATES OF AMERICA,08/24/2017,"GLOBAL NEST, LLC",NJ,08/25/2014,7751,Y,NaN,24440,PROGRAMMER ANALYST,5415,54151,541511,NaT,Year,53706.00,Year,15-24440,15-1131,COMPUTER PROGRAMMERS,2014-08-25,1.0,N,H-1B,55000.000,55000.00,NaN,37025,CHARLOTTE,MECKLENBURG,NC,28262,15,Y,True
24758,28761,I-200-14245-594256,CERTIFIED-WITHDRAWN,2014-12-12,Y,600 ALEXANDER ROAD,NaN,PRINCETON,UNITED STATES OF AMERICA,11/25/2017,SOFTCRYLIC LLC,NJ,11/25/2014,8540,Y,NaN,24758,SENIOR PROGRAMMER ANALYST,5415,54151,541511,NaT,Year,91000.00,Year,15-24758,15-1131,COMPUTER PROGRAMMERS,2014-09-02,1.0,N,H-1B,110500.000,91000.00,130000.00,36061,NEW YORK,NEW YORK,NY,10010,15,Y,True
25533,29680,I-200-14258-290155,WITHDRAWN,2015-02-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,Y,NaN,25533,NaN,nan,nan,nan,NaT,NaN,NaN,NaN,15-25533,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2015-02-04,NaN,NaN,H-1B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,Y,False
27062,31449,I-200-14267-787941,CERTIFIED,2014-10-01,N,"5 INDEPENDENCE WAY, SUITE 300",NaN,PRINCETON,UNITED STATES OF AMERICA,09/25/2017,"VEDIC CONSULTING, INC.",NJ,09/25/2014,8540,Y,NaN,27062,PROGRAMMER ANALYST,5415,54151,541511,NaT,Year,90584.00,Year,15-27062,15-1131,COMPUTER PROGRAMMERS,2014-09-25,1.0,N,H-1B,117500.000,95000.00,140000.00,34021,PRINCETON,MERCER,NJ,08540,15,Y,True
29400,34253,I-200-14269-882192,CERTIFIED,2014-10-02,Y,600 ALEXANDER ROAD,NaN,PRINCETON,UNITED STATES OF AMERICA,10/01/2017,SOFTCRYLIC LLC,NJ,10/01/2014,8540,Y,NaN,29400,SR PROGRAMMER ANALYST,5415,54151,541511,NaT,Year,77854.00,Year,15-29400,15-1131,COMPUTER PROGRAMMERS,2014-09-26,1.0,N,H-1B,88927.000,77854.00,100000.00,34021,PRINCETON,MERCER,NJ,08540,15,Y,True
37140,43370,I-200-14280-286281,CERTIFIED,2014-10-14,Y,600 ALEXANDER ROAD,NaN,PRINCETON,UNITED STATES OF AMERICA,01/15/2018,SOFTCRYLIC LLC,NJ,01/15/2015,8540,Y,NaN,37140,PROGRAMMER ANALYST,5415,54151,541511,NaT,Year,73923.00,Year,15-37140,15-1131,COMPUTER PROGRAMMERS,2014-10-07,1.0,N,H-1B,83927.000,77854.00,90000.00,36061,NEW YORK,NEW YORK,NY,10018,15,Y,True
41001,47950,I-200-14283-308056,CERTIFIED,2014-10-20,N,1600 N. MAIN,NaN,LOVINGTON,UNITED STATES OF AMERICA,10/14/2017,NOR-LEA HOSPITAL DISTRICT,NM,10/15/2014,nan,Y,NaN,41001,PHYSICIAN ASSISTANT,6221,62211,622110,NaT,Year,31720.00,Year,15-41001,29-1071,PHYSICIAN ASSISTANTS,2014-10-14,1.0,N,H-1B,98000.000,98000.00,NaN,35025,LOVINGTON,LEA,NM,88260,15,Y,False
41318,48313,I-200-14283-598428,CERTIFIED,2014-10-17,N,DEPARTMENT OF HUMAN RESOURCES,NaN,FARMINGTON,UNITED STATES OF AMERICA,11/27/2015,UNIVERSITY OF CONNECTICUT HEALTH CENTER,CT,11/28/2014,6001,Y,NaN,41318,POSTDOCTORAL FELLOW,6113,61131,611310,NaT,Year,42000.00,Year,15-41318,19-1029,"BIOLOGICAL SCIENTISTS, ALL OTHER",2014-10-10,1.0,N,H-1B,51381.000,51381.00,NaN,09003,FARMINGTON,HARTFORD,CT,06032,15,Y,True
41446,48454,I-200-14283-704598,CERTIFIED,2014-10-17,Y,"100 WOOD AVENUE SOUTH, SUITE 108",NaN,ISELIN,UNITED STATES OF AMERICA,10/09/2017,ADROIT ASSOCIATES INC,NJ,10/10/2014,8830,Y,NaN,41446,SOFTWARE ENGINEER,5415,54151,541511,NaT,Year,55744.00,Year,15-41446,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-10-10,1.0,N,H-1B,60000.000,60000.00,NaN,26065,LANSING,INGHAM,MI,48933,15,Y,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1785529,617760,I-200-17180-597617,WITHDRAWN,2017-06-29,N,"147 WEST 35TH STREET, SUITE 605",NaN,NEW YORK,UNITED STATES OF AMERICA,2020-09-05 00:00:00,"AUTOMATED BUILDING MANAGEMENT SYSTEMS, INC.",NY,2017-09-06 00:00:00,1001,Y,518873,518873,PROJECT COMMISSIONING ENGINEER,5413,54133,541330,NaT,Year,58386.00,Year,17-518873,17-2199,"ENGINEERS, ALL OTHER",2017-06-29,1.0,N,H-1B,31250.000,62500.00,0.00,36061,NEW YORK,NEW YORK,NY,10001,17,Y,True
1791515,624811,I-200-17180-938063,CERTIFIED,2017-07-07,N,7705 SANDIA LOOP,NaN,AUSTIN,NaN,2020-11-30 00:00:00,"LAMAR SEARCH CONSULTANTS, INC.",TX,2017-12-01 00:00:00,nan,Y,524859,524859,PROSOURCE WELL DATA MANAGER,5613,56133,561330,NaT,Year,116771.00,Year,17-524859,11-9041,ARCHITECTURAL AND ENGINEERING MANAGERS,2017-06-29,1.0,N,H-1B,70000.000,140000.00,0.00,48201,HOUSTON,HARRIS,TX,77070,17,Y,False
1791942,625315,I-200-17180-367056,CERTIFIED,2017-07-07,N,550 WEST VAN BUREN STREET,NaN,CHICAGO,NaN,2020-07-05 00:00:00,HURON CONSULTING SERVICES LLC,IL,2017-07-05 00:00:00,COOK,Y,525286,525286,ORACLE CLOUD MANAGER,5416,54161,541611,NaT,Year,118498.00,Year,17-525286,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-06-29,1.0,N,H-1B,135000.000,130000.00,140000.00,48113,DALLAS,DALLAS,TX,75219,17,Y,False
1797273,631524,I-200-17081-243343,CERTIFIED-WITHDRAWN,2017-07-12,N,245 FIRST STREET,NaN,CAMBRIDGE,UNITED STATES OF AMERICA,2020-09-20 00:00:00,"VASSIT SERVICES US, INC.",MA,2017-09-21 00:00:00,nan,Y,530617,530617,PMO PROJECT SPECIALIST,5415,54151,541511,2017-03-28,Year,82098.00,Year,17-530617,13-1111,MANAGEMENT ANALYSTS,2017-03-22,1.0,N,H-1B,47500.000,95000.00,0.00,25017,CAMBRIDGE,MIDDLESEX,MA,02142,17,Y,False
1801765,636786,I-200-17191-569468,CERTIFIED,2017-07-14,N,801 BROADWAY N,NaN,FARGO,NaN,2020-09-30 00:00:00,SANFORD MEDICAL CENTER FARGO,ND,2017-10-01 00:00:00,CASS,Y,535109,535109,MEDICAL LABORATORY SCIENTIST,6221,62211,622110,NaT,Hour,18.98,Hour,17-535109,29-2011,MEDICAL AND CLINICAL LABORATORY TECHNOLOGISTS,2017-07-10,1.0,N,H-1B,11.875,23.75,0.00,38017,FARGO,CASS,ND,58102,17,Y,False
1822747,661676,I-203-16336-101834,CERTIFIED-WITHDRAWN,2017-08-02,NaN,650 NEWPORT CENTER DRIVE,NaN,NEWPORT BEACH,UNITED STATES OF AMERICA,2018-12-15 00:00:00,"PACIFIC INVESTMENT MANAGEMENT COMPANY, LLC",CA,2016-12-16 00:00:00,CA,Y,556091,556091,"SVP, PORTFOLIO MANAGER",5239,52392,523920,2016-12-12,Year,141960.00,Year,17-556091,11-3031,FINANCIAL MANAGERS,2016-12-06,1.0,NaN,E-3 Australian,235000.000,220000.00,250000.00,06059,NEWPORT CENTER DRIVE,ORANGE,CA,92660,17,Y,False
1858109,703326,I-200-17234-027707,CERTIFIED,2017-08-30,N,111 N. CANAL ST.,NaN,CHICAGO,NaN,2020-12-03 00:00:00,GOGO LLC,IL,2017-12-03 00:00:00,6606,Y,591453,591453,"MANAGER, QA ENGINEERING",3342,33422,334220,NaT,Year,108118.00,Year,17-591453,11-3021,COMPUTER AND INFORMATION SYSTEMS MANAGERS,2017-08-24,1.0,N,H-1B,132559.000,108118.00,157000.00,17031,CHICAGO,COOK,IL,60606,17,Y,True
1862715,708925,I-203-17234-152528,CERTIFIED,2017-09-05,NaN,200 NORTH BROADWAY,NaN,ST. LOUIS,NaN,2019-08-28 00:00:00,"FLEISHMAN-HILLARD, INC.",MO,2017-08-29 00:00:00,nan,Y,596059,596059,SENIOR VICE PRESIDENT,5416,54161,541613,NaT,Year,170560.00,Year,17-596059,11-2031,PUBLIC RELATIONS AND FUNDRAISING MANAGERS,2017-08-29,1.0,NaN,E-3 Australian,95750.000,191500.00,0.00,36061,NEW YORK,NEW YORK,NY,10017,17,Y,False
1871933,719939,I-200-17248-918983,WITHDRAWN,2017-09-13,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,nan,NaN,605277,605277,NaN,nan,nan,nan,NaT,NaN,0.00,NaN,17-605277,NaN,NaN,2017-09-13,0.0,NaN,H-1B,0.000,0.00,0.00,NaN,NaN,NaN,NaN,NaN,17,Y,False
1872885,721080,I-200-17249-980150,CERTIFIED,2017-09-14,N,111 N. CANAL ST.,NaN,CHICAGO,NaN,2020-09-08 00:00:00,GOGO LLC,IL,2017-09-11 00:00:00,6606,Y,606229,606229,"MANAGER, QA ENGINEERING",3342,33422,334220,NaT,Year,116646.00,Year,17-606229,11-3021,COMPUTER AND INFORMATION SYSTEMS MANAGERS,2017-09-08,1.0,N,H-1B,136823.000,116646.00,157000.00,17031,CHICAGO,COOK,IL,60606,17,Y,True
1879115,728448,I-200-17255-411178,CERTIFIED,2017-09-20,N,161 N. CLARK ST.,NaN,CHICAGO,NaN,2020-09-18 00:00:00,ACCENTURE LLP,IL,2017-09-19 00:00:00,6061,Y,612459,612459,COMPUTER SYSTEMS ANALYST 3,5416,5416,5416,NaT,Year,78749.00,Year,17-612459,15-1121,COMPUTER SYSTEMS ANALYSTS,2017-09-14,1.0,N,H-1B,124500.000,98000.00,151000.00,26111,MIDLAND,MIDLAND,MI,48674,17,Y,True
1879116,728449,I-200-17255-171711,CERTIFIED,2017-09-20,N,161 N. CLARK ST.,NaN,CHICAGO,NaN,2020-09-18 00:00:00,ACCENTURE LLP,IL,2017-09-19 00:00:00,6061,Y,612460,612460,COMPUTER SYSTEMS ANALYST 3,5416,5416,5416,NaT,Year,77938.00,Year,17-612460,15-1121,COMPUTER SYSTEMS ANALYSTS,2017-09-14,1.0,N,H-1B,134500.000,106000.00,163000.00,26017,AUBURN,BAY,MI,48611,17,Y,True
1879370,728747,I-200-17255-793338,CERTIFIED,2017-09-20,N,161 N. CLARK ST.,NaN,CHICAGO,NaN,2020-09-18 00:00:00,ACCENTURE LLP,IL,2017-09-19 00:00:00,6061,Y,612714,612714,COMPUTER SYSTEMS ANALYST 3,5416,5416,5416,NaT,Year,89419.00,Year,17-612714,15-1121,COMPUTER SYSTEMS ANALYSTS,2017-09-14,1.0,N,H-1B,126209.500,89419.00,163000.00,17031,CHICAGO,COOK,IL,60601,17,Y,True
1905613,16648,I-200-17269-703876,CERTIFIED,2017-10-12,N,10056 HIGHWAY 52 NORTH,NaN,ANSONVILLE,UNITED STATES OF AMERICA,2021-02-15 00:00:00,"PREMIERE FIBERS, LLC",NC,2018-02-16 00:00:00,nan,Y,14307,14307,SENIOR QUALITY ENGINEER,3131,31311,313113,NaT,Year,105976.00,Year,18-14307,11-9041,ARCHITECTURAL AND ENGINEERING MANAGERS,2017-10-05,1.0,N,H-1B,52988.000,105976.00,0.00,37007,ANSONVILLE,ANSON,NC,28007,18,Y,False
1907724,19099,I-200-17276-466062,CERTIFIED,2017-10-11,N,1741 WHITEHORSE-MERCERVILLE RD.,NaN,MERCERVILLE,UNITED STATES OF AMERICA,2020-10-15 00:00:00,"JCMS, INC.",NJ,2017-10-16 00:00:00,8619,Y,16418,16418,COST ESTIMATOR,5413,54133,541330,NaT,Year,58323.00,Year,18-16418,13-1051,COST ESTIMATORS,2017-10-04,1.0,N,H-1B,35000.000,70000.00,0.00,34021,MERCERVILLE,MERCER,NJ,08619,18,Y,True
1910063,21864,I-200-17275-180089,CERTIFIED,2017-10-13,N,21045 CALIFA STREET,NaN,WOODLAND HILLS,UNITED STATES OF AMERICA,2020-10-15 00:00:00,"ASSOCIATED FOREIGN EXCHANGE, INC.",CA,2017-10-16 00:00:00,9137,Y,18757,18757,BUSINESS INTELLIGENCE RISK ANALYST,5231,52313,523130,NaT,Year,82347.00,Year,18-18757,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2017-10-09,1.0,N,H-1B,55000.000,110000.00,0.00,06037,WOODLAND HILLS,LOS ANGELES,CA,91367,18,Y,True
1910155,21974,I-200-17272-584000,DENIED,2017-10-03,Y,NaN,NaN,NaN,NaN,2020-09-28 00:00:00,NaN,NaN,2017-09-29 00:00:00,nan,Y,18849,18849,LEAD ENGINEER,nan,nan,nan,NaT,Year,81910.00,Year,18-18849,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2017-09-29,1.0,N,H-1B,40955.000,81910.00,0.00,25009,ANDOVER,ESSEX,MA,01810,18,Y,False
1913959,26408,I-200-17270-294434,CERTIFIED,2017-10-10,N,16661 JACINTOPORT BOULEVARD,NaN,HOUSTON,UNITED STATES OF AMERICA,2021-03-08 00:00:00,"TECHNIP UMBILICALS, INC.",TX,2018-03-09 00:00:00,7015,Y,22653,22653,PLANNING MANAGER,5413,54133,541330,NaT,Year,103147.00,Year,18-22653,11-9021,CONSTRUCTION MANAGERS,2017-10-03,1.0,N,H-1B,64000.000,128000.00,0.00,48201,HOUSTON,HARRIS,TX,77015,18,Y,True
1918189,31382,I-200-17298-869821,CERTIFIED,2017-10-31,N,"281 ROUTE 79, SUITE # 208",NaN,MORGANVILLE,UNITED STATES OF AMERICA,2020-12-04 00:00:00,"GLOBAL NEST, LLC",NJ,2017-12-05 00:00:00,7751,Y,26883,26883,DATABASE ADMINISTRATOR,5415,54151,541511,NaT,Year,75338.00,Year,18-26883,15-1141,DATABASE ADMINISTRATORS,2017-10-25,1.0,N,H-1B,38500.000,77000.00,0.00,09001,DANBURY,FAIRFIELD COUNTY,CT,06810,18,Y,True
1925528,40038,I-200-17324-079651,CERTIFIED,2017-11-27,Y,"100 WOOD AVENUE SOUTH, SUITE 108",NaN,ISELIN,UNITED STATES OF AMERICA,2020-11-19 00:00:00,ADROIT ASSOCIATES INC,NJ,2017-11-20 00:00:00,8830,Y,34222,34222,HYPERION ESSBASE DEVELOPER,5415,54151,541511,NaT,Year,91229.00,Year,18-34222,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-11-20,1.0,N,H-1B,46750.000,93500.00,0.00,29095,KANSAS CITY,JACKSON,MO,64105,18,Y,True
1929905,45215,I-200-17310-193136,CERTIFIED,2017-11-13,Y,"100 WOOD AVENUE SOUTH, SUITE 108",NaN,ISELIN,UNITED STATES OF AMERICA,2021-01-07 00:00:00,ADROIT ASSOCIATES INC,NJ,2018-01-07 00:00:00,8830,Y,38599,38599,SR. QA SOFTWARE ENGINEER,5415,54151,541511,NaT,Year,76211.00,Year,18-38599,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-11-06,1.0,N,H-1B,38150.000,76300.00,0.00,47037,ANTIOCH,DAVIDSON,TN,37013,18,Y,True
1939326,56352,I-203-17319-946719,CERTIFIED,2017-11-27,NaN,405 LEXINGTON AVENUE,NaN,NEW YORK,UNITED STATES OF AMERICA,2019-12-03 00:00:00,LODIGE USA INC,NY,2017-12-04 00:00:00,174,Y,48020,48020,PLC SOFTWARE ENGINEER,3332,3332,3332,NaT,Year,93600.00,Year,18-48020,15-1133,"SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE",2017-11-20,1.0,NaN,E-3 Australian,55500.000,111000.00,0.00,45083,GREER,SPARTANBURG,SC,29651,18,Y,True
1940023,57176,I-200-17341-720184,CERTIFIED,2017-12-18,N,101 HUDSON STREET,NaN,JERSEY CITY,UNITED STATES OF AMERICA,2020-12-14 00:00:00,"STRATACENT, INC.",NJ,2017-12-15 00:00:00,nan,Y,48717,48717,COMPUTER SYSTEM ANALYST,5415,54151,541512,NaT,Year,123115.00,Year,18-48717,15-1121,COMPUTER SYSTEMS ANALYSTS,2017-12-12,1.0,N,H-1B,62000.000,124000.00,0.00,51059,RESTON,FAIRFAX,VA,20190,18,Y,False

In [648]:
#parking vvdatafull
vvdatafull1 = vvdatafull1[vvdatafull1['DROP'] != 'Y']

In [649]:
len(vvdatafull1)

1985544

In [650]:
vvdatafull1['emp_zip'] = vvdatafull1['emp_zip'].astype('str')
vvdatafull1['emp_zip2'] = vvdatafull1['emp_zip'].apply(lambda x: x[0:5])

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [639]:
vvdatafull1['emp_zip'].head(100)

0     55432
1     73019
2     75039
3     77088
4     22102
5     55117
6     94304
7     22102
8     94304
9     30024
10    94304
11    55802
12    20170
13    94304
14    08872
15    94304
16    27408
17    22102
18    77027
19    77027
20    91124
21    48098
22    80110
23    08817
24    17011
25    53719
26    22102
27    22102
28    13021
29    08830
      ...
70    77056
71    77079
72    77024
73    22102
74    22102
75    75057
76    22102
77    22102
78    21205
79    30305
80    19898
81    76102
82    60015
83    60015
84    92617
85    10038
86    94304
87    19898
88    22102
89    75201
90    60015
91    77056
92    22102
93    20191
94    20191
95    77079
96    22102
97    98006
98    77042
99    53719
Name: emp_zip, Length: 100, dtype: object

In [431]:
#vvdatafull1['emp_zip'] = pd.to_numeric(vvdatafull1['emp_zip'], errors = 'coerce')

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [442]:
#vvdatafull1['emp_zip'] = vvdatafull1['emp_zip'].astype('str')
#vvdatafull1.loc[(vvdatafull1['emp_zip'].apply(lambda x: len(x) < 5)),'DROP'] = 'Y'

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [651]:
numpattern = r'[0-9]'
vvdatafull1['test'] = pd.Series(vvdatafull1['emp_zip2']).str.match(numpattern)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [652]:
vvdatafull1.loc[(vvdatafull1['test'] == False), 'DROP'] = 'DROP'

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [654]:
vvdatafull1[vvdatafull1['test'] == False] #165 rows

,level_0,case_num,case_status,decision_date,dependent,emp_address,emp_cfips,emp_city,emp_cntry,emp_end,emp_name,emp_st,emp_start,emp_zip,full_time,id,index,job,naics4,naics5,naics_full,org_cert_date,payunit,pw,pw_payunit,row_id,soc_code,soc_name,submit_date,tot_workers,violator,visa_class,wage,wage_from,wage_to,work_cfips,work_city,work_cnty,work_st,work_zip,year,DROP,test,emp_zip2
341,395,I-200-11269-063015,WITHDRAWN,2014-10-06,Y,555 METRO PLACE NORTH,NaN,DUBLIN,UNITED STATES OF AMERICA,10/09/2014,UNITED SOFTWARE GROUP INC.,OH,10/10/2011,FRANK,Y,NaN,341,PROGRAMMER ANALYST,5415,54151,541511,NaT,Year,48672.00,Year,15-341,15-1131,COMPUTER PROGRAMMERS,2011-09-26,1.0,N,H-1B,60000.000,60000.00,NaN,26125,TROY,OAKLAND,MI,48084,15,DROP,False,FRANK
17026,19632,I-200-14070-344523,CERTIFIED-WITHDRAWN,2014-10-01,N,1 REDWOOD CRESCENT,NaN,EAST KILBRIDGE,UNITED KINGDOM,09/16/2017,CBC HIVE USA INC.,NaN,09/17/2014,G74 5,Y,NaN,17026,CHIEF EXECUTIVE OFFICER,2131,21311,213112,NaT,Year,159806.00,Year,15-17026,11-1021,GENERAL AND OPERATIONS MANAGERS,2014-03-19,1.0,N,H-1B,250000.000,250000.00,NaN,48201,HOUSTON,HARRIS,TX,77064,15,DROP,False,G74 5
31944,37270,I-200-14273-907132,CERTIFIED,2014-10-07,N,259 STEPHENS STREET,NaN,BELLEVILLE,UNITED STATES OF AMERICA,01/06/2018,"INTEGRATED CONSTRUCTION ENTERPRISES, INC.",NJ,01/07/2015,ESSEX,Y,NaN,31944,DESIGN BUILD ENGINEER/ESTIMATOR,2362,23622,236220,NaT,Year,91395.00,Year,15-31944,13-1051,COST ESTIMATORS,2014-10-01,1.0,N,H-1B,103500.000,99000.00,108000.00,34013,BELLEVILLE,ESSEX,NJ,07109,15,DROP,False,ESSEX
36137,42207,I-200-14279-488046,WITHDRAWN,2014-10-09,N,400-1818 CORNWALL AVENUE,NaN,VANCOUVER,CANADA,10/12/2017,LULULEMON USA INC.,NaN,10/13/2014,V6J 1,Y,NaN,36137,ORDER MANAGEMENT SYSTEMS LEAD,4481,4481,4481,NaT,Year,114400.00,Year,15-36137,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-10-07,1.0,N,H-1B,125000.000,125000.00,NaN,06075,SAN FRANCISCO,SAN FRANCISCO,CA,94111,15,DROP,False,V6J 1
39102,45714,I-200-14281-778311,CERTIFIED,2014-10-16,N,400-1818 CORNWALL AVENUE,NaN,VANCOUVER,CANADA,10/15/2017,LULULEMON USA INC.,NaN,10/15/2014,V6J 1,Y,NaN,39102,ORDER MANAGEMENT SYSTEMS LEAD,4481,4481,4481,NaT,Year,114400.00,Year,15-39102,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-10-09,1.0,N,H-1B,125000.000,125000.00,NaN,06075,SAN FRANCISCO,SAN FRANCISCO,CA,94111,15,DROP,False,V6J 1
47506,55674,I-200-14290-390206,CERTIFIED,2014-10-23,N,2255 CENTRE AVENUE,NaN,BELLMORE,UNITED STATES OF AMERICA,11/02/2017,"RELIABLE GROUP VENTURES, LLC",NY,11/03/2014,NASSA,Y,NaN,47506,PROJECT MANAGER,5415,54151,541511,NaT,Year,68536.00,Year,15-47506,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2014-10-17,1.0,N,H-1B,71000.000,71000.00,NaN,36059,BELLMORE,NASSAU,NY,11710,15,DROP,False,NASSA
63120,74164,I-200-14309-144324,CERTIFIED,2014-11-17,N,621 MAIN STREET,NaN,WALTHAM,UNITED STATES OF AMERICA,11/10/2017,"HERO4HIRE CREATIVE, LLC",MA,11/11/2014,MIDDL,Y,NaN,63120,TECHNICAL DIRECTOR,5414,54149,541490,NaT,Year,39582.00,Year,15-63120,27-2012,PRODUCERS AND DIRECTORS,2014-11-10,1.0,N,H-1B,50016.000,50016.00,NaN,25017,WALTHAM,MIDDLESEX,MA,02452,15,DROP,False,MIDDL
91032,107108,I-200-14342-879109,CERTIFIED,2014-12-12,N,"NTT DATA, INC.",NaN,PRINCETON,UNITED STATES OF AMERICA,12/14/2017,"NTT DATA, INC.",NJ,12/15/2014,PRINC,Y,NaN,91032,COMPUTER SYSTEMS ANALYST,5415,54151,541511,NaT,Year,97178.00,Year,15-91032,15-1121,COMPUTER SYSTEMS ANALYSTS,2014-12-08,1.0,N,H-1B,118589.000,97178.00,140000.00,09003,PLAINVILLE,HARTFORD,CT,06062,15,DROP,False,PRINC
118317,139239,I-200-15009-422303,CERTIFIED,2015-01-15,N,"NTT DATA, INC.",NaN,PRINCETON,UNITED STATES OF AMERICA,01/15/2018,"NTT DATA, INC.",NJ,01/16/2015,PRINC,Y,NaN,118317,DATABASE ADMINISTRATOR,5415,54151,541511,NaT,Year,70741.00,Year,15-118317,15-1141,DATABASE ADMINISTRATORS,2015-01-09,1.0,N,H-1B,90370.500,70741.00,110000.00,13121,ATLANTA,FULTON,GA,30328,15,DROP,False,PRINC
120091,141388,I-200-15012-399514,CERTIFIED,2015-01-20,N,"16302 PLEASANTVILLE RD, SUITE 100",NaN,SAN ANTONIO,UNITED STATES OF AMERICA,07/10/2018,"THE CONSULTING ENGINEERS GROUP, INC.",TX,07/11/2015,SAN A,Y,NaN,120091,DESIGN ENGINEER,5413,54133,541330,NaT,Year,48984.00,Year,15-120091,17-2051,CIVIL ENGINEERS,2015-01-13,1.0,N,H-1B,60000.000,60000.00,NaN,48029,SAN ANTONIO,BEXAR,TX,78233,15,DROP,False,SAN A
135690,159988,I-200-15023-866051,CERTIFIED,2015-02-09,N,1252 BORREGAS AVENUE,NaN,SUNNYVALE,UNITED STATES OF AMERICA,08/05/2018,EGAIN CORPORATION,CA,08/05/2015,SUNNY,Y,NaN,135690,SR. SOFTWARE ENGINEER (15-1199.02),5415,54151,541511,NaT,Year,94598.00,Year,15-135690,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2015-02-03,1.0,N,H-1B,120000.000,120000.00,NaN,06085,SUNNYVALE,SANTA CLARA,CA,94089,15,DROP,False,SUNNY
144952,170971,I-200-15029-764879,CERTIFIED,2015-02-04,N,"NTT DATA, INC.",NaN,PRINCETON,UNITED STATES OF AMERICA,06/30/2018,"NTT DATA, INC.",NJ,07/01/2015,PRINC,Y,NaN,144952,COMPUTER PROGRAMMER,5415,54151,541511,NaT,Year,99549.00,Year,15-144952,15-1131,COMPUTER PROGRAMMERS,2015-01-29,2.0,N,H-1B,119774.500,99549.00,140000.00,06081,SAN CARLOS,SAN MATEO,CA,94070,15,DROP,False,PRINC
154001,181653,I-200-15034-407961,CERTIFIED,2015-02-24,N,40 WEST 57TH STREET,NaN,NEW YORK,UNITED STATES OF AMERICA,08/17/2018,TWO CREEKS CAPITAL MANAGEMENT LP,NY,08/17/2015,NEW Y,Y,NaN,154001,ANALYST,5239,52392,523920,NaT,Year,95576.00,Year,15-154001,13-2051,FINANCIAL ANALYSTS,2015-02-18,1.0,N,H-1B,250000.000,250000.00,NaN,36061,NEW YORK,NEW YORK,NY,10019,15,DROP,False,NEW Y
176881,208619,I-200-15041-748544,CERTIFIED,2015-02-17,N,85 BROAD STREET,NaN,NEW YORK,UNITED STATES OF AMERICA,08/01/2018,SUNGARD SYSTEMS INTERNATIONAL INC.,NY,08/01/2015,NEW Y,Y,NaN,176881,FRONT ARENA ANALYST,5415,54151,541511,NaT,Year,63086.00,Year,15-176881,15-1121,COMPUTER SYSTEMS ANALYSTS,2015-02-10,1.0,N,H-1B,75000.000,75000.00,NaN,36061,NEW YORK,NEW YORK,NY,10173,15,DROP,False,NEW Y
237424,280530,I-200-15058-658353,CERTIFIED,2015-03-05,Y,10901 WEST 120TH AVE,NaN,BROOMFIELD,UNITED STATES OF AMERICA,08/20/2018,"GAVS TECHNOLOGIES, NA, INC.",CO,08/20/2015,BROOM,Y,NaN,237424,SYSTEMS ADMINISTRATOR,5415,54151,541511,NaT,Year,54621.00,Year,15-237424,15-1142,NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS,2015-02-28,1.0,N,H-1B,54621.000,54621.00,NaN,17031,CHICAGO,COOK,IL,60601,15,DROP,False,BROOM
260425,308143,I-200-15063-739033,CERTIFIED,2015-03-12,N,425 BEDFORD STREET,NaN,DALLAS,UNITED STATES OF AMERICA,08/31/2018,WEST DALLAS INVESTMENTS LP,TX,09/01/2015,DALLA,Y,NaN,260425,MARKET RESEARCH ANALYST,5413,54132,541320,NaT,Year,42973.00,Year,15-260425,13-1161,MARKET RESEARCH ANALYSTS AND MARKETING SPECIAL...,2015-03-06,1.0,N,H-1B,45000.000,45000.00,NaN,48113,DALLAS,DALLAS,TX,75212,15,DROP,False,DALLA
260877,308694,I-200-15063-795081,DENIED,2015-03-17,N,2450 NW 76 ST,NaN,MIAMI,UNITED STATES OF AMERICA,03/08/2018,"LEASA INDUSTRIES CO., INC.",FL,03/09/2015,SS147,Y,NaN,260877,HUMAN RESOURCES SPECIALIST,9231,92313,923130,NaT,Hour,17.50,Hour,15-260877,13-1071,HUMAN RESOURCES SPECIALISTS,2015-03-09,1.0,N,H-1B,16.390,16.39,NaN,12086,MIAMI,MIAMI DADE,FL,33147,15,DROP,False,SS147
270278,320026,I-200-15064-946797,DENIED,2015-03-16,N,5859 AMERICA WAY,NaN,ORLANDO,UNITED STATES OF AMERICA,09/03/2018,SUN SOL MANAGEMENT CORP,FL,09/04/2015,ORANG,N,NaN,270278,HOSPITALITY MANAGER,7211,72111,721110,NaT,Hour,25.63,Hour,15-270278,11-2021,MARKETING MANAGERS,2015-03-05,1.0,N,H-1B,25.630,25.63,NaN,NaN,ORLANDO,ORANGE,FL,NaN,15,DROP,False,ORANG
296190,351995,I-200-15069-553690,CERTIFIED,2015-03-16,N,6941 SW 196 AVENUE,NaN,FORT LAUDERDALE,UNITED STATES OF AMERICA,09/08/2018,"CAMELLIA & ASSOCIATES, LLC",FL,09/09/2015,BROWA,N,NaN,296190,PRODUCT DEVELOPMENT MANAGER,4244,42445,424450,NaT,Hour,14.91,Hour,15-296190,27-1022,FASHION DESIGNERS,2015-03-10,1.0,N,H-1B,15.000,15.00,NaN,12011,FORT LAUDERDALE,BROWARD,FL,33332,15,DROP,False,BROWA
325656,388142,I-200-15072-810216,CERTIFIED,2015-03-19,N,33 WEST 17TH STREET,NaN,NEW YORK,UNITED STATES OF AMERICA,08/31/2018,FACTORY 798 MEDIA INC,NY,09/01/2015,NEW Y,Y,NaN,325656,DATA ANALYST,5182,51821,518210,NaT,Year,48048.00,Year,15-325656,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2015-03-13,1.0,N,H-1B,48048.000,48048.00,NaN,36061,NEW YORK,NEW YORK,NY,10017,15,DROP,False,NEW Y
359331,429928,I-200-15078-092793,CERTIFIED,2015-03-25,N,226 WEST 47TH STREET,NaN,NEW YORK,UNITED STATES OF AMERICA,09/01/2018,TOWN SQUARE PRODUCTIONS INC.,NY,09/02/2015,NEW Y,N,NaN,359331,ASSOCIATE PRODUCER,5121,51219,512199,NaT,Hour,24.38,Hour,15-359331,27-2012,PRODUCERS AND DIRECTORS,2015-03-19,1.0,N,H-1B,24.500,24.50,NaN,36061,NEW YORK,NEW YORK,NY,10036,15,DROP,False,NEW Y
363396,434834,I-200-15078-596424,CERTIFIED,2015-03-30,N,315 HUDSON STREET,NaN,NEW YORK,UNITED STATES OF AMERICA,09/15/2018,"MODA OPERANDI, INC.",NY,09/15/2015,NEW Y,Y,NaN,363396,RETAIL OPERATIONS ANALYST,4541,45411,45411,NaT,Hour,22.54,Hour,15-363396,13-1199,"BUSINESS OPERATIONS SPECIALISTS, ALL OTHER",2015-03-24,1.0,N,H-1B,22.645,22.54,22.75,36061,NEW YORK,NEW YORK,NY,10013,15,DROP,False,NEW Y
367538,439952,I-200-15079-087996,CERTIFIED,2015-03-26,N,5859 AMERICA WAY,NaN,ORLANDO,UNITED STATES OF AMERICA,09/18/2018,SUN SOL MANAGEMENT CORP,FL,09/19/2015,ORANG,N,NaN,367538,HOSPITALITY MANAGER,7211,72111,721110,NaT,Hour,25.63,Hour,15-367538,11-2021,MARKETING MANAGERS,2015-03-20,1.0,N,H-1B,25.630,25.63,NaN,NaN,ORLANDO,ORANGE,FL,NaN,15,DROP,False,ORANG
392141,470279,I-200-15085-030783,DENIED,2015-04-07,N,267 CANE CREEK ROAD,NaN,FLETCHER,UNITED STATES OF AMERICA,09/19/2018,SMARTRAC TECHNOLOGY FLETCHER INC,NC,09/20/2015,HENDE,Y,NaN,392141,PROCESS ENGINEER,3344,33441,334419,NaT,Year,57491.00,Year,15-392141,17-2112,INDUSTRIAL ENGINEERS,2015-03-30,1.0,N,H-1B,60000.000,60000.00,NaN,37089,FLETCHER,HENDERSON,NC,28732,15,DROP,False,HENDE
395420,474268,I-200-15086-120791,CERTIFIED,2015-04-02,N,1003 WEST SUNFLOWER ROAD,NaN,CLEVELAND,UNITED STATES OF AMERICA,07/31/2018,DELTA STATE UNIVERSITY,MS,08/01/2015,BOLIV,Y,NaN,395420,ASSISTANT PROFESSOR OF COMPUTER INFORMATION SY...,6113,61131,611310,NaT,Hour,20.44,Hour,15-395420,25-1021,"COMPUTER SCIENCE TEACHERS, POSTSECONDARY",2015-03-27,1.0,N,H-1B,48.400,48.40,NaN,28011,CLEVELAND,BOLIVAR,MS,38733,15,DROP,False,BOLIV
395778,474712,I-200-15086-261338,WITHDRAWN,2015-04-07,N,2609 METROPOLITAN PARKWAY,NaN,STERLING HEIGHTS,UNITED STATES OF AMERICA,09/30/2017,ONE SOURCE HEALTH & SPINE,MI,04/14/2015,MACOM,Y,NaN,395778,CHIROPRACTOR,6213,62131,62131,NaT,Year,39354.00,Year,15-395778,29-1011,CHIROPRACTORS,2015-04-07,1.0,N,H-1B,40000.000,40000.00,NaN,26099,STERLING HEIGHTS,MACOMB,MI,48310,15,DROP,False,MACOM
406544,487625,I-200-15093-652125,CERTIFIED,2015-04-09,N,8001 REDWOOD BLVD.,NaN,NOVATO,UNITED STATES OF AMERICA,05/14/2018,BUCK INSTITUTE FOR RESEARCH ON AGING,CA,05/15/2015,MARIN,Y,NaN,406544,POSTDOCTORAL RESEARCH FELLOW,5417,54171,541710,NaT,Year,51230.00,Year,15-406544,19-1029,"BIOLOGICAL SCIENTISTS, ALL OTHER",2015-04-03,1.0,N,H-1B,51230.000,51230.00,NaN,06041,NOVATO,MARIN,CA,94945,15,DROP,False,MARIN
427874,512811,I-200-15111-193810,CERTIFIED,2015-04-27,N,"FIVE SANTA FE WAY,",NaN,CRANBURY,UNITED STATES OF AMERICA,09/30/2018,HORIZON TIRE INC.,NJ,10/01/2015,NEW J,Y,NaN,427874,COMPUTER SYSTEMS ENGINEER,4231,42313,423130,NaT,Hour,22.39,Hour,15-427874,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2015-04-21,1.0,N,H-1B,22.390,22.39,NaN,34021,CRANBURY,MIDDLESEX-EDISON,NJ,08512,15,DROP,False,NEW J
432177,517921,I-200-15113-574568,CERTIFIED,2015-04-30,N,400-1818 CORNWALL AVENUE,NaN,VANCOUVER,CANADA,04/30/2018,LULULEMON USA INC.,NaN,05/01/2015,V6J 1,Y,NaN,432177,SENIOR ENDECA DEVELOPER,4481,4481,4481,NaT,Year,114400.00,Year,15-432177,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2015-04-24,1.0,N,H-1B,120000.000,120000.00,NaN,06075,SAN FRANCISCO,SAN FRANCISCO,CA,94111,15,DROP,False,V6J 1
457335,547652,I-200-15134-218109,CERTIFIED,2015-05-29,N,2500 CALIFORNIA PLAZA,NaN,OMAHA,UNITED STATES OF AMERICA,06/30/2016,CREIGHTON UNIVERSITY,NE,07/01/2015,DOUGL,Y,NaN,457335,RESIDENT PHYSICIAN,6113,61131,611310,NaT,Year,51605.00,Year,15-457335,29-1069,"PHYSICIANS AND SURGEONS, ALL OTHER",2015-05-23,1.0,N,H-1B,61191.000,61191.00,NaN,31055,OMAHA,DOUGLAS,NE,68131,15,DROP,False,DOUGL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595134,389360,I-200-17046-069808,CERTIFIED,2017-03-22,N,7423 DOIG DR.,NaN,GARDEN GROVE,UNITED STATES OF AMERICA,2020-09-12 00:00:00,EASYFLEX INC.,CA,2017-09-12 00:00:00,GARDE,N,328478,328478,HUMAN RESOURCES MANAGERS,3329,33291,332913,NaT,Hour,31.22,Hour,17-328478,11-3121,HUMAN RESOURCES MANAGERS,2017-03-16,1.0,N,H-1B,19.025,38.05,0.00,06059,GARDEN GROVE,ORANGE,CA,92841,17,DROP,False,GARDE
1597983,392706,I-200-17069-181239,CERTIFIED,2017-03-22,N,400 - 1818 CORNWALL AVENUE,NaN,VANCOUVER,CANADA,2020-07-26 00:00:00,LULULEMON USA INC.,NaN,2017-07-27 00:00:00,V6J 1,Y,331327,331327,SENIOR ATG DEVELOPER (INTERNAL TITLE: SR. SFTW...,4481,4481,4481,NaT,Year,117770.00,Year,17-331327,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-03-16,1.0,N,H-1B,127171.500,117770.00,136573.00,06075,SAN FRANCISCO,SAN FRANCISCO,CA,94105,17,DROP,False,V6J 1
1605730,401907,I-200-17081-894170,WITHDRAWN,2017-03-22,N,11 BROADWAY,NaN,NEW YORK,UNITED STATES OF AMERICA,2020-09-20 00:00:00,"RCC VENTURES, LLC",NY,2017-09-21 00:00:00,NEW Y,N,339074,339074,FINANCIAL ANALYST,5239,52393,523930,NaT,Hour,31.61,Hour,17-339074,13-2051,FINANCIAL ANALYSTS,2017-03-22,1.0,N,H-1B,15.805,31.61,0.00,36061,NEWYORK,NEW YORK,NY,10004,17,DROP,False,NEW Y
1608775,405552,I-200-17074-189170,CERTIFIED,2017-03-23,N,400 NORTHRIDGE ROAD,NaN,ATLANTA,UNITED STATES OF AMERICA,2020-03-23 00:00:00,"COVIUS TECHNOLOGY SOLUTIONS, LLC",GA,2017-03-24 00:00:00,FULTO,Y,342119,342119,SENIOR DEVELOPER,5415,54151,541511,NaT,Year,95306.00,Year,17-342119,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-03-17,1.0,N,H-1B,55750.000,111500.00,0.00,13089,ATLANTA,FULTON,GA,30350,17,DROP,False,FULTO
1611079,408386,I-200-17076-017253,CERTIFIED,2017-03-23,N,"35325 FIRCREST ST, #A",NaN,NEWARK,UNITED STATES OF AMERICA,2020-09-09 00:00:00,"GUILD SYSTEMS, INC",CA,2017-09-10 00:00:00,ALAME,Y,344423,344423,CONTENT MANAGEMENT SYSTEMS SOLUTION ARCHITECT,5416,54161,541618,NaT,Year,93870.00,Year,17-344423,15-1133,"SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE",2017-03-17,1.0,N,H-1B,54000.000,108000.00,0.00,36081,NEW YORK CITY,NEW YORK,NY,11101,17,DROP,False,ALAME
1613335,411167,I-200-17076-169446,CERTIFIED,2017-03-23,N,201 MISSION STREET,NaN,SAN FRANCISCO,UNITED STATES OF AMERICA,2020-07-17 00:00:00,"CLEAN POWER FINANCE, INC.,",CA,2017-07-17 00:00:00,SAN F,Y,346679,346679,QA MANGER,5182,51821,518210,NaT,Year,114795.00,Year,17-346679,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-03-17,1.0,N,H-1B,65000.000,130000.00,0.00,06075,SAN FRANCISCO,SAN FRANCISCO,CA,94105,17,DROP,False,SAN F
1614250,412318,I-200-17076-488032,CERTIFIED,2017-03-23,N,"35325 FIRCREST ST, #A",NaN,NEWARK,UNITED STATES OF AMERICA,2020-09-09 00:00:00,"GUILD SYSTEMS, INC",CA,2017-09-10 00:00:00,ALAME,Y,347594,347594,DEVOPS SYSTEMS ENGINEER,5416,54161,541618,NaT,Year,90646.00,Year,17-347594,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-03-17,1.0,N,H-1B,50000.000,100000.00,0.00,51059,RESTON,FAIRFAX,VA,20190,17,DROP,False,ALAME
1620555,419991,I-200-17043-731079,CERTIFIED,2017-03-23,N,617 W. 7TH STREET,NaN,LOS ANGELES,UNITED STATES OF AMERICA,2020-05-01 00:00:00,"FLO TECHNOLOGIES, INC.",CA,2017-05-01 00:00:00,CA 90,Y,353899,353899,SOFTWARE ENGINEER,3329,33291,332913,NaT,Year,73882.00,Year,17-353899,15-1133,"SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE",2017-03-19,1.0,N,H-1B,37500.000,75000.00,0.00,06037,LOS ANGELES,LOS ANGELES,CA,90017,17,DROP,False,CA 90
1663598,471867,I-200-17083-283014,CERTIFIED,2017-03-30,N,9234 RUSH STREET,NaN,SOUTH EL MONTE,UNITED STATES OF AMERICA,2020-09-14 00:00:00,"CHAMSA, INC.",CA,2017-09-15 00:00:00,SOU91,Y,396942,396942,SALES MANAGER,4246,42461,42461,NaT,Year,55037.00,Year,17-396942,11-2022,SALES MANAGERS,2017-03-24,1.0,N,H-1B,28000.000,56000.00,0.00,06037,SOUTH EL MONTE,LOS ANGELES,CA,91733,17,DROP,False,SOU91
1690417,504328,I-200-17096-243747,CERTIFIED,2017-04-12,N,1600 OLD COUNTRY ROAD,NaN,PLAINVIEW,UNITED STATES OF AMERICA,2020-04-16 00:00:00,"NEULION USA, INC.",NY,2017-04-17 00:00:00,NASSA,Y,423761,423761,SENIOR ANDROID DEVELOPER,5415,54151,541519,NaT,Year,78229.00,Year,17-423761,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-04-06,1.0,N,H-1B,45000.000,90000.00,0.00,36059,PLAINVIEW,NASSAU,NY,11803,17,DROP,False,NASSA
1697685,513043,I-203-17082-129346,WITHDRAWN,2017-04-17,NaN,"500 FRANK W. BURR BLVD.,SUITE 19",NaN,TEANECK,UNITED STATES OF AMERICA,2019-03-31 00:00:00,"GIZMODO MEDIA GROUP, LLC (F/K/A UNIMODA, LLC)",NJ,2017-04-24 00:00:00,NEW J,Y,431029,431029,EXECUTIVE PRODUCER,5191,51913,519130,NaT,Year,135637.00,Year,17-431029,27-2012,PRODUCERS AND DIRECTORS,2017-04-17,1.0,NaN,E-3 Australian,80000.000,160000.00,0.00,06037,LOS ANGELES,CALIFORNIA,CA,90045,17,DROP,False,NEW J
1704595,521239,I-200-17111-107894,WITHDRAWN,2017-04-21,Y,210 NORTH CENTER DRIVE,NaN,NORTH BRUNSWICK,UNITED STATES OF AMERICA,2020-04-23 00:00:00,NGA GROUP INC,NJ,2017-04-24 00:00:00,NORTH,Y,437939,437939,TECHNICAL LEAD,5416,54161,541614,NaT,Year,76731.00,Year,17-437939,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2017-04-21,1.0,N,H-1B,38500.000,77000.00,0.00,08035,CENTENNIAL,ARAPAHOE,CO,80112,17,DROP,False,NORTH
1707024,524076,I-203-17108-326582,DENIED,2017-04-25,NaN,"500 FRANK W. BURR BLVD.,SUITE 19",NaN,TEANECK,UNITED STATES OF AMERICA,2019-03-31 00:00:00,"GIZMODO MEDIA GROUP, LLC (F/K/A UNIMODA, LLC)",NJ,2017-04-24 00:00:00,NEW J,Y,440368,440368,EXECUTIVE PRODUCER,5191,51913,519130,NaT,Year,135637.00,Year,17-440368,27-2012,PRODUCERS AND DIRECTORS,2017-04-19,1.0,NaN,E-3 Australian,80000.000,160000.00,0.00,06037,LOS ANGELES,CALIFORNIA,CA,90045,17,DROP,False,NEW J
1720257,539988,I-200-17118-571281,CERTIFIED,2017-05-04,Y,50 CRAGWOOD ROAD,NaN,SOUTH PLAINFIELD,UNITED STATES OF AMERICA,2020-05-04 00:00:00,ASTIR IT SOLUTIONS INC,NJ,2017-05-05 00:00:00,MIDDL,Y,453601,453601,QA ANALYST,5415,54151,541511,NaT,Year,53165.00,Year,17-453601,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2017-04-28,1.0,N,H-1B,30000.000,60000.00,0.00,36119,HARRISON,WESTCHESTER,NY,10528,17,DROP,False,MIDDL
1732773,554766,I-200-17128-132509,CERTIFIED,2017-05-16,N,8401 IMPERIAL DRIVE,NaN,WACO,UNITED STATES OF AMERICA,2020-06-04 00:00:00,"PACKLESS METAL HOSE, INC.",TX,2017-06-05 00:00:00,MCLEN,Y,466117,466117,SALES AND ENGINEERING MANAGER,3329,33299,332999,NaT,Year,125944.00,Year,17-466117,11-9041,ARCHITECTURAL AND ENGINEERING MANAGERS,2017-05-10,1.0,N,H-1B,62972.000,125944.00,0.00,48309,WACO,MCLENNAN,TX,76712,17,DROP,False,MCLEN
1773548,603492,I-200-17165-610730,CERTIFIED,2017-06-20,N,1441 BROADWAY,NaN,NEW YORK,UNITED STATES OF AMERICA,2020-06-21 00:00:00,"AETION, INC.",NY,2017-06-22 00:00:00,NEW Y,Y,506892,506892,SENIOR SCIENTIST,5417,5417,5417,NaT,Year,91832.00,Year,17-506892,19-1041,EPIDEMIOLOGISTS,2017-06-14,1.0,N,H-1B,57500.000,115000.00,0.00,25017,NEWTON,MIDDLESEX,MA,02466,17,DROP,False,NEW Y
1797561,631856,I-200-17180-259692,CERTIFIED,2017-07-12,N,400 - 1818 CORNWALL AVENUE,NaN,VANCOUVER,NaN,2020-07-23 00:00:00,LULULEMON USA INC.,NaN,2017-07-24 00:00:00,V6J 1,Y,530905,530905,SENIOR CQ (AEM) DEVELOPER,4481,4481,4481,NaT,Year,122429.00,Year,17-530905,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-07-06,1.0,N,H-1B,65000.000,130000.00,0.00,06075,SAN FRANCISCO,SAN FRANCISCO,CA,94105,17,DROP,False,V6J 1
1800075,634811,I-200-17163-592936,CERTIFIED,2017-07-13,N,555 RICHMOND STREET WEST,NaN,TORONTO,NaN,2019-08-01 00:00:00,"SYNAPTIVE MEDICAL USA, INC.",NaN,2017-08-01 00:00:00,M5V 3,Y,533419,533419,CLINICAL APPLICATION SPECIALIST,3345,33451,334510,NaT,Year,69306.00,Year,17-533419,41-9031,SALES ENGINEERS,2017-07-07,1.0,N,H-1B,39000.000,78000.00,0.00,06001,CASTRO VALLEY,ALAMEDA,CA,94546,17,DROP,False,M5V 3

In [655]:
#parking vvdatafull1
vvdatafull2 = vvdatafull1

In [656]:
vvdatafull2.dtypes

level_0                   int64
case_num                 object
case_status            category
decision_date    datetime64[ns]
dependent                object
emp_address              object
emp_cfips                object
emp_city                 object
emp_cntry                object
emp_end                  object
emp_name                 object
emp_st                   object
emp_start                object
emp_zip                  object
full_time                object
id                       object
index                     int64
job                      object
naics4                   object
naics5                   object
naics_full               object
org_cert_date    datetime64[ns]
payunit                category
pw                      float64
pw_payunit               object
row_id                   object
soc_code                 object
soc_name                 object
submit_date      datetime64[ns]
tot_workers             float64
violator                 object
visa_class             category
wage                    float64
wage_from               float64
wage_to                 float64
work_cfips               object
work_city                object
work_cnty                object
work_st                  object
work_zip                 object
year                   category
DROP                     object
test                       bool
emp_zip2                 object
dtype: object

In [657]:
vvdatafull2['work_zip'] = vvdatafull2['work_zip'].astype('str')
vvdatafull2.loc[(vvdatafull2['work_zip'].apply(lambda x: len(x) < 5)),'DROP2'] = 'DROP'

vvdatafull2['work_zip'] = vvdatafull2['work_zip'].apply(lambda x: x[0:5])

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:357: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)
/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [658]:
numpattern = r'[0-9]'
vvdatafull2['test2'] = pd.Series(vvdatafull2['work_zip']).str.match(numpattern)

vvdatafull2.loc[(vvdatafull2['test2'] == False), 'DROP2'] = 'DROP'

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [659]:
vvdatafull2.loc[(vvdatafull2['test2'] == False), 'DROP2'] = 'DROP'

vvdatafull2[vvdatafull2['test2'] == False] #38677 ROWS

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

,level_0,case_num,case_status,decision_date,dependent,emp_address,emp_cfips,emp_city,emp_cntry,emp_end,emp_name,emp_st,emp_start,emp_zip,full_time,id,index,job,naics4,naics5,naics_full,org_cert_date,payunit,pw,pw_payunit,row_id,soc_code,soc_name,submit_date,tot_workers,violator,visa_class,wage,wage_from,wage_to,work_cfips,work_city,work_cnty,work_st,work_zip,year,DROP,test,emp_zip2,DROP2,test2
5,5,I-200-09195-662319,WITHDRAWN,2015-01-22,N,2885 COUNTRY DRIVE,27123,LITTLE CANADA,UNITED STATES OF AMERICA,01/25/2016,"APLARS, LLC",MN,01/25/2015,55117,Y,NaN,5,BUSINESS ANALYST,4541,45411,454111,NaT,Year,20000.00,Year,15-5,19-3021.00,MARKET RESEARCH ANALYSTS,2015-01-22,1.0,N,H-1B,20000.00,20000.00,NaN,NaN,SIT,LUNGE,LA,nan,15,NaN,True,55117,DROP,False
159,189,I-200-11068-196462,CERTIFIED,2015-01-13,N,660 ROSEDALE ROAD,NaN,PRINCETON,UNITED STATES OF AMERICA,06/11/2018,EDUCATIONAL TESTING SERVICE,NJ,06/12/2015,08541,Y,NaN,159,PSYCHOMETRICIAN,6117,61171,611710,NaT,Year,69326.00,Year,15-159,15-2041,STATISTICIANS,2015-01-07,1.0,N,H-1B,95000.00,80000.00,110000.0,NaN,PRINCETON,MERCER,NJ,nan,15,NaN,True,08541,DROP,False
299,351,I-200-11235-783702,CERTIFIED-WITHDRAWN,2014-10-06,N,"PIERPONT COMMONS, INTERNATIONAL CENTER",26161,ANN ARBOR,UNITED STATES OF AMERICA,12/31/2014,UNIVERSITY OF MICHIGAN,MI,01/01/2012,48109,Y,NaN,299,POSTDOCTORAL RESEARCH FELLOW,6113,61131,611310,NaT,Year,38522.00,Year,15-299,19-1042.00,"MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS",2011-08-23,1.0,N,H-1B,42624.00,42624.00,NaN,NaN,ANN ARBOR,WASHTENAW,MI,nan,15,NaN,True,48109,DROP,False
302,354,I-200-11242-387122,CERTIFIED-WITHDRAWN,2014-10-14,N,5323 HARRY HINES BLVD.,48113,DALLAS,UNITED STATES OF AMERICA,12/16/2014,THE UNIVERSITY OF TEXAS SOUTHWESTERN MEDICAL C...,TX,12/17/2011,75390,Y,NaN,302,POSTDOCTORAL RESEARCHER,6113,61131,611310,NaT,Year,33238.00,Year,15-302,19-1042,"MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS",2011-08-30,1.0,N,H-1B,42624.00,42624.00,NaN,NaN,DALLAS,DALLAS,TX,nan,15,NaN,True,75390,DROP,False
325,378,I-200-11262-092959,CERTIFIED,2015-06-12,N,"4111 E. 37TH STREET, NORTH",20173,WICHITA,UNITED STATES OF AMERICA,09/30/2018,"JOHN ZINK COMPANY, LLC",KS,09/30/2015,67220,Y,NaN,325,CONTROLS ENGINEER VAPOR CONTROL SYSTEMS,5413,54133,541330,NaT,Year,60486.00,Year,15-325,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2015-06-08,1.0,N,H-1B,112000.00,112000.00,NaN,NaN,TULSA,TULSA,OK,nan,15,NaN,True,67220,DROP,False
331,385,I-200-11263-816008,CERTIFIED-WITHDRAWN,2014-10-14,N,5323 HARRY HINES BLVD.,48113,DALLAS,UNITED STATES OF AMERICA,01/31/2015,THE UNIVERSITY OF TEXAS SOUTHWESTERN MEDICAL C...,TX,02/01/2012,75390,Y,NaN,331,POSTDOCTORAL RESERACHER,6113,61131,611310,NaT,Year,33238.00,Year,15-331,19-1042,"MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS",2011-09-20,1.0,N,H-1B,38496.00,38496.00,NaN,NaN,DALLAS,DALLAS,TX,nan,15,NaN,True,75390,DROP,False
367,423,I-200-11278-650560,CERTIFIED-WITHDRAWN,2014-12-16,Y,1 CORPORATE PLACE SOUTH,34039,PISCATAWAY,UNITED STATES OF AMERICA,12/18/2014,"MARLABS, INC",NJ,12/18/2011,08854,Y,NaN,367,PROGRAMMER/ANALYST,5415,54151,541511,NaT,Year,63877.00,Year,15-367,15-1131,COMPUTER PROGRAMMERS,2011-10-05,1.0,N,H-1B,63900.00,63900.00,NaN,NaN,CHICAGO,COOK COUNTY,IL,nan,15,NaN,True,08854,DROP,False
423,486,I-200-11300-403742,CERTIFIED-WITHDRAWN,2014-10-31,N,"PIERPONT COMMONS, INTERNATIONAL CENTER",26161,ANN ARBOR,UNITED STATES OF AMERICA,04/15/2015,UNIVERSITY OF MICHIGAN,MI,04/16/2012,48109,Y,NaN,423,POSTDOCTORAL RESEARCH FELLOW,6113,61131,611310,NaT,Year,38293.00,Year,15-423,19-1021.00,BIOCHEMISTS AND BIOPHYSICISTS,2011-10-27,1.0,N,H-1B,41000.00,41000.00,NaN,NaN,ANN ARBOR,WASHTENAW,MI,nan,15,NaN,True,48109,DROP,False
448,513,I-200-11307-836815,CERTIFIED-WITHDRAWN,2014-10-07,N,8404 INDIAN HILLS DRIVE,31055,OMAHA,UNITED STATES OF AMERICA,03/03/2015,"HDR ENGINEERING, INC.",NE,03/04/2012,68114,Y,NaN,448,WATER/WASTEWATER ENGINEER IN TRAINING,5413,54133,541330,NaT,Year,56679.00,Year,15-448,17-2051,CIVIL ENGINEERS,2011-11-03,1.0,N,H-1B,56679.00,56679.00,NaN,NaN,MAHWAH,BERGEN,NJ,nan,15,NaN,True,68114,DROP,False
502,575,I-200-11319-249133,CERTIFIED-WITHDRAWN,2014-11-07,N,CENTER FOR GLOBAL ENGAGEMENT,12073,TALLAHASSEE,UNITED STATES OF AMERICA,12/31/2014,THE FLORIDA STATE UNIVERSITY,FL,01/01/2012,32306,Y,NaN,502,POSTDOCTORAL RESEARCH ASSOCIATE,6113,61131,611310,NaT,Year,32968.00,Year,15-502,19-1029,"BIOLOGICAL SCIENTISTS, ALL OTHER",2011-11-15,1.0,N,H-1B,39328.64,39328.64,NaN,NaN,TALLAHASSEE,LEON,FL,nan,15,NaN,True,32306,DROP,False
510,588,I-200-11320-719754,CERTIFIED-WITHDRAWN,2014-11-13,Y,1 CORPORATE PLACE SOUTH,34039,PISCATAWAY,UNITED STATES OF AMERICA,01/04/2015,"MARLABS, INC",NJ,01/04/2012,08854,Y,NaN,510,PROGRAMMER/ANALYST,5415,54151,541511,NaT,Year,67101.00,Year,15-510,15-1131,COMPUTER PROGRAMMERS,2011-11-16,1.0,N,H-1B,67200.00,67200.00,NaN,NaN,WHITE PLAINS,WESTCHESTER COUNTY,NY,nan,15,NaN,True,08854,DROP,False
530,612,I-200-11325-840936,CERTIFIED,2014-11-24,Y,3325 NORTH ARLINGTON HEIGHTS ROAD,17031,ARLINGTON HEIGHTS,UNITED STATES OF AMERICA,11/18/2017,KIP INFORMATION TECHNOLOGIES INC,IL,11/19/2014,60004,Y,NaN,530,PROGRAMMER ANALYST,5415,54151,541511,NaT,Year,94494.00,Year,15-530,15-1131,COMPUTER PROGRAMMERS,2014-11-18,1.0,N,H-1B,94500.00,94500.00,NaN,NaN,ROCKVILLE,MONTGOMERY COUNTY,MD,nan,15,NaN,True,60004,DROP,False
538,620,I-200-11326-901976,CERTIFIED-WITHDRAWN,2015-03-02,N,"PIERPONT COMMONS, INTERNATIONAL CENTER",26161,ANN ARBOR,UNITED STATES OF AMERICA,05/19/2015,UNIVERSITY OF MICHIGAN,MI,05/20/2012,48109,N,NaN,538,ASSISTANT RESEARCH SCIENTIST,6113,61131,611310,NaT,Hour,29.21,Hour,15-538,19-2042.00,"GEOSCIENTISTS, EXCEPT HYDROLOGISTS AND GEOGRAP...",2011-11-22,1.0,N,H-1B,29.22,29.22,NaN,NaN,ANN ARBOR,WASHTENAW,MI,nan,15,NaN,True,48109,DROP,False
578,676,I-200-11342-483009,CERTIFIED-WITHDRAWN,2015-02-03,N,101A YMCA BUILDING,48041,COLLEGE STATION,UNITED STATES OF AMERICA,06/01/2015,TEXAS A&M UNIVERSITY,TX,06/02/2012,77843,Y,NaN,578,SENIOR LEAD SOFTWARE APPLICATIONS DEVELOPER,6113,61131,611310,NaT,Year,76294.00,Year,15-578,11-3021,COMPUTER AND INFORMATION SYSTEMS MANAGERS,2011-12-09,1.0,N,H-1B,77044.08,77044.08,NaN,NaN,COLLEGE STATION,BRAZOS,TX,nan,15,NaN,True,77843,DROP,False
657,766,I-200-12005-567538,CERTIFIED-WITHDRAWN,2014-10-31,N,OFFICE OF INTERNATIONAL STUDENTS AND SCHOLARS,54061,MORGANTOWN,UNITED STATES OF AMERICA,05/15/2015,WEST VIRGINIA UNIVERSITY,WV,05/16/2012,26506,Y,NaN,657,TEACHING ASSISTANT PROFESSOR,6113,61131,611310,NaT,Year,37220.00,Year,15-657,25-1052,"CHEMISTRY TEACHERS, POSTSECONDARY",2012-01-05,1.0,N,H-1B,53097.19,53097.19,NaN,NaN,MORGANTOWN,MONONGALIA,WV,nan,15,NaN,True,26506,DROP,False
692,806,I-200-12017-168645,CERTIFIED-WITHDRAWN,2014-12-15,Y,1 CORPORATE PLACE SOUTH,34039,PISCATAWAY,UNITED STATES OF AMERICA,01/17/2015,"MARLABS, INC",NJ,01/17/2012,08854,Y,NaN,692,PROGRAMMER/ANALYST,5415,54151,541511,NaT,Year,76378.00,Year,15-692,15-1131,COMPUTER PROGRAMMERS,2012-01-17,1.0,N,H-1B,76400.00,76400.00,NaN,NaN,WATERTOWN,MIDDLESEX COUNTY,MA,nan,15,NaN,True,08854,DROP,False
730,847,I-200-12023-633506,CERTIFIED-WITHDRAWN,2014-12-02,N,47765 HALYARD DRIVE,NaN,PLYMOUTH,UNITED STATES OF AMERICA,07/23/2015,"BREMBO NORTH AMERICA, INC.",MI,07/23/2012,48170,Y,NaN,730,MANUFACTURING ENGINEER,3363,33634,336340,NaT,Year,56202.00,Year,15-730,17.2199.04,MANUFACTURING ENGINEERS,2012-03-02,1.0,N,H-1B,65000.00,65000.00,NaN,NaN,HOMER,CALHOUN,MI,nan,15,NaN,True,48170,DROP,False
745,867,I-200-12025-206227,CERTIFIED-WITHDRAWN,2014-10-28,N,DEPT. OF PHYSICS AND ASTRONOMY,NaN,ALBUQUERQUE,UNITED STATES OF AMERICA,02/28/2015,UNIVERSITY OF NEW MEXICO,NM,02/29/2012,87131,Y,NaN,745,RESEARCH ASSISTANT PROFESSOR,6113,61131,611310,NaT,Year,46509.00,Year,15-745,19-2012,PHYSICISTS,2012-01-25,1.0,N,H-1B,46600.00,46600.00,46600.0,NaN,ALBUQUERQUE,BERNALILLO,NM,nan,15,NaN,True,87131,DROP,False
796,935,I-200-12032-964586,CERTIFIED-WITHDRAWN,2015-07-24,N,CENTER FOR INTERNATIONAL EDUCATION,47093,KNOXVILLE,UNITED STATES OF AMERICA,07/31/2015,THE UNIVERSITY OF TENNESSEE,TN,08/01/2012,37996,Y,NaN,796,POST-DOCTORAL RESEARCH ASSOCIATE,6113,61131,611310,NaT,Year,48401.60,Year,15-796,19-2011,ASTRONOMERS,2012-02-01,1.0,N,H-1B,48401.64,48401.64,NaN,NaN,KNOXVILLE,KNOX,TN,nan,15,NaN,True,37996,DROP,False
804,946,I-200-12033-925061,CERTIFIED-WITHDRAWN,2014-10-29,N,SMOLIAN INTERNATIONAL HOUSE (SIH),01073,BIRMINGHAM,UNITED STATES OF AMERICA,06/30/2015,THE UNIV. OF ALA. AT BIRMINGHAM (UAB),AL,07/01/2012,35294,Y,NaN,804,RESIDENT,6113,61131,61131,NaT,Year,38522.00,Year,15-804,29-1063,"INTERNISTS, GENERAL",2012-02-02,1.0,N,H-1B,48000.00,48000.00,NaN,NaN,BIRMINGHAM,JEFFERSON,AL,nan,15,NaN,True,35294,DROP,False
826,970,I-200-12038-276523,CERTIFIED-WITHDRAWN,2015-02-16,N,5323 HARRY HINES BOULEVARD,48113,DALLAS,UNITED STATES OF AMERICA,05/14/2015,THE UNIVERSITY OF TEXAS SOUTHWESTERN MEDICAL C...,TX,05/15/2012,75390,Y,NaN,826,RESEARCH ASSOCIATE,6113,61131,611310,NaT,Year,29806.40,Year,15-826,19-4021,BIOLOGICAL TECHNICIANS,2012-02-07,1.0,N,H-1B,40908.00,40908.00,NaN,NaN,DALLAS,DALLAS,TX,nan,15,NaN,True,75390,DROP,False
829,973,I-200-12038-526144,CERTIFIED-WITHDRAWN,2014-11-03,N,105 BB COMER HALL,NaN,TUSCALOOSA,UNITED STATES OF AMERICA,04/30/2015,THE UNIVERSITY OF ALABAMA,AL,05/01/2012,35487,Y,NaN,829,INSTITUTIONAL RESEARCH ANALYST,6113,61131,61131,NaT,Year,29515.00,Year,15-829,43-9111,STATISTICAL ASSISTANTS,2012-02-07,1.0,N,H-1B,40000.00,40000.00,NaN,NaN,TUSCALOOSA,TUSCALOOSA,AL,nan,15,NaN,True,35487,DROP,False
846,991,I-200-12039-943599,CERTIFIED-WITHDRAWN,2014-10-27,N,1500 MERRILL LYNCH DR,34021,PENNINGTON,UNITED STATES OF AMERICA,08/09/2015,BANK OF AMERICA N.A.,NJ,08/09/2012,08534,Y,NaN,846,TECH ASSOCIATE,5221,52211,522110,NaT,Year,59051.00,Year,15-846,15-1121,COMPUTER SYSTEMS ANALYSTS,2012-02-15,1.0,N,H-1B,85000.00,75000.00,95000.0,NaN,CHARLOTTE,MECKLENBURG,NC,nan,15,NaN,True,08534,DROP,False
861,1009,I-200-12041-279624,CERTIFIED-WITHDRAWN,2014-12-02,Y,1 CORPORATE PLACE SOUTH,34039,PISCATAWAY,UNITED STATES OF AMERICA,04/20/2015,"MARLABS, INC",NJ,04/20/2012,08854,Y,NaN,861,PROGRAMMER/ANALYST,5415,54151,541511,NaT,Year,61568.00,Year,15-861,15-1131,COMPUTER PROGRAMMERS,2012-02-10,1.0,N,H-1B,61600.00,61600.00,NaN,NaN,BLOOMINGTON,MCLEAN COUNTY,IL,nan,15,NaN,True,08854,DROP,False
862,1010,I-200-12041-419625,CERTIFIED-WITHDRAWN,2015-05-28,Y,30 RICHARD ROAD,34039,EDISON,UNITED STATES OF AMERICA,03/01/2013,REVISION TECHNOLOGIES INC,NJ,03/01/2012,08820,Y,NaN,862,NETWORK AND COMPUTER SYSTEMS ADMINISTRATOR,5415,54151,541511,NaT,Year,48963.00,Year,15-862,15-1142,NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS*,2012-02-10,1.0,Y,H-1B,60000.00,55000.00,65000.0,NaN,FRANKLIN,WILLIAMSON,TN,nan,15,NaN,True,08820,DROP,False
893,1047,I-200-12045-762286,CERTIFIED-WITHDRAWN,2015-02-25,N,14TH AND R STREETS,31109,LINCOLN,UNITED STATES OF AMERICA,08/25/2015,BOARD OF REGENTS OF THE UNIVERSITY OF NEBRASKA,NE,08/26/2012,68588,Y,NaN,893,ASSISTANT EXTENSION EDUCATOR,6113,61131,611310,NaT,Year,48360.00,Year,15-893,17-2021,AGRICULTURAL ENGINEERS,2012-03-05,1.0,N,H-1B,48658.00,48658.00,NaN,NaN,LINCOLN,LANCASTER,NE,nan,15,NaN,True,68588,DROP,False
918,1077,I-200-12046-933499,WITHDRAWN,2015-01-20,N,ONE CA PLAZA,36103,ISLANDIA,UNITED STATES OF AMERICA,08/14/2015,CA TECHNOLOGIES,NY,08/14/2012,11749,Y,NaN,918,SOFTWARE ENGINEER,5415,54151,541519,NaT,Year,69930.00,Year,15-918,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2012-02-15,1.0,N,H-1B,71550.00,71550.00,NaN,NaN,PLANO,COLLIN,TX,nan,15,NaN,True,11749,DROP,False
943,1107,I-200-12048-844253,CERTIFIED-WITHDRAWN,2014-12-11,N,"PIERPONT COMMONS, INTERNATIONAL CENTER",26161,ANN ARBOR,UNITED STATES OF AMERICA,03/11/2015,UNIVERSITY OF MICHIGAN,MI,03/12/2012,48109,Y,NaN,943,ASSISTANT RESEARCH SCIENTIST,6113,61131,611310,NaT,Year,38293.00,Year,15-943,19-1021.00,BIOCHEMISTS AND BIOPHYSICISTS,2012-02-17,1.0,N,H-1B,54103.00,54103.00,NaN,NaN,ANN ARBOR,WASHTENAW,MI,nan,15,NaN,True,48109,DROP,False
959,1127,I-200-12052-384757,CERTIFIED-WITHDRAWN,2015-06-05,N,108 BRYAN HALL,53075,PULLMAN,UNITED STATES OF AMERICA,06/30/2015,WASHINGTON STATE UNIVERSITY,WA,07/01/2012,99164,Y,NaN,959,ASSISTANT RESEARCH PROFESSOR,6113,61131,611310,NaT,Year,39458.00,Year,15-959,19-1021,BIOCHEMISTS AND BIOPHYSICISTS,2012-02-21,1.0,N,H-1B,48000.00,48000.00,NaN,NaN,PULLMAN,WHITMAN,WA,nan,15,NaN,True,99164,DROP,False
1002,1177,I-200-12055-036703,CERTIFIED-WITHDRAWN,2015-01-13,N,CENTER FOR INTERNATIONAL EDUCATION,47093,KNOXVILLE,UNITED STATES OF AMERICA,05/31/2015,THE UNIVERSITY OF TENNESSEE,TN,06/01/2012,37996,Y,NaN,1002,POST-DOCTORAL RESEARCH ASSOCIATE,6113,61131,611310,NaT,Year,40830.40,Year,15-1002,19-1042,"MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS",2012-02-24,1.0,N,H-1B,40830.48,40830.48,NaN,NaN,KNOXVILLE,KNOX,TN,nan,15,NaN,True,37996,DROP,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1984767,109721,I-200-17346-604307,CERTIFIED,2017-12-18,N,9690 DEERECO ROAD,NaN,TIMONIUM,UNITED STATES OF AMERICA,2020-12-24 00:00:00,"BILL ME LATER, INC.",MD,2017-12-25 00:00:00,21093,Y,93461,93461,"MANAGER, SOFTWARE DEVELOPMENT 1",5416,54161,541611,NaT,Year,121139.00,Year,18-93461,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-12-12,1.0,N,H-1B,66469.00,132938.00,0.0,NaN,TIMONIUM,BALTIMORE,MD,nan,18,NaN,True,21093,DROP,False
1984781,109737,I-200-17346-328080,CERTIFIED,2017-12-18,N,8404 INDIAN HILLS DRIVE,31055,OMAHA,UNITED STATES OF AMERICA,2021-03-02 00:00:00,"HDR ENGINEERING, INC.",NE,2018-03-03 00:00:00,68114,Y,93475,93475,WATER RESOURCES ENGINEER,5413,54133,541330,NaT,Year,78104.00,Year,18-93475,17-2051,CIVIL ENGINEERS,2017-12-12,1.0,N,H-1B,44148.00,88296.00,0.0,NaN,PITTSBURGH,ALLEGHENY,PA,nan,18,NaN,True,68114,DROP,False
1984789,109745,I-200-17346-052110,CERTIFIED,2017-12-18,Y,399 CAMPUS DRIVE,34035,SOMERSET,UNITED STATES OF AMERICA,2020-12-19 00:00:00,"BHRIGUS, INC.",NJ,2017-12-20 00:00:00,08873,Y,93483,93483,PROGRAMMER ANALYST,5415,54151,541511,NaT,Year,87693.00,Year,18-93483,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-12-12,1.0,N,H-1B,44000.00,88000.00,0.0,NaN,PRINCETON,MERCER,NJ,nan,18,NaN,True,08873,DROP,False
1984795,109751,I-200-17346-686448,CERTIFIED,2017-12-22,N,ONE CHECKERBOARD SQUARE,29510,ST. LOUIS,UNITED STATES OF AMERICA,2021-01-17 00:00:00,"NESTLE REGIONAL GLOBE OFFICE NORTH AMERICA, INC.",MO,2018-01-18 00:00:00,63164,Y,93489,93489,ECS REGIONAL TEAM LEAD - DC INFRASTRUCTURE,3119,31199,31199,NaT,Year,115669.00,Year,18-93489,15-1143,COMPUTER NETWORK ARCHITECTS,2017-12-18,1.0,N,H-1B,135000.00,125000.00,145000.0,NaN,PHOENIX,MARICOPA,AZ,nan,18,NaN,True,63164,DROP,False
1984890,109866,I-200-17341-977551,CERTIFIED,2017-12-13,N,104 INTERNATIONAL STUDENT CENTER,20161,MANHATTAN,UNITED STATES OF AMERICA,2020-08-13 00:00:00,KANSAS STATE UNIVERSITY,KS,2018-01-03 00:00:00,66506,Y,93584,93584,ASSISTANT PROFESSOR,6113,61131,611310,NaT,Year,21740.00,Year,18-93584,25-1041,"AGRICULTURAL SCIENCES TEACHERS, POSTSECONDARY",2017-12-07,1.0,N,H-1B,37500.00,75000.00,0.0,NaN,MANHATTAN,RILEY,KS,nan,18,NaN,True,66506,DROP,False
1984893,109869,I-200-17341-627245,CERTIFIED,2017-12-14,N,35803 VERONICA STREET,26163,LIVONIA,UNITED STATES OF AMERICA,2020-12-17 00:00:00,RIVIAN AUTOMOTIVE LLC,MI,2017-12-18 00:00:00,48150,Y,93587,93587,DURABILITY ENGINEER,3361,33611,336111,NaT,Year,91458.00,Year,18-93587,17-2141,MECHANICAL ENGINEERS,2017-12-08,1.0,N,H-1B,52500.00,105000.00,0.0,NaN,LIVONIA,WAYNE,MI,nan,18,NaN,True,48150,DROP,False
1984916,109896,I-200-17341-803041,CERTIFIED,2017-12-14,Y,6100 TENNYSON PARKWAY,48085,PLANO,UNITED STATES OF AMERICA,2021-03-04 00:00:00,INFOSYS LIMITED,TX,2018-03-07 00:00:00,75024,Y,93610,93610,PRINCIPAL CONSULTANT - US,5415,54151,541511,NaT,Year,117125.00,Year,18-93610,13-1111,MANAGEMENT ANALYSTS,2017-12-08,1.0,N,H-1B,63692.50,127385.00,0.0,NaN,ROSEMEAD,LOS ANGELES,CA,nan,18,NaN,True,75024,DROP,False
1984954,109941,I-200-17352-954323,CERTIFIED,2017-12-26,Y,6100 TENNYSON PARKWAY,48085,PLANO,UNITED STATES OF AMERICA,2021-01-05 00:00:00,INFOSYS LIMITED,TX,2018-01-08 00:00:00,75024,Y,93648,93648,TECHNICAL TEST LEAD - US - PRACTITIONER,5415,54151,541511,NaT,Year,74818.00,Year,18-93648,15-1199,SOFTWARE QUALITY ASSURANCE ENGINEERS AND TESTERS,2017-12-19,1.0,N,H-1B,37409.00,74818.00,0.0,NaN,CHICAGO,COOK,IL,nan,18,NaN,True,75024,DROP,False
1984959,109948,I-200-17353-670688,CERTIFIED,2017-12-26,N,1 MICROSOFT WAY,53033,REDMOND,UNITED STATES OF AMERICA,2021-06-19 00:00:00,MICROSOFT CORPORATION,WA,2018-06-20 00:00:00,98052,Y,93653,93653,SOFTWARE ENGINEER,5112,51121,51121,NaT,Year,68266.00,Year,18-93653,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-12-19,1.0,N,H-1B,51750.00,103500.00,0.0,NaN,FARGO,CASS,ND,nan,18,NaN,True,98052,DROP,False
1984982,109973,I-200-17341-217335,CERTIFIED,2017-12-22,N,DEPARTMENT OF COMMUNICATION STUDIES,NaN,HUNTSVILLE,UNITED STATES OF AMERICA,2021-05-12 00:00:00,SAM HOUSTON STATE UNIVERSITY,TX,2018-05-13 00:00:00,77341,Y,93676,93676,ASSISTANT PROFESSOR OF COMMUNICATION STUDIES,6113,61131,611310,NaT,Year,38320.00,Year,18-93676,25-1122,"COMMUNICATIONS TEACHERS, POSTSECONDARY",2017-12-18,1.0,N,H-1B,28251.00,56502.00,0.0,NaN,HUNTSVILLE,WALKER,TX,nan,18,NaN,True,77341,DROP,False
1985008,110003,I-200-17344-440392,CERTIFIED,2017-12-20,N,50 ROCKEFELLER PLAZA,36061,NEW YORK,UNITED STATES OF AMERICA,2021-06-12 00:00:00,BANK OF AMERICA N.A.,NY,2018-06-12 00:00:00,10020,Y,93702,93702,"AVP, QUANTITATIVE FINANCE ANALYST",5221,52211,522110,NaT,Year,69909.00,Year,18-93702,15-2041,STATISTICIANS,2017-12-14,1.0,N,H-1B,52000.00,104000.00,0.0,NaN,CHARLOTTE,MECKLENBURG,NC,nan,18,NaN,True,10020,DROP,False
1985020,110015,I-200-17344-921596,CERTIFIED,2017-12-15,Y,6100 TENNYSON PARKWAY,48085,PLANO,UNITED STATES OF AMERICA,2020-12-19 00:00:00,INFOSYS LIMITED,TX,2017-12-22 00:00:00,75024,Y,93714,93714,PRINCIPAL CONSULTANT - US,5415,54151,541511,NaT,Year,96762.00,Year,18-93714,13-1111,MANAGEMENT ANALYSTS,2017-12-11,1.0,N,H-1B,59481.50,118963.00,0.0,NaN,CHERRY HILL,CAMDEN,NJ,nan,18,NaN,True,75024,DROP,False
1985031,110027,I-200-17341-053217,CERTIFIED,2017-12-18,N,2525 N. FREMONT AVENUE,NaN,IDAHO FALLS,UNITED STATES OF AMERICA,2021-01-01 00:00:00,"BATTELLE ENERGY ALLIANCE, LLC",ID,2018-01-02 00:00:00,83415,Y,93725,93725,COMPUTATIONAL SCIENTIST (R&D SCI/ENG 3),2211,22111,221113,NaT,Year,72322.00,Year,18-93725,17-2161,NUCLEAR ENGINEERS,2017-12-12,1.0,N,H-1B,57060.00,114120.00,0.0,NaN,IDAHO FALLS,BONNEVILLE,ID,nan,18,NaN,True,83415,DROP,False
1985038,110034,I-200-17341-457486,CERTIFIED,2017-12-13,N,500 S. KRAEMER BLVD.,NaN,BREA,UNITED STATES OF AMERICA,2021-03-12 00:00:00,"ASCEND SOFTWARE, INC.",CA,2018-03-12 00:00:00,92821,Y,93732,93732,SYSTEMS ENGINEER/PROGRAMMER,5415,54151,541511,NaT,Year,65978.00,Year,18-93732,15-1199,COMPUTER SYSTEMS ENGINEERS/ARCHITECTS,2017-12-07,1.0,N,H-1B,36750.00,73500.00,0.0,NaN,BREA,ORANGE,CA,nan,18,NaN,True,92821,DROP,False
1985068,110068,I-200-17342-978296,CERTIFIED,2017-12-14,N,21 ROBERT PITT DRIVE,NaN,MONSEY,UNITED STATES OF AMERICA,2018-01-24 00:00:00,"BUSINESS LICENSES, LLC",NY,2017-12-25 00:00:00,10952,Y,93762,93762,LEGAL RESEARCH ANALYST,5411,5411,5411,NaT,Year,48838.00,Year,18-93762,23-2099,"LEGAL SUPPORT WORKERS, ALL OTHER",2017-12-10,1.0,N,H-1B,24419.00,48838.00,0.0,NaN,MONSEY,ROCKLAND,NY,nan,18,NaN,True,10952,DROP,False
1985149,110160,I-200-17345-107332,CERTIFIED,2017-12-18,Y,CONCOURSE CORPORATE CENTER,13121,ATLANTA,UNITED STATES OF AMERICA,2021-03-30 00:00:00,"TECHPILLARS, INC.",GA,2018-03-31 00:00:00,30328,Y,93843,93843,CONSULTANT,5415,54151,541511,NaT,Year,92768.00,Year,18-93843,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-12-12,1.0,N,H-1B,103000.00,93000.00,113000.0,NaN,NEW YORK,NEW YORK,NY,nan,18,NaN,True,30328,DROP,False

In [661]:
len(vvdatafull2)

1985544

In [662]:
#parking vvdatafull2
vvdatafull3 = vvdatafull2[vvdatafull2['DROP'] != 'DROP']
vvdatafull3 = vvdatafull3[vvdatafull2['DROP2'] != 'DROP']

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until

In [663]:
len(vvdatafull3)

1946707

In [664]:
vvdatafull3.head(100)

,level_0,case_num,case_status,decision_date,dependent,emp_address,emp_cfips,emp_city,emp_cntry,emp_end,emp_name,emp_st,emp_start,emp_zip,full_time,id,index,job,naics4,naics5,naics_full,org_cert_date,payunit,pw,pw_payunit,row_id,soc_code,soc_name,submit_date,tot_workers,violator,visa_class,wage,wage_from,wage_to,work_cfips,work_city,work_cnty,work_st,work_zip,year,DROP,test,emp_zip2,DROP2,test2
0,0,I-200-09121-701936,WITHDRAWN,2015-02-05,N,710 MEDTRONIC PARKWAY NE,27003,MINNEAPOLIS,UNITED STATES OF AMERICA,02/28/2015,"MEDTRONIC, INC.",MN,02/09/2015,55432,Y,NaN,0,MECHANICAL ENGINEER,3345,33451,334510,NaT,Year,19000.00,Year,15-0,17-2141.00,MECHANICAL ENGINEERS,2015-02-05,1.0,N,H-1B,20000.000,20000.00,NaN,27053,EDEN PRAIRIE,STERNS,CA,55412,15,NaN,True,55432,NaN,True
1,1,I-200-09146-796321,CERTIFIED,2014-12-18,N,905 ASP AVE,40027,NORMAN,UNITED STATES OF AMERICA,01/04/2018,UNIVERSITY OF OKLAHOMA,OK,01/05/2015,73019,Y,NaN,1,ASSISTANT PROFESSOR,6113,61131,611310,NaT,Year,42860.00,Year,15-1,25-1032,"ENGINEERING TEACHERS, POSTSECONDARY",2014-12-12,1.0,N,H-1B,85000.000,85000.00,NaN,40027,NORMAN,CLEVELAND,OK,73019,15,NaN,True,73019,NaN,True
2,2,I-200-09180-329758,WITHDRAWN,2014-12-15,N,6021 CONNECTION DRIVE,48113,IRVING,UNITED STATES OF AMERICA,01/06/2016,NOKIA INC.,TX,01/07/2013,75039,Y,NaN,2,RELEASE AND SOFTWARE TEST MANAGER,5172,51721,517212,NaT,Year,73965.00,Year,15-2,15-1799,"COMPUTER OCCUPATIONS, ALL OTHER*",2013-01-03,1.0,N,H-1B,94000.000,94000.00,NaN,06073,SAN DIEGO,SAN DIEGO,CA,92127,15,NaN,True,75039,NaN,True
3,3,I-200-09183-259985,CERTIFIED,2015-03-16,N,9510 N. HOUSTON ROSSLYN ROAD,48201,HOUSTON,UNITED STATES OF AMERICA,09/07/2018,"OMRON OILFIELD AND MARINE, INC.",TX,09/07/2015,77088,Y,NaN,3,CONTROL ENGINEERING SPECIALIST,3353,33531,335314,NaT,Year,65998.00,Year,15-3,17-2072,"ELECTRONICS ENGINEERS, EXCEPT COMPUTER",2015-03-10,2.0,N,H-1B,68000.000,66000.00,70000.00,48201,HOUSTON,HARRIS,TX,77088,15,NaN,True,77088,NaN,True
4,4,I-200-09189-800933,CERTIFIED,2014-12-23,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,06/05/2018,FEDERAL HOME LOAN MORTGAGE CO.,VA,06/06/2015,22102,Y,NaN,4,DEVELOPMENT SENIOR,5222,52229,522294,NaT,Year,96907.00,Year,15-4,15-1131,COMPUTER PROGRAMMERS,2014-12-17,1.0,N,H-1B,120150.000,97000.00,143300.00,51059,MCLEAN,FAIRFAX,VA,22102,15,NaN,True,22102,NaN,True
6,6,I-200-09212-834534,CERTIFIED,2014-10-20,N,3401 HILLVIEW AVE,06085,PALO ALTO,UNITED STATES OF AMERICA,11/02/2017,"VMWARE, INC.",CA,11/03/2014,94304,Y,NaN,6,STAFF ENGINEER,5415,54151,541511,NaT,Year,133976.00,Year,15-6,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-10-14,1.0,N,H-1B,155000.000,155000.00,NaN,06085,PALO ALTO,SANTA CLARA,CA,94304,15,NaN,True,94304,NaN,True
7,7,I-200-09232-212049,CERTIFIED,2014-12-23,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,06/13/2018,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,06/14/2015,22102,Y,NaN,7,CREDIT GUARANTEE ANALYTICS SENIOR,5222,52229,522294,NaT,Year,64085.00,Year,15-7,15-2031,OPERATIONS RESEARCH ANALYSTS,2014-12-17,1.0,N,H-1B,95550.000,64100.00,127000.00,51059,MCLEAN,FAIRFAX,VA,22102,15,NaN,True,22102,NaN,True
8,8,I-200-09233-732656,CERTIFIED,2014-11-04,N,3401 HILLVIEW AVE,06085,PALO ALTO,UNITED STATES OF AMERICA,11/16/2017,"VMWARE, INC.",CA,11/17/2014,94304,Y,NaN,8,PROGRAMMER/ANALYST - SENIOR APPLICATIONS DEVEL...,5415,54151,541511,NaT,Year,101900.00,Year,15-8,15-1121,COMPUTER SYSTEMS ANALYSTS,2014-10-29,1.0,N,H-1B,125000.000,125000.00,NaN,06085,PALO ALTO,SANTA CLARA,CA,94304,15,NaN,True,94304,NaN,True
9,9,I-200-09238-535119,DENIED,2015-03-30,N,65 CRESTRIDGE DRIVE,13135,SUWANEE,UNITED STATES OF AMERICA,09/17/2018,IMAEX TRADING COMPANY,GA,09/17/2015,30024,N,NaN,9,COST ACCOUNTANT,4244,42446,424460,NaT,Hour,22.46,Hour,15-9,13-2011,ACCOUNTANTS AND AUDITORS,2015-03-19,1.0,N,H-1B,22.460,22.46,NaN,13135,SUWANEE,FORSYTH,GA,30024,15,NaN,True,30024,NaN,True
10,12,I-200-09244-289740,CERTIFIED,2014-10-28,N,3401 HILLVIEW AVE,06085,PALO ALTO,UNITED STATES OF AMERICA,04/22/2018,"VMWARE, INC.",CA,04/23/2015,94304,Y,NaN,10,MEMBER OF TECHNICAL STAFF - SOFTWARE ENGINEERING,5415,54151,541511,NaT,Year,98557.00,Year,15-10,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-10-22,1.0,N,H-1B,122430.000,122430.00,NaN,06085,PALO ALTO,SANTA CLARA,CA,94304,15,NaN,True,94304,NaN,True
11,13,I-200-09258-461335,DENIED,2015-01-29,N,21 WEST SUPERIOR STREET,27137,DULUTH,UNITED STATES OF AMERICA,01/22/2016,"LHB, INC.",MN,01/22/2015,55802,Y,NaN,11,F,5413,54133,541330,NaT,Year,345000.00,Year,15-11,13-2011,ACCOUNTANTS AND AUDITORS,2015-01-22,1.0,N,H-1B,20000.000,20000.00,NaN,27053,2 WORK,WORK,ME,55401,15,NaN,True,55802,NaN,True
12,14,I-200-09261-001558,DENIED,2015-03-31,Y,1110 ELDEN STREET,51059,HERNDON,UNITED STATES OF AMERICA,08/20/2018,"INTERNATIONAL SOLUTIONS GROUP, INC.",VA,08/20/2015,20170,Y,NaN,12,PROGRAMMER ANALYST,5415,54151,541511,NaT,Year,66976.00,Year,15-12,15-1021.00,COMPUTER PROGRAMMERS,2015-03-20,1.0,N,H-1B,64688.000,64688.00,NaN,10003,MIDDLETOWN,NEW CASTLE,DE,19709,15,NaN,True,20170,NaN,True
13,15,I-200-09274-925070,CERTIFIED,2014-10-28,N,3401 HILLVIEW AVE,06085,PALO ALTO,UNITED STATES OF AMERICA,11/09/2017,"VMWARE, INC.",CA,11/10/2014,94304,Y,NaN,13,SENIOR MEMBER OF TECHNICAL STAFF - QUALITY ENG...,5415,54151,541511,NaT,Year,111742.00,Year,15-13,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2014-10-22,1.0,N,H-1B,140000.000,140000.00,NaN,06085,PALO ALTO,SANTA CLARA,CA,94304,15,NaN,True,94304,NaN,True
14,16,I-200-09285-514415,CERTIFIED,2014-10-30,Y,388 WASHINGTON ROAD,34023,SAYREVILLE,UNITED STATES OF AMERICA,10/23/2017,IT CATS LLC,NJ,10/24/2014,08872,Y,NaN,14,SENIOR BUSINESS ANALYST,5415,54151,541511,NaT,Hour,52.46,Hour,15-14,15-1121,COMPUTER SYSTEMS ANALYSTS,2014-10-24,1.0,N,H-1B,62.500,60.00,65.00,42091,"NORTH WALES,",MONTGOMERY,PA,19454,15,NaN,True,08872,NaN,True
15,18,I-200-09296-661220,CERTIFIED,2014-11-04,N,3401 HILLVIEW AVE,06085,PALO ALTO,UNITED STATES OF AMERICA,02/02/2018,"VMWARE, INC.",CA,02/03/2015,94304,Y,NaN,15,SENIOR MEMBER OF TECHNICAL STAFF - SOFTWARE EN...,5415,54151,541511,NaT,Year,113775.00,Year,15-15,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-10-29,1.0,N,H-1B,140000.000,140000.00,NaN,06085,PALO ALTO,SANTA CLARA,CA,94304,15,NaN,True,94304,NaN,True
16,19,I-200-09302-785109,CERTIFIED-WITHDRAWN,2014-10-29,N,105 CORPORATE CENTER BLVD,37081,GREENSBORO,UNITED STATES OF AMERICA,04/25/2015,VF CORPORATION,NC,04/25/2012,27408,Y,NaN,16,PROJECT MANAGER (DIGITAL/ECOMMERCE),5415,54151,541512,NaT,Year,110300.00,Year,15-16,11-3021,COMPUTER AND INFORMATION SYSTEMS MANAGERS,2012-02-02,1.0,N,H-1B,125000.000,125000.00,NaN,06059,CYPRESS,ORANGE,CA,90630,15,NaN,True,27408,NaN,True
17,21,I-200-09313-334737,CERTIFIED,2014-12-29,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,06/15/2018,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,06/16/2015,22102,Y,NaN,17,SYSTEMS ANALYSIS SENIOR,5222,52229,522294,NaT,Year,75200.00,Year,15-17,15-1121,COMPUTER SYSTEMS ANALYSTS,2014-12-19,1.0,N,H-1B,103850.000,75200.00,132500.00,51059,RESTON,FAIRFAX,VA,20190,15,NaN,True,22102,NaN,True
18,22,I-200-09316-752823,WITHDRAWN,2014-10-13,N,1510 WEST LOOP SOUTH,48201,HOUSTON,UNITED STATES OF AMERICA,10/12/2017,"LANDRY'S RESTAURANTS, INC.",TX,10/13/2014,77027,Y,NaN,18,GENERAL MANAGER,7221,72211,722110,NaT,Year,89569.00,Year,15-18,11-9051.00,FOOD SERVICE MANAGERS,2014-10-13,1.0,N,H-1B,136700.000,109360.00,164040.00,48201,HOUSTON,HARRIS,TX,77027,15,NaN,True,77027,NaN,True
19,23,I-200-09317-262420,WITHDRAWN,2014-10-13,N,1510 WEST LOOP SOUTH,48201,HOUSTON,UNITED STATES OF AMERICA,10/12/2017,"LANDRY'S RESTAURANTS, INC.",TX,10/13/2014,77027,Y,NaN,19,GENERAL MANAGER,7221,72211,722110,NaT,Year,56722.00,Year,15-19,11-9051.00,FOOD SERVICE MANAGERS,2014-10-13,1.0,N,H-1B,69175.000,69175.00,NaN,35001,ALBUQUERQUE,BERNALILLO,NM,87109,15,NaN,True,77027,NaN,True
20,24,I-200-09321-731590,CERTIFIED,2014-12-24,N,100 WEST WALNUT STREET,06037,PASADENA,UNITED STATES OF AMERICA,01/11/2018,PARSONS SERVICES COMPANY,CA,01/12/2015,91124,Y,NaN,20,SENIOR IT SPECIALIST,5511,55111,551114,NaT,Year,108472.00,Year,15-20,15-1141,DATABASE ADMINISTRATORS,2014-12-18,1.0,N,H-1B,127500.000,110000.00,145000.00,06037,PAASADENA,LOS ANGELES,CA,91124,15,NaN,True,91124,NaN,True
21,25,I-200-09329-943146,CERTIFIED-WITHDRAWN,2015-07-27,N,5725 DELPHI DRIVE,26125,TROY,UNITED STATES OF AMERICA,09/13/2017,DELPHI CORPORATION,MI,05/31/2015,48098,Y,NaN,21,ALGORITHM-STATE ESTIMATION DEVELOPMENT ENGINEER,3363,33639,336399,NaT,Year,91936.00,Year,15-21,17-2071,ELECTRICAL ENGINEERS,2015-01-14,1.0,N,H-1B,91936.000,91936.00,NaN,06037,AGOURA HILLS,LOS ANGELES,CA,91301,15,NaN,True,48098,NaN,True
22,26,I-200-09334-392690,WITHDRAWN,2014-10-13,N,3333 S. BANNOCK STREET,08031,ENGLEWOOD,UNITED STATES OF AMERICA,10/12/2017,DAIRY INFORMATION SYSTEMS HOLDINGS LLC,CO,10/13/2014,80110,Y,NaN,22,APPLICATIONS PROGRAMMING MANAGER,5112,51121,511210,NaT,Year,94411.00,Year,15-22,15-1051.00,COMPUTER SYSTEMS ANALYSTS,2014-10-13,1.0,N,H-1B,107872.000,107872.00,NaN,08031,ENGLEWOOD,ARAPAHOE,CO,80110,15,NaN,True,80110,NaN,True
23,28,I-200-09338-814236,CERTIFIED-WITHDRAWN,2015-01-19,Y,"4 ETHEL RD, SUITE 403B",34023,EDISON,UNITED STATES OF AMERICA,09/21/2015,"INTEGRATED RESOURCES, INC",NJ,02/21/2013,08817,Y,NaN,23,OCCUPATIONAL THERAPISTS,5613,56132,561320,NaT,Hour,32.97,Hour,15-23,29-1122,OCCUPATIONAL THERAPISTS,2013-02-21,1.0,N,H-1B,35.000,35.00,NaN,34011,VINELAND,CUMBERLAND,NJ,08362,15,NaN,True,08817,NaN,True
24,29,I-200-09341-564186,CERTIFIED-WITHDRAWN,2015-01-26,Y,205 HOUSE AVENUE SUITE#103,42041,CAMP HILL,UNITED STATES OF AMERICA,06/19/2016,"XPERT TECHNOLOGIES, INC.",PA,06/19/2013,17011,Y,NaN,24,QUALITY ASSURANCE ANALYST,5415,54151,541511,NaT,Year,58282.00,Year,15-24,15-1799,"COMPUTER OCCUPATIONS, ALL OTHER*",2013-06-17,1.0,N,H-1B,60000.000,60000.00,NaN,42041,CAMP HILL,CUMBERLAND,PA,17011,15,NaN,True,17011,NaN,True
25,31,I-200-09342-274341,CERTIFIED,2015-02-22,Y,"559 D'ONOFRIO DRIVE, SUITE 101 & 102",55025,MADISON,UNITED STATES OF AMERICA,03/03/2018,"ISR INFO WAY, INC.",WI,03/04/2015,53719,Y,NaN,25,SR. SOFTWARE DEVELOPER,5415,54151,541511,NaT,Year,84906.00,Year,15-25,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2015-02-13,1.0,N,H-1B,94953.000,84906.00,105000.00,17031,CHICAGO,COOK,IL,60601,15,NaN,True,53719,NaN,True
26,32,I-200-09362-088372,CERTIFIED,2014-12-26,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,06/17/2018,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,06/18/2015,22102,Y,NaN,26,CREDIT GUARANTEE ANALYTICS SENIOR,5222,52229,522294,NaT,Year,64085.00,Year,15-26,15-2031,OPERATIONS RESEARCH ANALYSTS,2014-12-19,1.0,N,H-1B,95550.000,64100.00,127000.00,51059,MCLEAN,FAIRFAX,VA,22102,15,NaN,True,22102,NaN,True
27,33,I-200-09362-500914,CERTIFIED,2015-01-07,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,06/27/2018,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,06/28/2015,22102,Y,NaN,27,SHARED INFORMATION SUPPORT SENIOR,5222,52229,522294,NaT,Year,90800.00,Year,15-27,15-1141,DATABASE ADMINISTRATORS,2014-12-30,1.0,N,H-1B,105550.000,90800.00,120300.00,51059,MCLEAN,FAIRFAX,VA,22102,15,NaN,True,22102,NaN,True
28,34,I-200-09364-425868,CERTIFIED,2015-03-20,N,7 PULASKI STREET,36067,AUBURN,UNITED STATES OF AMERICA,09/15/2018,MAGIC CIRCLE FILMS INTERNATIONAL LLC,NY,09/15/2015,13021,Y,NaN,28,VIDEO EDITOR,5121,51219,51219,NaT,Year,39333.00,Year,15-28,27-4032,FILM AND VIDEO EDITORS,2015-03-16,1.0,N,H-1B,50003.000,50003.00,NaN,36067,AUBURN,CAYUGA,NY,13021,15,NaN,True,13021,NaN,True
29,36,I-200-10006-413683,WITHDRAWN,2015-03-11,Y,"523 GREEN STREET, 2ND FLOOR",34023,ISELIN,UNITED STATES OF AMERICA,04/15/2018,SAPHIRE SOLUTIONS INC,NJ,04/16/2015,08830,Y,NaN,29,SYSTEMS ADMINISTRATOR,5415,54151,541511,NaT,Year,68638.00,Year,15-29,15-1142,NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS,2015-03-10,1.0,N,H-1B,79560.000,79560.00,NaN,36059,BETHPAGE,NASSAU,NY,11714,15,NaN,True,08830,NaN,True
30,37,I-200-10028-389232,CERTIFIED,2015-02-04,Y,"510 FRANKLIN AVENUE, SUITE 7 & 8",34013,NUTLEY,UNITED STATES OF AMERICA,09/10/2017,SWANKTEK INC,NJ,01/29/2015,07110,Y,NaN,30,BI APPLICATIONS CONSULTANT,5415,54151,541511,NaT,Year,66602.00,Year,15-30,15-1121,COMPUTER SYSTEMS ANALYSTS,2015-01-29,1.0,N,H-1B,70000.000,70000.00,NaN,06085,SAN JOSE,SANTA CLARA,CA,95112,15,NaN,True,07110,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,85,I-200-10207-775880,WITHDRAWN,2014-10-13,N,11700 KATY FREEWAY,48201,HOUSTON,UNITED STATES OF AMERICA,10/12/2017,"TECHNIP USA, INC.",TX,10/13/2014,77079,Y,NaN,71,SENIOR DEEPWATER RISER ENGINEER,5413,54133,541330,NaT,Year,80392.00,Year,15-71,17-2141.00,MECHANICAL ENGINEERS,2014-10-13,1.0,N,H-1B,85000.240,85000.24,NaN,48201,HOUSTON,HARRIS,TX,77079,15,NaN,True,77079,NaN,True
72,86,I-200-10214-358714,CERTIFIED-WITHDRAWN,2015-04-01,N,"920 MEMORIAL CITY WAY, SUITE 700",48201,HOUSTON,UNITED STATES OF AMERICA,08/17/2015,"WS ATKINS, INC.",TX,08/17/2012,77024,Y,NaN,72,ASSISTANT CFD CONSULTANT,5419,54199,541990,NaT,Year,64400.00,Year,15-72,17-2051,CIVIL ENGINEERS,2012-02-17,1.0,N,H-1B,68000.000,68000.00,NaN,48201,HOUSTON,HARRIS,TX,77024,15,NaN,True,77024,NaN,True
73,87,I-200-10214-421060,CERTIFIED,2015-01-06,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,01/04/2018,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,01/05/2015,22102,Y,NaN,73,SECURITIES MODELING PROFESSIONAL,5222,52229,522294,NaT,Year,64085.00,Year,15-73,15-2031,OPERATIONS RESEARCH ANALYSTS,2014-12-30,1.0,N,H-1B,90800.000,64100.00,117500.00,51059,MCLEAN,FAIRFAX,VA,22102,15,NaN,True,22102,NaN,True
74,88,I-200-10215-099771,CERTIFIED,2015-01-13,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,07/05/2018,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,07/06/2015,22102,Y,NaN,74,INFORMATION SECURITY SENIOR,5222,52229,522294,NaT,Year,85600.00,Year,15-74,15-1142,NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS,2015-01-07,1.0,N,H-1B,105900.000,85600.00,126200.00,51059,RESTON,FAIRFAX,VA,20190,15,NaN,True,22102,NaN,True
75,89,I-200-10217-966696,CERTIFIED,2015-02-10,Y,860 HEBRON PKWY,48121,LEWISVILLE,UNITED STATES OF AMERICA,09/29/2015,TRANS AMERICAN INFORMATION SYSTEMS INC,TX,02/04/2015,75057,Y,NaN,75,ATG DEVELOPER,5415,54151,541511,NaT,Year,79747.00,Year,15-75,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2015-02-04,1.0,N,H-1B,90000.000,90000.00,NaN,48113,RICHARDSON,DALLAS,TX,75081,15,NaN,True,75057,NaN,True
76,90,I-200-10223-731658,CERTIFIED-WITHDRAWN,2015-07-02,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,08/31/2018,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,09/01/2015,22102,Y,NaN,76,INTERNAL AUDIT PROFESSIONAL,5222,52229,522294,NaT,Year,55286.00,Year,15-76,13-2011,ACCOUNTANTS AND AUDITORS,2015-03-02,1.0,N,H-1B,74450.000,55300.00,93600.00,51059,MCLEAN,FAIRFAX,VA,22102,15,NaN,True,22102,NaN,True
77,91,I-200-10224-292346,CERTIFIED,2015-03-06,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,08/31/2018,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,09/01/2015,22102,Y,NaN,77,RISK MODELING SENIOR,5222,52229,522294,NaT,Year,64085.00,Year,15-77,15-2031,OPERATIONS RESEARCH ANALYSTS,2015-03-02,1.0,N,H-1B,85100.000,64100.00,106100.00,51059,MCLEAN,FAIRFAX,VA,22102,15,NaN,True,22102,NaN,True
78,92,I-200-10228-828212,CERTIFIED-WITHDRAWN,2014-12-01,N,1620 MCELDERRY STREET,24510,BALTIMORE,UNITED STATES OF AMERICA,01/14/2018,THE JOHNS HOPKINS UNIVERSITY,MD,01/15/2015,21205,Y,NaN,78,RESEARCH TECHNOLOGIST,6113,61131,611310,NaT,Year,27768.00,Year,15-78,19-4021,BIOLOGICAL TECHNICIANS,2014-09-02,1.0,N,H-1B,28320.000,28320.00,NaN,24510,BALTIMORE,BALTIMORE CITY,MD,21205,15,NaN,True,21205,NaN,True
79,93,I-200-10237-048581,WITHDRAWN,2014-10-13,N,3333 PIEDMONT ROAD,13121,ATLANTA,UNITED STATES OF AMERICA,10/12/2017,SONY ERICSSON MOBILE COMMUNICATIONS (USA) INC.,GA,10/13/2014,30305,Y,NaN,79,REGIONAL BUSINESS MANAGER,3342,33422,334220,NaT,Year,54912.00,Year,15-79,15-2031.00,OPERATIONS RESEARCH ANALYSTS,2014-10-13,1.0,N,H-1B,91348.000,76550.00,106146.00,13121,ATLANTA,FULTON,GA,30305,15,NaN,True,30305,NaN,True
80,94,I-200-10244-239911,CERTIFIED,2015-03-18,N,"1007 MARKET STREET, D-7031",10003,WILMINGTON,UNITED STATES OF AMERICA,09/08/2018,E.I. DU PONT DE NEMOURS AND COMPANY,DE,09/08/2015,19898,Y,NaN,80,"RESEARCH INVESTIGATOR, APPLICATION TECHNOLOGY",3251,32519,325199,NaT,Year,68370.00,Year,15-80,17-2021,AGRICULTURAL ENGINEERS,2015-03-09,1.0,N,H-1B,106015.000,83690.00,128340.00,10003,NEWARK,NEW CASTLE,DE,19711,15,NaN,True,19898,NaN,True
81,95,I-200-10246-559292,WITHDRAWN,2014-10-13,N,1000 THROCKMORTON STREET,48439,FORT WORTH,UNITED STATES OF AMERICA,10/12/2017,THE CITY OF FORT WORTH,TX,10/13/2014,76102,Y,NaN,81,FORENSIC DIVISION MANAGER,9221,92212,92212,NaT,Year,58864.00,Year,15-81,19-4092.00,FORENSIC SCIENCE TECHNICIANS,2014-10-13,1.0,N,H-1B,97240.000,97240.00,NaN,48439,FORT WORTH,TARRANT,TX,76102,15,NaN,True,76102,NaN,True
82,96,I-200-10250-971984,CERTIFIED-WITHDRAWN,2015-04-06,N,2700 LAKE COOK ROAD,17097,RIVERWOODS,UNITED STATES OF AMERICA,06/03/2017,"UNIVERSAL TAX SYSTEMS, INC.",IL,06/03/2014,60015,Y,NaN,82,FIELD SALES REP,5112,51121,511210,NaT,Year,48589.00,Year,15-82,41-1012,FIRST-LINE SUPERVISORS OF NON-RETAIL SALES WOR...,2014-05-22,1.0,N,H-1B,66794.500,48589.00,85000.00,12011,DAVIE,BROWARD,FL,33314,15,NaN,True,60015,NaN,True
83,97,I-200-10250-986276,CERTIFIED-WITHDRAWN,2015-05-12,N,2700 LAKE COOK ROAD,17097,RIVERWOODS,UNITED STATES OF AMERICA,09/12/2017,CCH INCORPORATED,IL,09/12/2014,60015,Y,NaN,83,IT ARCHITECT,5112,51121,511210,NaT,Year,85738.00,Year,15-83,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-08-19,1.0,N,H-1B,94919.000,85738.00,104100.00,20173,WICHITA,SEDGWICK,KS,67207,15,NaN,True,60015,NaN,True
84,98,I-200-10263-046043,WITHDRAWN,2014-10-24,N,5300 CALIFORNIA AVE.,06059,IRVINE,UNITED STATES OF AMERICA,09/30/2015,BROADCOM CORPORATION,CA,10/01/2012,92617,Y,NaN,84,"ENGINEER, PRINCIPAL - IC DESIGN",3344,33441,334413,NaT,Year,131019.00,Year,15-84,17-2072.00,"ELECTRONICS ENGINEERS, EXCEPT COMPUTER",2012-04-02,1.0,N,H-1B,131040.000,131040.00,NaN,06085,SUNNYVALE,SANTA CLARA,CA,94086,15,NaN,True,92617,NaN,True
85,99,I-200-10284-765613,CERTIFIED-WITHDRAWN,2015-02-13,N,180 MAIDEN LANE,36061,NEW YORK,UNITED STATES OF AMERICA,09/22/2016,"AIG PC GLOBAL SERVICES, INC.",NY,09/23/2013,10038,Y,NaN,85,"DIRECTOR, SCIENCE CONSUMER",5242,52429,524298,NaT,Year,141835.00,Year,15-85,11-3031,FINANCIAL MANAGERS,2013-09-17,1.0,N,H-1B,165000.000,165000.00,NaN,36061,NEW YORK,NEW YORK,NY,10038,15,NaN,True,10038,NaN,True
86,100,I-200-10286-468947,CERTIFIED,2014-11-17,N,3401 HILLVIEW AVE,06085,PALO ALTO,UNITED STATES OF AMERICA,05/11/2018,"VMWARE, INC.",CA,05/12/2015,94304,Y,NaN,86,MEMBER OF TECHNICAL STAFF - QUALITY ENGINEERING,5415,54151,541511,NaT,Year,97503.00,Year,15-86,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2014-11-10,1.0,N,H-1B,107277.000,107277.00,NaN,06085,PALO ALTO,SANTA CLARA,CA,94304,15,NaN,True,94304,NaN,True
87,101,I-200-10292-944449,CERTIFIED,2015-03-18,N,"1007 MARKET STREET, D-7031",10003,WILMINGTON,UNITED STATES OF AMERICA,09/08/2018,E.I. DU PONT DE NEMOURS AND COMPANY,DE,09/08/2015,19898,Y,NaN,87,"RESEARCH INVESTIGATOR, RESIDUE FIELD STUDY",3251,32519,325199,NaT,Year,82347.00,Year,15-87,17-2081,ENVIRONMENTAL ENGINEERS,2015-03-09,1.0,N,H-1B,106015.000,83690.00,128340.00,10003,NEWARK,NEW CASTLE,DE,19711,15,NaN,True,19898,NaN,True
88,102,I-200-10293-841987,CERTIFIED,2015-02-09,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,07/30/2018,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,07/31/2015,22102,Y,NaN,88,RELEASE MANAGEMENT SENIOR,5222,52229,522294,NaT,Year,79100.00,Year,15-88,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2015-02-02,1.0,N,H-1B,95400.000,79100.00,111700.00,51059,RESTON,FAIRFAX,VA,20190,15,NaN,True,22102,NaN,True

In [327]:
vvdatafull2.head()

,level_0,index,year,row_id,case_num,case_status,submit_date,decision_date,visa_class,emp_start,emp_end,emp_name,emp_address,emp_city,emp_st,emp_zip,emp_cfips,emp_cntry,work_city,work_cnty,work_cfips,work_st,job,soc_code,soc_name,naics_full,naics4,naics5,tot_workers,full_time,wage,wage_from,wage_to,payunit,pw,pw_payunit,dependent,violator,org_cert_date,DROP
0,0,0,15,15-0,I-200-09121-701936,WITHDRAWN,2015-02-05,2015-02-05,H-1B,02/09/2015,02/28/2015,"MEDTRONIC, INC.",710 MEDTRONIC PARKWAY NE,MINNEAPOLIS,MN,55432,27003,UNITED STATES OF AMERICA,EDEN PRAIRIE,STERNS,27053,CA,MECHANICAL ENGINEER,17-2141.00,MECHANICAL ENGINEERS,334510,3345,33451,1,Y,20000,20000.0,NaN,Year,19000.0,Year,N,N,NaT,NaN
1,1,1,15,15-1,I-200-09146-796321,CERTIFIED,2014-12-12,2014-12-18,H-1B,01/05/2015,01/04/2018,UNIVERSITY OF OKLAHOMA,905 ASP AVE,NORMAN,OK,73019,40027,UNITED STATES OF AMERICA,NORMAN,CLEVELAND,40027,OK,ASSISTANT PROFESSOR,25-1032,"ENGINEERING TEACHERS, POSTSECONDARY",611310,6113,61131,1,Y,85000,85000.0,NaN,Year,42860.0,Year,N,N,NaT,NaN
2,2,2,15,15-2,I-200-09180-329758,WITHDRAWN,2013-01-03,2014-12-15,H-1B,01/07/2013,01/06/2016,NOKIA INC.,6021 CONNECTION DRIVE,IRVING,TX,75039,48113,UNITED STATES OF AMERICA,SAN DIEGO,SAN DIEGO,06073,CA,RELEASE AND SOFTWARE TEST MANAGER,15-1799,"COMPUTER OCCUPATIONS, ALL OTHER*",517212,5172,51721,1,Y,94000,94000.0,NaN,Year,73965.0,Year,N,N,NaT,NaN
3,3,3,15,15-3,I-200-09183-259985,CERTIFIED,2015-03-10,2015-03-16,H-1B,09/07/2015,09/07/2018,"OMRON OILFIELD AND MARINE, INC.",9510 N. HOUSTON ROSSLYN ROAD,HOUSTON,TX,77088,48201,UNITED STATES OF AMERICA,HOUSTON,HARRIS,48201,TX,CONTROL ENGINEERING SPECIALIST,17-2072,"ELECTRONICS ENGINEERS, EXCEPT COMPUTER",335314,3353,33531,2,Y,68000,66000.0,70000,Year,65998.0,Year,N,N,NaT,NaN
4,4,4,15,15-4,I-200-09189-800933,CERTIFIED,2014-12-17,2014-12-23,H-1B,06/06/2015,06/05/2018,FEDERAL HOME LOAN MORTGAGE CO.,8250 JONES BRANCH DRIVE,MCLEAN,VA,22102,51059,UNITED STATES OF AMERICA,MCLEAN,FAIRFAX,51059,VA,DEVELOPMENT SENIOR,15-1131,COMPUTER PROGRAMMERS,522294,5222,52229,1,Y,120150,97000.0,143300,Year,96907.0,Year,N,N,NaT,NaN

### Before checking for cfips empty values 
Trying to rematch with another zip to county zip file

In [669]:
#zipref = zip_county[['zip', 'county']]
zipref.dtypes

zip       object
county    object
dtype: object

In [670]:
zipref = zip_county[['zip', 'county']]

In [688]:
zipref.head()

    zip2 county2
0  06010   09003
1  06013   09003
2  06033   09003
3  06037   09003
4  06040   09003

In [672]:
#vvdatafull3['emp_zip'] = vvdatafull3['emp_zip'].astype('str')
vvdatafull3.dtypes

level_0                   int64
case_num                 object
case_status            category
decision_date    datetime64[ns]
dependent                object
emp_address              object
emp_cfips                object
emp_city                 object
emp_cntry                object
emp_end                  object
emp_name                 object
emp_st                   object
emp_start                object
emp_zip                  object
full_time                object
id                       object
index                     int64
job                      object
naics4                   object
naics5                   object
naics_full               object
org_cert_date    datetime64[ns]
payunit                category
pw                      float64
pw_payunit               object
row_id                   object
soc_code                 object
soc_name                 object
submit_date      datetime64[ns]
tot_workers             float64
violator                 object
visa_class             category
wage                    float64
wage_from               float64
wage_to                 float64
work_cfips               object
work_city                object
work_cnty                object
work_st                  object
work_zip                 object
year                   category
DROP                     object
test                       bool
emp_zip2                 object
DROP2                    object
test2                      bool
test3                      bool
test4                      bool
DROP3                    object
DROP4                    object
dtype: object

In [712]:
import json 
zipref2 = json.dumps("../cross-walk/zip_to_cntyfip.json")

In [713]:
file = "../cross-walk/zip_to_cntyfip.json"
with open(file) as crosswalk_file:
    dict_cross = json.load(crosswalk_file)
    
zipref2 = pd.DataFrame.from_dict(dict_cross, orient='index')
zipref2.reset_index(level=0, inplace=True)

In [715]:
zipref2.columns = ['zip2', 'county2']

In [721]:
zipref3 = zipref2[['zip2','county2']]

In [722]:
zipref3.columns = ['zip3', 'county3']

In [787]:
zipref3[zipref3['zip3'] == '48337']

Empty DataFrame
Columns: [zip3, county3]
Index: []

In [702]:
numpattern = r'[0-9]'
vvdatafull4['test3'] = pd.Series(vvdatafull4['emp_cfips']).str.match(numpattern)
vvdatafull4['test4'] = pd.Series(vvdatafull4['work_cfips']).str.match(numpattern)

In [705]:
#vvdatafull4.loc[(vvdatafull4['test3'] == False), 'DROP3'] = 'DROP'
#vvdatafull4.loc[(vvdatafull4['test4'] == False), 'DROP4'] = 'DROP'

In [706]:
vvdatafull4[(vvdatafull4['DROP3'] == 'DROP') | (vvdatafull4['DROP4'] == 'DROP')] 
#29444 before second join

,level_0,case_num,case_status,decision_date,dependent,emp_address,emp_cfips,emp_city,emp_cntry,emp_end,emp_name,emp_st,emp_start,emp_zip,full_time,id,index,job,naics4,naics5,naics_full,org_cert_date,payunit,pw,pw_payunit,row_id,soc_code,soc_name,submit_date,tot_workers,violator,visa_class,wage,wage_from,wage_to,work_cfips,work_city,work_cnty,work_st,work_zip,year,DROP,test,emp_zip2,DROP2,test2,test3,test4,DROP3,DROP4,zip2,county2,zip3,county3
53,54,I-200-10083-675557,CERTIFIED-WITHDRAWN,2015-01-13,N,"WASHINGTON STATE UNIV., INT'L PROGS-GLOBAL SER...",53075,PULLMAN,UNITED STATES OF AMERICA,02/17/2016,WASHINGTON STATE UNIVERSITY,WA,02/18/2013,99164,Y,NaN,45,TECHNICAL TRANSFER SPECIALIST,6113,61131,611310,NaT,Year,39166.00,Year,15-45,19-1029,"BIOLOGICAL SCIENTISTS, ALL OTHER",2013-01-22,1.0,N,H-1B,45000.000,45000.00,NaN,53077,PROSSER,BENTON,WA,99350,15,NaN,True,99164,NaN,True,False,True,DROP,NaN,99164,53075,99350,53077
317,319,I-200-11199-694531,CERTIFIED-WITHDRAWN,2014-11-03,N,11 MADISON AVENUE,36061,NEW YORK,UNITED STATES OF AMERICA,12/26/2014,CREDIT SUISSE SECURITIES (USA) LLC,NY,12/27/2011,10010,Y,NaN,274,ASSISTANT VICE PRESIDENT,5231,52311,523110,NaT,Year,71906.00,Year,15-274,13-2011,ACCOUNTANTS AND AUDITORS,2011-07-20,1.0,N,H-1B,90000.000,90000.00,NaN,36061,NEW YORK,NEW YORK,NY,10010,15,NaN,True,10010,NaN,True,False,True,DROP,NaN,10010,36061,10010,36061
318,320,I-200-11201-105420,CERTIFIED-WITHDRAWN,2015-06-02,N,"WASHINGTON STATE UNIV., INT'L PROGS-GLOBAL SER...",53075,PULLMAN,UNITED STATES OF AMERICA,08/15/2016,WASHINGTON STATE UNIVERSITY,WA,08/16/2013,99164,Y,NaN,275,ASSISTANT PROFESSOR,6113,61131,611310,NaT,Year,61530.00,Year,15-275,25-1032,"ENGINEERING TEACHERS, POSTSECONDARY",2013-06-26,1.0,N,H-1B,85000.000,85000.00,NaN,53011,VANCOUVER,CLARK,WA,98686,15,NaN,True,99164,NaN,True,False,True,DROP,NaN,99164,53075,98686,53011
372,376,I-200-11258-536112,CERTIFIED-WITHDRAWN,2014-10-01,N,11 MADISON AVENUE,36061,NEW YORK,UNITED STATES OF AMERICA,10/02/2014,CREDIT SUISSE SECURITIES (USA) LLC,NY,10/03/2011,10010,Y,NaN,323,ASSISTANT VICE PRESIDENT,5231,52311,523110,NaT,Year,105456.00,Year,15-323,15-1121,COMPUTER SYSTEMS ANALYSTS,2011-09-19,1.0,N,H-1B,135000.000,135000.00,NaN,36061,NEW YORK,NEW YORK,NY,10010,15,NaN,True,10010,NaN,True,False,True,DROP,NaN,10010,36061,10010,36061
417,426,I-200-11279-396092,WITHDRAWN,2014-10-10,N,600 N. DAIRY ASHFORD,NaN,HOUSTON,UNITED STATES OF AMERICA,10/09/2017,CONOCOPHILLIPS COMPANY,OK,10/10/2014,74004,Y,NaN,370,STAFF PROCESS ENGINEER,3241,32411,324110,NaT,Year,77804.00,Year,15-370,17-2041,CHEMICAL ENGINEERS,2014-10-10,1.0,N,H-1B,96802.000,77804.00,115800.00,06037,WILMINGTON,LOS ANGELES,CA,90744,15,NaN,True,74004,NaN,True,False,True,DROP,NaN,NaN,NaN,90744,06037
423,432,I-200-11284-111851,CERTIFIED,2015-03-05,N,1300 ELMWOOD AVENUE,36029,BUFFALO,UNITED STATES OF AMERICA,08/20/2018,STATE UNIVERSITY OF NEW YORK - BUFFALO STATE C...,NY,08/21/2015,14222,Y,NaN,376,ASSOCIATE PROFESSOR,6113,61131,611310,NaT,Year,46410.00,Year,15-376,25-1031,"ARCHITECTURE TEACHERS, POSTSECONDARY",2015-02-27,1.0,N,H-1B,66731.000,66731.00,NaN,36029,BUFFALO,ERIE,NY,14222,15,NaN,True,14222,NaN,True,False,True,DROP,NaN,14222,36029,14222,36029
442,451,I-200-11290-420508,WITHDRAWN,2014-11-14,N,14400 N. 87TH STREET,04013,SCOTTSDALE,UNITED STATES OF AMERICA,04/02/2015,"JDA SOFTWARE, INC.",AZ,04/03/2012,85260,Y,NaN,392,SOFTWARE DEVELOPER (SR. SOLUTION ARCHITECT),5416,54160,541600,NaT,Year,92394.00,Year,15-392,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2011-11-08,1.0,N,H-1B,106413.000,92394.00,120432.00,04013,SCOTTSDALE,MARICOPA,AZ,85260,15,NaN,True,85260,NaN,True,False,True,DROP,NaN,85260,04013,85260,04013
444,453,I-200-11290-539121,CERTIFIED-WITHDRAWN,2014-10-01,N,11 MADISON AVENUE,36061,NEW YORK,UNITED STATES OF AMERICA,04/07/2015,CREDIT SUISSE SECURITIES (USA) LLC,NY,04/08/2012,10010,Y,NaN,394,ASSISTANT VICE PRESIDENT,5231,52311,523110,NaT,Year,70096.00,Year,15-394,15-1141,DATABASE ADMINISTRATORS,2011-10-19,1.0,N,H-1B,134000.000,134000.00,NaN,36061,NEW YORK,NEW YORK,NY,10010,15,NaN,True,10010,NaN,True,False,True,DROP,NaN,10010,36061,10010,36061
479,489,I-200-11304-027833,WITHDRAWN,2014-10-31,N,702 S. W. 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,11/21/2014,"WAL-MART ASSOCIATES, INC.",AR,11/21/2011,72716,Y,NaN,426,SENIOR SECURITY ENGINEER,4529,45291,452910,NaT,Year,107099.00,Year,15-426,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2011-11-03,1.0,N,H-1B,120000.000,120000.00,NaN,06081,SAN BRUNO,SAN MATEO,CA,94066,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,72716,05007,94066,06081
497,507,I-200-11307-317327,CERTIFIED-WITHDRAWN,2014-10-28,N,999 WEST BIG BEAVER ROAD,26125,TROY,UNITED STATES OF AMERICA,11/07/2014,"KELLY SERVICES, INC.",MI,11/07/2011,48084,Y,NaN,442,DATABASE PROGRAMMER 2.1,5613,56131,561310,NaT,Hour,39.93,Hour,15-442,15-1141,DATABASE ADMINISTRATORS,2011-11-03,1.0,N,H-1B,40.910,40.91,NaN,24031,BETHESDA,MONTGOMERY,MD,20892,15,NaN,True,48084,NaN,True,False,True,DROP,NaN,48084,26125,20892,24031
501,511,I-200-11307-576081,WITHDRAWN,2014-10-10,N,250 PARKCENTER BOULEVARD,NaN,BOISE,UNITED STATES OF AMERICA,02/16/2015,"SUPERVALU, INC.",ID,02/17/2012,83726,Y,NaN,446,SENIOR IT ARCHITECT,4461,44611,446110,NaT,Year,102461.00,Year,15-446,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2011-11-11,1.0,N,H-1B,120000.000,120000.00,NaN,27053,EDEN PRAIRIE,HENNEPIN,MN,55344,15,NaN,True,83726,NaN,True,False,True,DROP,NaN,NaN,NaN,55344,27053
533,544,I-200-11313-487983,WITHDRAWN,2014-12-11,N,210 E. GRAND AVENUE,06081,SOUTH SAN FRANCISCO,UNITED STATES OF AMERICA,04/30/2015,"EXELIXIS, INC.",CA,05/01/2012,94083,Y,NaN,474,SENIOR STATISTICAL PROGRAMMER I,5417,54171,541710,NaT,Year,92290.00,Year,15-474,15-1121,COMPUTER SYSTEMS ANALYSTS,2011-11-16,1.0,N,H-1B,106284.880,106284.88,NaN,06081,SOUTH SAN FRANCISCO,SAN MATEO,CA,94083,15,NaN,True,94083,NaN,True,False,True,DROP,NaN,94083,06081,94083,06081
596,610,I-200-11325-558370,CERTIFIED-WITHDRAWN,2015-01-09,N,1415 W. FOSTER AVENUE,17031,CHICAGO,UNITED STATES OF AMERICA,01/30/2015,UNITED METHODIST HOMES & SERVICES,IL,01/31/2012,60640,Y,NaN,528,PHYSICAL THERAPIST,6231,62311,623110,NaT,Hour,26.58,Hour,15-528,29-1123,PHYSICAL THERAPISTS,2011-12-03,2.0,N,H-1B,28.150,28.15,NaN,17031,CHICAGO,COOK,IL,60640,15,NaN,True,60640,NaN,True,False,True,DROP,NaN,60640,17031,60640,17031
615,631,I-200-11333-304521,CERTIFIED-WITHDRAWN,2015-01-08,N,3040 CORNWALLIS ROAD,37063,RESEARCH TRIANGLE PARK,UNITED STATES OF AMERICA,03/11/2015,RESEARCH TRIANGLE INSTITUTE,NC,03/12/2012,27709,Y,NaN,547,RESEARCH SURVEY METHODOLOGIST 3,5417,54171,541710,NaT,Year,52166.00,Year,15-547,19-3022,SURVEY RESEARCHERS,2011-12-01,1.0,N,H-1B,110012.500,58673.00,161352.00,37063,RESEARCH TRIANGLE PARK,DURHAM,NC,27709,15,NaN,True,27709,NaN,True,False,True,DROP,NaN,27709,37063,27709,37063
621,637,I-200-11335-196826,WITHDRAWN,2015-01-16,N,ONE MEDICAL CENTER DRIVE,33009,LEBANON,UNITED STATES OF AMERICA,03/21/2015,MARY HITCHCOCK MEMORIAL HOSPITAL/DHMC,NH,03/23/2012,03756,Y,NaN,551,PHARMASCIST,6221,62211,622110,NaT,Hour,46.83,Hour,15-551,29-1051,PHARMACISTS,2011-12-01,1.0,N,H-1B,55.140,55.14,NaN,33009,LEBANON,GRAFTON,NH,03784,15,NaN,True,03756,NaN,True,False,True,DROP,NaN,03756,33009,03784,33009
708,725,I-200-11355-085835,CERTIFIED-WITHDRAWN,2015-01-14,N,2180 RUTHERFORD ROAD,06073,CARLSBAD,UNITED STATES OF AMERICA,04/26/2015,CALLAWAY GOLF COMPANY,CA,04/26/2012,92008,Y,NaN,620,SENIOR PRINCIPAL SAP DEVELOPER,3399,33992,339920,NaT,Year,94307.00,Year,15-620,15-1121,COMPUTER SYSTEMS ANALYSTS,2011-12-21,1.0,N,H-1B,95482.200,95482.20,NaN,06073,CARLSBAD,SAN DIEGO,CA,92008,15,NaN,True,92008,NaN,True,False,True,DROP,NaN,92008,06073,92008,06073
730,749,I-200-11363-750401,CERTIFIED-WITHDRAWN,2015-04-02,N,11 MADISON AVENUE,36061,NEW YORK,UNITED STATES OF AMERICA,07/04/2015,CREDIT SUISSE SECURITIES (USA) LLC,NY,07/05/2012,10010,Y,NaN,642,ASSOCIATE,5231,52311,523110,NaT,Year,88213.00,Year,15-642,13-2051,FINANCIAL ANALYSTS,2012-01-09,1.0,N,H-1B,100000.000,100000.00,NaN,36061,NEW YORK,NEW YORK,NY,10010,15,NaN,True,10010,NaN,True,False,True,DROP,NaN,10010,36061,10010,36061
761,781,I-200-12010-284318,CERTIFIED-WITHDRAWN,2014-10-01,N,5998 ALCALA PARK,06073,SAN DIEGO,UNITED STATES OF AMERICA,01/31/2015,UNIVERSITY OF SAN DIEGO,CA,02/01/2012,92110,Y,NaN,669,SR. PROGRAMMER ANALYST,6113,61131,611310,NaT,Year,73299.00,Year,15-669,15-1034,"SOFTWARE DEVELOPERS, APPLICATIONS, NON R & D",2012-01-13,1.0,N,H-1B,80000.000,80000.00,NaN,06073,SAN DIEGO,SAN DIEGO,CA,92110,15,NaN,True,92110,NaN,True,False,True,DROP,NaN,92110,06073,92110,06073
790,811,I-200-12018-269336,CERTIFIED-WITHDRAWN,2014-10-28,N,11 MADISON AVENUE,36061,NEW YORK,UNITED STATES OF AMERICA,02/05/2015,CREDIT SUISSE SECURITIES (USA) LLC,NY,02/06/2012,10010,Y,NaN,697,ASSISTANT VICE PRESIDENT,5231,52311,523110,NaT,Year,74422.00,Year,15-697,15-1121,COMPUTER SYSTEMS ANALYSTS,2012-01-26,1.0,N,H-1B,90000.000,90000.00,NaN,36061,NEW YORK,NEW YORK,NY,10010,15,NaN,True,10010,NaN,True,False,True,DROP,NaN,10010,36061,10010,36061
802,823,I-200-12019-593934,CERTIFIED-WITHDRAWN,2015-03-27,N,3135 TAMU,48041,COLLEGE STATION,UNITED STATES OF AMERICA,05/25/2015,TEXAS TRANSPORTATION INSTITUTE,TX,05/26/2012,77843,Y,NaN,707,ASSOCIATE RESEARCH SPECIALIST,5417,54171,54171,NaT,Year,47902.00,Year,15-707,13-1111,MANAGEMENT ANALYSTS,2012-01-23,1.0,N,H-1B,53637.000,53637.00,NaN,48141,EL PASO,EL PASO,TX,79902,15,NaN,True,77843,NaN,True,False,True,DROP,NaN,77843,48041,79902,48141
811,832,I-200-12020-690929,CERTIFIED-WITHDRAWN,2015-01-09,N,1415 W. FOSTER AVENUE,17031,CHICAGO,UNITED STATES OF AMERICA,02/15/2015,UNITED METHODIST HOMES & SERVICES,IL,02/16/2012,60640,Y,NaN,715,OCCUPATIONAL THERAPIST,6231,62311,623110,NaT,Hour,24.57,Hour,15-715,29-1122,OCCUPATIONAL THERAPISTS,2012-01-20,1.0,N,H-1B,28.000,28.00,NaN,17031,CHICAGO,COOK,IL,60640,15,NaN,True,60640,NaN,True,False,True,DROP,NaN,60640,17031,60640,17031
884,907,I-200-12031-302744,CERTIFIED-WITHDRAWN,2015-05-05,N,11 MADISON AVENUE,36061,NEW YORK,UNITED STATES OF AMERICA,08/18/2015,CREDIT SUISSE SECURITIES (USA) LLC,NY,08/19/2012,10010,Y,NaN,778,ANALYST,5231,52311,523110,NaT,Year,88213.00,Year,15-778,13-2051,FINANCIAL ANALYSTS,2012-02-21,1.0,N,H-1B,90000.000,90000.00,NaN,36061,NEW YORK,NEW YORK,NY,10010,15,NaN,True,10010,NaN,True,False,True,DROP,NaN,10010,36061,10010,36061
960,987,I-200-12039-657588,CERTIFIED-WITHDRAWN,2014-11-17,N,"350 FIFTH AVENUE, 34TH FLOOR",36061,NEW YORK,UNITED STATES OF AMERICA,08/22/2015,HUMAN RIGHTS WATCH,NY,08/23/2012,10118,Y,NaN,843,FELLOW,8133,81331,81331,NaT,Year,30950.00,Year,15-843,19-4061,SOCIAL SCIENCE RESEARCH ASSISTANTS,2012-02-29,1.0,N,H-1B,55000.000,55000.00,NaN,36061,NEW YORK,NEW YORK,NY,10118,15,NaN,True,10118,NaN,True,False,True,DROP,NaN,10118,36061,10118,36061
1016,1046,I-200-12045-469077,CERTIFIED-WITHDRAWN,2015-04-08,N,11 MADISON AVENUE,36061,NEW YORK,UNITED STATES OF AMERICA,08/13/2015,CREDIT SUISSE SECURITIES (USA) LLC,NY,08/14/2012,10010,Y,NaN,892,ANALYST,5231,52311,523110,NaT,Year,62566.00,Year,15-892,13-2051,FINANCIAL ANALYSTS,2012-03-14,1.0,N,H-1B,70000.000,70000.00,NaN,36061,NEW YORK,NEW YORK,NY,10010,15,NaN,True,10010,NaN,True,False,True,DROP,NaN,10010,36061,10010,36061
1069,1101,I-200-12047-994447,CERTIFIED-WITHDRAWN,2014-10-28,N,11 MADISON AVENUE,36061,NEW YORK,UNITED STATES OF AMERICA,09/06/2015,CREDIT SUISSE SECURITIES (USA) LLC,NY,09/07/2012,10010,Y,NaN,937,ANALYST,5231,52311,523110,NaT,Year,62566.00,Year,15-937,13-2051,FINANCIAL ANALYSTS,2012-03-08,1.0,N,H-1B,70000.000,70000.00,NaN,36061,NEW YORK,NEW YORK,NY,10010,15,NaN,True,10010,NaN,True,False,True,DROP,NaN,10010,36061,10010,36061
1172,1207,I-200-12058-433190,CERTIFIED-WITHDRAWN,2015-05-06,N,2929 ALLEN PARKWAY,48201,HOUSTON,UNITED STATES OF AMERICA,08/26/2015,BAKER HUGHES INCORPORATED,TX,08/26/2012,77019,Y,NaN,1028,FIELD ENGINEER I,5413,54133,541330,NaT,Year,70366.00,Year,15-1028,17-2112,INDUSTRIAL ENGINEERS,2012-03-14,1.0,N,H-1B,71000.000,71000.00,NaN,48355,CORPUS CHRISTI,NUECES,TX,78401,15,NaN,True,77019,NaN,True,False,True,DROP,NaN,77019,48201,78401,48355
1230,1266,I-200-12060-872192,WITHDRAWN,2014-10-31,N,702 S. W. 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,03/19/2015,"WAL-MART ASSOCIATES, INC.",AR,03/19/2012,72716,Y,NaN,1075,QUALITY ASSURANCE SOFTWARE ENGINEER III,4529,45291,452910,NaT,Year,92019.00,Year,15-1075,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2012-02-29,1.0,N,H-1B,95000.000,95000.00,NaN,06081,SAN BRUNO,SAN MATEO,CA,94066,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,72716,05007,94066,06081
1248,1284,I-200-12061-199475,CERTIFIED-WITHDRAWN,2015-03-19,N,702 S. W. 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,08/30/2015,"WAL-MART ASSOCIATES, INC.",AR,08/30/2012,72716,Y,NaN,1089,PHARMACIST,4521,45211,452112,NaT,Year,104208.00,Year,15-1089,29-1051,PHARMACISTS,2012-03-01,1.0,N,H-1B,129448.500,129448.50,NaN,48001,PALESTINE,ANDERSON,TX,75801,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,72716,05007,75801,48001
1325,1363,I-200-12065-052069,CERTIFIED-WITHDRAWN,2014-10-28,N,11 MADISON AVENUE,36061,NEW YORK,UNITED STATES OF AMERICA,09/06/2015,CREDIT SUISSE SECURITIES (USA) LLC,NY,09/07/2012,10010,Y,NaN,1153,ANALYST,5231,52311,523110,NaT,Year,62566.00,Year,15-1153,13-2051,FINANCIAL ANALYSTS,2012-03-08,1.0,N,H-1B,70000.000,70000.00,NaN,36061,NEW YORK,NEW YORK,NY,10010,15,NaN,True,10010,NaN,True,False,True,DROP,NaN,10010,36061,10010,36061
1329,1367,I-200-12065-133030,CERTIFIED-WITHDRAWN,2015-03-16,N,2929 ALLEN PARKWAY,48201,HOUSTON,UNITED STATES OF AMERICA,09/04/2015,BAKER HUGHES INCORPORATED,TX,09/04/2012,77019,Y,NaN,1157,SENIOR SYSTEM ANALYST,5413,54133,541330,NaT,Year,69014.00,Year,15-1157,15-1121,COMPUTER SYSTEMS ANALYSTS,2012-03-12,1.0,N,H-1B,95000.000,95000.00,NaN,48201,HOUSTON,HARRIS,TX,77073,15,NaN,True,77019,NaN,True,False,True,DROP,NaN,77019,48201,77073,48201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2326711,109697,I-203-17345-029102,CERTIFIED,2017-12-15,NaN,"2711 SULLIVAN DRIVE, CB 7210",NaN,RALEIGH,UNITED STATES OF AMERICA,2020-01-01 00:00:00,NORTH CAROLINA STATE UNIVERSITY,NC,2018-01-02 00:00:00,27695,Y,93437,93437,NEUROLOGY RESIDENT,6113,61131,611310,NaT,Year,34527.00,Year,18-93437,29-1131,VETERINARIANS,2017-12-11,1.0,NaN,E-3 Australian,35000.000,35000.00,35000.00,37183,RALEIGH,WAKE,NC,27607,18,NaN,True,27695,NaN,True,False,True,DROP,NaN,NaN,NaN,27607,37183
2326729,109716,I-200-17346-962068,CERTIFIED,2017-12-20,N,333 N SUMMIT ST.,39095,TOLEDO,UNITED STATES OF AMERICA,2021-05-16 00:00:00,"HEARTLAND EMPLOYMENT SERVICES, LLC",OH,2018-05-17 00:00:00,43604,N,93456,93456,OCCUPATIONAL THERAPIST,6231,62311,623110,NaT,Hour,39.13,Hour,18-93456,29-1122,OCCUPATIONAL THERAPISTS,2017-12-14,1.0,N,H-1B,19.565,39.13,0.00,24031,CHEVY CHASE,MONTGOMERY,MD,20815,18,NaN,True,43604,NaN,True,False,True,DROP,NaN,43604,39095,20815,24031
2326786,109777,I-200-17354-634179,CERTIFIED,2017-12-28,N,720 CITY CENTER DRIVE,18011,CARMEL,UNITED STATES OF AMERICA,2020-12-31 00:00:00,"MIDCONTINENT INDEPENDENT SYSTEM OPERATOR, INC.",IN,2018-01-01 00:00:00,46032,Y,93509,93509,"ENGINEER II, MARKET ENGINEERING",2211,22112,221121,NaT,Year,68578.00,Year,18-93509,17-2071,ELECTRICAL ENGINEERS,2017-12-21,1.0,N,H-1B,45037.500,90075.00,0.00,18011,CARMEL,HAMILTON,IN,46032,18,NaN,True,46032,NaN,True,False,True,DROP,NaN,46032,18011,46032,18011
2326806,109797,I-200-17354-677438,CERTIFIED,2017-12-27,Y,20 CORPORATE PLACE SOUTH,34039,PISCATAWAY,UNITED STATES OF AMERICA,2020-12-26 00:00:00,POLARIS CONSULTING & SERVICES LTD,NJ,2017-12-27 00:00:00,08854,Y,93523,93523,IT PROJECT MANAGER 3,5415,54151,541512,NaT,Hour,48.26,Hour,18-93523,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2017-12-20,1.0,N,H-1B,30.000,60.00,0.00,34035,WARREN,SOMERSET,NJ,07059,18,NaN,True,08854,NaN,True,False,True,DROP,NaN,08854,34039,07059,34035
2326834,109825,I-200-17341-735035,CERTIFIED,2017-12-13,N,702 S.W. 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,2021-06-04 00:00:00,"WAL-MART ASSOCIATES, INC.",AR,2018-06-05 00:00:00,72716,Y,93546,93546,PROGRAMMER ANALYST,4521,45211,452112,NaT,Year,70491.00,Year,18-93546,15-1121,COMPUTER SYSTEMS ANALYSTS,2017-12-07,1.0,N,H-1B,39110.370,78220.74,0.00,05007,BENTONVILLE,BENTON,AR,72716,18,NaN,True,72716,NaN,True,False,True,DROP,NaN,72716,05007,72716,05007
2326842,109833,I-200-17346-359183,CERTIFIED,2017-12-21,N,200 S. 108TH AVE.,31055,OMAHA,UNITED STATES OF AMERICA,2020-12-31 00:00:00,TD AMERITRADE HOLDING CORPORATION,NE,2018-01-01 00:00:00,68154,Y,93554,93554,"CONSULTANT, SOFTWARE DEVELOPMENT",5231,52312,52312,NaT,Year,114941.00,Year,18-93554,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-12-15,1.0,N,H-1B,71844.890,143689.78,0.00,29189,ST. LOUIS,ST. LOUIS,MO,63131,18,NaN,True,68154,NaN,True,False,True,DROP,NaN,68154,31055,63131,29189
2326859,109850,I-200-17346-636532,CERTIFIED,2017-12-18,Y,110 JERICHO TURNPIKE,36081,FLORAL PARK,UNITED STATES OF AMERICA,2021-01-24 00:00:00,RITNOA INC.,NY,2018-01-25 00:00:00,11001,Y,93569,93569,BO DEVELOPER,5415,54151,541512,NaT,Year,92768.00,Year,18-93569,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-12-12,1.0,N,H-1B,94000.000,93000.00,95000.00,36061,NEW YORK,NEW YORK,NY,10282,18,NaN,True,11001,NaN,True,False,True,DROP,NaN,11001,36081,10282,36061
2326871,109862,I-200-17354-012944,CERTIFIED,2017-12-27,N,INTERNATIONAL CENTER,26161,ANN ARBOR,UNITED STATES OF AMERICA,2020-11-30 00:00:00,UNIVERSITY OF MICHIGAN,MI,2018-01-15 00:00:00,48109,Y,93580,93580,ASSISTANT RESEARCH SCIENTIST,6113,61131,611310,NaT,Year,62379.00,Year,18-93580,17-2144,"MECHANICAL ENGINEERS, R&D",2017-12-20,1.0,N,H-1B,35000.000,70000.00,0.00,26161,ANN ARBOR,WASHTENAW,MI,48109,18,NaN,True,48109,NaN,True,False,True,DROP,NaN,48109,26161,48109,26161
2326923,109917,I-200-17342-327719,CERTIFIED,2017-12-14,N,702 S.W. 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,2020-12-14 00:00:00,"WAL-MART ASSOCIATES, INC.",AR,2017-12-15 00:00:00,72716,Y,93627,93627,NETWORK ENGINEER III,4521,45211,452112,NaT,Year,97552.00,Year,18-93627,15-1143,COMPUTER NETWORK ARCHITECTS,2017-12-08,1.0,N,H-1B,49500.000,99000.00,0.00,51059,RESTON,FAIRFAX,VA,20191,18,NaN,True,72716,NaN,True,False,True,DROP,NaN,72716,05007,20191,51059
2327047,110048,I-200-17342-344587,CERTIFIED,2017-12-14,N,TAMU 1158,48041,COLLEGE STATION,UNITED STATES OF AMERICA,2021-04-30 00:00:00,TEXAS A&M HEALTH SCIENCE CENTER,TX,2018-05-01 00:00:00,77843,Y,93745,93745,POSTDOCTORAL RESEARCH ASSOCIATE,6113,61131,61131,NaT,Year,39624.00,Year,18-93745,19-1022,MICROBIOLOGISTS,2017-12-08,1.0,N,H-1B,22500.000,45000.00,0.00,48041,COLLEGE STATION,BRAZOS,TX,77843,18,NaN,True,77843,NaN,True,False,True,DROP,NaN,77843,48041,77843,48041
2327102,110104,I-200-17347-063564,CERTIFIED,2017-12-19,N,2395 MIDWAY ROAD,48113,CARROLLTON,UNITED STATES OF AMERICA,2021-01-01 00:00:00,"THOMSON REUTERS (TAX & ACCOUNTING), INC.",TX,2018-01-02 00:00:00,75006,Y,93794,93794,SOFTWARE ENGINEER,5191,5191,5191,NaT,Year,90646.00,Year,18-93794,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-12-13,1.0,N,H-1B,50000.000,100000.00,0.00,48113,CARROLLTON,DALLAS,TX,75006,18,NaN,True,75006,NaN,True,False,True,DROP,NaN,75006,48113,75006,48113
2327134,110136,I-200-17345-064056,CERTIFIED,2017-12-20,N,2323 ROSS AVENUE,48113,DALLAS,UNITED STATES OF AMERICA,2021-01-01 00:00:00,KPMG LLP,TX,2018-01-01 00:00:00,75201,Y,93822,93822,ASSOCIATE,5412,54121,54121,NaT,Year,71300.00,Year,18-93822,13-2051,FINANCIAL ANALYSTS,2017-12-14,1.0,N,H-1B,78150.000,71300.00,85000.00,51059,MCLEAN,FAIRFAX,VA,22102,18,NaN,True,75201,NaN,True,False,True,DROP,NaN,75201,48113,22102,51059

In [725]:
vvdatafulltest = pd.merge(vvdatafull3, zipref2, how = 'left', left_on = 'emp_zip', right_on = 'zip2', validate = "m:m")

vvdatafulltest = vvdatafulltest.drop_duplicates(subset=['row_id'], keep = 'first')

In [726]:
vvdatafull4 = pd.merge(vvdatafulltest, zipref3, how = 'left', left_on = 'work_zip', right_on = 'zip3', validate = "m:m")

vvdatafull4 = vvdatafull4.drop_duplicates(subset=['row_id'], keep = 'first')

In [739]:
vvdatafull4.loc[(vvdatafull4['test3'] != True), 'emp_cfips'] = vvdatafull4['county2']
vvdatafull4.loc[(vvdatafull4['test4'] != True), 'work_cfips'] = vvdatafull4['county3']

In [740]:
vvdatafull4.head()

,level_0,case_num,case_status,decision_date,dependent,emp_address,emp_cfips,emp_city,emp_cntry,emp_end,emp_name,emp_st,emp_start,emp_zip,full_time,id,index,job,naics4,naics5,naics_full,org_cert_date,payunit,pw,pw_payunit,row_id,soc_code,soc_name,submit_date,tot_workers,violator,visa_class,wage,wage_from,wage_to,work_cfips,work_city,work_cnty,work_st,work_zip,year,DROP,test,emp_zip2,DROP2,test2,test3,test4,DROP3,DROP4,zip2,county2,zip3,county3,test5,test6,DROP5,DROP6
0,0,I-200-09121-701936,WITHDRAWN,2015-02-05,N,710 MEDTRONIC PARKWAY NE,27003,MINNEAPOLIS,UNITED STATES OF AMERICA,02/28/2015,"MEDTRONIC, INC.",MN,02/09/2015,55432,Y,NaN,0,MECHANICAL ENGINEER,3345,33451,334510,NaT,Year,19000.0,Year,15-0,17-2141.00,MECHANICAL ENGINEERS,2015-02-05,1.0,N,H-1B,20000.0,20000.0,NaN,27053,EDEN PRAIRIE,STERNS,CA,55412,15,NaN,True,55432,NaN,True,True,True,NaN,NaN,55432,27003,55412,27053,True,True,DROP,DROP
1,1,I-200-09146-796321,CERTIFIED,2014-12-18,N,905 ASP AVE,40027,NORMAN,UNITED STATES OF AMERICA,01/04/2018,UNIVERSITY OF OKLAHOMA,OK,01/05/2015,73019,Y,NaN,1,ASSISTANT PROFESSOR,6113,61131,611310,NaT,Year,42860.0,Year,15-1,25-1032,"ENGINEERING TEACHERS, POSTSECONDARY",2014-12-12,1.0,N,H-1B,85000.0,85000.0,NaN,40027,NORMAN,CLEVELAND,OK,73019,15,NaN,True,73019,NaN,True,True,True,NaN,NaN,73019,40027,73019,40027,True,True,DROP,DROP
2,2,I-200-09180-329758,WITHDRAWN,2014-12-15,N,6021 CONNECTION DRIVE,48113,IRVING,UNITED STATES OF AMERICA,01/06/2016,NOKIA INC.,TX,01/07/2013,75039,Y,NaN,2,RELEASE AND SOFTWARE TEST MANAGER,5172,51721,517212,NaT,Year,73965.0,Year,15-2,15-1799,"COMPUTER OCCUPATIONS, ALL OTHER*",2013-01-03,1.0,N,H-1B,94000.0,94000.0,NaN,06073,SAN DIEGO,SAN DIEGO,CA,92127,15,NaN,True,75039,NaN,True,True,True,NaN,NaN,75039,48113,92127,06073,True,True,DROP,DROP
3,3,I-200-09183-259985,CERTIFIED,2015-03-16,N,9510 N. HOUSTON ROSSLYN ROAD,48201,HOUSTON,UNITED STATES OF AMERICA,09/07/2018,"OMRON OILFIELD AND MARINE, INC.",TX,09/07/2015,77088,Y,NaN,3,CONTROL ENGINEERING SPECIALIST,3353,33531,335314,NaT,Year,65998.0,Year,15-3,17-2072,"ELECTRONICS ENGINEERS, EXCEPT COMPUTER",2015-03-10,2.0,N,H-1B,68000.0,66000.0,70000.0,48201,HOUSTON,HARRIS,TX,77088,15,NaN,True,77088,NaN,True,True,True,NaN,NaN,77088,48201,77088,48201,True,True,DROP,DROP
4,4,I-200-09189-800933,CERTIFIED,2014-12-23,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,06/05/2018,FEDERAL HOME LOAN MORTGAGE CO.,VA,06/06/2015,22102,Y,NaN,4,DEVELOPMENT SENIOR,5222,52229,522294,NaT,Year,96907.0,Year,15-4,15-1131,COMPUTER PROGRAMMERS,2014-12-17,1.0,N,H-1B,120150.0,97000.0,143300.0,51059,MCLEAN,FAIRFAX,VA,22102,15,NaN,True,22102,NaN,True,True,True,NaN,NaN,22102,51059,22102,51059,True,True,DROP,DROP

In [747]:
numpattern = r'[0-9]'
vvdatafull4['test7'] = pd.Series(vvdatafull4['emp_cfips']).str.match(numpattern)
vvdatafull4['test8'] = pd.Series(vvdatafull4['work_cfips']).str.match(numpattern)

In [750]:
vvdatafull4.loc[(vvdatafull4['test7'] != True), 'DROP7'] = 'DROP'
vvdatafull4.loc[(vvdatafull4['test8'] != True), 'DROP8'] = 'DROP'

In [785]:
zipref[zipref['zip2'] == '48337']

Empty DataFrame
Columns: [zip2, county2]
Index: []

In [755]:
vvdatafull4[(vvdatafull4['DROP7'] == 'DROP')] # | (vvdatafull4['DROP8'] == 'DROP')]

,level_0,case_num,case_status,decision_date,dependent,emp_address,emp_cfips,emp_city,emp_cntry,emp_end,emp_name,emp_st,emp_start,emp_zip,full_time,id,index,job,naics4,naics5,naics_full,org_cert_date,payunit,pw,pw_payunit,row_id,soc_code,soc_name,submit_date,tot_workers,violator,visa_class,wage,wage_from,wage_to,work_cfips,work_city,work_cnty,work_st,work_zip,year,DROP,test,emp_zip2,DROP2,test2,test3,test4,DROP3,DROP4,zip2,county2,zip3,county3,test5,test6,DROP5,DROP6,test7,test8,DROP7,DROP8
416,489,I-200-11304-027833,WITHDRAWN,2014-10-31,N,702 S. W. 8TH STREET,NaN,BENTONVILLE,UNITED STATES OF AMERICA,11/21/2014,"WAL-MART ASSOCIATES, INC.",AR,11/21/2011,72716,Y,NaN,426,SENIOR SECURITY ENGINEER,4529,45291,452910,NaT,Year,107099.00,Year,15-426,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2011-11-03,1.0,N,H-1B,120000.00,120000.00,NaN,06081,SAN BRUNO,SAN MATEO,CA,94066,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,94066,06081,NaN,True,DROP,DROP,NaN,True,DROP,NaN
1040,1266,I-200-12060-872192,WITHDRAWN,2014-10-31,N,702 S. W. 8TH STREET,NaN,BENTONVILLE,UNITED STATES OF AMERICA,03/19/2015,"WAL-MART ASSOCIATES, INC.",AR,03/19/2012,72716,Y,NaN,1075,QUALITY ASSURANCE SOFTWARE ENGINEER III,4529,45291,452910,NaT,Year,92019.00,Year,15-1075,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2012-02-29,1.0,N,H-1B,95000.00,95000.00,NaN,06081,SAN BRUNO,SAN MATEO,CA,94066,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,94066,06081,NaN,True,DROP,DROP,NaN,True,DROP,NaN
1054,1284,I-200-12061-199475,CERTIFIED-WITHDRAWN,2015-03-19,N,702 S. W. 8TH STREET,NaN,BENTONVILLE,UNITED STATES OF AMERICA,08/30/2015,"WAL-MART ASSOCIATES, INC.",AR,08/30/2012,72716,Y,NaN,1089,PHARMACIST,4521,45211,452112,NaT,Year,104208.00,Year,15-1089,29-1051,PHARMACISTS,2012-03-01,1.0,N,H-1B,129448.50,129448.50,NaN,48001,PALESTINE,ANDERSON,TX,75801,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,75801,48001,NaN,True,DROP,DROP,NaN,True,DROP,NaN
1238,1504,I-200-12067-982312,CERTIFIED-WITHDRAWN,2015-03-12,N,3 POLARIS WAY,NaN,ALISO VIEJO,UNITED STATES OF AMERICA,09/13/2015,"FLUOR ENTERPRISES, INC.",CA,09/14/2012,92698,Y,NaN,1279,SENIOR PROCESS/SPECIALTY ENGINEER,2379,23799,237990,NaT,Year,110136.00,Year,15-1279,17-2041,CHEMICAL ENGINEERS,2012-03-16,1.0,N,H-1B,130168.00,130168.00,NaN,48157,SUGAR LAND,HARRIS,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN
1584,1912,I-200-12080-267882,CERTIFIED-WITHDRAWN,2015-05-18,N,702 S. W. 8TH STREET,NaN,BENTONVILLE,UNITED STATES OF AMERICA,08/25/2015,"WAL-MART ASSOCIATES, INC.",AR,08/25/2012,72716,Y,NaN,1634,PHARMACY MANAGER,4521,45211,452112,NaT,Year,121472.00,Year,15-1634,29-1051,PHARMACISTS,2012-03-20,1.0,N,H-1B,141960.00,141960.00,NaN,48225,CROCKETT,HOUSTON,TX,75835,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,75835,48225,NaN,True,DROP,DROP,NaN,True,DROP,NaN
1782,2144,I-200-12087-438087,WITHDRAWN,2014-11-20,N,702 S. W. 8TH STREET,NaN,BENTONVILLE,UNITED STATES OF AMERICA,09/26/2015,"WAL-MART ASSOCIATES, INC.",AR,09/26/2012,72716,Y,NaN,1837,STAFF SOFTWARE ENGINEER,4529,45291,452910,NaT,Year,92019.00,Year,15-1837,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2012-03-27,1.0,N,H-1B,150000.00,150000.00,NaN,06081,SAN BRUNO,SAN MATEO,CA,94066,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,94066,06081,NaN,True,DROP,DROP,NaN,True,DROP,NaN
2004,2422,I-200-12096-946014,CERTIFIED-WITHDRAWN,2015-08-28,N,702 S. W. 8TH STREET,NaN,BENTONVILLE,UNITED STATES OF AMERICA,10/02/2015,"WAL-MART ASSOCIATES, INC.",AR,10/02/2012,72716,Y,NaN,2064,PHARMACIST,4521,45211,452112,NaT,Year,83741.00,Year,15-2064,29-1051,PHARMACISTS,2012-04-05,1.0,N,H-1B,129391.08,129391.08,NaN,21029,JEFFERSONTOWN,JEFFERSON,KY,40299,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,40299,21111,NaN,True,DROP,DROP,NaN,True,DROP,NaN
2215,2684,I-200-12108-197677,CERTIFIED-WITHDRAWN,2015-05-05,N,3 POLARIS WAY,NaN,ALISO VIEJO,UNITED STATES OF AMERICA,08/03/2015,"FLUOR ENTERPRISES, INC.",CA,08/04/2012,92698,Y,NaN,2282,PRINCIPAL DESIGN ENGINEER,2379,23799,237990,NaT,Year,159515.00,Year,15-2282,11-9041,ARCHITECTURAL AND ENGINEERING MANAGERS,2012-04-18,1.0,N,H-1B,172700.00,172700.00,NaN,48157,SUGAR LAND,FORT BEND,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN
2284,2764,I-200-12110-734694,CERTIFIED-WITHDRAWN,2015-08-26,N,3 POLARIS WAY,NaN,ALISO VIEJO,UNITED STATES OF AMERICA,09/30/2015,"FLUOR ENTERPRISES, INC.",CA,10/01/2012,92698,Y,NaN,2354,ASSOCIATE PROCESS / SPECIALTY ENGINEER II,2379,23799,237990,NaT,Year,77584.00,Year,15-2354,17-2041,CHEMICAL ENGINEERS,2012-04-24,1.0,N,H-1B,79000.00,79000.00,NaN,48157,SUGAR LAND,HARRIS,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN
2286,2766,I-200-12110-804965,CERTIFIED-WITHDRAWN,2015-04-08,N,3 POLARIS WAY,NaN,ALISO VIEJO,UNITED STATES OF AMERICA,05/01/2015,"FLUOR ENTERPRISES, INC.",CA,05/02/2012,92698,Y,NaN,2356,SENIOR ESTIMATOR,2379,23799,237990,NaT,Year,86174.00,Year,15-2356,13-2011,ACCOUNTANTS AND AUDITORS,2012-04-24,1.0,N,H-1B,130000.00,130000.00,NaN,48157,SUGAR LAND,HARRIS,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN
2327,2810,I-200-12114-354425,CERTIFIED-WITHDRAWN,2015-06-01,N,3 POLARIS WAY,NaN,ALISO VIEJO,UNITED STATES OF AMERICA,09/30/2015,"FLUOR ENTERPRISES, INC.",CA,10/01/2012,92698,Y,NaN,2397,ASSOCIATE PROCESS/ SPECIALTY ENGINEER II,2379,23799,237990,NaT,Year,53290.00,Year,15-2397,17-2131,MATERIALS ENGINEERS,2012-04-24,1.0,N,H-1B,72000.00,72000.00,NaN,48157,SUGAR LAND,HARRIS,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN
2409,2908,I-200-12117-236011,CERTIFIED-WITHDRAWN,2015-09-17,N,3 POLARIS WAY,NaN,ALISO VIEJO,UNITED STATES OF AMERICA,09/30/2015,"FLUOR ENTERPRISES, INC.",CA,10/01/2012,92698,Y,NaN,2479,ASSOCIATE PROCESS/SPECIALTY ENGINEER II,2379,23799,237990,NaT,Year,59093.00,Year,15-2479,17-2141,MECHANICAL ENGINEERS,2012-04-30,1.0,N,H-1B,75000.00,75000.00,NaN,48157,SUGAR LAND,HARRIS,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN
2455,2958,I-200-12121-514620,CERTIFIED-WITHDRAWN,2015-09-17,N,3 POLARIS WAY,NaN,ALISO VIEJO,UNITED STATES OF AMERICA,09/30/2015,"FLUOR ENTERPRISES, INC.",CA,10/01/2012,92698,Y,NaN,2527,PROCESS / SPECIALTY ENGINEER I,2379,23799,237990,NaT,Year,77584.00,Year,15-2527,17-2041,CHEMICAL ENGINEERS,2012-05-02,1.0,N,H-1B,78000.00,78000.00,NaN,48157,SUGAR LAND,HARRIS,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN
2490,3001,I-200-12122-572392,CERTIFIED-WITHDRAWN,2015-01-22,N,3 POLARIS WAY,NaN,ALISO VIEJO,UNITED STATES OF AMERICA,05/13/2015,"FLUOR ENTERPRISES, INC.",CA,05/14/2012,92698,Y,NaN,2563,PROJECT CONTROLS SPECIALIST I,2379,23799,237990,NaT,Year,51334.00,Year,15-2563,11-9021,CONSTRUCTION MANAGERS,2012-05-02,1.0,N,H-1B,85000.00,85000.00,NaN,48157,SUGAR LAND,FORT BEND,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN
2660,3206,I-200-12130-874600,CERTIFIED-WITHDRAWN,2015-03-31,N,3 POLARIS WAY,NaN,ALISO VIEJO,UNITED STATES OF AMERICA,05/15/2015,"FLUOR ENTERPRISES, INC.",CA,06/07/2012,92698,Y,NaN,2735,PROJECT ENGINEER 2,2379,23799,237990,NaT,Year,95534.00,Year,15-2735,17-2051,CIVIL ENGINEERS,2012-06-06,1.0,N,H-1B,96187.00,96187.00,NaN,08031,DENVER,ADAMS,CO,80202,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,80202,08031,NaN,True,DROP,DROP,NaN,True,DROP,NaN
3721,4472,I-200-12207-088513,CERTIFIED-WITHDRAWN,2015-03-16,N,3 POLARIS WAY,NaN,ALISO VIEJO,UNITED STATES OF AMERICA,08/07/2015,"FLUOR ENTERPRISES, INC.",CA,08/08/2012,92698,Y,NaN,3829,PROCESS/SPECIALITY ENGINEER 1,2379,23799,237990,NaT,Year,79664.00,Year,15-3829,17-2041,CHEMICAL ENGINEERS,2012-07-26,1.0,N,H-1B,82000.00,82000.00,NaN,48157,SUGAR LAND,HARRIS,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN
3824,4591,I-200-12215-835482,CERTIFIED-WITHDRAWN,2015-05-22,N,702 S. W. 8TH STREET,NaN,BENTONVILLE,UNITED STATES OF AMERICA,08/06/2015,"WAL-MART ASSOCIATES, INC.",AR,08/07/2012,72716,Y,NaN,3939,SENIOR SYSTEMS ENGINEER,4521,45211,452112,NaT,Year,87734.00,Year,15-3939,15-1133,"SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE",2012-08-02,1.0,N,H-1B,88304.32,88304.32,NaN,48491,AUSTIN,TRAVIS,TX,78727,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,78727,48453,NaN,True,DROP,DROP,NaN,True,DROP,NaN
4206,5041,I-200-12255-273861,CERTIFIED-WITHDRAWN,2015-05-04,N,702 SW 8TH STREET,NaN,BENTONVILLE,UNITED STATES OF AMERICA,09/23/2015,"WAL-MART ASSOCIATES, INC.",AR,09/24/2012,72716,Y,NaN,4340,SOFTWARE ENGINEER III,4529,45291,452910,NaT,Year,92789.00,Year,15-4340,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2012-09-11,1.0,N,H-1B,120000.00,120000.00,NaN,06081,SAN BRUNO,SAN MATEO,CA,94066,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,94066,06081,NaN,True,DROP,DROP,NaN,True,DROP,NaN
4491,5391,I-200-12282-236827,WITHDRAWN,2014-10-31,N,702 S. W. 8TH STREET,NaN,BENTONVILLE,UNITED STATES OF AMERICA,02/11/2016,"WAL-MART ASSOCIATES, INC.",AR,02/11/2013,72716,Y,NaN,4639,SENIOR SOFTWARE ENGINEER,4529,45291,452910,NaT,Year,111675.00,Year,15-4639,15-1121,COMPUTER SYSTEMS ANALYSTS,2012-10-08,1.0,N,H-1B,125705.00,125705.00,NaN,06081,BRISBANE,SAN MATEO,CA,94005,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,94005,06081,NaN,True,DROP,DROP,NaN,True,DROP,NaN
4626,5544,I-200-12290-420110,CERTIFIED-WITHDRAWN,2014-10-20,N,3 POLARIS WAY,NaN,ALISO VIEJO,UNITED STATES OF AMERICA,11/04/2015,"FLUOR ENTERPRISES, INC.",CA,11/05/2012,92698,Y,NaN,4778,PROCESS / SPECIALTY ENGINEER I,2379,23799,237990,NaT,Year,79664.00,Year,15-4778,17-2041,CHEMICAL ENGINEERS,2012-10-18,1.0,N,H-1B,85000.00,85000.00,NaN,48157,SUGAR LAND,FORT BEND,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN
4686,5614,I-200-12296-329147,CERTIFIED-WITHDRAWN,2015-07-07,N,702 SW 8TH STREET,NaN,BENTONVILLE,UNITED STATES OF AMERICA,11/03/2015,"WAL-MART ASSOCIATES, INC.",AR,11/03/2012,72716,Y,NaN,4840,PHARMACIST,4521,45211,452112,NaT,Year,105373.00,Year,15-4840,29-1051,PHARMACISTS,2012-10-22,1.0,N,H-1B,131040.00,131040.00,NaN,48225,CROCKETT,CROCKETT,TX,75835,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,75835,48225,NaN,True,DROP,DROP,NaN,True,DROP,NaN
4916,5881,I-200-12318-610013,CERTIFIED-WITHDRAWN,2015-06-24,N,702 S. W. 8TH STREET,NaN,BENTONVILLE,UNITED STATES OF AMERICA,11/26/2015,"WAL-MART ASSOCIATES, INC.",AR,11/27/2012,72716,Y,NaN,5079,PROGRAMMER ANALYST,4521,45211,452112,NaT,Year,51605.00,Year,15-5079,15-1121,COMPUTER SYSTEMS ANALYSTS,2012-11-13,1.0,N,H-1B,65250.00,65250.00,NaN,05007,BENTONVILLE,BENTON,AR,72716,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,NaN,NaN,NaN,True,DROP,DROP,NaN,True,DROP,NaN
4947,5917,I-200-12320-425231,WITHDRAWN,2015-04-30,N,702 S. W. 8TH STREET,NaN,BENTONVILLE,UNITED STATES OF AMERICA,12/03/2015,"WAL-MART ASSOCIATES, INC.",AR,12/03/2012,72716,Y,NaN,5110,SENIOR SOFTWARE ENGINEER,4529,45291,452910,NaT,Year,100984.00,Year,15-5110,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2012-11-15,1.0,N,H-1B,118000.00,118000.00,NaN,06085,SANTA CLARA,SANTA CLARA,CA,95051,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,95051,06085,NaN,True,DROP,DROP,NaN,True,DROP,NaN
5349,6389,I-200-12366-413320,CERTIFIED-WITHDRAWN,2015-09-03,N,702 SW 8TH STREET,NaN,BENTONVILLE,UNITED STATES OF AMERICA,01/15/2016,"WAL-MART ASSOCIATES, INC.",CA,01/15/2013,72716,Y,NaN,5531,"DIRECTOR, COMMERCIAL MANAGEMENT",4529,45291,452910,NaT,Year,181438.00,Year,15-5531,11-3021,COMPUTER AND INFORMATION SYSTEMS MANAGERS,2012-12-31,1.0,N,H-1B,190000.00,190000.00,NaN,06081,SAN BRUNO,SAN MATEO,CA,94066,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,94066,06081,NaN,True,DROP,DROP,NaN,True,DROP,NaN
5374,6416,I-200-13003-139654,CERTIFIED-WITHDRAWN,2015-06-15,N,702 S. W. 8TH STREET,NaN,BENTONVILLE,UNITED STATES OF AMERICA,01/14/2016,"WAL-MART ASSOCIATES, INC.",AR,01/15/2013,72716,Y,NaN,5556,PROGRAMMER ANALYST,4521,45211,452112,NaT,Year,51605.00,Year,15-5556,15-1121,COMPUTER SYSTEMS ANALYSTS,2013-01-03,1.0,N,H-1B,65000.00,65000.00,NaN,05007,BENTONVILLE,BENTON,AR,72716,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,NaN,NaN,NaN,True,DROP,DROP,NaN,True,DROP,NaN
5671,6767,I-200-13023-746771,WITHDRAWN,2014-10-31,N,702 SW 8TH STREET,NaN,BENTONVILLE,UNITED STATES OF AMERICA,02/07/2016,"WAL-MART ASSOCIATES, INC.",AR,02/07/2013,72716,Y,NaN,5863,SENIOR SQA ENGINEER,4529,45291,452910,NaT,Year,92789.00,Year,15-5863,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2013-01-23,1.0,N,H-1B,120000.00,120000.00,NaN,06081,SAN BRUNO,SAN MATEO,CA,94066,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,94066,06081,NaN,True,DROP,DROP,NaN,True,DROP,NaN
5715,6816,I-200-13025-556870,CERTIFIED-WITHDRAWN,2014-10-23,N,3 POLARIS WAY,NaN,ALISO VIEJO,UNITED STATES OF AMERICA,02/05/2016,"FLUOR ENTERPRISES, INC.",CA,02/06/2013,92698,Y,NaN,5907,PROCESS/SPECIALTY ENGINEER II,2379,23799,237990,NaT,Year,65666.00,Year,15-5907,17-2131,MATERIALS ENGINEERS,2013-01-28,1.0,N,H-1B,97000.00,97000.00,NaN,48157,SUGAR LAND,FORT BEND,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN
5816,6933,I-200-13031-193962,CERTIFIED-WITHDRAWN,2015-09-03,N,702 SW 8TH STREET,NaN,BENTONVILLE,UNITED STATES OF AMERICA,02/20/2016,"WAL-MART ASSOCIATES, INC.",AR,02/20/2013,72716,Y,NaN,6009,SENIOR SOFTWARE ENGINEER,4529,45291,452910,NaT,Year,100984.00,Year,15-6009,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2013-02-06,1.0,N,H-1B,120000.00,120000.00,NaN,06085,MOUNTAIN VIEW,SANTA CLARA,CA,94041,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,94041,06085,NaN,True,DROP,DROP,NaN,True,DROP,NaN
5925,7060,I-200-13037-146251,CERTIFIED-WITHDRAWN,2015-06-12,N,1601 WEST DIEHL ROAD,NaN,NAPERVILLE,UNITED STATES OF AMERICA,08/28/2016,NALCO COMPANY,IL,08/28/2013,60563,Y,NaN,6121,SENIOR RESEARCH CHEMIST,3251,3251,3251,NaT,Year,55869.00,Year,15-6121,19-2031,CHEMISTS,2013-03-11,1.0,N,H-1B,85000.00,85000.00,NaN,08005,DENVER,DENVER COUNTY,CO,80231,15,NaN,True,60563,NaN,True,False,True,DROP,NaN,NaN,NaN,80231,08005,NaN,True,DROP,DROP,NaN,True,DROP,NaN
6146,7324,I-200-13046-462589,CERTIFIED-WITHDRAWN,2015-04-29,N,3 POLARIS WAY,NaN,ALISO VIEJO,UNITED STATES OF AMERICA,08/11/2016,"FLUOR ENTERPRISES, INC.",CA,08/12/2013,92698,Y,NaN,6354,DESIGN ENGINEER IV,2379,23799,237990,NaT,Year,100547.00,Year,15-6354,17-2051,CIVIL ENGINEERS,2013-07-23,1.0,N,H-1B,107154.00,107154.00,NaN,06001,DUBLIN,ALAMEDA,CA,94568,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,94568,06001,NaN,True,DROP,DROP,NaN,True,DROP,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1927235,87627,I-200-17304-743270,CERTIFIED,2017-11-06,N,1891 METRO CENTER DRIVE,NaN,RESTON,UNITED STATES OF AMERICA,2020-11-13 00:00:00,"MAXIMUS, INC.",VA,2017-11-13 00:00:00,20190,Y,74588,74588,SENIOR ENGINEER - SOFTWARE ENGINEERING,5416,54161,541611,NaT,Year,102274.00,Year,18-74588,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-10-31,1.0,N,H-1B,127637.00,102274.00,153000.0,48453,AUSTIN,TRAVIS COUNTY,TX,78754,18,NaN,True,20190,NaN,True,False,True,DROP,NaN,NaN,NaN,78754,48453,NaN,True,DROP,DROP,NaN,True,DROP,NaN
1927688,88165,I-200-17312-340883,CERTIFIED,2017-11-15,N,702 S.W. 8TH STREET,NaN,BENTONVILLE,UNITED STATES OF AMERICA,2020-11-14 00:00:00,"WAL-MART ASSOCIATES, INC.",AR,2017-11-15 00:00:00,72716,Y,75052,75052,SYSTEMS ANALYST,4521,45211,452112,NaT,Year,72946.00,Year,18-75052,15-1121,COMPUTER SYSTEMS ANALYSTS,2017-11-08,1.0,N,H-1B,60000.00,120000.00,0.0,48439,SOUTHLAKE,TARRANT,TX,76092,18,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,76092,48439,NaN,True,DROP,DROP,NaN,True,DROP,NaN
1927690,88168,I-200-17305-114325,CERTIFIED,2017-11-16,Y,55 NORTH WATER STREET,NaN,NORWALK,UNITED STATES OF AMERICA,2020-11-20 00:00:00,SDG CORPORATION,CT,2017-11-20 00:00:00,06584,Y,75054,75054,TECHNICAL LEAD,5415,54151,541511,NaT,Year,69701.00,Year,18-75054,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2017-11-10,1.0,N,H-1B,43000.00,86000.00,0.0,36061,NEW YORK,NEW YORK,NY,10112,18,NaN,True,06584,NaN,True,False,True,DROP,NaN,NaN,NaN,10112,36061,NaN,True,DROP,DROP,NaN,True,DROP,NaN
1928298,88890,I-200-17321-955651,CERTIFIED,2017-11-24,Y,4637 CHABOT DRIVE,NaN,PLEASANTON,UNITED STATES OF AMERICA,2020-11-23 00:00:00,BAYONE SOLUTIONS INC,CA,2017-11-24 00:00:00,94588,Y,75678,75678,BUSINESS SYSTEMS ANALYST,5415,54151,541511,NaT,Year,99195.00,Year,18-75678,15-1121,COMPUTER SYSTEMS ANALYSTS,2017-11-17,1.0,N,H-1B,57500.00,115000.00,0.0,06075,SAN FRANCISCO,SAN FRANCISCO,CA,94111,18,NaN,True,94588,NaN,True,False,True,DROP,NaN,NaN,NaN,94111,06075,NaN,True,DROP,DROP,NaN,True,DROP,NaN
1929253,90053,I-200-17284-741449,CERTIFIED,2017-10-20,N,50505 SCHOENHERR ROAD,NaN,SHELBY TWP,UNITED STATES OF AMERICA,2020-10-31 00:00:00,"PULMONARY & CRITICAL CARE ASSOCIATES, P.C.",MI,2017-11-01 00:00:00,48315,Y,76652,76652,PHYSICIAN,6211,62111,621111,NaT,Year,121389.00,Year,18-76652,29-1063,"INTERNISTS, GENERAL",2017-10-16,1.0,N,H-1B,162500.00,325000.00,0.0,26099,SAINT CLAIR SHORES,MACOMB,MI,48081,18,NaN,True,48315,NaN,True,False,True,DROP,NaN,NaN,NaN,48081,26099,NaN,True,DROP,DROP,NaN,True,DROP,NaN
1929928,90874,I-200-17318-498269,CERTIFIED,2017-11-20,N,702 S.W. 8TH STREET,NaN,BENTONVILLE,UNITED STATES OF AMERICA,2020-12-04 00:00:00,"WAL-MART ASSOCIATES, INC.",AR,2017-12-05 00:00:00,72716,Y,77354,77354,PROGRAMMER ANALYST,4521,45211,452112,NaT,Year,58781.00,Year,18-77354,15-1121,COMPUTER SYSTEMS ANALYSTS,2017-11-14,1.0,N,H-1B,39000.00,78000.00,0.0,05007,BENTONVILLE,BENTON,AR,72716,18,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,NaN,NaN,NaN,True,DROP,DROP,NaN,True,DROP,NaN
1930171,91163,I-200-17332-387210,CERTIFIED,2017-12-05,Y,2788 SAN TOMAS EXPRESSWAY,NaN,SANTA CLARA,UNITED STATES OF AMERICA,2020-11-29 00:00:00,NVIDIA CORPORATION,CA,2017-11-30 00:00:00,8. CO,Y,77601,77601,MANAGER SECTION SYSTEMS SOFTWARE,3341,33411,334111,NaT,Year,156337.00,Year,18-77601,11-9041,ARCHITECTURAL AND ENGINEERING MANAGERS,2017-11-29,25.0,N,H-1B,175182.50,156337.00,194028.0,06085,SANTA CLARA,SANTA CLARA,CA,95051,18,NaN,True,8. CO,NaN,True,False,True,DROP,NaN,NaN,NaN,95051,06085,NaN,True,DROP,DROP,NaN,True,DROP,NaN
1930954,92108,I-200-17321-851985,CERTIFIED,2017-11-24,N,702 S.W. 8TH STREET,NaN,BENTONVILLE,UNITED STATES OF AMERICA,2020-12-07 00:00:00,"WAL-MART ASSOCIATES, INC.",AR,2017-12-08 00:00:00,72716,Y,78403,78403,PROGRAMMER ANALYST,4521,45211,452112,NaT,Year,58781.00,Year,18-78403,15-1121,COMPUTER SYSTEMS ANALYSTS,2017-11-17,1.0,N,H-1B,35500.00,71000.00,0.0,05007,BENTONVILLE,BENTON,AR,72716,18,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,NaN,NaN,NaN,True,DROP,DROP,NaN,True,DROP,NaN
1931500,92779,I-200-17338-208678,CERTIFIED,2017-12-08,N,702 S.W. 8TH STREET,NaN,BENTONVILLE,UNITED STATES OF AMERICA,2020-12-24 00:00:00,"WAL-MART ASSOCIATES, INC.",AR,2017-12-25 00:00:00,72716,Y,78962,78962,"SENIOR SOFTWARE ENGINEER, CYBERSECURITY",4521,45211,452112,NaT,Year,77002.00,Year,18-78962,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-12-04,1.0,N,H-1B,47500.00,95000.00,0.0,05007,BENTONVILLE,BENTON,AR,72716,18,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,NaN,NaN,NaN,True,DROP,DROP,NaN,True,DROP,NaN

#### all work zipcodes have been assigned fips code; for some reason, emp_zipcode hasn't been matched. 
Trying one more time to join with original zipref

In [761]:
zipref10 = zipref[['zip2','county2']]

In [762]:
zipref10.columns = ['zip10','county10']

In [763]:
#parking vvdatafull4

vvdatafull5 = pd.merge(vvdatafull4, zipref10, how = 'left', left_on = 'emp_zip', right_on = 'zip10', validate = "m:m")

vvdatafull5 = vvdatafull5.drop_duplicates(subset=['row_id'], keep = 'first')

In [770]:
vvdatafull5.loc[(vvdatafull5['DROP7'] == 'DROP'), 'emp_cfips'] = vvdatafull5['county10']

In [771]:
vvdatafull5[vvdatafull5['DROP7'] == 'DROP']

,level_0,case_num,case_status,decision_date,dependent,emp_address,emp_cfips,emp_city,emp_cntry,emp_end,emp_name,emp_st,emp_start,emp_zip,full_time,id,index,job,naics4,naics5,naics_full,org_cert_date,payunit,pw,pw_payunit,row_id,soc_code,soc_name,submit_date,tot_workers,violator,visa_class,wage,wage_from,wage_to,work_cfips,work_city,work_cnty,work_st,work_zip,year,DROP,test,emp_zip2,DROP2,test2,test3,test4,DROP3,DROP4,zip2,county2,zip3,county3,test5,test6,DROP5,DROP6,test7,test8,DROP7,DROP8,zip10,county10
464,489,I-200-11304-027833,WITHDRAWN,2014-10-31,N,702 S. W. 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,11/21/2014,"WAL-MART ASSOCIATES, INC.",AR,11/21/2011,72716,Y,NaN,426,SENIOR SECURITY ENGINEER,4529,45291,452910,NaT,Year,107099.00,Year,15-426,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2011-11-03,1.0,N,H-1B,120000.00,120000.00,NaN,06081,SAN BRUNO,SAN MATEO,CA,94066,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,94066,06081,NaN,True,DROP,DROP,NaN,True,DROP,NaN,72716,05007
1238,1266,I-200-12060-872192,WITHDRAWN,2014-10-31,N,702 S. W. 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,03/19/2015,"WAL-MART ASSOCIATES, INC.",AR,03/19/2012,72716,Y,NaN,1075,QUALITY ASSURANCE SOFTWARE ENGINEER III,4529,45291,452910,NaT,Year,92019.00,Year,15-1075,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2012-02-29,1.0,N,H-1B,95000.00,95000.00,NaN,06081,SAN BRUNO,SAN MATEO,CA,94066,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,94066,06081,NaN,True,DROP,DROP,NaN,True,DROP,NaN,72716,05007
1254,1284,I-200-12061-199475,CERTIFIED-WITHDRAWN,2015-03-19,N,702 S. W. 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,08/30/2015,"WAL-MART ASSOCIATES, INC.",AR,08/30/2012,72716,Y,NaN,1089,PHARMACIST,4521,45211,452112,NaT,Year,104208.00,Year,15-1089,29-1051,PHARMACISTS,2012-03-01,1.0,N,H-1B,129448.50,129448.50,NaN,48001,PALESTINE,ANDERSON,TX,75801,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,75801,48001,NaN,True,DROP,DROP,NaN,True,DROP,NaN,72716,05007
1468,1504,I-200-12067-982312,CERTIFIED-WITHDRAWN,2015-03-12,N,3 POLARIS WAY,06059,ALISO VIEJO,UNITED STATES OF AMERICA,09/13/2015,"FLUOR ENTERPRISES, INC.",CA,09/14/2012,92698,Y,NaN,1279,SENIOR PROCESS/SPECIALTY ENGINEER,2379,23799,237990,NaT,Year,110136.00,Year,15-1279,17-2041,CHEMICAL ENGINEERS,2012-03-16,1.0,N,H-1B,130168.00,130168.00,NaN,48157,SUGAR LAND,HARRIS,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN,92698,06059
1859,1912,I-200-12080-267882,CERTIFIED-WITHDRAWN,2015-05-18,N,702 S. W. 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,08/25/2015,"WAL-MART ASSOCIATES, INC.",AR,08/25/2012,72716,Y,NaN,1634,PHARMACY MANAGER,4521,45211,452112,NaT,Year,121472.00,Year,15-1634,29-1051,PHARMACISTS,2012-03-20,1.0,N,H-1B,141960.00,141960.00,NaN,48225,CROCKETT,HOUSTON,TX,75835,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,75835,48225,NaN,True,DROP,DROP,NaN,True,DROP,NaN,72716,05007
2091,2144,I-200-12087-438087,WITHDRAWN,2014-11-20,N,702 S. W. 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,09/26/2015,"WAL-MART ASSOCIATES, INC.",AR,09/26/2012,72716,Y,NaN,1837,STAFF SOFTWARE ENGINEER,4529,45291,452910,NaT,Year,92019.00,Year,15-1837,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2012-03-27,1.0,N,H-1B,150000.00,150000.00,NaN,06081,SAN BRUNO,SAN MATEO,CA,94066,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,94066,06081,NaN,True,DROP,DROP,NaN,True,DROP,NaN,72716,05007
2370,2422,I-200-12096-946014,CERTIFIED-WITHDRAWN,2015-08-28,N,702 S. W. 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,10/02/2015,"WAL-MART ASSOCIATES, INC.",AR,10/02/2012,72716,Y,NaN,2064,PHARMACIST,4521,45211,452112,NaT,Year,83741.00,Year,15-2064,29-1051,PHARMACISTS,2012-04-05,1.0,N,H-1B,129391.08,129391.08,NaN,21029,JEFFERSONTOWN,JEFFERSON,KY,40299,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,40299,21111,NaN,True,DROP,DROP,NaN,True,DROP,NaN,72716,05007
2615,2684,I-200-12108-197677,CERTIFIED-WITHDRAWN,2015-05-05,N,3 POLARIS WAY,06059,ALISO VIEJO,UNITED STATES OF AMERICA,08/03/2015,"FLUOR ENTERPRISES, INC.",CA,08/04/2012,92698,Y,NaN,2282,PRINCIPAL DESIGN ENGINEER,2379,23799,237990,NaT,Year,159515.00,Year,15-2282,11-9041,ARCHITECTURAL AND ENGINEERING MANAGERS,2012-04-18,1.0,N,H-1B,172700.00,172700.00,NaN,48157,SUGAR LAND,FORT BEND,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN,92698,06059
2694,2764,I-200-12110-734694,CERTIFIED-WITHDRAWN,2015-08-26,N,3 POLARIS WAY,06059,ALISO VIEJO,UNITED STATES OF AMERICA,09/30/2015,"FLUOR ENTERPRISES, INC.",CA,10/01/2012,92698,Y,NaN,2354,ASSOCIATE PROCESS / SPECIALTY ENGINEER II,2379,23799,237990,NaT,Year,77584.00,Year,15-2354,17-2041,CHEMICAL ENGINEERS,2012-04-24,1.0,N,H-1B,79000.00,79000.00,NaN,48157,SUGAR LAND,HARRIS,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN,92698,06059
2698,2766,I-200-12110-804965,CERTIFIED-WITHDRAWN,2015-04-08,N,3 POLARIS WAY,06059,ALISO VIEJO,UNITED STATES OF AMERICA,05/01/2015,"FLUOR ENTERPRISES, INC.",CA,05/02/2012,92698,Y,NaN,2356,SENIOR ESTIMATOR,2379,23799,237990,NaT,Year,86174.00,Year,15-2356,13-2011,ACCOUNTANTS AND AUDITORS,2012-04-24,1.0,N,H-1B,130000.00,130000.00,NaN,48157,SUGAR LAND,HARRIS,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN,92698,06059
2742,2810,I-200-12114-354425,CERTIFIED-WITHDRAWN,2015-06-01,N,3 POLARIS WAY,06059,ALISO VIEJO,UNITED STATES OF AMERICA,09/30/2015,"FLUOR ENTERPRISES, INC.",CA,10/01/2012,92698,Y,NaN,2397,ASSOCIATE PROCESS/ SPECIALTY ENGINEER II,2379,23799,237990,NaT,Year,53290.00,Year,15-2397,17-2131,MATERIALS ENGINEERS,2012-04-24,1.0,N,H-1B,72000.00,72000.00,NaN,48157,SUGAR LAND,HARRIS,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN,92698,06059
2845,2908,I-200-12117-236011,CERTIFIED-WITHDRAWN,2015-09-17,N,3 POLARIS WAY,06059,ALISO VIEJO,UNITED STATES OF AMERICA,09/30/2015,"FLUOR ENTERPRISES, INC.",CA,10/01/2012,92698,Y,NaN,2479,ASSOCIATE PROCESS/SPECIALTY ENGINEER II,2379,23799,237990,NaT,Year,59093.00,Year,15-2479,17-2141,MECHANICAL ENGINEERS,2012-04-30,1.0,N,H-1B,75000.00,75000.00,NaN,48157,SUGAR LAND,HARRIS,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN,92698,06059
2893,2958,I-200-12121-514620,CERTIFIED-WITHDRAWN,2015-09-17,N,3 POLARIS WAY,06059,ALISO VIEJO,UNITED STATES OF AMERICA,09/30/2015,"FLUOR ENTERPRISES, INC.",CA,10/01/2012,92698,Y,NaN,2527,PROCESS / SPECIALTY ENGINEER I,2379,23799,237990,NaT,Year,77584.00,Year,15-2527,17-2041,CHEMICAL ENGINEERS,2012-05-02,1.0,N,H-1B,78000.00,78000.00,NaN,48157,SUGAR LAND,HARRIS,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN,92698,06059
2936,3001,I-200-12122-572392,CERTIFIED-WITHDRAWN,2015-01-22,N,3 POLARIS WAY,06059,ALISO VIEJO,UNITED STATES OF AMERICA,05/13/2015,"FLUOR ENTERPRISES, INC.",CA,05/14/2012,92698,Y,NaN,2563,PROJECT CONTROLS SPECIALIST I,2379,23799,237990,NaT,Year,51334.00,Year,15-2563,11-9021,CONSTRUCTION MANAGERS,2012-05-02,1.0,N,H-1B,85000.00,85000.00,NaN,48157,SUGAR LAND,FORT BEND,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN,92698,06059
3140,3206,I-200-12130-874600,CERTIFIED-WITHDRAWN,2015-03-31,N,3 POLARIS WAY,06059,ALISO VIEJO,UNITED STATES OF AMERICA,05/15/2015,"FLUOR ENTERPRISES, INC.",CA,06/07/2012,92698,Y,NaN,2735,PROJECT ENGINEER 2,2379,23799,237990,NaT,Year,95534.00,Year,15-2735,17-2051,CIVIL ENGINEERS,2012-06-06,1.0,N,H-1B,96187.00,96187.00,NaN,08031,DENVER,ADAMS,CO,80202,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,80202,08031,NaN,True,DROP,DROP,NaN,True,DROP,NaN,92698,06059
4379,4472,I-200-12207-088513,CERTIFIED-WITHDRAWN,2015-03-16,N,3 POLARIS WAY,06059,ALISO VIEJO,UNITED STATES OF AMERICA,08/07/2015,"FLUOR ENTERPRISES, INC.",CA,08/08/2012,92698,Y,NaN,3829,PROCESS/SPECIALITY ENGINEER 1,2379,23799,237990,NaT,Year,79664.00,Year,15-3829,17-2041,CHEMICAL ENGINEERS,2012-07-26,1.0,N,H-1B,82000.00,82000.00,NaN,48157,SUGAR LAND,HARRIS,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN,92698,06059
4504,4591,I-200-12215-835482,CERTIFIED-WITHDRAWN,2015-05-22,N,702 S. W. 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,08/06/2015,"WAL-MART ASSOCIATES, INC.",AR,08/07/2012,72716,Y,NaN,3939,SENIOR SYSTEMS ENGINEER,4521,45211,452112,NaT,Year,87734.00,Year,15-3939,15-1133,"SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE",2012-08-02,1.0,N,H-1B,88304.32,88304.32,NaN,48491,AUSTIN,TRAVIS,TX,78727,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,78727,48453,NaN,True,DROP,DROP,NaN,True,DROP,NaN,72716,05007
4958,5041,I-200-12255-273861,CERTIFIED-WITHDRAWN,2015-05-04,N,702 SW 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,09/23/2015,"WAL-MART ASSOCIATES, INC.",AR,09/24/2012,72716,Y,NaN,4340,SOFTWARE ENGINEER III,4529,45291,452910,NaT,Year,92789.00,Year,15-4340,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2012-09-11,1.0,N,H-1B,120000.00,120000.00,NaN,06081,SAN BRUNO,SAN MATEO,CA,94066,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,94066,06081,NaN,True,DROP,DROP,NaN,True,DROP,NaN,72716,05007
5294,5391,I-200-12282-236827,WITHDRAWN,2014-10-31,N,702 S. W. 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,02/11/2016,"WAL-MART ASSOCIATES, INC.",AR,02/11/2013,72716,Y,NaN,4639,SENIOR SOFTWARE ENGINEER,4529,45291,452910,NaT,Year,111675.00,Year,15-4639,15-1121,COMPUTER SYSTEMS ANALYSTS,2012-10-08,1.0,N,H-1B,125705.00,125705.00,NaN,06081,BRISBANE,SAN MATEO,CA,94005,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,94005,06081,NaN,True,DROP,DROP,NaN,True,DROP,NaN,72716,05007
5449,5544,I-200-12290-420110,CERTIFIED-WITHDRAWN,2014-10-20,N,3 POLARIS WAY,06059,ALISO VIEJO,UNITED STATES OF AMERICA,11/04/2015,"FLUOR ENTERPRISES, INC.",CA,11/05/2012,92698,Y,NaN,4778,PROCESS / SPECIALTY ENGINEER I,2379,23799,237990,NaT,Year,79664.00,Year,15-4778,17-2041,CHEMICAL ENGINEERS,2012-10-18,1.0,N,H-1B,85000.00,85000.00,NaN,48157,SUGAR LAND,FORT BEND,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN,92698,06059
5518,5614,I-200-12296-329147,CERTIFIED-WITHDRAWN,2015-07-07,N,702 SW 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,11/03/2015,"WAL-MART ASSOCIATES, INC.",AR,11/03/2012,72716,Y,NaN,4840,PHARMACIST,4521,45211,452112,NaT,Year,105373.00,Year,15-4840,29-1051,PHARMACISTS,2012-10-22,1.0,N,H-1B,131040.00,131040.00,NaN,48225,CROCKETT,CROCKETT,TX,75835,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,75835,48225,NaN,True,DROP,DROP,NaN,True,DROP,NaN,72716,05007
5777,5881,I-200-12318-610013,CERTIFIED-WITHDRAWN,2015-06-24,N,702 S. W. 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,11/26/2015,"WAL-MART ASSOCIATES, INC.",AR,11/27/2012,72716,Y,NaN,5079,PROGRAMMER ANALYST,4521,45211,452112,NaT,Year,51605.00,Year,15-5079,15-1121,COMPUTER SYSTEMS ANALYSTS,2012-11-13,1.0,N,H-1B,65250.00,65250.00,NaN,05007,BENTONVILLE,BENTON,AR,72716,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,NaN,NaN,NaN,True,DROP,DROP,NaN,True,DROP,NaN,72716,05007
5811,5917,I-200-12320-425231,WITHDRAWN,2015-04-30,N,702 S. W. 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,12/03/2015,"WAL-MART ASSOCIATES, INC.",AR,12/03/2012,72716,Y,NaN,5110,SENIOR SOFTWARE ENGINEER,4529,45291,452910,NaT,Year,100984.00,Year,15-5110,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2012-11-15,1.0,N,H-1B,118000.00,118000.00,NaN,06085,SANTA CLARA,SANTA CLARA,CA,95051,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,95051,06085,NaN,True,DROP,DROP,NaN,True,DROP,NaN,72716,05007
6267,6389,I-200-12366-413320,CERTIFIED-WITHDRAWN,2015-09-03,N,702 SW 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,01/15/2016,"WAL-MART ASSOCIATES, INC.",CA,01/15/2013,72716,Y,NaN,5531,"DIRECTOR, COMMERCIAL MANAGEMENT",4529,45291,452910,NaT,Year,181438.00,Year,15-5531,11-3021,COMPUTER AND INFORMATION SYSTEMS MANAGERS,2012-12-31,1.0,N,H-1B,190000.00,190000.00,NaN,06081,SAN BRUNO,SAN MATEO,CA,94066,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,94066,06081,NaN,True,DROP,DROP,NaN,True,DROP,NaN,72716,05007
6297,6416,I-200-13003-139654,CERTIFIED-WITHDRAWN,2015-06-15,N,702 S. W. 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,01/14/2016,"WAL-MART ASSOCIATES, INC.",AR,01/15/2013,72716,Y,NaN,5556,PROGRAMMER ANALYST,4521,45211,452112,NaT,Year,51605.00,Year,15-5556,15-1121,COMPUTER SYSTEMS ANALYSTS,2013-01-03,1.0,N,H-1B,65000.00,65000.00,NaN,05007,BENTONVILLE,BENTON,AR,72716,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,NaN,NaN,NaN,True,DROP,DROP,NaN,True,DROP,NaN,72716,05007
6639,6767,I-200-13023-746771,WITHDRAWN,2014-10-31,N,702 SW 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,02/07/2016,"WAL-MART ASSOCIATES, INC.",AR,02/07/2013,72716,Y,NaN,5863,SENIOR SQA ENGINEER,4529,45291,452910,NaT,Year,92789.00,Year,15-5863,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2013-01-23,1.0,N,H-1B,120000.00,120000.00,NaN,06081,SAN BRUNO,SAN MATEO,CA,94066,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,94066,06081,NaN,True,DROP,DROP,NaN,True,DROP,NaN,72716,05007
6686,6816,I-200-13025-556870,CERTIFIED-WITHDRAWN,2014-10-23,N,3 POLARIS WAY,06059,ALISO VIEJO,UNITED STATES OF AMERICA,02/05/2016,"FLUOR ENTERPRISES, INC.",CA,02/06/2013,92698,Y,NaN,5907,PROCESS/SPECIALTY ENGINEER II,2379,23799,237990,NaT,Year,65666.00,Year,15-5907,17-2131,MATERIALS ENGINEERS,2013-01-28,1.0,N,H-1B,97000.00,97000.00,NaN,48157,SUGAR LAND,FORT BEND,TX,77478,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,77478,48157,NaN,True,DROP,DROP,NaN,True,DROP,NaN,92698,06059
6797,6933,I-200-13031-193962,CERTIFIED-WITHDRAWN,2015-09-03,N,702 SW 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,02/20/2016,"WAL-MART ASSOCIATES, INC.",AR,02/20/2013,72716,Y,NaN,6009,SENIOR SOFTWARE ENGINEER,4529,45291,452910,NaT,Year,100984.00,Year,15-6009,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2013-02-06,1.0,N,H-1B,120000.00,120000.00,NaN,06085,MOUNTAIN VIEW,SANTA CLARA,CA,94041,15,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,94041,06085,NaN,True,DROP,DROP,NaN,True,DROP,NaN,72716,05007
6923,7060,I-200-13037-146251,CERTIFIED-WITHDRAWN,2015-06-12,N,1601 WEST DIEHL ROAD,17043,NAPERVILLE,UNITED STATES OF AMERICA,08/28/2016,NALCO COMPANY,IL,08/28/2013,60563,Y,NaN,6121,SENIOR RESEARCH CHEMIST,3251,3251,3251,NaT,Year,55869.00,Year,15-6121,19-2031,CHEMISTS,2013-03-11,1.0,N,H-1B,85000.00,85000.00,NaN,08005,DENVER,DENVER COUNTY,CO,80231,15,NaN,True,60563,NaN,True,False,True,DROP,NaN,NaN,NaN,80231,08005,NaN,True,DROP,DROP,NaN,True,DROP,NaN,60563,17043
7171,7324,I-200-13046-462589,CERTIFIED-WITHDRAWN,2015-04-29,N,3 POLARIS WAY,06059,ALISO VIEJO,UNITED STATES OF AMERICA,08/11/2016,"FLUOR ENTERPRISES, INC.",CA,08/12/2013,92698,Y,NaN,6354,DESIGN ENGINEER IV,2379,23799,237990,NaT,Year,100547.00,Year,15-6354,17-2051,CIVIL ENGINEERS,2013-07-23,1.0,N,H-1B,107154.00,107154.00,NaN,06001,DUBLIN,ALAMEDA,CA,94568,15,NaN,True,92698,NaN,True,False,True,DROP,NaN,NaN,NaN,94568,06001,NaN,True,DROP,DROP,NaN,True,DROP,NaN,92698,06059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2351650,87627,I-200-17304-743270,CERTIFIED,2017-11-06,N,1891 METRO CENTER DRIVE,51059,RESTON,UNITED STATES OF AMERICA,2020-11-13 00:00:00,"MAXIMUS, INC.",VA,2017-11-13 00:00:00,20190,Y,74588,74588,SENIOR ENGINEER - SOFTWARE ENGINEERING,5416,54161,541611,NaT,Year,102274.00,Year,18-74588,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-10-31,1.0,N,H-1B,127637.00,102274.00,153000.0,48453,AUSTIN,TRAVIS COUNTY,TX,78754,18,NaN,True,20190,NaN,True,False,True,DROP,NaN,NaN,NaN,78754,48453,NaN,True,DROP,DROP,NaN,True,DROP,NaN,20190,51059
2352200,88165,I-200-17312-340883,CERTIFIED,2017-11-15,N,702 S.W. 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,2020-11-14 00:00:00,"WAL-MART ASSOCIATES, INC.",AR,2017-11-15 00:00:00,72716,Y,75052,75052,SYSTEMS ANALYST,4521,45211,452112,NaT,Year,72946.00,Year,18-75052,15-1121,COMPUTER SYSTEMS ANALYSTS,2017-11-08,1.0,N,H-1B,60000.00,120000.00,0.0,48439,SOUTHLAKE,TARRANT,TX,76092,18,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,76092,48439,NaN,True,DROP,DROP,NaN,True,DROP,NaN,72716,05007
2352202,88168,I-200-17305-114325,CERTIFIED,2017-11-16,Y,55 NORTH WATER STREET,NaN,NORWALK,UNITED STATES OF AMERICA,2020-11-20 00:00:00,SDG CORPORATION,CT,2017-11-20 00:00:00,06584,Y,75054,75054,TECHNICAL LEAD,5415,54151,541511,NaT,Year,69701.00,Year,18-75054,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2017-11-10,1.0,N,H-1B,43000.00,86000.00,0.0,36061,NEW YORK,NEW YORK,NY,10112,18,NaN,True,06584,NaN,True,False,True,DROP,NaN,NaN,NaN,10112,36061,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN
2352916,88890,I-200-17321-955651,CERTIFIED,2017-11-24,Y,4637 CHABOT DRIVE,06001,PLEASANTON,UNITED STATES OF AMERICA,2020-11-23 00:00:00,BAYONE SOLUTIONS INC,CA,2017-11-24 00:00:00,94588,Y,75678,75678,BUSINESS SYSTEMS ANALYST,5415,54151,541511,NaT,Year,99195.00,Year,18-75678,15-1121,COMPUTER SYSTEMS ANALYSTS,2017-11-17,1.0,N,H-1B,57500.00,115000.00,0.0,06075,SAN FRANCISCO,SAN FRANCISCO,CA,94111,18,NaN,True,94588,NaN,True,False,True,DROP,NaN,NaN,NaN,94111,06075,NaN,True,DROP,DROP,NaN,True,DROP,NaN,94588,06001
2354056,90053,I-200-17284-741449,CERTIFIED,2017-10-20,N,50505 SCHOENHERR ROAD,26099,SHELBY TWP,UNITED STATES OF AMERICA,2020-10-31 00:00:00,"PULMONARY & CRITICAL CARE ASSOCIATES, P.C.",MI,2017-11-01 00:00:00,48315,Y,76652,76652,PHYSICIAN,6211,62111,621111,NaT,Year,121389.00,Year,18-76652,29-1063,"INTERNISTS, GENERAL",2017-10-16,1.0,N,H-1B,162500.00,325000.00,0.0,26099,SAINT CLAIR SHORES,MACOMB,MI,48081,18,NaN,True,48315,NaN,True,False,True,DROP,NaN,NaN,NaN,48081,26099,NaN,True,DROP,DROP,NaN,True,DROP,NaN,48315,26099
2354864,90874,I-200-17318-498269,CERTIFIED,2017-11-20,N,702 S.W. 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,2020-12-04 00:00:00,"WAL-MART ASSOCIATES, INC.",AR,2017-12-05 00:00:00,72716,Y,77354,77354,PROGRAMMER ANALYST,4521,45211,452112,NaT,Year,58781.00,Year,18-77354,15-1121,COMPUTER SYSTEMS ANALYSTS,2017-11-14,1.0,N,H-1B,39000.00,78000.00,0.0,05007,BENTONVILLE,BENTON,AR,72716,18,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,NaN,NaN,NaN,True,DROP,DROP,NaN,True,DROP,NaN,72716,05007
2355142,91163,I-200-17332-387210,CERTIFIED,2017-12-05,Y,2788 SAN TOMAS EXPRESSWAY,NaN,SANTA CLARA,UNITED STATES OF AMERICA,2020-11-29 00:00:00,NVIDIA CORPORATION,CA,2017-11-30 00:00:00,8. CO,Y,77601,77601,MANAGER SECTION SYSTEMS SOFTWARE,3341,33411,334111,NaT,Year,156337.00,Year,18-77601,11-9041,ARCHITECTURAL AND ENGINEERING MANAGERS,2017-11-29,25.0,N,H-1B,175182.50,156337.00,194028.0,06085,SANTA CLARA,SANTA CLARA,CA,95051,18,NaN,True,8. CO,NaN,True,False,True,DROP,NaN,NaN,NaN,95051,06085,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN
2356032,92108,I-200-17321-851985,CERTIFIED,2017-11-24,N,702 S.W. 8TH STREET,05007,BENTONVILLE,UNITED STATES OF AMERICA,2020-12-07 00:00:00,"WAL-MART ASSOCIATES, INC.",AR,2017-12-08 00:00:00,72716,Y,78403,78403,PROGRAMMER ANALYST,4521,45211,452112,NaT,Year,58781.00,Year,18-78403,15-1121,COMPUTER SYSTEMS ANALYSTS,2017-11-17,1.0,N,H-1B,35500.00,71000.00,0.0,05007,BENTONVILLE,BENTON,AR,72716,18,NaN,True,72716,NaN,True,False,True,DROP,NaN,NaN,NaN,NaN,NaN,NaN,True,DROP,DROP,NaN,True,DROP,NaN,72716,05007

In [775]:
numpattern = r'[0-9]'
vvdatafull5['test10'] = pd.Series(vvdatafull5['emp_cfips']).str.match(numpattern)

In [783]:
vvdatafull5[vvdatafull5['emp_cfips'].isnull()] #821

,level_0,case_num,case_status,decision_date,dependent,emp_address,emp_cfips,emp_city,emp_cntry,emp_end,emp_name,emp_st,emp_start,emp_zip,full_time,id,index,job,naics4,naics5,naics_full,org_cert_date,payunit,pw,pw_payunit,row_id,soc_code,soc_name,submit_date,tot_workers,violator,visa_class,wage,wage_from,wage_to,work_cfips,work_city,work_cnty,work_st,work_zip,year,DROP,test,emp_zip2,DROP2,test2,test3,test4,DROP3,DROP4,zip2,county2,zip3,county3,test5,test6,DROP5,DROP6,test7,test8,DROP7,DROP8,zip10,county10,test10
8612,8780,I-200-13073-177631,CERTIFIED-WITHDRAWN,2015-06-22,N,39600 LEWIS DRIVE,NaN,NOVI,UNITED STATES OF AMERICA,09/12/2016,"MAGNA SEATING OF AMERICA, INC.",MI,09/13/2013,48337,Y,NaN,7587,PRODUCT ENGINEER,3261,32615,326150,NaT,Year,54122.00,Year,15-7587,17-2199,"ENGINEERS, ALL OTHER",2013-03-15,1.0,N,H-1B,61261.00,54122.00,68400.0,26125,NOVI,OAKLAND,MI,48377,15,NaN,True,48337,NaN,True,False,True,DROP,NaN,NaN,NaN,NaN,NaN,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
13241,13467,I-200-13248-662829,CERTIFIED-WITHDRAWN,2015-06-21,N,6205 SOUTH MAIN STREET,NaN,AURORA,UNITED STATES OF AMERICA,09/04/2016,"W/H/I/P SYSTEMS, LLC D/B/A AROGHIA GROUP, LLC",CO,09/05/2013,70016,Y,NaN,11698,SR. ETL DEVELOPER,5415,54151,541511,NaT,Year,71219.00,Year,15-11698,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2013-09-05,1.0,N,H-1B,71219.00,71219.00,NaN,06001,OAKLAND,ALAMEDA,CA,94612,15,NaN,True,70016,NaN,True,False,True,DROP,NaN,NaN,NaN,94612,06001,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
13551,13767,I-200-13262-551923,CERTIFIED-WITHDRAWN,2015-03-25,N,2401 SOUTH 31ST STREET,NaN,TEMPLE,UNITED STATES OF AMERICA,10/08/2016,SCOTT & WHITE MEMORIAL HOSPITAL,TX,10/09/2013,78508,Y,NaN,11974,PHYSICAL THERAPIST,6221,62211,622110,NaT,Year,57242.00,Year,15-11974,29-1123,PHYSICAL THERAPISTS,2013-09-23,1.0,N,H-1B,69097.00,69097.00,NaN,48041,COLLEGE STATION,BRAZOS,TX,77845,15,NaN,True,78508,NaN,True,False,True,DROP,NaN,NaN,NaN,NaN,NaN,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
20931,21124,I-200-14077-963434,CERTIFIED-WITHDRAWN,2014-12-05,N,2401 SOUTH 31ST STREET,NaN,TEMPLE,UNITED STATES OF AMERICA,06/22/2017,SCOTT & WHITE MEMORIAL HOSPITAL,TX,06/23/2014,78508,Y,NaN,18222,RESIDENT RADIATION ONCOLOGY PHYSICS,6221,62211,622110,NaT,Year,40456.00,Year,15-18222,19-2012,PHYSICISTS,2014-03-25,1.0,N,H-1B,49922.84,49922.84,NaN,48027,TEMPLE,BELL,TX,76502,15,NaN,True,78508,NaN,True,False,True,DROP,NaN,NaN,NaN,76502,48027,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
23378,23565,I-200-14118-035869,WITHDRAWN,2014-10-23,N,30 IRVING PLACE,NaN,NEW YORK,UNITED STATES OF AMERICA,05/05/2017,OCP COLLECTIVE CORP.,NY,05/05/2014,54189,Y,NaN,20289,DIRECTOR OF WEB ENGINEERING,5418,54189,54189,NaT,Year,105789.00,Year,15-20289,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-04-29,1.0,N,H-1B,125000.00,125000.00,NaN,36061,NEW YORK,NEW YORK,NY,10003,15,NaN,True,54189,NaN,True,False,True,DROP,NaN,NaN,NaN,10003,36061,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
27773,28005,I-200-14230-537063,CERTIFIED-WITHDRAWN,2014-10-07,N,P.O. BOX 1088,NaN,ROSEBURG,UNITED STATES OF AMERICA,09/01/2017,ROSEBURG FOREST PRODUCTS CO.,OR,09/02/2014,94741,Y,NaN,24125,LEAD PROGRAMMER ANALYST,3219,3219,3219,NaT,Year,83491.00,Year,15-24125,15-1121,COMPUTER SYSTEMS ANALYSTS,2014-08-20,1.0,N,H-1B,133560.00,133560.00,NaN,41039,COBURG,LANE,OR,97408,15,NaN,True,94741,NaN,True,False,True,DROP,NaN,NaN,NaN,NaN,NaN,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
34164,34433,I-200-14269-991391,CERTIFIED,2014-10-02,N,P.O. BOX 7,NaN,HAGATNA,UNITED STATES OF AMERICA,10/15/2017,"MICRONESIAN BROKERS, INC.",GU,10/15/2014,96932,Y,NaN,29552,SUPPLY CHAIN MANAGER,4244,42440,424400,NaT,Year,49026.00,Year,15-29552,11-9199,"MANAGERS, ALL OTHER",2014-09-26,1.0,N,H-1B,49525.00,49525.00,49525.0,66010,MAITE,GUAM,GU,96910,15,NaN,True,96932,NaN,True,False,True,DROP,NaN,NaN,NaN,96910,66010,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
40614,40738,I-200-14276-390270,WITHDRAWN,2014-10-04,N,POST OFFICE BOX 2767,NaN,HAGATNA,UNITED STATES OF AMERICA,12/30/2017,INLAND BUILDERS CORPORATION,GU,12/31/2014,96932,Y,NaN,34887,PROJECT ELECTRICAL ENGINEER,2362,23622,236220,NaT,Year,48880.00,Year,15-34887,17-2071,ELECTRICAL ENGINEERS,2014-10-03,1.0,N,H-1B,48880.00,48880.00,NaN,66010,HARMON,HARMON,GU,96913,15,NaN,True,96932,NaN,True,False,True,DROP,NaN,NaN,NaN,96913,66010,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
40670,40786,I-200-14276-428664,WITHDRAWN,2014-10-04,N,POST OFFICE BOX 2767,NaN,HAGATNA,UNITED STATES OF AMERICA,12/30/2017,INLAND BUILDERS CORPORATION,GU,12/31/2014,96932,Y,NaN,34929,PROJECT CIVIL ENGINEER,2362,23622,236220,NaT,Year,37170.00,Year,15-34929,17-2051,CIVIL ENGINEERS,2014-10-03,1.0,N,H-1B,37170.00,37170.00,NaN,66010,HARMON,HARMON,GU,96913,15,NaN,True,96932,NaN,True,False,True,DROP,NaN,NaN,NaN,96913,66010,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
40744,40865,I-200-14276-513803,CERTIFIED,2014-10-15,N,236 GLENMOOR ROAD,NaN,GLADWYNE,UNITED STATES OF AMERICA,10/21/2017,ELITE SEM,PA,10/22/2014,10935,Y,NaN,34999,MARKET RESEARCH ANALYST,5416,54161,541613,NaT,Year,37814.00,Year,15-34999,13-1161,MARKET RESEARCH ANALYSTS AND MARKETING SPECIAL...,2014-10-08,1.0,N,H-1B,81000.00,81000.00,NaN,36061,NEW YORK,MONTGOMERY,NY,10001,15,NaN,True,10935,NaN,True,False,True,DROP,NaN,NaN,NaN,10001,36061,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
40901,41022,I-200-14276-671731,WITHDRAWN,2014-10-04,N,POST OFFICE BOX 2767,NaN,HAGATNA,UNITED STATES OF AMERICA,12/30/2017,INLAND BUILDERS CORPORATION,GU,12/31/2014,96932,Y,NaN,35130,PROJECT CIVIL ENGINEER,2362,23622,236220,NaT,Year,37170.00,Year,15-35130,17-2051,CIVIL ENGINEERS,2014-10-03,1.0,N,H-1B,37170.00,37170.00,NaN,66010,HARMON,HARMON,GU,96913,15,NaN,True,96932,NaN,True,False,True,DROP,NaN,NaN,NaN,96913,66010,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
41276,41368,I-200-14277-118910,CERTIFIED,2014-10-09,N,POST OFFICE BOX 2767,NaN,HAGATNA,UNITED STATES OF AMERICA,12/30/2017,INLAND BUILDERS CORPORATION,GU,12/31/2014,96932,Y,NaN,35432,PROJECT MECHANICAL ENGINEER,2362,23622,236220,NaT,Year,42910.00,Year,15-35432,17-2141,MECHANICAL ENGINEERS,2014-10-04,1.0,N,H-1B,43680.00,43680.00,NaN,66010,HARMON,HARMON,GU,96913,15,NaN,True,96932,NaN,True,False,True,DROP,NaN,NaN,NaN,96913,66010,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
41277,41369,I-200-14277-150973,CERTIFIED,2014-10-09,N,POST OFFICE BOX 2767,NaN,HAGATNA,UNITED STATES OF AMERICA,12/30/2017,INLAND BUILDERS CORPORATION,GU,12/31/2014,96932,Y,NaN,35433,PROJECT CIVIL ENGINEER,2362,23622,236220,NaT,Year,37170.00,Year,15-35433,17-2051,CIVIL ENGINEERS,2014-10-04,1.0,N,H-1B,37170.00,37170.00,NaN,66010,HARMON,HARMON,GU,96913,15,NaN,True,96932,NaN,True,False,True,DROP,NaN,NaN,NaN,96913,66010,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
41280,41374,I-200-14277-216664,CERTIFIED,2014-10-09,N,POST OFFICE BOX 2767,NaN,HAGATNA,UNITED STATES OF AMERICA,12/30/2017,INLAND BUILDERS CORPORATION,GU,12/31/2014,96932,Y,NaN,35436,PROJECT CIVIL ENGINEER,2362,23622,236220,NaT,Year,37170.00,Year,15-35436,17-2051,CIVIL ENGINEERS,2014-10-04,1.0,N,H-1B,37170.00,37170.00,NaN,66010,HARMON,HARMON,GU,96913,15,NaN,True,96932,NaN,True,False,True,DROP,NaN,NaN,NaN,96913,66010,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
41306,41392,I-200-14277-650119,CERTIFIED,2014-10-09,N,POST OFFICE BOX 2767,NaN,HAGATNA,UNITED STATES OF AMERICA,12/13/2017,INLAND BUILDERS CORPORATION,GU,12/14/2014,96932,Y,NaN,35453,PROJECT CIVIL ENGINEER,2362,23622,236220,NaT,Year,37170.00,Year,15-35453,17-2051,CIVIL ENGINEERS,2014-10-04,1.0,N,H-1B,37170.00,37170.00,NaN,66010,HARMON,HARMON,GU,96913,15,NaN,True,96932,NaN,True,False,True,DROP,NaN,NaN,NaN,96913,66010,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
41324,41410,I-200-14277-939367,CERTIFIED,2014-10-09,N,POST OFFICE BOX 2767,NaN,HAGATNA,UNITED STATES OF AMERICA,12/30/2017,INLAND BUILDERS CORPORATION,GU,12/31/2014,96932,Y,NaN,35467,PROJECT ELECTRICAL ENGINEER,2362,23622,236220,NaT,Year,48880.00,Year,15-35467,17-2071,ELECTRICAL ENGINEERS,2014-10-04,1.0,N,H-1B,48880.00,48880.00,NaN,66010,HARMON,HARMON,GU,96913,15,NaN,True,96932,NaN,True,False,True,DROP,NaN,NaN,NaN,96913,66010,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
41945,42034,I-200-14279-360510,CERTIFIED,2014-10-10,N,1 PROGRESS DRIVE,NaN,DOVER,UNITED STATES OF AMERICA,10/20/2017,"ELECTROCRAFT NEW HAMPSHIRE, INC.",NH,10/20/2014,03829,Y,NaN,35988,GLOBAL JONIOR ERP ANALYST,3353,33531,335312,NaT,Year,44491.00,Year,15-35988,15-2031,OPERATIONS RESEARCH ANALYSTS,2014-10-06,1.0,N,H-1B,50000.00,50000.00,NaN,18051,PRINCETON,GIBSON,IN,47670,15,NaN,True,03829,NaN,True,False,True,DROP,NaN,NaN,NaN,47670,18051,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
42549,42633,I-200-14279-772846,CERTIFIED,2014-10-10,N,1 PROGRESS DRIVE,NaN,DOVER,UNITED STATES OF AMERICA,10/20/2017,"ELECTROCRAFT NEW HAMPSHIRE, INC.",NH,10/20/2014,03829,Y,NaN,36497,GLOBAL JONIOR ERP ANALYST,3353,33531,335312,NaT,Year,48360.00,Year,15-36497,15-2031,OPERATIONS RESEARCH ANALYSTS,2014-10-06,1.0,N,H-1B,50000.00,50000.00,NaN,33017,DOVER,STRAFFORD,NH,03820,15,NaN,True,03829,NaN,True,False,True,DROP,NaN,NaN,NaN,03820,33017,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
43577,43614,I-200-14280-443536,CERTIFIED,2014-10-16,N,P.O. BOX I,NaN,HAGATNA,UNITED STATES OF AMERICA,11/14/2017,PACIFIC TECHNOLOGY DEVELOPMENT LLC,GU,11/15/2014,96932,Y,NaN,37345,ENGINEERING MANAGER,5415,54151,541511,NaT,Year,54912.00,Year,15-37345,11-9041,ARCHITECTURAL AND ENGINEERING MANAGERS,2014-10-09,1.0,N,H-1B,55000.00,55000.00,55000.0,66010,ANIGUA,GUAM,GU,96910,15,NaN,True,96932,NaN,True,False,True,DROP,NaN,NaN,NaN,96910,66010,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
47568,47487,I-200-14282-958556,CERTIFIED,2014-10-16,Y,916 WINDSTONE COURT,NaN,LAKE IN THE HILLS,UNITED STATES OF AMERICA,10/12/2017,THOUGHTLINE TECHNOLOGIES INC,IL,10/13/2014,69558,Y,NaN,40611,SOFTWARE DEVELOPER,5415,54151,541511,NaT,Year,67288.00,Year,15-40611,15-1133,"SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE",2014-10-09,1.0,N,H-1B,72000.00,72000.00,NaN,17031,DES PLAINS,COOK,IL,60016,15,NaN,True,69558,NaN,True,False,True,DROP,NaN,NaN,NaN,60016,17031,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
47795,47701,I-200-14283-122500,WITHDRAWN,2014-10-14,N,275 W. HOSPITALITY LANE,NaN,SAN BERNARDINO,UNITED STATES OF AMERICA,10/23/2017,DESIGN WEST ENGINEERING,CA,10/24/2014,92480,Y,NaN,40794,ELECTRICAL PROJECT MANAGER,5413,54133,541330,NaT,Year,88317.00,Year,15-40794,17-2071,ELECTRICAL ENGINEERS,2014-10-13,1.0,N,H-1B,88317.00,88317.00,NaN,06073,SAN DIEGO,SAN DIEGO,CA,92122,15,NaN,True,92480,NaN,True,False,True,DROP,NaN,NaN,NaN,92122,06073,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
49272,49156,I-200-14286-065304,CERTIFIED,2014-10-20,N,275 W. HOSPITALITY LANE,NaN,SAN BERNARDINO,UNITED STATES OF AMERICA,10/23/2017,DESIGN WEST ENGINEERING,CA,10/24/2014,92480,Y,NaN,42025,ELECTRICAL PROJECT MANAGER,5413,54133,541330,NaT,Year,88317.00,Year,15-42025,17-2071,ELECTRICAL ENGINEERS,2014-10-14,1.0,N,H-1B,88317.00,88317.00,NaN,06073,SAN DIEGO,SAN DIEGO,CA,92122,15,NaN,True,92480,NaN,True,False,True,DROP,NaN,NaN,NaN,92122,06073,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
52328,52111,I-200-14288-034372,CERTIFIED,2014-10-22,N,47281 BAYSIDE PARKWAY,NaN,FREMONT,UNITED STATES OF AMERICA,12/01/2017,AVOCENT FREMONT CORP.,CA,12/01/2014,94358,Y,NaN,44506,SENIOR SOFTWARE ENGINEER,5415,54151,541519,NaT,Year,126630.00,Year,15-44506,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-10-16,1.0,N,H-1B,136743.00,126630.00,146856.0,06001,FREMONT,ALAMEDA,CA,94538,15,NaN,True,94358,NaN,True,False,True,DROP,NaN,NaN,NaN,94538,06001,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
52586,52363,I-200-14288-187351,CERTIFIED,2014-10-21,N,POST OFFICE BOX 2767,NaN,HAGATNA,UNITED STATES OF AMERICA,02/02/2017,INLAND BUILDERS CORPORATION,GU,12/31/2014,96932,Y,NaN,44713,PROJECT ELECTRICAL ENGINEER,2362,23622,236220,NaT,Year,48880.00,Year,15-44713,17-2071,ELECTRICAL ENGINEERS,2014-10-15,1.0,N,H-1B,48880.00,48880.00,NaN,66010,HARMON,HARMON,GU,96913,15,NaN,True,96932,NaN,True,False,True,DROP,NaN,NaN,NaN,96913,66010,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
56166,55822,I-200-14290-476992,CERTIFIED,2014-10-23,N,1 WILLIAM L JONES DR,NaN,COOKEVILLE,UNITED STATES OF AMERICA,08/15/2015,TENNESSEE TECHNOLOGICAL UNIVERSITY,TN,12/03/2014,38505,Y,NaN,47625,ACADEMIC ADVISOR,6113,61131,611310,NaT,Year,58718.00,Year,15-47625,17-2143,"MECHANICAL ENGINEERS, NON R&D",2014-10-17,1.0,N,H-1B,58794.00,58794.00,NaN,47141,COOKEVILLE,PUTNAM,TN,38501,15,NaN,True,38505,NaN,True,False,True,DROP,NaN,NaN,NaN,38501,47141,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
63146,62584,I-200-14297-340629,CERTIFIED,2014-10-30,Y,"850 ROUTE 1 NORTH, 3RD FLOOR",NaN,NORTH BRUNSWICK,UNITED STATES OF AMERICA,10/26/2017,DICE IT SOLUTIONS LLC,NJ,10/27/2014,08920,Y,NaN,53357,ORACLE APPLICATION FUNCTIONAL SOFTWARE ENGINEER,5415,54151,541511,NaT,Year,76648.00,Year,15-53357,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-10-24,1.0,N,H-1B,103710.00,103710.00,NaN,26125,SOUTHFIELD,OAKLAND,MI,48033,15,NaN,True,08920,NaN,True,False,True,DROP,NaN,NaN,NaN,48033,26125,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
74683,73802,I-200-14308-885455,CERTIFIED,2014-11-22,N,7799 MCHENRY STREET,NaN,MEADVILLE,UNITED STATES OF AMERICA,10/01/2017,PHOENIX TECHNICAL SOLUTIONS INC.,PA,11/17/2014,16355,Y,NaN,62812,BILL OF MATERIAL ENGINEER,5413,54133,54133,NaT,Year,47070.00,Year,15-62812,17-2141,MECHANICAL ENGINEERS,2014-11-17,1.0,N,H-1B,58000.00,58000.00,NaN,42049,ERIE,ERIE,PA,16510,15,NaN,True,16355,NaN,True,False,True,DROP,NaN,NaN,NaN,16510,42049,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
74772,73894,I-200-14308-946206,CERTIFIED,2014-11-13,N,1600 WEST CARSON STREET,NaN,PITTSBURGH,UNITED STATES OF AMERICA,02/27/2018,"HATCH ASSOCIATES CONSULTANTS, INC.",PA,02/28/2015,54133,Y,NaN,62884,SENIOR MINING ENGINEER,5413,54133,541330,NaT,Year,87714.00,Year,15-62884,17-2151,"MINING AND GEOLOGICAL ENGINEERS, INCLUDING MINING",2014-11-06,1.0,N,H-1B,125000.00,125000.00,NaN,04013,SCOTTSDALE,MARICOPA,AZ,85251,15,NaN,True,54133,NaN,True,False,True,DROP,NaN,NaN,NaN,85251,04013,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
75472,74587,I-200-14309-438319,CERTIFIED,2014-12-03,N,175 WYMAN STREET,NaN,WALTHAM,UNITED STATES OF AMERICA,03/19/2018,DASSAULT SYSTEMES SOLIDWORKS CORPORATION,MA,03/19/2015,00245,Y,NaN,63482,SOFTWARE ENGINEER,5112,51121,511210,NaT,Year,84781.00,Year,15-63482,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-11-26,1.0,N,H-1B,100000.00,95000.00,105000.0,06037,WOODLAND HILLS,LOS ANGELES,CA,91367,15,NaN,True,00245,NaN,True,False,True,DROP,NaN,NaN,NaN,91367,06037,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
82013,81039,I-200-14315-768850,DENIED,2014-11-24,Y,126 QUEEN STREET,NaN,HONOLULU,UNITED STATES OF AMERICA,04/30/2016,"PACIFIC LEATHER COMPANY, LLC",HI,05/01/2015,96681,Y,NaN,68920,ORTHOPEDIC SHOE MAKER AND REPAIRER,8114,81143,81143,NaT,Week,25060.00,Year,15-68920,51-6041,SHOE AND LEATHER WORKERS AND REPAIRERS,2014-11-17,1.0,N,H-1B,750.00,700.00,800.0,15003,HONOLULU,HONOLULU,HI,96813,15,NaN,True,96681,NaN,True,False,True,DROP,NaN,NaN,NaN,96813,15003,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2249684,727126,I-203-17258-720906,DENIED,2017-09-19,NaN,P.O. BOX 2997,NaN,HAGATNA,NaN,2019-09-30 00:00:00,ENDEAVOUR INSPECTION SERVICES LLC,GU,2017-10-01 00:00:00,96932,Y,611351,611351,CHIEF OPERATING OFFICER,2131,21311,213112,NaT,Year,34029.00,Year,17-611351,11-1011,CHIEF EXECUTIVES,2017-09-15,1.0,NaN,E-3 Australian,52002.00,52002.00,52002.0,66010,HAGATNA,NaN,GU,96910,17,NaN,True,96932,NaN,True,False,True,DROP,NaN,NaN,NaN,96910,66010,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
2250941,728443,I-200-17250-533120,CERTIFIED,2017-09-20,N,1090 SPRINGFIELD ROAD,NaN,UNION,NaN,2018-09-30 00:00:00,DEEP FOODS INC,NJ,2017-12-08 00:00:00,07038,Y,612456,612456,QA MANAGER,3119,31199,311999,NaT,Year,80995.00,Year,17-612456,19-1012,FOOD SCIENTISTS AND TECHNOLOGISTS,2017-09-14,1.0,N,H-1B,45000.00,90000.00,0.0,34013,UNION,UNION,NJ,07083,17,NaN,True,07038,NaN,True,False,True,DROP,NaN,NaN,NaN,07083,34039,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
2253388,730891,I-200-17258-116685,CERTIFIED,2017-09-21,N,P.O. BOX 2997,NaN,HAGATNA,NaN,2020-10-31 00:00:00,ENDEAVOUR INSPECTION SERVICES LLC,GU,2017-11-01 00:00:00,96932,Y,614470,614470,MECHANICAL ENGINEER,2131,21311,213112,NaT,Year,43763.00,Year,17-614470,17-2141,MECHANICAL ENGINEERS,2017-09-15,1.0,N,H-1B,50000.00,50000.00,50000.0,66010,HAGATNA,GUAM,GU,96910,17,NaN,True,96932,NaN,True,False,True,DROP,NaN,NaN,NaN,96910,66010,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
2258182,735776,I-200-17263-649818,CERTIFIED,2017-09-26,N,"ONE MIFFLIN PLACE, SUITE 400",NaN,CAMBRIDGE,NaN,2020-05-21 00:00:00,CONTINUSERVE LLC,MA,2017-09-29 00:00:00,02318,Y,618538,618538,F&A SHARED SERVICES DELIVERY MANAGER,5415,54151,541519,NaT,Year,94120.00,Year,17-618538,13-2011,ACCOUNTANTS AND AUDITORS,2017-09-20,1.0,N,H-1B,60500.00,121000.00,0.0,13121,ALPHARETTA,FULTON,GA,30004,17,NaN,True,02318,NaN,True,False,True,DROP,NaN,NaN,NaN,NaN,NaN,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
2259202,736805,I-203-17263-276461,CERTIFIED,2017-09-26,NaN,P.O. BOX 2997,NaN,HAGATNA,NaN,2019-09-30 00:00:00,ENDEAVOUR INSPECTION SERVICES LLC,GU,2017-10-01 00:00:00,96932,Y,619415,619415,CHIEF OPERATING OFFICER,2131,21311,213112,NaT,Year,34029.00,Year,17-619415,11-1011,CHIEF EXECUTIVES,2017-09-20,1.0,NaN,E-3 Australian,52002.00,52002.00,52002.0,66010,HAGATNA,NaN,GU,96910,17,NaN,True,96932,NaN,True,False,True,DROP,NaN,NaN,NaN,96910,66010,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
2264148,741912,I-200-17268-527696,CERTIFIED,2017-09-29,N,1069 STATE ROUTE 46 EAST,NaN,BATESVILLE,NaN,2021-03-16 00:00:00,"HILL-ROM SERVICES, INC.",IN,2018-03-16 00:00:00,47000,Y,623691,623691,SENIOR CODES & STANDARDS ENGINEER,4234,42345,423450,NaT,Year,52894.00,Year,17-623691,13-1041,COMPLIANCE OFFICERS,2017-09-25,1.0,N,H-1B,55434.50,110869.00,0.0,18137,BATESVILLE,RIPLEY,IN,47006,17,NaN,True,47000,NaN,True,False,True,DROP,NaN,NaN,NaN,47006,18047,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
2265387,164,I-200-15027-672230,CERTIFIED-WITHDRAWN,2017-10-12,N,801 NORTH BROADWAY,NaN,FARGO,UNITED STATES OF AMERICA,2018-05-28 00:00:00,SANFORD CLINIC NORTH,ND,2015-05-28 00:00:00,58112,Y,139,139,PSYCHIATRIST,6221,62211,622110,2015-02-02,Year,96242.00,Year,18-139,29-1066,PSYCHIATRISTS,2015-01-27,1.0,N,H-1B,120000.00,240000.00,0.0,27113,THIEF RIVER FALLS,PENNINGTON,MN,56701,18,NaN,True,58112,NaN,True,False,True,DROP,NaN,NaN,NaN,56701,27113,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
2265815,580,I-200-15061-888614,CERTIFIED-WITHDRAWN,2017-10-04,N,1 WILLIAM L JONES DR,NaN,COOKEVILLE,UNITED STATES OF AMERICA,2018-05-10 00:00:00,TENNESSEE TECHNOLOGICAL UNIVERSITY,TN,2015-05-11 00:00:00,38505,Y,503,503,INSTRUCTOR,6113,61131,611310,2015-03-06,Year,30000.00,Year,18-503,25-1052,"CHEMISTRY TEACHERS, POSTSECONDARY",2015-03-02,1.0,N,H-1B,21822.50,43645.00,0.0,47141,COOKEVILLE,PUTNAM,TN,38501,18,NaN,True,38505,NaN,True,False,True,DROP,NaN,NaN,NaN,38501,47141,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN
2266047,803,I-200-15062-111643,CERTIFIED-WITHDRAWN,2017-11-13,N,1 WILLIAM L JONES DR,NaN,COOKEVILLE,UNITED STATES OF AMERICA,2018-05-08 00:00:00,TENNESSEE TECHNOLOGICAL UNIVERSITY,TN,2015-05-09 00:00:00,38505,Y,688,688,LECTURER,6113,61131,611310,2015-03-09,Year,43380.00,Year,18-688,25-1192,"HOME ECONOMICS TEACHERS, POSTSECONDARY",2015-03-03,1.0,N,H-1B,25000.00,50000.00,0.0,47141,COOKEVILLE,PUTNAM,TN,38501,18,NaN,True,38505,NaN,True,False,True,DROP,NaN,NaN,NaN,38501,47141,NaN,True,DROP,DROP,NaN,True,DROP,NaN,NaN,NaN,NaN

In [789]:
## dropping the final 821 rows that didn't get a match for employer cfips
vvdatafull5.loc[(vvdatafull5['emp_cfips'].isnull()), 'final_drop'] = 'fdrop'

In [792]:
# parking vvdatafull5
vvdatafull6 = vvdatafull5[vvdatafull5['final_drop'] != 'fdrop']

In [793]:
vvdatafull6.columns

Index(['level_0', 'case_num', 'case_status', 'decision_date', 'dependent',
       'emp_address', 'emp_cfips', 'emp_city', 'emp_cntry', 'emp_end',
       'emp_name', 'emp_st', 'emp_start', 'emp_zip', 'full_time', 'id',
       'index', 'job', 'naics4', 'naics5', 'naics_full', 'org_cert_date',
       'payunit', 'pw', 'pw_payunit', 'row_id', 'soc_code', 'soc_name',
       'submit_date', 'tot_workers', 'violator', 'visa_class', 'wage',
       'wage_from', 'wage_to', 'work_cfips', 'work_city', 'work_cnty',
       'work_st', 'work_zip', 'year', 'DROP', 'test', 'emp_zip2', 'DROP2',
       'test2', 'test3', 'test4', 'DROP3', 'DROP4', 'zip2', 'county2', 'zip3',
       'county3', 'test5', 'test6', 'DROP5', 'DROP6', 'test7', 'test8',
       'DROP7', 'DROP8', 'zip10', 'county10', 'test10', 'final_drop'],
      dtype='object')

In [794]:
vvdatafull6 = vvdatafull6[['level_0', 'case_num', 'case_status', 'decision_date', 'dependent',
       'emp_address', 'emp_cfips', 'emp_city', 'emp_cntry', 'emp_end',
       'emp_name', 'emp_st', 'emp_start', 'emp_zip', 'full_time', 'id',
       'index', 'job', 'naics4', 'naics5', 'naics_full', 'org_cert_date',
       'payunit', 'pw', 'pw_payunit', 'row_id', 'soc_code', 'soc_name',
       'submit_date', 'tot_workers', 'violator', 'visa_class', 'wage',
       'wage_from', 'wage_to', 'work_cfips', 'work_city', 'work_cnty',
       'work_st', 'work_zip', 'year']]

In [796]:
vvdatafull6.dtypes

level_0                   int64
case_num                 object
case_status            category
decision_date    datetime64[ns]
dependent                object
emp_address              object
emp_cfips                object
emp_city                 object
emp_cntry                object
emp_end                  object
emp_name                 object
emp_st                   object
emp_start                object
emp_zip                  object
full_time                object
id                       object
index                     int64
job                      object
naics4                   object
naics5                   object
naics_full               object
org_cert_date    datetime64[ns]
payunit                category
pw                      float64
pw_payunit               object
row_id                   object
soc_code                 object
soc_name                 object
submit_date      datetime64[ns]
tot_workers             float64
violator                 object
visa_class             category
wage                    float64
wage_from               float64
wage_to                 float64
work_cfips               object
work_city                object
work_cnty                object
work_st                  object
work_zip                 object
year                   category
dtype: object

In [801]:
vvdatafull6['tot_workers'] = vvdatafull6['tot_workers'].fillna(0)
vvdatafull6['tot_workers'] = vvdatafull6['tot_workers'].astype('int')

In [806]:
vvdatafull6['emp_start'] = pd.to_datetime(vvdatafull6['emp_start'], dayfirst = True, errors='coerce')
vvdatafull6['emp_end'] = pd.to_datetime(vvdatafull6['emp_end'], dayfirst = True, errors='coerce')
vvdatafull6['org_cert_date'] = pd.to_datetime(vvdatafull6['org_cert_date'], dayfirst = True, errors='coerce')

#### duration calc of interest: 
1. time it took to get certified ('dec_dur'): decision duration
2. time before they withdrew ('to_withdraw')

In [811]:
#DURATION 
vvdatafull6.loc[((vvdatafull6['year'] != '15') & (vvdatafull6['case_status'] == 'CERTIFIED-WITHDRAWN')),'dec_dur'] = vvdatafull6['org_cert_date'] - vvdatafull6['submit_date']
vvdatafull6.loc[vvdatafull6['dec_dur'].isnull(), 'dec_dur'] = vvdatafull6['decision_date'] - vvdatafull6['submit_date']

In [808]:
vvdatafull6.columns

Index(['level_0', 'case_num', 'case_status', 'decision_date', 'dependent',
       'emp_address', 'emp_cfips', 'emp_city', 'emp_cntry', 'emp_end',
       'emp_name', 'emp_st', 'emp_start', 'emp_zip', 'full_time', 'id',
       'index', 'job', 'naics4', 'naics5', 'naics_full', 'org_cert_date',
       'payunit', 'pw', 'pw_payunit', 'row_id', 'soc_code', 'soc_name',
       'submit_date', 'tot_workers', 'violator', 'visa_class', 'wage',
       'wage_from', 'wage_to', 'work_cfips', 'work_city', 'work_cnty',
       'work_st', 'work_zip', 'year'],
      dtype='object')

In [812]:
#parking vvdatafull6 
vvvdata = vvdatafull6

#### Periodic Indexing: Quarterly and Monthly

In [813]:
### Quarterly Indexing ###
qtRange = pd.date_range('9/1/2014', '12/31/2017', freq='Q')

In [814]:
qtRange

DatetimeIndex(['2014-09-30', '2014-12-31', '2015-03-31', '2015-06-30',
               '2015-09-30', '2015-12-31', '2016-03-31', '2016-06-30',
               '2016-09-30', '2016-12-31', '2017-03-31', '2017-06-30',
               '2017-09-30', '2017-12-31'],
              dtype='datetime64[ns]', freq='Q-DEC')

In [815]:
qtLabels = ['2015Q1', '2015Q2', '2015Q3', '2015Q4', '2016Q1', '2016Q2', '2016Q3', '2016Q4','2017Q1', '2017Q2', '2017Q3', '2017Q4', '2018Q1']

In [821]:
len(qtRange) #14
len(qtLabels) #13

13

In [824]:
### Monthly Indexing ###
mtRange = pd.date_range('9/1/2014', '1/1/2018', freq='MS')

In [825]:
mtRange

DatetimeIndex(['2014-09-01', '2014-10-01', '2014-11-01', '2014-12-01',
               '2015-01-01', '2015-02-01', '2015-03-01', '2015-04-01',
               '2015-05-01', '2015-06-01', '2015-07-01', '2015-08-01',
               '2015-09-01', '2015-10-01', '2015-11-01', '2015-12-01',
               '2016-01-01', '2016-02-01', '2016-03-01', '2016-04-01',
               '2016-05-01', '2016-06-01', '2016-07-01', '2016-08-01',
               '2016-09-01', '2016-10-01', '2016-11-01', '2016-12-01',
               '2017-01-01', '2017-02-01', '2017-03-01', '2017-04-01',
               '2017-05-01', '2017-06-01', '2017-07-01', '2017-08-01',
               '2017-09-01', '2017-10-01', '2017-11-01', '2017-12-01',
               '2018-01-01'],
              dtype='datetime64[ns]', freq='MS')

In [826]:
mtLabels = ['14-Sep', '14-Oct', '14-Nov', '14-Dec', '15-Jan', '15-Feb', '15-Mar', '15-Apr',
           '15-May', '15-Jun', '15-Jul', '15-Aug', '15-Sep', '15-Oct', '15-Nov', '15-Dec',
           '16-Jan', '16-Feb', '16-Mar', '16-Apr', '16-May', '16-Jun', '16-Jul', '16-Aug',
           '16-Sep', '16-Oct', '16-Nov', '16-Dec', '17-Jan', '17-Feb', '17-Mar', '17-Apr',
           '17-May', '17-Jun', '17-Jul', '17-Aug', '17-Sep', '17-Oct', '17-Nov', '17-Dec']

In [828]:
len(mtRange) #41
#len(mtLabels) #40

41

In [829]:
vvvdata["quarter"] = pd.cut(vvvdata["decision_date"], qtRange, labels = qtLabels)
vvvdata["months"] = pd.cut(vvvdata["decision_date"], mtRange, labels = mtLabels)

In [831]:
vvvdata[['decision_date','quarter','months']]

        decision_date quarter  months
0          2015-02-05  2015Q2  15-Feb
2          2014-12-18  2015Q1  14-Dec
3          2014-12-15  2015Q1  14-Dec
4          2015-03-16  2015Q2  15-Mar
5          2014-12-23  2015Q1  14-Dec
6          2014-10-20  2015Q1  14-Oct
7          2014-12-23  2015Q1  14-Dec
8          2014-11-04  2015Q1  14-Nov
9          2015-03-30  2015Q2  15-Mar
12         2014-10-28  2015Q1  14-Oct
13         2015-01-29  2015Q2  15-Jan
14         2015-03-31  2015Q2  15-Mar
15         2014-10-28  2015Q1  14-Oct
16         2014-10-30  2015Q1  14-Oct
17         2014-11-04  2015Q1  14-Nov
18         2014-10-29  2015Q1  14-Oct
19         2014-12-29  2015Q1  14-Dec
20         2014-10-13  2015Q1  14-Oct
21         2014-10-13  2015Q1  14-Oct
22         2014-12-24  2015Q1  14-Dec
23         2015-07-27  2015Q4  15-Jul
24         2014-10-13  2015Q1  14-Oct
26         2015-01-19  2015Q2  15-Jan
27         2015-01-26  2015Q2  15-Jan
29         2015-02-22  2015Q2  15-Feb
30         2014-12-26  2015Q1  14-Dec
31         2015-01-07  2015Q2  15-Jan
32         2015-03-20  2015Q2  15-Mar
34         2015-03-11  2015Q2  15-Mar
35         2015-02-04  2015Q2  15-Feb
...               ...     ...     ...
2374531    2017-12-21  2018Q1  17-Dec
2374532    2017-12-22  2018Q1  17-Dec
2374533    2017-12-27  2018Q1  17-Dec
2374534    2017-12-22  2018Q1  17-Dec
2374535    2017-12-27  2018Q1  17-Dec
2374536    2017-12-22  2018Q1  17-Dec
2374537    2017-12-22  2018Q1  17-Dec
2374538    2017-12-19  2018Q1  17-Dec
2374539    2017-12-27  2018Q1  17-Dec
2374541    2017-12-19  2018Q1  17-Dec
2374542    2017-12-22  2018Q1  17-Dec
2374543    2017-12-22  2018Q1  17-Dec
2374544    2017-12-22  2018Q1  17-Dec
2374545    2017-12-22  2018Q1  17-Dec
2374546    2017-12-22  2018Q1  17-Dec
2374547    2017-12-22  2018Q1  17-Dec
2374548    2017-12-26  2018Q1  17-Dec
2374549    2017-12-22  2018Q1  17-Dec
2374550    2017-12-22  2018Q1  17-Dec
2374551    2017-12-22  2018Q1  17-Dec
2374552    2017-12-22  2018Q1  17-Dec
2374553    2017-12-27  2018Q1  17-Dec
2374554    2017-12-28  2018Q1  17-Dec
2374555    2017-12-21  2018Q1  17-Dec
2374556    2017-12-26  2018Q1  17-Dec
2374557    2017-12-20  2018Q1  17-Dec
2374558    2017-12-22  2018Q1  17-Dec
2374559    2017-12-27  2018Q1  17-Dec
2374560    2017-12-22  2018Q1  17-Dec
2374561    2017-12-27  2018Q1  17-Dec

[1945886 rows x 3 columns]

In [832]:
vdatafull.dtypes

index                                  int64
CASE_NUMBER                           object
CASE_STATUS                         category
CASE_SUBMITTED                datetime64[ns]
DECISION_DATE                 datetime64[ns]
VISA_CLASS                            object
EMPLOYMENT_START_DATE         datetime64[ns]
EMPLOYMENT_END_DATE           datetime64[ns]
EMPLOYER_NAME                         object
EMPLOYER_BUSINESS_DBA                 object
EMPLOYER_ADDRESS                      object
EMPLOYER_CITY                         object
EMPLOYER_STATE                        object
EMPLOYER_POSTAL_CODE                  object
EMPLOYER_COUNTRY                      object
EMPLOYER_PROVINCE                     object
JOB_TITLE                             object
SOC_CODE                              object
SOC_NAME                              object
NAICS_CODE                            object
TOTAL_WORKERS                          int64
NEW_EMPLOYMENT                         int64
CONTINUED_EMPLOYMENT                   int64
CHANGE_PREVIOUS_EMPLOYMENT             int64
NEW_CONCURRENT_EMPLOYMENT              int64
CHANGE_EMPLOYER                        int64
AMENDED_PETITION                       int64
FULL_TIME_POSITION                    object
PREVAILING_WAGE                      float64
PW_UNIT_OF_PAY                        object
PW_WAGE_LEVEL                         object
PW_SOURCE                             object
PW_SOURCE_YEAR                       float64
PW_SOURCE_OTHER                       object
WAGE_RATE_OF_PAY_FROM                float64
WAGE_RATE_OF_PAY_TO                  float64
WAGE_UNIT_OF_PAY                      object
H1B_DEPENDENT                         object
WILLFUL_VIOLATOR                      object
SUPPORT_H1B                           object
LABOR_CON_AGREE                       object
PUBLIC_DISCLOSURE_LOCATION           float64
WORKSITE_CITY                         object
WORKSITE_COUNTY                       object
WORKSITE_STATE                        object
WORKSITE_POSTAL_CODE                  object
ORIGINAL_CERT_DATE            datetime64[ns]
NAICS4                                object
PAYUNIT                             category
WAGE                                 float64
YEAR                                  object
ID                                    object
ROW_ID                                object
EMP_ZIP                               object
EMP_CNTY                              object
WORK_ZIP                              object
WORK_CNTY                             object
NAICS5                                object
dtype: object

In [227]:
#vvvdata.loc[(vvvdata['case_status'] =='DENIED'), 'RESULT'] = 'DENIED'
#vvvdata.loc[(vvvdata['case_status'] =='CERTIFIED'), 'RESULT'] = 'CERTIFIED'
#vvvdata.loc[(vvvdata['case_status'] =='CERTIFIED-WITHDRAWN'), 'RESULT'] = 'CERT-WITHD'
#vvvdata.loc[(vvvdata['case_status'] =='WITHDRAWN'), 'RESULT'] = 'WITHDRAWN'

### wage calc

In [834]:
vvvdata['payunit'].unique()

[Year, Hour, Month, Week, Bi-Weekly, NaN]
Categories (5, object): [Year, Hour, Month, Week, Bi-Weekly]

In [840]:
#normaling wages 
#visa17all['PW_UNIT_OF_PAY'].unique() 
# [Year, Hour, Month, NaN, Week, Bi-Weekly]
# hourly: x40 x52
# Month: x12
# Week: x52
# Bi-Weekly: x26
vvvdata.loc[(vvvdata['payunit'] =='Year'),'yr_sal'] = vvvdata['wage']
vvvdata.loc[(vvvdata['payunit'] =='Month'),'yr_sal'] = vvvdata['wage']*12
vvvdata.loc[(vvvdata['payunit'] =='Hour'),'yr_sal'] = vvvdata['wage']*40*52
vvvdata.loc[(vvvdata['payunit'] =='Week'),'yr_sal'] = vvvdata['wage']*52
vvvdata.loc[(vvvdata['payunit'] =='Bi-Weekly'),'yr_sal'] = vvvdata['wage']*26

In [835]:
vvvdata['pw_payunit'].unique()

array(['Year', 'Hour', 'Month', 'Week', nan, 'Bi-Weekly'], dtype=object)

In [838]:
#vvvdata.dtypes

In [841]:
vvvdata.loc[(vvvdata['pw_payunit'] =='Year'),'pw_sal'] = vvvdata['pw']
vvvdata.loc[(vvvdata['pw_payunit'] =='Month'),'pw_sal'] = vvvdata['pw']*12
vvvdata.loc[(vvvdata['pw_payunit'] =='Hour'),'pw_sal'] = vvvdata['pw']*40*52
vvvdata.loc[(vvvdata['pw_payunit'] =='Week'),'pw_sal'] = vvvdata['pw']*52
vvvdata.loc[(vvvdata['pw_payunit'] =='Bi-Weekly'),'pw_sal'] = vvvdata['pw']*26

In [844]:
vvvdata['yr_sal'] = vvvdata['yr_sal'].astype('float')
vvvdata['pw_sal'] = vvvdata['pw_sal'].astype('float')

In [847]:
vvvdata['wage'] = vvvdata['wage'].astype('float')
vvvdata['wage_from'] = vvvdata['wage_from'].astype('float')
vvvdata['wage_to'] = vvvdata['wage_to'].astype('float')

In [866]:
vvvdata = vvvdata[['level_0', 'case_num', 'case_status', 'decision_date', 'dependent',
       'emp_address', 'emp_cfips', 'emp_city', 'emp_cntry', 'emp_end',
       'emp_name', 'emp_st', 'emp_start', 'emp_zip', 'full_time', 'id',
       'index', 'job', 'naics4', 'naics5', 'naics_full', 'org_cert_date',
       'payunit', 'pw', 'pw_payunit', 'row_id', 'soc_code', 'soc_name',
       'submit_date', 'tot_workers', 'violator', 'visa_class', 'wage',
       'wage_from', 'wage_to', 'work_cfips', 'work_city', 'work_cnty',
       'work_st', 'work_zip', 'year', 'dec_dur', 'quarter', 'months', 'yr_sal',
       'pw_sal']]

In [872]:
vvvdata1 = vvvdata.copy()

In [875]:
vvvdata.head()

,level_0,case_num,case_status,decision_date,dependent,emp_address,emp_cfips,emp_city,emp_cntry,emp_end,emp_name,emp_st,emp_start,emp_zip,full_time,id,index,job,naics4,naics5,naics_full,org_cert_date,payunit,pw,pw_payunit,row_id,soc_code,soc_name,submit_date,tot_workers,violator,visa_class,wage,wage_from,wage_to,work_cfips,work_city,work_cnty,work_st,work_zip,year,dec_dur,quarter,months,yr_sal,pw_sal
0,0,I-200-09121-701936,WITHDRAWN,2015-02-05,N,710 MEDTRONIC PARKWAY NE,27003,MINNEAPOLIS,UNITED STATES OF AMERICA,2015-02-28,"MEDTRONIC, INC.",MN,2015-09-02,55432,Y,NaN,0,MECHANICAL ENGINEER,3345,33451,334510,NaT,Year,19000.0,Year,15-0,17-2141.00,MECHANICAL ENGINEERS,2015-02-05,1,N,H-1B,20000.0,20000.0,NaN,27053,EDEN PRAIRIE,STERNS,CA,55412,15,0 days,2015Q2,15-Feb,20000.0,19000.0
2,1,I-200-09146-796321,CERTIFIED,2014-12-18,N,905 ASP AVE,40027,NORMAN,UNITED STATES OF AMERICA,2018-04-01,UNIVERSITY OF OKLAHOMA,OK,2015-05-01,73019,Y,NaN,1,ASSISTANT PROFESSOR,6113,61131,611310,NaT,Year,42860.0,Year,15-1,25-1032,"ENGINEERING TEACHERS, POSTSECONDARY",2014-12-12,1,N,H-1B,85000.0,85000.0,NaN,40027,NORMAN,CLEVELAND,OK,73019,15,6 days,2015Q1,14-Dec,85000.0,42860.0
3,2,I-200-09180-329758,WITHDRAWN,2014-12-15,N,6021 CONNECTION DRIVE,48113,IRVING,UNITED STATES OF AMERICA,2016-06-01,NOKIA INC.,TX,2013-07-01,75039,Y,NaN,2,RELEASE AND SOFTWARE TEST MANAGER,5172,51721,517212,NaT,Year,73965.0,Year,15-2,15-1799,"COMPUTER OCCUPATIONS, ALL OTHER*",2013-01-03,1,N,H-1B,94000.0,94000.0,NaN,06073,SAN DIEGO,SAN DIEGO,CA,92127,15,711 days,2015Q1,14-Dec,94000.0,73965.0
4,3,I-200-09183-259985,CERTIFIED,2015-03-16,N,9510 N. HOUSTON ROSSLYN ROAD,48201,HOUSTON,UNITED STATES OF AMERICA,2018-07-09,"OMRON OILFIELD AND MARINE, INC.",TX,2015-07-09,77088,Y,NaN,3,CONTROL ENGINEERING SPECIALIST,3353,33531,335314,NaT,Year,65998.0,Year,15-3,17-2072,"ELECTRONICS ENGINEERS, EXCEPT COMPUTER",2015-03-10,2,N,H-1B,68000.0,66000.0,70000.0,48201,HOUSTON,HARRIS,TX,77088,15,6 days,2015Q2,15-Mar,68000.0,65998.0
5,4,I-200-09189-800933,CERTIFIED,2014-12-23,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,2018-05-06,FEDERAL HOME LOAN MORTGAGE CO.,VA,2015-06-06,22102,Y,NaN,4,DEVELOPMENT SENIOR,5222,52229,522294,NaT,Year,96907.0,Year,15-4,15-1131,COMPUTER PROGRAMMERS,2014-12-17,1,N,H-1B,120150.0,97000.0,143300.0,51059,MCLEAN,FAIRFAX,VA,22102,15,6 days,2015Q1,14-Dec,120150.0,96907.0

In [881]:
len(vvvdata)

1945886

In [893]:
## comparing worksite vs hq location
vvvdata.loc[(vvvdata['emp_st'] == vvvdata['work_st']),'sameState'] = True
vvvdata.loc[(vvvdata['emp_st'] != vvvdata['work_st']),'sameState'] = False

In [894]:
vvvdata.loc[(vvvdata['emp_cfips'] == vvvdata['work_cfips']),'sameCounty'] = True
vvvdata.loc[(vvvdata['emp_cfips'] != vvvdata['work_cfips']),'sameCounty'] = False

In [895]:
vvvdata[vvvdata['sameState']]

,level_0,case_num,case_status,decision_date,dependent,emp_address,emp_cfips,emp_city,emp_cntry,emp_end,emp_name,emp_st,emp_start,emp_zip,full_time,id,index,job,naics4,naics5,naics_full,org_cert_date,payunit,pw,pw_payunit,row_id,soc_code,soc_name,submit_date,tot_workers,violator,visa_class,wage,wage_from,wage_to,work_cfips,work_city,work_cnty,work_st,work_zip,year,dec_dur,quarter,months,yr_sal,pw_sal,sameState,sameCounty
2,1,I-200-09146-796321,CERTIFIED,2014-12-18,N,905 ASP AVE,40027,NORMAN,UNITED STATES OF AMERICA,2018-04-01,UNIVERSITY OF OKLAHOMA,OK,2015-05-01,73019,Y,NaN,1,ASSISTANT PROFESSOR,6113,61131,611310,NaT,Year,42860,Year,15-1,25-1032,"ENGINEERING TEACHERS, POSTSECONDARY",2014-12-12,1,N,H-1B,85000,85000,NaN,40027,NORMAN,CLEVELAND,OK,73019,15,6 days,2015Q1,14-Dec,85000,42860,True,True
4,3,I-200-09183-259985,CERTIFIED,2015-03-16,N,9510 N. HOUSTON ROSSLYN ROAD,48201,HOUSTON,UNITED STATES OF AMERICA,2018-07-09,"OMRON OILFIELD AND MARINE, INC.",TX,2015-07-09,77088,Y,NaN,3,CONTROL ENGINEERING SPECIALIST,3353,33531,335314,NaT,Year,65998,Year,15-3,17-2072,"ELECTRONICS ENGINEERS, EXCEPT COMPUTER",2015-03-10,2,N,H-1B,68000,66000,70000,48201,HOUSTON,HARRIS,TX,77088,15,6 days,2015Q2,15-Mar,68000,65998,True,True
5,4,I-200-09189-800933,CERTIFIED,2014-12-23,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,2018-05-06,FEDERAL HOME LOAN MORTGAGE CO.,VA,2015-06-06,22102,Y,NaN,4,DEVELOPMENT SENIOR,5222,52229,522294,NaT,Year,96907,Year,15-4,15-1131,COMPUTER PROGRAMMERS,2014-12-17,1,N,H-1B,120150,97000,143300,51059,MCLEAN,FAIRFAX,VA,22102,15,6 days,2015Q1,14-Dec,120150,96907,True,True
6,6,I-200-09212-834534,CERTIFIED,2014-10-20,N,3401 HILLVIEW AVE,06085,PALO ALTO,UNITED STATES OF AMERICA,2017-02-11,"VMWARE, INC.",CA,2014-03-11,94304,Y,NaN,6,STAFF ENGINEER,5415,54151,541511,NaT,Year,133976,Year,15-6,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-10-14,1,N,H-1B,155000,155000,NaN,06085,PALO ALTO,SANTA CLARA,CA,94304,15,6 days,2015Q1,14-Oct,155000,133976,True,True
7,7,I-200-09232-212049,CERTIFIED,2014-12-23,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,2018-06-13,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,2015-06-14,22102,Y,NaN,7,CREDIT GUARANTEE ANALYTICS SENIOR,5222,52229,522294,NaT,Year,64085,Year,15-7,15-2031,OPERATIONS RESEARCH ANALYSTS,2014-12-17,1,N,H-1B,95550,64100,127000,51059,MCLEAN,FAIRFAX,VA,22102,15,6 days,2015Q1,14-Dec,95550,64085,True,True
8,8,I-200-09233-732656,CERTIFIED,2014-11-04,N,3401 HILLVIEW AVE,06085,PALO ALTO,UNITED STATES OF AMERICA,2017-11-16,"VMWARE, INC.",CA,2014-11-17,94304,Y,NaN,8,PROGRAMMER/ANALYST - SENIOR APPLICATIONS DEVEL...,5415,54151,541511,NaT,Year,101900,Year,15-8,15-1121,COMPUTER SYSTEMS ANALYSTS,2014-10-29,1,N,H-1B,125000,125000,NaN,06085,PALO ALTO,SANTA CLARA,CA,94304,15,6 days,2015Q1,14-Nov,125000,101900,True,True
9,9,I-200-09238-535119,DENIED,2015-03-30,N,65 CRESTRIDGE DRIVE,13135,SUWANEE,UNITED STATES OF AMERICA,2018-09-17,IMAEX TRADING COMPANY,GA,2015-09-17,30024,N,NaN,9,COST ACCOUNTANT,4244,42446,424460,NaT,Hour,22,Hour,15-9,13-2011,ACCOUNTANTS AND AUDITORS,2015-03-19,1,N,H-1B,22,22,NaN,13135,SUWANEE,FORSYTH,GA,30024,15,11 days,2015Q2,15-Mar,46717,46717,True,True
12,12,I-200-09244-289740,CERTIFIED,2014-10-28,N,3401 HILLVIEW AVE,06085,PALO ALTO,UNITED STATES OF AMERICA,2018-04-22,"VMWARE, INC.",CA,2015-04-23,94304,Y,NaN,10,MEMBER OF TECHNICAL STAFF - SOFTWARE ENGINEERING,5415,54151,541511,NaT,Year,98557,Year,15-10,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-10-22,1,N,H-1B,122430,122430,NaN,06085,PALO ALTO,SANTA CLARA,CA,94304,15,6 days,2015Q1,14-Oct,122430,98557,True,True
15,15,I-200-09274-925070,CERTIFIED,2014-10-28,N,3401 HILLVIEW AVE,06085,PALO ALTO,UNITED STATES OF AMERICA,2017-09-11,"VMWARE, INC.",CA,2014-10-11,94304,Y,NaN,13,SENIOR MEMBER OF TECHNICAL STAFF - QUALITY ENG...,5415,54151,541511,NaT,Year,111742,Year,15-13,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2014-10-22,1,N,H-1B,140000,140000,NaN,06085,PALO ALTO,SANTA CLARA,CA,94304,15,6 days,2015Q1,14-Oct,140000,111742,True,True
17,18,I-200-09296-661220,CERTIFIED,2014-11-04,N,3401 HILLVIEW AVE,06085,PALO ALTO,UNITED STATES OF AMERICA,2018-02-02,"VMWARE, INC.",CA,2015-03-02,94304,Y,NaN,15,SENIOR MEMBER OF TECHNICAL STAFF - SOFTWARE EN...,5415,54151,541511,NaT,Year,113775,Year,15-15,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-10-29,1,N,H-1B,140000,140000,NaN,06085,PALO ALTO,SANTA CLARA,CA,94304,15,6 days,2015Q1,14-Nov,140000,113775,True,True
19,21,I-200-09313-334737,CERTIFIED,2014-12-29,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,2018-06-15,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,2015-06-16,22102,Y,NaN,17,SYSTEMS ANALYSIS SENIOR,5222,52229,522294,NaT,Year,75200,Year,15-17,15-1121,COMPUTER SYSTEMS ANALYSTS,2014-12-19,1,N,H-1B,103850,75200,132500,51059,RESTON,FAIRFAX,VA,20190,15,10 days,2015Q1,14-Dec,103850,75200,True,True
20,22,I-200-09316-752823,WITHDRAWN,2014-10-13,N,1510 WEST LOOP SOUTH,48201,HOUSTON,UNITED STATES OF AMERICA,2017-12-10,"LANDRY'S RESTAURANTS, INC.",TX,2014-10-13,77027,Y,NaN,18,GENERAL MANAGER,7221,72211,722110,NaT,Year,89569,Year,15-18,11-9051.00,FOOD SERVICE MANAGERS,2014-10-13,1,N,H-1B,136700,109360,164040,48201,HOUSTON,HARRIS,TX,77027,15,0 days,2015Q1,14-Oct,136700,89569,True,True
22,24,I-200-09321-731590,CERTIFIED,2014-12-24,N,100 WEST WALNUT STREET,06037,PASADENA,UNITED STATES OF AMERICA,2018-11-01,PARSONS SERVICES COMPANY,CA,2015-12-01,91124,Y,NaN,20,SENIOR IT SPECIALIST,5511,55111,551114,NaT,Year,108472,Year,15-20,15-1141,DATABASE ADMINISTRATORS,2014-12-18,1,N,H-1B,127500,110000,145000,06037,PAASADENA,LOS ANGELES,CA,91124,15,6 days,2015Q1,14-Dec,127500,108472,True,True
24,26,I-200-09334-392690,WITHDRAWN,2014-10-13,N,3333 S. BANNOCK STREET,08031,ENGLEWOOD,UNITED STATES OF AMERICA,2017-12-10,DAIRY INFORMATION SYSTEMS HOLDINGS LLC,CO,2014-10-13,80110,Y,NaN,22,APPLICATIONS PROGRAMMING MANAGER,5112,51121,511210,NaT,Year,94411,Year,15-22,15-1051.00,COMPUTER SYSTEMS ANALYSTS,2014-10-13,1,N,H-1B,107872,107872,NaN,08031,ENGLEWOOD,ARAPAHOE,CO,80110,15,0 days,2015Q1,14-Oct,107872,94411,True,True
26,28,I-200-09338-814236,CERTIFIED-WITHDRAWN,2015-01-19,Y,"4 ETHEL RD, SUITE 403B",34023,EDISON,UNITED STATES OF AMERICA,2015-09-21,"INTEGRATED RESOURCES, INC",NJ,2013-02-21,08817,Y,NaN,23,OCCUPATIONAL THERAPISTS,5613,56132,561320,NaT,Hour,33,Hour,15-23,29-1122,OCCUPATIONAL THERAPISTS,2013-02-21,1,N,H-1B,35,35,NaN,34011,VINELAND,CUMBERLAND,NJ,08362,15,697 days,2015Q2,15-Jan,72800,68578,True,False
27,29,I-200-09341-564186,CERTIFIED-WITHDRAWN,2015-01-26,Y,205 HOUSE AVENUE SUITE#103,42041,CAMP HILL,UNITED STATES OF AMERICA,2016-06-19,"XPERT TECHNOLOGIES, INC.",PA,2013-06-19,17011,Y,NaN,24,QUALITY ASSURANCE ANALYST,5415,54151,541511,NaT,Year,58282,Year,15-24,15-1799,"COMPUTER OCCUPATIONS, ALL OTHER*",2013-06-17,1,N,H-1B,60000,60000,NaN,42041,CAMP HILL,CUMBERLAND,PA,17011,15,588 days,2015Q2,15-Jan,60000,58282,True,True
30,32,I-200-09362-088372,CERTIFIED,2014-12-26,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,2018-06-17,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,2015-06-18,22102,Y,NaN,26,CREDIT GUARANTEE ANALYTICS SENIOR,5222,52229,522294,NaT,Year,64085,Year,15-26,15-2031,OPERATIONS RESEARCH ANALYSTS,2014-12-19,1,N,H-1B,95550,64100,127000,51059,MCLEAN,FAIRFAX,VA,22102,15,7 days,2015Q1,14-Dec,95550,64085,True,True
31,33,I-200-09362-500914,CERTIFIED,2015-01-07,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,2018-06-27,FEDERAL HOME LOAN MORTGAGE CORPORATION,VA,2015-06-28,22102,Y,NaN,27,SHARED INFORMATION SUPPORT SENIOR,5222,52229,522294,NaT,Year,90800,Year,15-27,15-1141,DATABASE ADMINISTRATORS,2014-12-30,1,N,H-1B,105550,90800,120300,51059,MCLEAN,FAIRFAX,VA,22102,15,8 days,2015Q2,15-Jan,105550,90800,True,True
32,34,I-200-09364-425868,CERTIFIED,2015-03-20,N,7 PULASKI STREET,36067,AUBURN,UNITED STATES OF AMERICA,2018-09-15,MAGIC CIRCLE FILMS INTERNATIONAL LLC,NY,2015-09-15,13021,Y,NaN,28,VIDEO EDITOR,5121,51219,51219,NaT,Year,39333,Year,15-28,27-4032,FILM AND VIDEO EDITORS,2015-03-16,1,N,H-1B,50003,50003,NaN,36067,AUBURN,CAYUGA,NY,13021,15,4 days,2015Q2,15-Mar,50003,39333,True,True
37,38,I-200-10028-460244,CERTIFIED,2015-03-04,Y,"631 E. BIG BEAVER, SUITE 109",26125,TROY,UNITED STATES OF AMERICA,2018-08-26,"SUNERA TECHNOLOGIES, INC",MI,2015-08-27,48083,Y,NaN,31,PROGRAMMER ANALYST,5415,5415,5415,NaT,Year,61901,Year,15-31,15-1131,COMPUTER PROGRAMMERS,2015-02-26,1,N,H-1B,65000,65000,NaN,26125,TROY,OAKLAND,MI,48083,15,6 days,2015Q2,15-Mar,65000,61901,True,True
42,44,I-200-10041-053406,WITHDRAWN,2014-10-13,N,"15840 FM 529, SUITE 211",48201,HOUSTON,UNITED STATES OF AMERICA,2017-12-10,"H & H RESOURCES, INC.",TX,2014-10-13,77095,Y,NaN,36,GRADUATE ENGINEER,5413,54133,541330,NaT,Year,52865,Year,15-36,17-2051.00,CIVIL ENGINEERS,2014-10-13,1,N,H-1B,54080,54080,NaN,48157,SUGAR LAND,FORT BEND,TX,77478,15,0 days,2015Q1,14-Oct,54080,52865,True,False
44,46,I-200-10053-213884,CERTIFIED,2015-03-18,N,510 S. UNIVERSITY AVE.,17077,CARBONDALE,UNITED STATES OF AMERICA,2018-08-09,LIANG LLC,IL,2015-09-09,62901,N,NaN,38,FINANCIAL ANALYST,5239,52399,523999,NaT,Hour,24,Hour,15-38,13-2051,FINANCIAL ANALYSTS,2015-03-12,1,N,H-1B,25,25,NaN,17077,CARBONDALE,JACKSON,IL,62901,15,6 days,2015Q2,15-Mar,52000,49109,True,True
46,48,I-200-10068-389593,CERTIFIED,2015-02-04,N,2527 CAMINO RAMON,06013,SAN RAMON,UNITED STATES OF AMERICA,2018-09-02,BANK OF THE WEST,CA,2015-09-02,94583,Y,NaN,39,JAVA DEVELOPER,5221,52219,522190,NaT,Year,84781,Year,15-39,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2015-01-29,1,N,H-1B,95000,95000,NaN,06037,MONTEREY PARK,LOS ANGELES,CA,91755,15,6 days,2015Q2,15-Feb,95000,84781,True,False
47,49,I-200-10070-200317,CERTIFIED,2015-03-24,N,9913 GRALYN RD.,37183,RALEIGH,UNITED STATES OF AMERICA,2018-08-30,"CONSULTWEBS.COM, INC.",NC,2015-08-31,27613,Y,NaN,40,VICE PRESIDENT (PROGRAMMING),5416,54161,541613,NaT,Year,67371,Year,15-40,15-1131,COMPUTER PROGRAMMERS,2015-03-18,1,N,H-1B,135000,135000,NaN,37183,RALEIGH,WAKE,NC,27615,15,6 days,2015Q2,15-Mar,135000,67371,True,True
50,51,I-200-10075-818637,CERTIFIED,2014-10-14,N,3401 HILLVIEW AVE,06085,PALO ALTO,UNITED STATES OF AMERICA,2017-10-26,"VMWARE, INC.",CA,2014-10-27,94304,Y,NaN,42,SENIOR MEMBER OF TECHNICAL STAFF - SOFTWARE EN...,5415,54151,541511,NaT,Year,113775,Year,15-42,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-10-07,1,N,H-1B,132500,132500,NaN,06085,PALO ALTO,SANTA CLARA,CA,94304,15,7 days,2015Q1,14-Oct,132500,113775,True,True
52,53,I-200-10076-701665,CERTIFIED,2014-10-14,N,3401 HILLVIEW AVE,06085,PALO ALTO,UNITED STATES OF AMERICA,2017-10-26,"VMWARE, INC.",CA,2014-10-27,94304,Y,NaN,44,MEMBER OF TECHNICAL STAFF - SOFTWARE ENGINEERING,5415,54151,541511,NaT,Year,98557,Year,15-44,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-10-07,1,N,H-1B,112250,112250,NaN,06085,PALO ALTO,SANTA CLARA,CA,94304,15,7 days,2015Q1,14-Oct,112250,98557,True,True
53,54,I-200-10083-675557,CERTIFIED-WITHDRAWN,2015-01-13,N,"WASHINGTON STATE UNIV., INT'L PROGS-GLOBAL SER...",53075,PULLMAN,UNITED STATES OF AMERICA,2016-02-17,WASHINGTON STATE UNIVERSITY,WA,2013-02-18,99164,Y,NaN,45,TECHNICAL TRANSFER SPECIALIST,6113,61131,611310,NaT,Year,39166,Year,15-45,19-1029,"BIOLOGICAL SCIENTISTS, ALL OTHER",2013-01-22,1,N,H-1B,45000,45000,NaN,53077,PROSSER,BENTON,WA,99350,15,721 days,2015Q2,15-Jan,45000,39166,True,False
54,57,I-200-10088-558626,CERTIFIED-WITHDRAWN,2014-12-02,N,1200 E. CALIFORNIA BLVD,06037,PASADENA,UNITED STATES OF AMERICA,2015-07-18,CALIFORNIA INSTITUTE OF TECHNOLOGY,CA,2012-07-19,91125,Y,NaN,46,RESEARCHER,6113,61131,611310,NaT,Year,47320,Year,15-46,15-2021,MATHEMATICIANS,2012-02-24,1,N,H-1B,62000,62000,NaN,06037,PASADENA,LOS ANGELES,CA,91125,15,1012 days,2015Q1,14-Dec,62000,47320,True,True
55,58,I-200-10097-538466,CERTIFIED,2015-06-18,N,HUMAN RESOURCE SERVICES,48141,EL PASO,UNITED STATES OF AMERICA,2018-06-30,UNIVERSITY OF TEXAS AT EL PASO,TX,2015-01-07,79968,Y,NaN,47,PROGRAM COORDINATOR,6113,61131,611310,NaT,Year,33987,Year,15-47,27-3031,PUBLIC RELATIONS SPECIALISTS,2015-06-12,1,N,H-1B,33987,33987,NaN,48141,EL PASO,EL PASO,TX,79968,15,6 days,2015Q3,15-Jun,33987,33987,True,True
59,61,I-200-10111-541256,WITHDRAWN,2014-10-13,N,1669 WORLD TRADE CENTER LOOP,48479,LAREDO,UNITED STATES OF AMERICA,2017-12-10,THE VALDEN GROUP,TX,2014-10-13,78045,Y,NaN,50,TRADE ANALYST/ECONOMIST,4885,4885,4885,NaT,Year,45739,Year,15-50,19-3011.00,ECONOMISTS,2014-10-13,1,N,H-1B,50000,50000,NaN,48479,LAREDO,WEBB,TX,78045,15,0 days,2015Q1,14-Oct,50000,45739,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2374468,110972,I-203-17345-552252,CERTIFIED,2017-12-15,NaN,4260 EL CAMINO REAL,06085,PALO ALTO,UNITED STATES OF AMERICA,2020-06-09,FOODCOMM INTERNATIONAL,CA,2018-06-10,94306,Y,94541,94541,COO,4244,42447,424470,NaT,Year,201302,Year,18-94541,11-3131,TRAINING AND DEVELOPMENT MANAGERS,2017-12-11,1,NaN,E-3 Australian,175000,350000,0,06085,PALO ALTO,SANTA CLARA,CA,94306,18,4 days,2018Q1,17-Dec,175000,201302,True,True
2374470,110976,I-200-17345-694062,CERTIFIED,2017-12-21,N,4001 OFFICE COURT DRIVE,35049,SANTA FE,UNITED STATES OF AMERICA,2021-01-01,"NEW MEXICO INTERACTIVE, LLC",NM,2018-01-02,87507,Y,94543,94543,SOFTWARE DEVELOPER,5415,54151,541511,NaT,Year,84302,Year,18-94543,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-12-17,1,N,H-1B,44000,88000,0,35049,SANTA FE,SANTA FE,NM,87507,18,4 days,2018Q1,17-Dec,44000,84302,True,True
2374471,110977,I-200-17345-321555,CERTIFIED,2017-12-15,Y,6627 DUMBARTON CIRCLE,06001,FREMONT,UNITED STATES OF AMERICA,2021-05-01,ETOUCH SYSTEMS CORPORATION,CA,2018-05-02,94555,Y,94544,94544,SOFTWARE TEST ENGINEER,5415,54151,541511,NaT,Year,75941,Year,18-94544,15-1131,COMPUTER PROGRAMMERS,2017-12-11,1,N,H-1B,47500,95000,0,06085,MOUNTAIN VIEW,SANTA CLARA,CA,94043,18,4 days,2018Q1,17-Dec,47500,75941,True,False
2374474,110979,I-203-17345-661091,CERTIFIED,2017-12-18,NaN,160 W. SANTA CLARA ST.,06085,SAN JOSE,UNITED STATES OF AMERICA,2019-12-13,"THREATMETRIX, INC.",CA,2017-12-14,95113,Y,94546,94546,"DIRECTOR OF MOBILE, MALWARE AND FRONT-END PROD...",5415,54151,541519,NaT,Year,195270,Year,18-94546,11-3021,COMPUTER AND INFORMATION SYSTEMS MANAGERS,2017-12-12,1,NaN,E-3 Australian,110000,220000,0,06085,SAN JOSE,SANTA CLARA,CA,95113,18,6 days,2018Q1,17-Dec,110000,195270,True,True
2374475,110980,I-200-17345-411382,CERTIFIED,2017-12-18,N,333 LAKESIDE DRIVE,06081,FOSTER CITY,UNITED STATES OF AMERICA,2021-03-31,"GILEAD SCIENCES, INC.",CA,2018-04-01,94404,Y,94547,94547,"MANAGER, PHARMACEUTICAL ENGINEERING",5417,54171,541710,NaT,Year,131318,Year,18-94547,11-9121,NATURAL SCIENCES MANAGERS,2017-12-12,25,N,H-1B,65659,131318,0,06081,FOSTER CITY,SAN MATEO,CA,94404,18,6 days,2018Q1,17-Dec,65659,131318,True,True
2374476,110981,I-203-17345-696381,CERTIFIED,2017-12-15,NaN,"517 ROUTE 1 SOUTH, SUITE 1193",34023,ISELIN,UNITED STATES OF AMERICA,2020-02-22,PRIAMBA SOFT LLC,NJ,2018-02-23,08830,Y,94548,94548,SYSTEMS ENGINEER,5415,54151,541511,NaT,Hour,42,Hour,18-94548,15-1121,COMPUTER SYSTEMS ANALYSTS,2017-12-11,1,NaN,E-3 Australian,21,42,0,34023,ISELIN,NJ,NJ,08830,18,4 days,2018Q1,17-Dec,43326,86653,True,True
2374483,110987,I-200-17354-032764,CERTIFIED,2017-12-27,N,301 MEMORIAL MEDICAL PARKWAY,12127,DAYTONA BEACH,UNITED STATES OF AMERICA,2020-12-28,"MEMORIAL HEALTH SYSTEMS, INC.",FL,2017-12-28,32117,Y,94553,94553,MEDICAL TECHNOLOGIST,6221,62211,622110,NaT,Hour,24,Hour,18-94553,29-2011,MEDICAL AND CLINICAL LABORATORY TECHNOLOGISTS,2017-12-20,1,N,H-1B,12,25,0,12127,DAYTONA BEACH,VOLUSIA,FL,32117,18,7 days,2018Q1,17-Dec,25636,50773,True,True
2374510,111013,I-200-17356-273316,CERTIFIED,2017-12-29,N,750 LEXINGTON AVE.,36061,NEW YORK,UNITED STATES OF AMERICA,2020-01-01,"STEMLINE THERAPEUTICS, INC.",NY,2018-01-01,10022,Y,94575,94575,CLINICAL PROJECT MANAGER,5417,54171,541710,NaT,Year,124600,Year,18-94575,11-9121,NATURAL SCIENCES MANAGERS,2017-12-22,1,N,H-1B,62500,125000,0,36061,NEW YORK,NEW YORK,NY,10022,18,7 days,2018Q1,17-Dec,62500,124600,True,True
2374513,111018,I-200-17356-901918,CERTIFIED,2017-12-29,N,832 SANSOME STREET,06075,SAN FRANCISCO,UNITED STATES OF AMERICA,2021-01-02,"RENTLEVER, INC.",CA,2018-01-02,94111,Y,94578,94578,SENIOR SOFTWARE ENGINEER,5313,53131,531311,NaT,Year,142168,Year,18-94578,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-12-24,1,N,H-1B,75000,150000,0,06075,SAN FRANCISCO,SAN FRANCISCO,CA,94111,18,5 days,2018Q1,17-Dec,75000,142168,True,True
2374514,111019,I-200-17356-184290,CERTIFIED,2017-12-29,N,14507 FRONTIER ROAD,31055,OMAHA,UNITED STATES OF AMERICA,2021-01-05,"WERNER ENTERPRISES, INC.",NE,2018-01-05,68138,Y,94579,94579,APPLICATION ARCHITECT I,4841,48412,484121,NaT,Year,90626,Year,18-94579,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2017-12-22,1,N,H-1B,54980,109960,0,31055,OMAHA,DOUGLAS,NE,68138,18,7 days,2018Q1,17-Dec,54980,90626,True,True
2374518,111023,I-200-17356-320675,CERTIFIED,2017-12-29,Y,1825 W. WALNUT HILL LN.,48113,IRVING,UNITED STATES OF AMERICA,2021-01-02,ADALITEK GROUP LLC,TX,2018-01-03,75038,Y,94582,94582,SOFTWARE DEVELOPER,5415,54151,541511,NaT,Year,90646,Year,18-94582,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-12-22,1,N,H-1B,45500,91000,0,48113,IRVING,DALLAS,TX,75038,18,7 days,2018Q1,17-Dec,45500,90646,True,True
2374520,111025,I-200-17352-382313,CERTIFIED,2017-12-29,N,601 CONGRESS STREET,25025,BOSTON,UNITED STATES OF AMERICA,2021-05-31,JOHN HANCOCK LIFE INSURANCE COMPANY (USA),MA,2018-06-01,02210,Y,94584,94584,"PROJECT DIRECTOR, CYBER SECURITY",5241,52411,524113,NaT,Year,113256,Year,18-94584,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2017-12-22,1,N,H-1B,66938,133875,0,25025,BOSTON,SUFFOLK,MA,02116,18,7 days,2018Q1,17-Dec,66938,113256,True,True
2374522,111027,I-200-17352-973965,CERTIFIED,2017-12-27,N,200 OLD TAPPAN ROAD,34003,OLD TAPPAN,UNITED STATES OF AMERICA,2021-01-01,"PEARSON EDUCATION, INC.",NJ,2018-01-02,07675,Y,94586,94586,SR. PROGRAM MANAGER,5111,51113,511130,NaT,Year,106954,Year,18-94586,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2017-12-20,1,N,H-1B,123477,106954,140000,34017,HOBOKEN,HUDSON,NJ,07030,18,7 days,2018Q1,17-Dec,123477,106954,True,False
2374524,111029,I-200-17352-401620,CERTIFIED,2017-12-22,N,1199 PRINCE AVENUE,13221,ATHENS,UNITED STATES OF AMERICA,2020-06-30,"PIEDMONT ATHENS REGIONAL MEDICAL CENTER, INC.",GA,2018-06-17,30660,Y,94588,94588,RESIDENT PHYSICIAN,6221,62211,622110,NaT,Year,51148,Year,18-94588,29-1069,"PHYSICIANS AND SURGEONS, ALL OTHER",2017-12-18,1,N,H-1B,25755,51510,0,13059,ATHENS,CLARKE COUNTY,GA,30606,18,4 days,2018Q1,17-Dec,25755,51148,True,False
2374532,111035,I-200-17352-840416,CERTIFIED,2017-12-22,N,30 NORTH JEFFERSON ROAD,34027,WHIPPANY,UNITED STATES OF AMERICA,2021-04-08,"HALO PHARMACEUTICAL, INC.",NJ,2018-04-09,07981,Y,94592,94592,"VICE PRESIDENT, SCIENTIFIC AFFAIRS",3254,32541,325411,NaT,Year,206253,Year,18-94592,11-9121,NATURAL SCIENCES MANAGERS,2017-12-18,1,N,H-1B,119738,239476,0,34027,WHIPPANY,MORRIS,NJ,07981,18,4 days,2018Q1,17-Dec,119738,206253,True,True
2374533,111036,I-200-17352-535494,CERTIFIED,2017-12-27,N,600 ROE AVE.,36015,ELMIRA,UNITED STATES OF AMERICA,2021-04-19,ARNOT OGDEN MEDICAL CENTER,NY,2018-04-20,14905,Y,94593,94593,SENIOR INTEGRATION AND DATABASE ANALYST,6221,62211,622110,NaT,Year,80122,Year,18-94593,15-2031,OPERATIONS RESEARCH ANALYSTS,2017-12-20,1,N,H-1B,42006,84011,0,36015,ELMIRA,CHEMUNG,NY,14905,18,7 days,2018Q1,17-Dec,42006,80122,True,True
2374534,111037,I-200-17352-116774,CERTIFIED,2017-12-22,N,120 NORTH ROBERTSON BLVD.,06037,LOS ANGELES,UNITED STATES OF AMERICA,2021-06-14,DECURION MANAGEMENT COMPANY,CA,2018-06-15,90048,Y,94594,94594,ETL (EXACT TRANSFER LOAD) SPECIALIST,5415,54151,541519,NaT,Year,117229,Year,18-94594,15-1133,"SOFTWARE DEVELOPERS, SYSTEMS SOFTWARE",2017-12-18,1,N,H-1B,64750,129500,0,06037,LOS ANGELES,LOS ANGELES,CA,90048,18,4 days,2018Q1,17-Dec,64750,117229,True,True

In [897]:
100*len(vvvdata[vvvdata['sameState']])/len(vvvdata)

53.69739028905085

In [899]:
100*len(vvvdata[vvvdata['sameCounty']])/len(vvvdata[vvvdata['sameState']])

84.89620917034328

In [900]:
vvvdata[vvvdata['sameState'] == False]

,level_0,case_num,case_status,decision_date,dependent,emp_address,emp_cfips,emp_city,emp_cntry,emp_end,emp_name,emp_st,emp_start,emp_zip,full_time,id,index,job,naics4,naics5,naics_full,org_cert_date,payunit,pw,pw_payunit,row_id,soc_code,soc_name,submit_date,tot_workers,violator,visa_class,wage,wage_from,wage_to,work_cfips,work_city,work_cnty,work_st,work_zip,year,dec_dur,quarter,months,yr_sal,pw_sal,sameState,sameCounty
0,0,I-200-09121-701936,WITHDRAWN,2015-02-05,N,710 MEDTRONIC PARKWAY NE,27003,MINNEAPOLIS,UNITED STATES OF AMERICA,2015-02-28,"MEDTRONIC, INC.",MN,2015-09-02,55432,Y,NaN,0,MECHANICAL ENGINEER,3345,33451,334510,NaT,Year,19000,Year,15-0,17-2141.00,MECHANICAL ENGINEERS,2015-02-05,1,N,H-1B,20000,20000,NaN,27053,EDEN PRAIRIE,STERNS,CA,55412,15,0 days,2015Q2,15-Feb,20000,19000,False,False
3,2,I-200-09180-329758,WITHDRAWN,2014-12-15,N,6021 CONNECTION DRIVE,48113,IRVING,UNITED STATES OF AMERICA,2016-06-01,NOKIA INC.,TX,2013-07-01,75039,Y,NaN,2,RELEASE AND SOFTWARE TEST MANAGER,5172,51721,517212,NaT,Year,73965,Year,15-2,15-1799,"COMPUTER OCCUPATIONS, ALL OTHER*",2013-01-03,1,N,H-1B,94000,94000,NaN,06073,SAN DIEGO,SAN DIEGO,CA,92127,15,711 days,2015Q1,14-Dec,94000,73965,False,False
13,13,I-200-09258-461335,DENIED,2015-01-29,N,21 WEST SUPERIOR STREET,27137,DULUTH,UNITED STATES OF AMERICA,2016-01-22,"LHB, INC.",MN,2015-01-22,55802,Y,NaN,11,F,5413,54133,541330,NaT,Year,345000,Year,15-11,13-2011,ACCOUNTANTS AND AUDITORS,2015-01-22,1,N,H-1B,20000,20000,NaN,27053,2 WORK,WORK,ME,55401,15,7 days,2015Q2,15-Jan,20000,345000,False,False
14,14,I-200-09261-001558,DENIED,2015-03-31,Y,1110 ELDEN STREET,51059,HERNDON,UNITED STATES OF AMERICA,2018-08-20,"INTERNATIONAL SOLUTIONS GROUP, INC.",VA,2015-08-20,20170,Y,NaN,12,PROGRAMMER ANALYST,5415,54151,541511,NaT,Year,66976,Year,15-12,15-1021.00,COMPUTER PROGRAMMERS,2015-03-20,1,N,H-1B,64688,64688,NaN,10003,MIDDLETOWN,NEW CASTLE,DE,19709,15,11 days,2015Q2,15-Mar,64688,66976,False,False
16,16,I-200-09285-514415,CERTIFIED,2014-10-30,Y,388 WASHINGTON ROAD,34023,SAYREVILLE,UNITED STATES OF AMERICA,2017-10-23,IT CATS LLC,NJ,2014-10-24,08872,Y,NaN,14,SENIOR BUSINESS ANALYST,5415,54151,541511,NaT,Hour,52,Hour,15-14,15-1121,COMPUTER SYSTEMS ANALYSTS,2014-10-24,1,N,H-1B,62,60,65,42091,"NORTH WALES,",MONTGOMERY,PA,19454,15,6 days,2015Q1,14-Oct,130000,109117,False,False
18,19,I-200-09302-785109,CERTIFIED-WITHDRAWN,2014-10-29,N,105 CORPORATE CENTER BLVD,37081,GREENSBORO,UNITED STATES OF AMERICA,2015-04-25,VF CORPORATION,NC,2012-04-25,27408,Y,NaN,16,PROJECT MANAGER (DIGITAL/ECOMMERCE),5415,54151,541512,NaT,Year,110300,Year,15-16,11-3021,COMPUTER AND INFORMATION SYSTEMS MANAGERS,2012-02-02,1,N,H-1B,125000,125000,NaN,06059,CYPRESS,ORANGE,CA,90630,15,1000 days,2015Q1,14-Oct,125000,110300,False,False
21,23,I-200-09317-262420,WITHDRAWN,2014-10-13,N,1510 WEST LOOP SOUTH,48201,HOUSTON,UNITED STATES OF AMERICA,2017-12-10,"LANDRY'S RESTAURANTS, INC.",TX,2014-10-13,77027,Y,NaN,19,GENERAL MANAGER,7221,72211,722110,NaT,Year,56722,Year,15-19,11-9051.00,FOOD SERVICE MANAGERS,2014-10-13,1,N,H-1B,69175,69175,NaN,35001,ALBUQUERQUE,BERNALILLO,NM,87109,15,0 days,2015Q1,14-Oct,69175,56722,False,False
23,25,I-200-09329-943146,CERTIFIED-WITHDRAWN,2015-07-27,N,5725 DELPHI DRIVE,26125,TROY,UNITED STATES OF AMERICA,2017-09-13,DELPHI CORPORATION,MI,2015-05-31,48098,Y,NaN,21,ALGORITHM-STATE ESTIMATION DEVELOPMENT ENGINEER,3363,33639,336399,NaT,Year,91936,Year,15-21,17-2071,ELECTRICAL ENGINEERS,2015-01-14,1,N,H-1B,91936,91936,NaN,06037,AGOURA HILLS,LOS ANGELES,CA,91301,15,194 days,2015Q4,15-Jul,91936,91936,False,False
29,31,I-200-09342-274341,CERTIFIED,2015-02-22,Y,"559 D'ONOFRIO DRIVE, SUITE 101 & 102",55025,MADISON,UNITED STATES OF AMERICA,2018-03-03,"ISR INFO WAY, INC.",WI,2015-04-03,53719,Y,NaN,25,SR. SOFTWARE DEVELOPER,5415,54151,541511,NaT,Year,84906,Year,15-25,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2015-02-13,1,N,H-1B,94953,84906,105000,17031,CHICAGO,COOK,IL,60601,15,9 days,2015Q2,15-Feb,94953,84906,False,False
34,36,I-200-10006-413683,WITHDRAWN,2015-03-11,Y,"523 GREEN STREET, 2ND FLOOR",34023,ISELIN,UNITED STATES OF AMERICA,2018-04-15,SAPHIRE SOLUTIONS INC,NJ,2015-04-16,08830,Y,NaN,29,SYSTEMS ADMINISTRATOR,5415,54151,541511,NaT,Year,68638,Year,15-29,15-1142,NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS,2015-03-10,1,N,H-1B,79560,79560,NaN,36059,BETHPAGE,NASSAU,NY,11714,15,1 days,2015Q2,15-Mar,79560,68638,False,False
35,37,I-200-10028-389232,CERTIFIED,2015-02-04,Y,"510 FRANKLIN AVENUE, SUITE 7 & 8",34013,NUTLEY,UNITED STATES OF AMERICA,2017-10-09,SWANKTEK INC,NJ,2015-01-29,07110,Y,NaN,30,BI APPLICATIONS CONSULTANT,5415,54151,541511,NaT,Year,66602,Year,15-30,15-1121,COMPUTER SYSTEMS ANALYSTS,2015-01-29,1,N,H-1B,70000,70000,NaN,06085,SAN JOSE,SANTA CLARA,CA,95112,15,6 days,2015Q2,15-Feb,70000,66602,False,False
38,39,I-200-10033-402166,WITHDRAWN,2014-10-13,N,2900 SEMICONDUCTOR DRIVE,06085,SANTA CLARA,UNITED STATES OF AMERICA,2017-12-10,NATIONAL SEMICONDUCTOR CORPORATION,CA,2014-10-13,95052,Y,NaN,32,SENIOR APPLICATIONS ENGINEER,3344,33441,334413,NaT,Year,75899,Year,15-32,17-2071.00,ELECTRICAL ENGINEERS,2014-10-13,1,N,H-1B,93024,75899,110150,08013,LONGMONT,BOULDER,CO,80501,15,0 days,2015Q1,14-Oct,93024,75899,False,False
39,40,I-200-10034-822100,CERTIFIED,2014-11-26,Y,860 HEBRON PKWY. SUITE 604,48121,LEWISVILLE,UNITED STATES OF AMERICA,2016-09-13,AMENSYS INC,TX,2014-11-20,75057,Y,NaN,33,COMPUTER PROGRAMMER,5415,54151,541511,NaT,Year,55744,Year,15-33,15-1131,COMPUTER PROGRAMMERS,2014-11-20,1,N,H-1B,60000,60000,NaN,47037,NASHVILLE,DAVIDSON,TN,37211,15,6 days,2015Q1,14-Nov,60000,55744,False,False
40,42,I-200-10035-077428,CERTIFIED-WITHDRAWN,2015-01-10,Y,10 AUSTIN AVENUE,34023,ISELIN,UNITED STATES OF AMERICA,2016-05-14,"AKT, LLC.",NJ,2013-05-15,08830,Y,NaN,34,JAVA DEVELOPER,5415,54151,541519,NaT,Year,51210,Year,15-34,15-1131,COMPUTER PROGRAMMERS,2013-05-15,1,N,H-1B,60000,60000,NaN,39041,COLUMBUS,DELAWARE,OH,43240,15,605 days,2015Q2,15-Jan,60000,51210,False,False
41,43,I-200-10040-339674,CERTIFIED-WITHDRAWN,2015-04-17,N,280 PARK AVENUE,36061,NEW YORK,UNITED STATES OF AMERICA,2016-08-31,"EXLSERVICE.COM, INC.",NY,2013-01-09,10017,Y,NaN,35,ASSISTANT VICE PRESIDENT - DECISION ANALYTICS,5416,54161,541611,NaT,Year,99715,Year,15-35,11-3021,COMPUTER AND INFORMATION SYSTEMS MANAGERS,2013-08-09,1,N,H-1B,121571,121571,NaN,34017,JERSEY CITY,HUDSON,NJ,07302,15,616 days,2015Q3,15-Apr,121571,99715,False,False
43,45,I-200-10050-565007,DENIED,2015-01-29,N,21 WEST SUPERIOR STREET,27137,DULUTH,UNITED STATES OF AMERICA,2016-01-25,"LHB, INC.",MN,2015-01-25,55802,Y,NaN,37,SITE OPERATIONS MANAGER,5413,54133,541330,NaT,Year,20000,Year,15-37,15-2041.00,STATISTICIANS,2015-01-22,1,N,H-1B,20000,20000,NaN,27053,2 BARK,LEAF,LA,55401,15,7 days,2015Q2,15-Jan,20000,20000,False,False
49,50,I-200-10074-644541,CERTIFIED,2015-03-18,N,"301 MERRITT 7, 5TH FLOOR",09001,NORWALK,UNITED STATES OF AMERICA,2018-03-23,JARDEN CORPORATION,CT,2015-03-23,06851,Y,NaN,41,LEAD PEOPLESOFT PROGRAMMER/ANALYST,3352,3352,3352,NaT,Year,102066,Year,15-41,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2015-03-06,1,N,H-1B,112700,102500,122900,12099,BOCA RATON,PALM BEACH,FL,33431,15,12 days,2015Q2,15-Mar,112700,102066,False,False
51,52,I-200-10076-237054,CERTIFIED,2015-02-23,Y,1135 KILDAIRE FARM RD,37183,CARY,UNITED STATES OF AMERICA,2018-08-16,"EMINENCE IT SOLUTIONS, INC.",NC,2015-08-17,27511,Y,NaN,43,"STAFF II, ENVIRONMENTAL STAFF ENGINEER",5415,54151,541511,NaT,Year,62504,Year,15-43,17-2081.00,ENVIRONMENTAL ENGINEERS,2015-02-17,1,N,H-1B,70000,70000,NaN,48113,IRVING,DALLAS,TX,75039,15,6 days,2015Q2,15-Feb,70000,62504,False,False
56,59,I-200-10110-383326,CERTIFIED,2015-02-10,Y,14102 SULLYFIELD CIR,51059,CHANTILLY,UNITED STATES OF AMERICA,2018-08-02,AIMIC INC,VA,2015-09-02,20151,Y,NaN,48,PROGRAMMER ANALYST,5415,54151,541511,NaT,Year,47431,Year,15-48,15-1121,COMPUTER SYSTEMS ANALYSTS,2015-02-04,1,N,H-1B,47431,47431,NaN,36029,BUFFALO,NIAGARA,NY,14210,15,6 days,2015Q2,15-Feb,47431,47431,False,False
58,60,I-200-10110-892779,CERTIFIED-WITHDRAWN,2015-03-06,Y,870 E HIGGINS ROAD,17031,SCHAUMBURG,UNITED STATES OF AMERICA,2015-09-24,SARAYU CONSULTANTS INC,IL,2013-10-07,60173,Y,NaN,49,PROGRAMMER ANALYST,5415,54151,541512,NaT,Year,65707,Year,15-49,15-1131,COMPUTER PROGRAMMERS,2013-07-10,1,N,H-1B,66000,66000,NaN,37119,CHARLOTTE,MECKLENBURG,NC,28202,15,604 days,2015Q2,15-Mar,66000,65707,False,False
60,62,I-200-10116-840479,CERTIFIED,2015-02-10,Y,860 HEBRON PKWY,48121,LEWISVILLE,UNITED STATES OF AMERICA,2018-04-02,TRANS AMERICAN INFORMATION SYSTEMS INC,TX,2015-04-02,75057,Y,NaN,51,E-COMMERCE QA ANALYST,5415,54151,541511,NaT,Year,57678,Year,15-51,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2015-02-04,1,N,H-1B,65000,65000,NaN,06041,CORTE MADERA,MARIN,CA,94925,15,6 days,2015Q2,15-Feb,65000,57678,False,False
64,66,I-200-10137-273423,DENIED,2015-03-31,Y,1110 ELDEN STREET,51059,HERNDON,UNITED STATES OF AMERICA,2018-08-15,"INTERNATIONAL SOLUTIONS GROUP, INC.",VA,2015-08-15,20170,Y,NaN,55,PROGRAMMER ANALYST,5415,54151,541511,NaT,Year,70013,Year,15-55,15-1021.00,COMPUTER PROGRAMMERS,2015-03-20,1,N,H-1B,63523,63523,NaN,04013,CHANDLER,MARICOPA,AZ,85248,15,11 days,2015Q2,15-Mar,63523,70013,False,False
65,68,I-200-10137-791989,DENIED,2015-03-31,N,1110 ELDEN STREET,51059,HERNDON,UNITED STATES OF AMERICA,2018-08-14,"INTERNATIONAL SOLUTIONS GROUP, INC.",VA,2015-08-15,20170,Y,NaN,56,PROGRAMMER ANALYST,5415,54151,541511,NaT,Year,69056,Year,15-56,15-1131,COMPUTER PROGRAMMERS,2015-03-20,1,N,H-1B,69056,69056,NaN,11001,WASHINGTON,WASHINGTON,DC,20001,15,11 days,2015Q2,15-Mar,69056,69056,False,False
66,69,I-200-10147-349494,CERTIFIED-WITHDRAWN,2015-08-09,N,8510 S STEPHANIE LN,04013,TEMPE,UNITED STATES OF AMERICA,2013-10-09,MAP-IT SOLUTIONS INC,AZ,2010-11-09,85284,Y,NaN,57,BUSINESS ANALYST,5415,54151,54151,NaT,Year,60216,Year,15-57,13-1111.00,MANAGEMENT ANALYSTS,2010-05-27,1,N,H-1B,80000,80000,NaN,06085,SAN JOSE,SANTA CLARA,CA,95134,15,1900 days,2015Q4,15-Aug,80000,60216,False,False
67,70,I-200-10147-884998,WITHDRAWN,2014-10-13,N,7001 DEVELOPMENT DRIVE,37063,RESEARCH TRIANGLE PARK,UNITED STATES OF AMERICA,2017-12-10,SONY ERICSSON MOBILE COMMUNICATIONS (USA) INC.,NC,2014-10-13,27709,Y,NaN,58,SOFTWARE QA STAFF ENGINEER (TEST/VERIFICATION),3342,33422,334220,NaT,Year,71386,Year,15-58,15-1031.00,"COMPUTER SOFTWARE ENGINEERS, APPLICATIONS",2014-10-13,1,N,H-1B,109500,94000,125000,06081,REDWOOD CITY,SAN MATEO,CA,94065,15,0 days,2015Q1,14-Oct,109500,71386,False,False
68,71,I-200-10154-842808,CERTIFIED-WITHDRAWN,2015-08-09,N,8510 S STEPHANIE LN,04013,TEMPE,UNITED STATES OF AMERICA,2011-06-06,MAP-IT SOLUTIONS INC,AZ,2010-07-06,85284,Y,NaN,59,QUALITY ANALYST,5415,54151,54151,NaT,Hour,43181,Year,15-59,15-1099.01,SOFTWARE QUALITY ASSURANCE ENGINEERS AND TESTERS,2010-06-04,1,N,H-1B,23,23,NaN,51107,STERLING,LOUDOUN,VA,20166,15,1892 days,2015Q4,15-Aug,47840,43181,False,False
70,73,I-200-10162-078390,CERTIFIED,2014-10-17,N,2700 LAKE COOK ROAD,17097,RIVERWOODS,UNITED STATES OF AMERICA,2018-01-25,CCH INCORPORATED,IL,2015-01-26,60015,Y,NaN,61,PROGRAMMER ANALYST III,5112,51121,511210,NaT,Year,98333,Year,15-61,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-10-13,1,N,H-1B,103496,98333,108660,06037,TORRANCE,LOS ANGELES,CA,90502,15,4 days,2015Q1,14-Oct,103496,98333,False,False
72,74,I-200-10162-700708,CERTIFIED-WITHDRAWN,2015-07-16,N,2700 LAKE COOK ROAD,17097,RIVERWOODS,UNITED STATES OF AMERICA,2017-06-29,"HEALTH LANGUAGE, INC.",IL,2014-06-29,60015,Y,NaN,62,SENIOR PRODUCT SUPPORT CONSULTANT,5417,5417,5417,NaT,Year,72530,Year,15-62,17-2031,BIOMEDICAL ENGINEERS,2014-05-22,1,N,H-1B,108239,72530,143948,08031,DENVER,DENVER,CO,80237,15,420 days,2015Q4,15-Jul,108239,72530,False,False
74,76,I-200-10162-830147,CERTIFIED-WITHDRAWN,2015-09-30,N,2700 LAKE COOK ROAD,17097,RIVERWOODS,UNITED STATES OF AMERICA,2017-06-21,CCH INCORPORATED,IL,2014-06-22,60015,Y,NaN,63,APPLICATIONS DEVELOPER III,5112,51121,511210,NaT,Year,69659,Year,15-63,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2014-06-09,1,N,H-1B,82086,69659,94513,19103,IOWA CITY,JOHNSON,IA,52246,15,478 days,2015Q4,15-Sep,82086,69659,False,False
76,77,I-200-10165-647269,CERTIFIED-WITHDRAWN,2014-10-22,Y,3601 W. DEVON AVENUE,17031,CHICAGO,UNITED STATES OF AMERICA,2016-09-26,WINDYCITY TECHNOLOGIES INC,IL,2013-09-27,60659,Y,NaN,64,BUSINESS ANALYST,5415,54151,541511,NaT,Year,59966,Year,15-64,13-1199,"BUSINESS OPERATIONS SPECIALISTS, ALL OTHER*",2013-03-28,1,N,H-1B,60000,60000,NaN,34023,NEW BRUNSWICK,MIDDLESEX,NJ,08901,15,573 days,2015Q1,14-Oct,60000,59966,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2374501,111004,I-200-17356-429247,CERTIFIED,2017-12-29,Y,"2035 LINCOLN HIGHWAY, EDISON SQUARE WEST",34023,EDISON,UNITED STATES OF AMERICA,2020-12-28,LARSEN & TOUBRO INFOTECH LIMITED,NJ,2017-12-29,08817,Y,94568,94568,SOFTWARE ENGINEER AND TESTER,5415,54151,541511,NaT,Year,68994,Year,18-94568,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2017-12-22,1,N,H-1B,41508,83016,0,09009,MERIDEN,NEW HAVEN,CT,06450,18,7 days,2018Q1,17-Dec,41508,68994,False,False
2374502,111005,I-200-17356-222895,CERTIFIED,2017-12-29,Y,4478 ROUTE 27,34035,KINGSTON,UNITED STATES OF AMERICA,2021-05-11,"HUMETIS TECHNOLOGIES, INC.",NJ,2018-05-12,08528,Y,94569,94569,COMPUTER PROGRAMMER ANALYST-QA,5415,54151,541511,NaT,Year,70554,Year,18-94569,15-1131,COMPUTER PROGRAMMERS,2017-12-22,1,N,H-1B,37440,74880,0,48085,PLANO,COLLIN,TX,75024,18,7 days,2018Q1,17-Dec,37440,70554,False,False
2374504,111007,I-200-17356-940094,CERTIFIED,2017-12-29,Y,2035 LINCOLN HIGHWAY,34023,EDISON,UNITED STATES OF AMERICA,2020-12-28,L&T TECHNOLOGY SERVICES LIMITED,NJ,2017-12-29,08817,Y,94570,94570,DATABASE ADMINISTRATOR,5413,54133,541330,NaT,Year,62046,Year,18-94570,15-1141,DATABASE ADMINISTRATORS,2017-12-22,1,N,H-1B,67023,62046,72000,50007,ST ALBANS CITY,FRANKLIN,VT,05478,18,7 days,2018Q1,17-Dec,67023,62046,False,False
2374505,111009,I-200-17356-873944,CERTIFIED,2017-12-29,Y,"4478 ROUTE 27, SUITE 201B",34035,KINGSTON,UNITED STATES OF AMERICA,2021-01-09,"HUMETIS TECHNOLOGIES, INC.",NJ,2018-01-10,08528,Y,94571,94571,PROGRAMMER ANALYST,5415,54151,541511,NaT,Year,61984,Year,18-94571,15-1131,COMPUTER PROGRAMMERS,2017-12-22,1,N,H-1B,31000,62000,0,18097,INDIANAPOLIS,MARION,IN,46204,18,7 days,2018Q1,17-Dec,31000,61984,False,False
2374507,111010,I-200-17356-838263,CERTIFIED,2017-12-29,Y,2035 LINCOLN HIGHWAY,34023,EDISON,UNITED STATES OF AMERICA,2020-12-28,L&T TECHNOLOGY SERVICES LIMITED,NJ,2017-12-29,08817,Y,94572,94572,PROJECT MANAGER,5413,54133,541330,NaT,Year,88254,Year,18-94572,17-2141,MECHANICAL ENGINEERS,2017-12-22,1,N,H-1B,93127,88254,98000,48201,HOUSTON,HARRIS,TX,77002,18,7 days,2018Q1,17-Dec,93127,88254,False,False
2374508,111011,I-200-17356-783976,CERTIFIED,2017-12-29,N,3039 CORNWALLIS ROAD,37063,DURHAM,UNITED STATES OF AMERICA,2020-06-30,IBM INDIA PRIVATE LIMITED,NC,2018-01-02,27709,Y,94573,94573,BUSINESS AREA MANAGER,5415,54151,54151,NaT,Year,50440,Year,18-94573,15-1131,COMPUTER PROGRAMMERS,2017-12-22,1,N,H-1B,38998,77997,0,53063,SPOKANE,SPOKANE,WA,99202,18,7 days,2018Q1,17-Dec,38998,50440,False,False
2374509,111012,I-200-17356-529614,CERTIFIED,2017-12-29,Y,2035 LINCOLN HIGHWAY,34023,EDISON,UNITED STATES OF AMERICA,2021-01-01,L&T TECHNOLOGY SERVICES LIMITED,NJ,2018-01-02,08817,Y,94574,94574,PROJECT MANAGER,5413,54133,541330,NaT,Year,65978,Year,18-94574,15-1199,"COMPUTER OCCUPATIONS, ALL OTHER",2017-12-22,1,N,H-1B,93000,88000,98000,06059,IRVINE,ORANGE,CA,92618,18,7 days,2018Q1,17-Dec,93000,65978,False,False
2374511,111014,I-200-17356-389617,CERTIFIED,2017-12-29,N,"6860 NORTH DALLAS PARKWAY, SUITE 550",48085,PLANO,UNITED STATES OF AMERICA,2021-01-21,"RELIANT PRO REHAB, LLC",TX,2018-01-22,75094,Y,94576,94576,PHYSICAL THERAPIST,6213,62134,621340,NaT,Year,74568,Year,18-94576,29-1123,PHYSICAL THERAPISTS,2017-12-22,1,N,H-1B,89500,75000,104000,18063,BROWNSBURG,HENDRICKS,IN,46112,18,7 days,2018Q1,17-Dec,89500,74568,False,False
2374512,111016,I-200-17356-432667,CERTIFIED,2017-12-29,Y,2125 MADERA ROAD,06111,SIMI VALLEY,UNITED STATES OF AMERICA,2020-12-23,XAVIENT INFORMATION SYSTEMS INC.,CA,2017-12-23,93065,Y,94577,94577,SOFTWARE TEST ENGINEER - AUTOMATION / SELENIUM,5415,54151,541512,NaT,Year,89502,Year,18-94577,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-12-22,1,N,H-1B,99751,89502,110000,08035,ENGLEWOOD,ARAPAHOE,CO,80112,18,7 days,2018Q1,17-Dec,99751,89502,False,False
2374516,111021,I-200-17356-222869,CERTIFIED,2017-12-29,N,1700 MARKET STREET,42101,PHILADELPHIA,UNITED STATES OF AMERICA,2020-12-28,DELOITTE CONSULTING LLP,PA,2017-12-29,19103,Y,94580,94580,SENIOR CONSULTANT,5416,54161,54161,NaT,Year,79414,Year,18-94580,15-1121,COMPUTER SYSTEMS ANALYSTS,2017-12-22,3,N,H-1B,41500,83000,0,48113,IRVING,DALLAS,TX,75039,18,7 days,2018Q1,17-Dec,41500,79414,False,False
2374517,111022,I-200-17356-369020,CERTIFIED,2017-12-29,Y,100 FRANKLIN SQUARE DR.,34035,SOMERSET,UNITED STATES OF AMERICA,2020-12-21,SCADEA SOLUTIONS INC,NJ,2017-12-22,08873,Y,94581,94581,INFORMATICA DEVELOPER,5415,54151,541512,NaT,Year,76523,Year,18-94581,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-12-22,1,N,H-1B,38262,76523,0,31055,OMAHA,DOUGLAS,NE,68106,18,7 days,2018Q1,17-Dec,38262,76523,False,False
2374519,111024,I-200-17356-064146,CERTIFIED,2017-12-29,Y,14301 N 87TH ST,04013,SCOTTSDALE,UNITED STATES OF AMERICA,2020-12-30,KOLLASOFT INC.,AZ,2017-12-30,85260,Y,94583,94583,SOFTWARE DEVELOPER,5415,54151,541512,NaT,Year,135283,Year,18-94583,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-12-22,1,N,H-1B,75000,150000,0,36061,NEW YORK,NEW YORK,NY,10168,18,7 days,2018Q1,17-Dec,75000,135283,False,False
2374521,111026,I-200-17352-492556,CERTIFIED,2017-12-22,N,3039 CORNWALLIS RD,37063,DURHAM,UNITED STATES OF AMERICA,2020-12-25,IBM CORPORATION,NC,2017-12-26,27709,Y,94585,94585,SOFTWARE ENGINEER,5415,54151,54151,NaT,Year,87173,Year,18-94585,15-1132,"SOFTWARE DEVELOPERS, APPLICATIONS",2017-12-18,1,N,H-1B,113552,101644,125460,42003,PITTSBURGH,ALLEGHENY,PA,15217,18,4 days,2018Q1,17-Dec,113552,87173,False,False
2374523,111028,I-200-17352-736894,CERTIFIED,2017-12-27,N,999 WEST BIG BEAVER ROAD,26125,TROY,UNITED STATES OF AMERICA,2021-03-04,"KELLY SERVICES, INC.",MI,2018-03-05,48084,Y,94587,94587,SCIENTIST 6,5613,56131,561310,NaT,Hour,33,Hour,18-94587,19-1029,"BIOLOGICAL SCIENTISTS, ALL OTHER",2017-12-20,1,N,H-1B,17,34,0,24031,BETHESDA,MONTGOMERY,MD,20892,18,7 days,2018Q1,17-Dec,35568,68370,False,False
2374527,111031,I-200-17352-195016,CERTIFIED,2017-12-22,N,1700 MARKET STREET,42101,PHILADELPHIA,UNITED STATES OF AMERICA,2021-06-17,DELOITTE CONSULTING LLP,PA,2018-06-18,19103,Y,94589,94589,STUDIO SENIOR,5416,54161,54161,NaT,Year,80808,Year,18-94589,15-1121,COMPUTER SYSTEMS ANALYSTS,2017-12-18,3,N,H-1B,41500,83000,0,08031,DENVER,DENVER,CO,80202,18,4 days,2018Q1,17-Dec,41500,80808,False,False
2374528,111032,I-200-17352-142518,CERTIFIED,2017-12-22,Y,22260 HAGGERTY ROAD,26161,NORTHVILLE,UNITED STATES OF AMERICA,2020-12-18,"RELIABLE SOFTWARE RESOURCES, INC.",MI,2017-12-18,48167,Y,94590,94590,PROGRAMMER ANALYST,5415,54151,54151,NaT,Year,74734,Year,18-94590,15-1121,COMPUTER SYSTEMS ANALYSTS,2017-12-18,1,N,H-1B,40000,80000,0,13121,ATLANTA,FULTON,GA,30328,18,4 days,2018Q1,17-Dec,40000,74734,False,False
2374531,111034,I-200-17352-079130,WITHDRAWN,2017-12-21,N,10 S. DEARBORN STREET,17031,CHICAGO,UNITED STATES OF AMERICA,2020-12-26,JPMORGAN CHASE &AMP; CO.,IL,2017-12-26,60603,Y,94591,94591,PROGRAM ANALYST,5511,55111,551112,NaT,Year,65501,Year,18-94591,13-2051,FINANCIAL ANALYSTS,2017-12-18,1,N,H-1B,32750,65501,0,36047,BROOKLYN,KINGS,NY,11245,18,3 days,2018Q1,17-Dec,32750,65501,False,False

## exporting final formats

In [879]:
pd.set_option('precision',0)

In [885]:
np.set_printoptions(suppress=True)

In [880]:
## first to csv - all full records
vvvdata.to_csv("../prepped/vvvdata.csv")

In [913]:
vvvdata.columns

Index(['level_0', 'case_num', 'case_status', 'decision_date', 'dependent',
       'emp_address', 'emp_cfips', 'emp_city', 'emp_cntry', 'emp_end',
       'emp_name', 'emp_st', 'emp_start', 'emp_zip', 'full_time', 'id',
       'index', 'job', 'naics4', 'naics5', 'naics_full', 'org_cert_date',
       'payunit', 'pw', 'pw_payunit', 'row_id', 'soc_code', 'soc_name',
       'submit_date', 'tot_workers', 'violator', 'visa_class', 'wage',
       'wage_from', 'wage_to', 'work_cfips', 'work_city', 'work_cnty',
       'work_st', 'work_zip', 'year', 'dec_dur', 'quarter', 'months', 'yr_sal',
       'pw_sal', 'sameState', 'sameCounty'],
      dtype='object')

In [887]:
importcheck = pd.read_csv("../prepped/vvvdata.csv")

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (15,19,20,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [888]:
len(importcheck)

1945886

In [919]:
importcheck.head()

,Unnamed: 0,level_0,case_num,case_status,decision_date,dependent,emp_address,emp_cfips,emp_city,emp_cntry,emp_end,emp_name,emp_st,emp_start,emp_zip,full_time,id,index,job,naics4,naics5,naics_full,org_cert_date,payunit,pw,pw_payunit,row_id,soc_code,soc_name,submit_date,tot_workers,violator,visa_class,wage,wage_from,wage_to,work_cfips,work_city,work_cnty,work_st,work_zip,year,dec_dur,quarter,months,yr_sal,pw_sal
0,0,0,I-200-09121-701936,WITHDRAWN,2015-02-05,N,710 MEDTRONIC PARKWAY NE,27003,MINNEAPOLIS,UNITED STATES OF AMERICA,2015-02-28,"MEDTRONIC, INC.",MN,2015-09-02,55432,Y,NaN,0,MECHANICAL ENGINEER,3345,33451,334510,NaN,Year,19000,Year,15-0,17-2141.00,MECHANICAL ENGINEERS,2015-02-05,1,N,H-1B,2000,20,NaN,27053,EDEN PRAIRIE,STERNS,CA,55412,15,0 days 00:00:00.000000000,2015Q2,15-Feb,2000,19000
1,2,1,I-200-09146-796321,CERTIFIED,2014-12-18,N,905 ASP AVE,40027,NORMAN,UNITED STATES OF AMERICA,2018-04-01,UNIVERSITY OF OKLAHOMA,OK,2015-05-01,73019,Y,NaN,1,ASSISTANT PROFESSOR,6113,61131,611310,NaN,Year,42860,Year,15-1,25-1032,"ENGINEERING TEACHERS, POSTSECONDARY",2014-12-12,1,N,H-1B,8500,85,NaN,40027,NORMAN,CLEVELAND,OK,73019,15,6 days 00:00:00.000000000,2015Q1,14-Dec,8500,42860
2,3,2,I-200-09180-329758,WITHDRAWN,2014-12-15,N,6021 CONNECTION DRIVE,48113,IRVING,UNITED STATES OF AMERICA,2016-06-01,NOKIA INC.,TX,2013-07-01,75039,Y,NaN,2,RELEASE AND SOFTWARE TEST MANAGER,5172,51721,517212,NaN,Year,73965,Year,15-2,15-1799,"COMPUTER OCCUPATIONS, ALL OTHER*",2013-01-03,1,N,H-1B,9400,94,NaN,6073,SAN DIEGO,SAN DIEGO,CA,92127,15,711 days 00:00:00.000000000,2015Q1,14-Dec,9400,73965
3,4,3,I-200-09183-259985,CERTIFIED,2015-03-16,N,9510 N. HOUSTON ROSSLYN ROAD,48201,HOUSTON,UNITED STATES OF AMERICA,2018-07-09,"OMRON OILFIELD AND MARINE, INC.",TX,2015-07-09,77088,Y,NaN,3,CONTROL ENGINEERING SPECIALIST,3353,33531,335314,NaN,Year,65998,Year,15-3,17-2072,"ELECTRONICS ENGINEERS, EXCEPT COMPUTER",2015-03-10,2,N,H-1B,6800,66,700,48201,HOUSTON,HARRIS,TX,77088,15,6 days 00:00:00.000000000,2015Q2,15-Mar,6800,65998
4,5,4,I-200-09189-800933,CERTIFIED,2014-12-23,N,8250 JONES BRANCH DRIVE,51059,MCLEAN,UNITED STATES OF AMERICA,2018-05-06,FEDERAL HOME LOAN MORTGAGE CO.,VA,2015-06-06,22102,Y,NaN,4,DEVELOPMENT SENIOR,5222,52229,522294,NaN,Year,96907,Year,15-4,15-1131,COMPUTER PROGRAMMERS,2014-12-17,1,N,H-1B,12015,97,1433,51059,MCLEAN,FAIRFAX,VA,22102,15,6 days 00:00:00.000000000,2015Q1,14-Dec,12015,96907

In [909]:
## aggregate function threw an error (below) for having float when expecting string
vvvdata['job'] = vvvdata['job'].astype('str')
vvvdata['soc_name'] = vvvdata['soc_name'].astype('str')

### aggregation

In [915]:
## Basic set (both hq and worksite)
grouping_basic = ['emp_cfips','case_status','quarter', 'months']
aggregation_basic = {
    'case_num': 'count', 
    'tot_workers': np.sum, 
    'yr_sal': [np.sum, np.mean], 
    'pw_sal': [np.sum, np.mean], 
    'dec_dur': (lambda x: x.mean()), 
    'naics4': (lambda x: x.value_counts().index[0]), 
    'job': (lambda x: ', '.join(x)), 
    'soc_name': (lambda x: ', '.join(x))
}

In [918]:
## hq interest: worksite 
# I want to somehow also get division for those that are requesting work 
# that will be done in the state or in the same county, 
# and those that are not. 

# ideally, I want to get something like, 
# sameState
# true   1
# false  0
# all    1

# which can also be grouped by to show how salary, naics4, etc are different
# when I'm looking at only true, only false, or both together.

In [920]:
# I should also create overall national trend summary table

# group by status then show trends (which can include things like 
# how many of them said they have dependent, or decision duration) 

# group by year then status. do the same. how does the trend over the year
# change?

In [917]:
hq_county = vvvdata.groupby(['emp_cfips','case_status','months']).agg({'case_num': 'count', 'tot_workers': np.sum, 'yr_sal': [np.sum, np.mean], 'pw_sal': [np.sum, np.mean], 'dec_dur': (lambda x: x.mean()), 'naics4': (lambda x: x.value_counts().index[0]), 'job': (lambda x: ','.join(x))}).reset_index().groupby(['sameState']).count()

KeyError: 'sameState'

In [911]:
hq_county.head()

                             case_num tot_workers yr_sal        pw_sal         \
                                count         sum    sum   mean    sum   mean
emp_cfips case_status months
01001     CERTIFIED   16-Mar        2           2  62500  31250  98467  49234
01003     CERTIFIED   15-Feb        1           1  24981  24981  24981  24981
                      15-Jun        1           1  20000  20000  17040  17040
                      16-Sep        1           1  38000  38000  73986  73986
01011     CERTIFIED   15-Mar        1           1  60008  60008  60008  60008

                              dec_dur   naics4  \
                             <lambda> <lambda>
emp_cfips case_status months
01001     CERTIFIED   16-Mar   6 days     3363
01003     CERTIFIED   15-Feb   6 days     7225
                      15-Jun   6 days     6116
                      16-Sep   6 days     2362
01011     CERTIFIED   15-Mar   6 days     3312

                                                                   job
                                                              <lambda>
emp_cfips case_status months
01001     CERTIFIED   16-Mar              MRO BUYER,SOFTWARE DEVELOPER
01003     CERTIFIED   15-Feb  GRAPHIC DESIGN AND MARKETING COORDINATOR
                      15-Jun            ASSISTANT DIRECTOR OF COACHING
                      16-Sep                       ELECTRICAL ENGINEER
01011     CERTIFIED   15-Mar                       INDUSTRIAL ENGINEER

In [910]:
hq_county2 = vvvdata.groupby(['emp_cfips','case_status','quarter', 'months']).agg({'case_num': 'count', 'tot_workers': np.sum, 'yr_sal': [np.sum, np.mean], 'pw_sal': [np.sum, np.mean], 'dec_dur': (lambda x: x.mean()), 'naics4': (lambda x: x.value_counts().index[0]), 'job': (lambda x: ','.join(x)), 'soc_name': (lambda x: ','.join(x))})

In [912]:
hq_county2

                                             case_num tot_workers  yr_sal  \
                                                count         sum     sum
emp_cfips case_status         quarter months
01001     CERTIFIED           2016Q2  16-Mar        2           2   62500
01003     CERTIFIED           2015Q2  15-Feb        1           1   24981
                              2015Q3  15-Jun        1           1   20000
                              2016Q4  16-Sep        1           1   38000
01011     CERTIFIED           2015Q2  15-Mar        1           1   60008
                              2015Q4  15-Sep        1           1   60000
                              2017Q3  17-Apr        1           1   22755
          WITHDRAWN           2015Q2  15-Mar        1           1   60008
01013     CERTIFIED           2015Q2  15-Feb        1           1  178512
                                      15-Mar        4           4  160500
                              2015Q4  15-Sep        3           3  195424
                              2016Q1  15-Dec        1           1   46500
                              2016Q2  16-Mar        2           2   77000
                              2017Q2  17-Jan        1           1   44000
                                      17-Mar        4           4  143000
                              2017Q4  17-Aug        1           1   36161
          WITHDRAWN           2015Q4  15-Aug        1           1   47424
01015     CERTIFIED           2015Q1  14-Sep        1           1   78874
                              2015Q2  15-Jan        1           1   52790
                                      15-Mar        2           2   80000
                              2015Q4  15-Jun        1           1   63304
                                      15-Jul        5           5  395551
                                      15-Aug        2           2  193200
                                      15-Sep        1           1  135200
                              2016Q2  16-Jan        2           2  117500
                              2016Q3  16-May        3           3  322500
                                      16-Jun        1           1   34102
                              2016Q4  16-Aug        2           2  182725
                                      16-Sep        1           1   43464
                              2017Q1  16-Oct        1           1   40088
...                                               ...         ...     ...
78030     CERTIFIED           2016Q3  16-Apr        7           7  213826
                                      16-Jun        2           2   50583
                              2016Q4  16-Jul        1           1   24616
                                      16-Aug        2           2   40258
                                      16-Sep        8           8  194644
                              2017Q1  16-Oct        1           1   57500
                                      16-Nov        2           2   44750
                                      16-Dec        2           2   53648
                              2017Q2  17-Jan        1           1   21102
                                      17-Feb        5           5  145218
                                      17-Mar       27          27  948014
                              2017Q3  17-Apr        4           4   93770
                                      17-May        2           2   60000
                              2017Q4  17-Aug        1           1   23182
                                      17-Sep        2           2   54000
                              2018Q1  17-Oct        3           3   73590
                                      17-Nov        1           1   25066
                                      17-Dec        2           2   49782
          CERTIFIED-WITHDRAWN 2017Q2  17-Jan        1           1   23750
          DENIED              2015Q1  14-Dec        1           1   48800
                              2016Q3  16-May        1           1   31200
                                      16-Jun        1           1   31200
                              2017Q4  17-Jul        1           1   16640
                                      17-Aug        1           1   22942
                              2018Q1  17-Nov        1           1   25066
                                      17-Dec        1           1   21550
          WITHDRAWN           2015Q2  15-Mar        1           1   49421
                              2015Q4  15-Jul        1           1   43067
                              2016Q1  15-Dec        1           1   19260
                              2017Q2  17-Mar        1           1   80000

                                                     pw_sal          \
                                                mean    sum    mean
emp_cfips case_status         quarter months
01001     CERTIFIED           2016Q2  16-Mar   31250  1e+05   49234
01003     CERTIFIED           2015Q2  15-Feb   24981  2e+04   24981
                              2015Q3  15-Jun   20000  2e+04   17040
                              2016Q4  16-Sep   38000  7e+04   73986
01011     CERTIFIED           2015Q2  15-Mar   60008  6e+04   60008
                              2015Q4  15-Sep   60000  5e+04   52458
                              2017Q3  17-Apr   22755  5e+04   45510
          WITHDRAWN           2015Q2  15-Mar   60008  6e+04   60008
01013     CERTIFIED           2015Q2  15-Feb  178512  2e+05  167024
                                      15-Mar   40125  1e+05   33686
                              2015Q4  15-Sep   65141  1e+05   45940
                              2016Q1  15-Dec   46500  5e+04   49837
                              2016Q2  16-Mar   38500  7e+04   36816
                              2017Q2  17-Jan   44000  4e+04   39042
                                      17-Mar   35750  2e+05   49062
                              2017Q4  17-Aug   36161  7e+04   72322
          WITHDRAWN           2015Q4  15-Aug   47424  5e+04   47424
01015     CERTIFIED           2015Q1  14-Sep   78874  8e+04   78874
                              2015Q2  15-Jan   52790  5e+04   52790
                                      15-Mar   40000  6e+04   32126
                              2015Q4  15-Jun   63304  5e+04   51667
                                      15-Jul   79110  3e+05   67478
                                      15-Aug   96600  1e+05   70444
                                      15-Sep  135200  9e+04   90168
                              2016Q2  16-Jan   58750  2e+05  100797
                              2016Q3  16-May  107500  6e+05  187200
                                      16-Jun   34102  2e+04   22963
                              2016Q4  16-Aug   91362  2e+05  104437
                                      16-Sep   43464  3e+04   30264
                              2017Q1  16-Oct   40088  8e+04   78437
...                                              ...    ...     ...
78030     CERTIFIED           2016Q3  16-Apr   30547  3e+05   49821
                                      16-Jun   25292  8e+04   42034
                              2016Q4  16-Jul   24616  3e+04   29349
                                      16-Aug   20129  6e+04   27970
                                      16-Sep   24330  3e+05   40579
                              2017Q1  16-Oct   57500  7e+04   74963
                                      16-Nov   22375  6e+04   29900
                                      16-Dec   26824  8e+04   41480
                              2017Q2  17-Jan   21102  4e+04   42203
                                      17-Feb   29044  3e+05   52957
                                      17-Mar   35112  1e+06   52730
                              2017Q3  17-Apr   23442  1e+05   35501
                                      17-May   30000  6e+04   30576
                              2017Q4  17-Aug   23182  5e+04   46363
                                      17-Sep   27000  9e+04   47216
                              2018Q1  17-Oct   24530  1e+05   46800
                                      17-Nov   25066  5e+04   50131
                                      17-Dec   24891  1e+05   49781
          CERTIFIED-WITHDRAWN 2017Q2  17-Jan   23750  5e+04   46738
          DENIED              2015Q1  14-Dec   48800  4e+04   40530
                              2016Q3  16-May   31200  6e+04   62400
                                      16-Jun   31200  6e+04   62400
                              2017Q4  17-Jul   16640  3e+04   33280
                                      17-Aug   22942  5e+04   45885
                              2018Q1  17-Nov   25066  5e+04   50131
                                      17-Dec   21550  5e+04   45915
          WITHDRAWN           2015Q2  15-Mar   49421  5e+04   49421
                              2015Q4  15-Jul   43067  4e+04   39180
                              2016Q1  15-Dec   19260  3e+04   33330
                              2017Q2  17-Mar   80000  1e+05  102294

                                                     dec_dur   naics4  \
                                                    <lambda> <lambda>
emp_cfips case_status         quarter months
01001     CERTIFIED           2016Q2  16-Mar 6 days 00:00:00     3363
01003     CERTIFIED           2015Q2  15-Feb 6 days 00:00:00     7225
                              2015Q3  15-Jun 6 days 00:00:00     6116
                              2016Q4  16-Sep 6 days 00:00:00     2362
01011     CERTIFIED           2015Q2  15-Mar 6 days 00:00:00     3312
                              2015Q4  15-Sep 7 days 00:00:00     8139
                              2017Q3  17-Apr 6 days 00:00:00     5182
          WITHDRAWN           2015Q2  15-Mar 0 days 00:00:00     3312
01013     CERTIFIED           2015Q2  15-Feb 7 days 00:00:00     6211
                                      15-Mar 4 days 12:00:00     3363
                              2015Q4  15-Sep 5 days 08:00:00     3363
                              2016Q1  15-Dec 6 days 00:00:00     5629
                              2016Q2  16-Mar 6 days 12:00:00     3363
                              2017Q2  17-Jan 6 days 00:00:00     3363
                                      17-Mar 4 days 12:00:00     3312
                              2017Q4  17-Aug 6 days 00:00:00     3363
          WITHDRAWN           2015Q4  15-Aug 0 days 00:00:00     3363
01015     CERTIFIED           2015Q1  14-Sep 6 days 00:00:00     3361
                              2015Q2  15-Jan 7 days 00:00:00     6117
                                      15-Mar 5 days 00:00:00     6212
                              2015Q4  15-Jun 6 days 00:00:00     6113
                                      15-Jul 5 days 14:24:00     3362
                                      15-Aug 6 days 12:00:00     3362
                                      15-Sep 6 days 00:00:00     3362
                              2016Q2  16-Jan 7 days 00:00:00     6211
                              2016Q3  16-May 6 days 00:00:00     6211
                                      16-Jun 6 days 00:00:00     6113
                              2016Q4  16-Aug 6 days 00:00:00     6211
                                      16-Sep 6 days 00:00:00     6113
                              2017Q1  16-Oct 6 days 00:00:00     3362
...                                                      ...      ...
78030     CERTIFIED           2016Q3  16-Apr 6 days 00:00:00     4239
                                      16-Jun 6 days 00:00:00     6111
                              2016Q4  16-Jul 6 days 00:00:00     6111
                                      16-Aug 5 days 00:00:00     6111
                                      16-Sep 4 days 12:00:00     4239
                              2017Q1  16-Oct 6 days 00:00:00     7139
                                      16-Nov 6 days 12:00:00     6111
                                      16-Dec 5 days 00:00:00     6111
                              2017Q2  17-Jan 7 days 00:00:00     3399
                                      17-Feb 6 days 00:00:00     4239
                                      17-Mar 4 days 16:53:20     4483
                              2017Q3  17-Apr 5 days 12:00:00     6111
                                      17-May 6 days 00:00:00     4483
                              2017Q4  17-Aug 6 days 00:00:00     4483
                                      17-Sep 6 days 00:00:00     4483
                              2018Q1  17-Oct 5 days 16:00:00     6111
                                      17-Nov 4 days 00:00:00     6111
                                      17-Dec 7 days 00:00:00     6111
          CERTIFIED-WITHDRAWN 2017Q2  17-Jan 6 days 00:00:00     4483
          DENIED              2015Q1  14-Dec 6 days 00:00:00     6111
                              2016Q3  16-May 4 days 00:00:00     6211
                                      16-Jun 5 days 00:00:00     6211
                              2017Q4  17-Jul 3 days 00:00:00     8122
                                      17-Aug 1 days 00:00:00     4483
                              2018Q1  17-Nov 4 days 00:00:00     6111
                                      17-Dec 1 days 00:00:00     6111
          WITHDRAWN           2015Q2  15-Mar 0 days 00:00:00     4483
                              2015Q4  15-Jul 0 days 00:00:00     6111
                              2016Q1  15-Dec 1 days 00:00:00     6111
                              2017Q2  17-Mar 0 days 00:00:00     6113

                                                                                            job  \
                                                                                       <lambda>
emp_cfips case_status         quarter months
01001     CERTIFIED           2016Q2  16-Mar                       MRO BUYER,SOFTWARE DEVELOPER
01003     CERTIFIED           2015Q2  15-Feb           GRAPHIC DESIGN AND MARKETING COORDINATOR
                              2015Q3  15-Jun                     ASSISTANT DIRECTOR OF COACHING
                              2016Q4  16-Sep                                ELECTRICAL ENGINEER
01011     CERTIFIED           2015Q2  15-Mar                                INDUSTRIAL ENGINEER
                              2015Q4  15-Sep                             ASSOCIATE FARM MANAGER
                              2017Q3  17-Apr                                 COMPLIANCE OFFICER
          WITHDRAWN           2015Q2  15-Mar                                INDUSTRIAL ENGINEER
01013     CERTIFIED           2015Q2  15-Feb             FAMILY PRACTICE / GERIATRICS PHYSICIAN
                                      15-Mar  ACCOUNTING MANAGER,IT COORDINATOR,PRODUCTION C...
                              2015Q4  15-Sep  BUSINESS SYSTEMS ANALYST,BODY ASSISTANT  MANAG...
                              2016Q1  15-Dec                                         ACCOUNTANT
                              2016Q2  16-Mar    INTERNATIONAL MARKET ANALYST,QUALITY SPECIALIST
                              2017Q2  17-Jan                                         ACCOUNTANT
                                      17-Mar  ACCOUNTANT,BUDGET SPECIALIST,IT SPECIALIST,ASS...
                              2017Q4  17-Aug                         SENIOR MECHANICAL ENGINEER
          WITHDRAWN           2015Q4  15-Aug                           BUSINESS SYSTEMS ANALYST
01015     CERTIFIED           2015Q1  14-Sep                       SENIOR ENGINEER - STRUCTURAL
                              2015Q2  15-Jan       EDUCATIONAL/VOCATIONAL COORDINATOR COUNSELOR
                                      15-Mar  HISPANIC COMMUNITY OUTREACH COORDINATOR,COMMUN...
                              2015Q4  15-Jun        HEAD COACH FOR THE MEN'S AND WOMEN'S TENNIS
                                      15-Jul  SR. DESIGN ENGINEER - BODY SYSTEMS,PEDIATRICIA...
                                      15-Aug  ASSISTANT PROFESSOR, EMERGENCY MANAGEMENT,CHIE...
                                      15-Sep         CHIEF ENGINEER - REFERENCE BUS ENGINEERING
                              2016Q2  16-Jan                PEDIATRICIAN,ASSOCIATE VETERINARIAN
                              2016Q3  16-May  INTERNAL MEDICINE PHYSICIAN-HOSPITALIST,HOSPIT...
                                      16-Jun                             ASSISTANT TENNIS COACH
                              2016Q4  16-Aug       SR. PROGRAMMER ANALYST,HOSPITALIST PHYSICIAN
                                      16-Sep                               INTERACTIVE DESIGNER
                              2017Q1  16-Oct                  SR DESIGN ENGINEER - BODY SYSTEMS
...                                                                                         ...
78030     CERTIFIED           2016Q3  16-Apr  DIRECTOR OF OPERATIONS,DIRECTOR OF OPERATIONS,...
                                      16-Jun    ASSISTANT PROFESSOR OF PHYSICS,SCHOOL LIBRARIAN
                              2016Q4  16-Jul                                   SCHOOL LIBRARIAN
                                      16-Aug   ELEMENTARY TEACHER,SECONDARY MATHEMATICS TEACHER
                                      16-Sep  ACCOUNTANT,ACCOUNTANT,ACCOUNTANT,ACCOUNTANT,AC...
                              2017Q1  16-Oct                           FACILITY GENERAL MANAGER
                                      16-Nov  HIGH SCHOOL SCIENCE TEACHER,SECONDARY FRENCH T...
                                      16-Dec  SPECIAL EDUCATION TEACHER,SPECIAL EDUCATION TE...
                              2017Q2  17-Jan                            MARKET RESEARCH ANALYST
                                      17-Feb  STAFF PSYCHIATRIST,POSTDOCTORAL RESEARCH ASSOC...
                                      17-Mar  BUSINESS ANALYST,FINANCIAL ANALYST,POST-DOCTOR...
                              2017Q3  17-Apr  FIRST LINE SUPERVISOR OF RETAIL SALES,ELEMENTA...
                                      17-May                              ACCOUNTANT,ACCOUNTANT
                              2017Q4  17-Aug                                  MARKETING MANAGER
                                      17-Sep                       MARKETING MANAGER,ACCOUNTANT
                              2018Q1  17-Oct  SCHOOL LIBRARIAN,SCHOOL LIBRARIAN,SPECIAL EDUC...
                                      17-Nov               ELEMENTARY SPECIAL EDUCATION TEACHER
                                      17-Dec  SECONDARY SPECIAL EDUCATION TEACHER,SECONDARY ...
          CERTIFIED-WITHDRAWN 2017Q2  17-Jan                                      SALES MANAGER
          DENIED              2015Q1  14-Dec            MIDDLE SCHOOL SPECIAL EDUCATION TEACHER
                              2016Q3  16-May                                     ONCOLOGY NURSE
                                      16-Jun                                     ONCOLOGY NURSE
                              2017Q4  17-Jul                                          MORTICIAN
                                      17-Aug                                  MARKETING MANAGER
                              2018Q1  17-Nov               ELEMENTARY SPECIAL EDUCATION TEACHER
                                      17-Dec                SECONDARY SPECIAL EDUCATION TEACHER
          WITHDRAWN           2015Q2  15-Mar                            MARKET RESEARCH ANALYST
                              2015Q4  15-Jul                          SPECIAL EDUCATION TEACHER
                              2016Q1  15-Dec               MIDDLE SCHOOL SOCIAL STUDIES TEACHER
                              2017Q2  17-Mar                                 EXECUTIVE DIRECTOR

                                                                                       soc_name
                                                                                       <lambda>
emp_cfips case_status         quarter months
01001     CERTIFIED           2016Q2  16-Mar  WHOLESALE AND RETAIL BUYERS, EXCEPT FARM PRODU...

In [31]:
#employerLoc = ts.groupby(['EMP_CNTY','RESULT']).agg({'TOTAL_WORKERS': np.sum,'YrSalary': [np.sum, np.mean], 'NAICS4': (lambda x: x.value_counts().index[0])})
#PREVAILING_WAGE, PW_UNITS_OF_PAY

In [250]:
worksiteLoc = ts.groupby(['WORK_CNTY','RESULT','PERIOD']).agg({'TOTAL_WORKERS': np.sum, 'YrSalary': [np.sum, np.mean], 'DEC_DUR': (lambda x: x.mean()), 'NAICS4': (lambda x: x.value_counts().index[0])})

In [251]:
employerLoc.columns = ["_".join(x) for x in employerLoc.columns.ravel()]
worksiteLoc.columns = ["_".join(x) for x in worksiteLoc.columns.ravel()]

In [258]:
worksiteLoc.head()

                            tot_workers  all_salary  avg_salary decision_dur  \
WORK_CNTY RESULT    PERIOD
01001     CERTIFIED 2015Q4          2.0    352000.0    176000.0       6 days
                    2016Q2          1.0     20000.0     20000.0       6 days
                    2016Q4          1.0     88000.0     88000.0       6 days
                    2017Q2          1.0     55000.0     55000.0       4 days
                    2017Q3          2.0    190000.0     95000.0       4 days

                           naics4                       index  cfips  \
WORK_CNTY RESULT    PERIOD
01001     CERTIFIED 2015Q4   6211  (01001, CERTIFIED, 2015Q4)  01001
                    2016Q2   3363  (01001, CERTIFIED, 2016Q2)  01001
                    2016Q4   6211  (01001, CERTIFIED, 2016Q4)  01001
                    2017Q2   3331  (01001, CERTIFIED, 2017Q2)  01001
                    2017Q3   6211  (01001, CERTIFIED, 2017Q3)  01001

                               result  peiord
WORK_CNTY RESULT    PERIOD
01001     CERTIFIED 2015Q4  CERTIFIED  2015Q4
                    2016Q2  CERTIFIED  2016Q2
                    2016Q4  CERTIFIED  2016Q4
                    2017Q2  CERTIFIED  2017Q2
                    2017Q3  CERTIFIED  2017Q3

In [253]:
employerLoc = employerLoc.rename(columns = {'TOTAL_WORKERS_sum' : 'tot_workers', 'YrSalary_sum': 'all_salary', 'YrSalary_mean': 'avg_salary', 'DEC_DUR_<lambda>': 'decision_dur', 'NAICS4_<lambda>': 'naics4'})
worksiteLoc = worksiteLoc.rename(columns = {'TOTAL_WORKERS_sum' : 'tot_workers', 'YrSalary_sum': 'all_salary', 'YrSalary_mean': 'avg_salary', 'DEC_DUR_<lambda>': 'decision_dur','NAICS4_<lambda>': 'naics4'})

In [255]:
employerLoc['index'] = employerLoc.index
worksiteLoc['index'] = worksiteLoc.index

In [257]:
worksiteLoc['cfips'] = worksiteLoc['index'].apply(lambda x: x[0])
worksiteLoc['result'] = worksiteLoc['index'].apply(lambda x: x[1])
worksiteLoc['peiord'] = worksiteLoc['index'].apply(lambda x: x[2])

In [259]:
employerLoc['cfips'] = employerLoc['index'].apply(lambda x: x[0])
employerLoc['result'] = employerLoc['index'].apply(lambda x: x[1])
employerLoc['peiord'] = employerLoc['index'].apply(lambda x: x[2])

In [206]:
#list(h1bbyWorkCounty) 
#h1bbyWorkCounty['agg_salary'].apply(np.floor)

In [260]:
worksiteLoc['avg_salary'] = worksiteLoc['avg_salary'].apply(np.floor)
employerLoc['avg_salary'] = employerLoc['avg_salary'].apply(np.floor)

In [261]:
worksiteLoc['all_salary'] = worksiteLoc['all_salary'].apply(np.floor)
employerLoc['all_salary'] = employerLoc['all_salary'].apply(np.floor)

In [263]:
worksiteLoc = worksiteLoc[['cfips','result','peiord', 'tot_workers',
 'all_salary','avg_salary', 'decision_dur','naics4']]
employerLoc = employerLoc[['cfips','result','peiord', 'tot_workers',
 'all_salary','avg_salary', 'decision_dur', 'naics4']]

In [264]:
worksiteLoc = worksiteLoc.rename(columns = {'peiord': 'period'})
employerLoc = employerLoc.rename(columns = {'peiord': 'period'})

In [281]:
worksiteLoc['decision_dur'] = (worksiteLoc['decision_dur']).dt.days
employerLoc['decision_dur'] = (employerLoc['decision_dur']).dt.days

In [282]:
worksiteLoc.to_json('../prepped/vdatafull_work.json', orient='records')

# ../prepped/h1b17Work.json DONE redone 
# ../prepped/h1b16Work.json DONE redone redone-wo-duplicates
# ../prepped/h1b15Work.json DONE redone redone-wo-duplicates
# ../prepped/h1b14Work.json
# ../prepped/h1b13Work.json
# ../prepped/h1b12Work.json
# ../prepped/h1b11Work.json
# ../prepped/h1b10Work.json
# ../prepped/h1b09Work.json
# ../prepped/h1b08Work.json

In [283]:
employerLoc.to_json('../prepped/vdatafull_hq.json', orient='records')

# ../prepped/h1b17Emp.json DONE redone
# ../prepped/h1b16Emp.json DONE redone redone-wo-duplicates
# ../prepped/h1b15Emp.json DONE redone redone-wo-duplicates
# ../prepped/h1b14Emp.json
# ../prepped/h1b13Emp.json
# ../prepped/h1b12Emp.json
# ../prepped/h1b11Emp.json
# ../prepped/h1b10Emp.json
# ../prepped/h1b09Emp.json
# ../prepped/h1b08Emp.json

In [284]:
worksiteLoc.to_csv('../prepped/vdatafull_work.csv')
employerLoc.to_csv('../prepped/vdatafull_hq.csv')

In [285]:
len(worksiteLoc)

37116

In [286]:
worksiteLoc.head(10)

                            cfips     result  period  tot_workers  all_salary  \
WORK_CNTY RESULT    PERIOD
01001     CERTIFIED 2015Q4  01001  CERTIFIED  2015Q4          2.0    352000.0
                    2016Q2  01001  CERTIFIED  2016Q2          1.0     20000.0
                    2016Q4  01001  CERTIFIED  2016Q4          1.0     88000.0
                    2017Q2  01001  CERTIFIED  2017Q2          1.0     55000.0
                    2017Q3  01001  CERTIFIED  2017Q3          2.0    190000.0
                    2018Q1  01001  CERTIFIED  2018Q1          1.0     78000.0
01003     CERTIFIED 2015Q1  01003  CERTIFIED  2015Q1          3.0    205360.0
                    2015Q2  01003  CERTIFIED  2015Q2          1.0     24980.0
                    2015Q3  01003  CERTIFIED  2015Q3          1.0     20000.0
                    2015Q4  01003  CERTIFIED  2015Q4          5.0     87500.0

                            avg_salary  decision_dur naics4
WORK_CNTY RESULT    PERIOD
01001     CERTIFIED 2015Q4    176000.0             6   6211
                    2016Q2     20000.0             6   3363
                    2016Q4     88000.0             6   6211
                    2017Q2     55000.0             4   3331
                    2017Q3     95000.0             4   6211
                    2018Q1     78000.0             6   6212
01003     CERTIFIED 2015Q1     68453.0             4   5415
                    2015Q2     24980.0             6   7225
                    2015Q3     20000.0             6   6116
                    2015Q4     87500.0             6   5413

In [287]:
len(employerLoc)

29390

In [294]:
employerLoc.head(10)

                           cfips     result  period  tot_workers  all_salary  \
EMP_CNTY RESULT    PERIOD
01001    CERTIFIED 2016Q2  01001  CERTIFIED  2016Q2          2.0     62500.0
01003    CERTIFIED 2015Q2  01003  CERTIFIED  2015Q2          1.0     24980.0
                   2015Q3  01003  CERTIFIED  2015Q3          1.0     20000.0
                   2016Q4  01003  CERTIFIED  2016Q4          1.0     38000.0
01011    CERTIFIED 2015Q2  01011  CERTIFIED  2015Q2          1.0     60008.0
                   2015Q4  01011  CERTIFIED  2015Q4          1.0     60000.0
                   2017Q3  01011  CERTIFIED  2017Q3          1.0     22755.0
         WITHDRAWN 2015Q2  01011  WITHDRAWN  2015Q2          1.0     60008.0
01013    CERTIFIED 2015Q2  01013  CERTIFIED  2015Q2          5.0    339012.0
                   2015Q4  01013  CERTIFIED  2015Q4          3.0    195424.0

                           avg_salary  decision_dur naics4
EMP_CNTY RESULT    PERIOD
01001    CERTIFIED 2016Q2     31250.0             6   3363
01003    CERTIFIED 2015Q2     24980.0             6   7225
                   2015Q3     20000.0             6   6116
                   2016Q4     38000.0             6   2362
01011    CERTIFIED 2015Q2     60008.0             6   3312
                   2015Q4     60000.0             7   8139
                   2017Q3     22755.0             6   5182
         WITHDRAWN 2015Q2     60008.0             0   3312
01013    CERTIFIED 2015Q2     67802.0             5   3363
                   2015Q4     65141.0             5   3363

In [295]:
worksiteLoc.head(20)

                            cfips     result  period  tot_workers  all_salary  \
WORK_CNTY RESULT    PERIOD
01001     CERTIFIED 2015Q4  01001  CERTIFIED  2015Q4          2.0    352000.0
                    2016Q2  01001  CERTIFIED  2016Q2          1.0     20000.0
                    2016Q4  01001  CERTIFIED  2016Q4          1.0     88000.0
                    2017Q2  01001  CERTIFIED  2017Q2          1.0     55000.0
                    2017Q3  01001  CERTIFIED  2017Q3          2.0    190000.0
                    2018Q1  01001  CERTIFIED  2018Q1          1.0     78000.0
01003     CERTIFIED 2015Q1  01003  CERTIFIED  2015Q1          3.0    205360.0
                    2015Q2  01003  CERTIFIED  2015Q2          1.0     24980.0
                    2015Q3  01003  CERTIFIED  2015Q3          1.0     20000.0
                    2015Q4  01003  CERTIFIED  2015Q4          5.0     87500.0
                    2016Q2  01003  CERTIFIED  2016Q2          8.0    402419.0
                    2016Q3  01003  CERTIFIED  2016Q3          7.0    486392.0
                    2016Q4  01003  CERTIFIED  2016Q4         12.0     86661.0
                    2017Q1  01003  CERTIFIED  2017Q1          2.0    192824.0
                    2017Q2  01003  CERTIFIED  2017Q2          5.0    234073.0
                    2017Q3  01003  CERTIFIED  2017Q3          1.0     42450.0
                    2018Q1  01003  CERTIFIED  2018Q1          1.0    118573.0
          DENIED    2016Q2  01003     DENIED  2016Q2          1.0     23400.0
                    2016Q3  01003     DENIED  2016Q3          2.0    208000.0
01005     CERTIFIED 2015Q4  01005  CERTIFIED  2015Q4          1.0    353392.0

                            avg_salary  decision_dur naics4
WORK_CNTY RESULT    PERIOD
01001     CERTIFIED 2015Q4    176000.0             6   6211
                    2016Q2     20000.0             6   3363
                    2016Q4     88000.0             6   6211
                    2017Q2     55000.0             4   3331
                    2017Q3     95000.0             4   6211
                    2018Q1     78000.0             6   6212
01003     CERTIFIED 2015Q1     68453.0             4   5415
                    2015Q2     24980.0             6   7225
                    2015Q3     20000.0             6   6116
                    2015Q4     87500.0             6   5413
                    2016Q2     57488.0             5   5415
                    2016Q3     69484.0             5   6211
                    2016Q4     28887.0             6   5413
                    2017Q1     96412.0             6   6211
                    2017Q2     58518.0             6   5413
                    2017Q3     42450.0             6   5415
                    2018Q1    118573.0             6   5413
          DENIED    2016Q2     23400.0             4   7225
                    2016Q3    104000.0             4   6211
01005     CERTIFIED 2015Q4    353392.0             6   5416

In [297]:
vdatafull.to_csv("../prepped/vdatafull_all.csv")

In [298]:
len(vdatafull)

1985928